### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by Targuinius** [Ellpeck/ActuallyAdditions#10]
If you shift click an item while in the crusher GUI, it will duplicate that stack of items.

**Comment by Targuinius** [comment]
Tested some more, seems like it only works in the first three slots of your inventory, haven't checked any other machines yet except for an Induction Smelter from TE

**Comment by Ellpeck** [comment]
I tested around a lot. It doesn't happen for me.
Happended in an earlier version though, did you update to 0.0.8.X?

**Comment by Targuinius** [comment]
I use 0.0.8.1, it actually only works in the second and third slot and only in the crusher GUI, the items also get moved to the furthest away (So 9 on the hotbar, if that is filled to 8 etc., not sure if relevant). I could post a full list of the mods and versions I use.

**Comment by Ellpeck** [comment]
The second and third slot of what? What happens? When does it get duplicated? How does it get duplicated?

**Comment by Ellpeck** [comment]
I've been trying around with lots of combinations of shift-clicking and items being in the inventory. It doesn't happen for me.

**Comment by Targuinius** [comment]
I tried to make a video of it, but the recording software is a bit glitchy. Here goes though: http://gfycat.com/WhisperedPowerlessFulmar

Probably should've mentioned this earlier, but I am using Fastcraft. Also, it only works in the normal Crusher.

**Comment by Ellpeck** [comment]
Huh, that's really odd.
Could you try to check if it happens for any of my other inventories? Would be a huge help! :)
Trying to fix during the weekend.

**Comment by Targuinius** [comment]
In the crusher it works with the second and third slot of the first row of your inventory.

The (Phantom) Placer, (Phantom) Breaker and Precision Dropper (They all use the same GUI) work with the first slot of the first row of your inventory.

Also something I noticed: It's impossible to craft paper with rice because it makes Rice Dough and trying to craft a Knife Blade will craft a Flint and Steel.

**Comment by Ellpeck** [comment]
The below is both untrue:
Paper is a shaped recipe, rice dough is shapeless.
The Knife blade is shaped, the flint and steel is shapeless.

**Comment by Targuinius** [comment]
Just tried it again: even shift clicking it with NEI doesn't work

**Comment by Ellpeck** [comment]
Yea, cause those both work for me all the time. Just tested both actually. Other people didn't notice though, so I'll probably be changing it..
