### ISSUE TITLE
[Suggestion] item placer/collector for atomic reconstructor

### ISSUE THREAD

**Issue by 4Magma** [Ellpeck/ActuallyAdditions#1000]
tried to make an automatic enchanted book splitter like in 
(https://www.youtube.com/watch?v=yA_sxhSD9fo) but there are too many
types of enchantments for the filter of the ranged collector.

So i suggest following block 
- combination of automatic precision dropper and ranged collector
- automatic placement of input items and collection of output items
- prevent items to be absorbed by hopper, magnet, collector ...
- placed under any air block on the way of the reconstructor beam

recipe:
- ranged collector + wooden plate + automatic precision dropper
- some other materials (but not empored ones)

gui:
- 9 input slots
- 9 output slots
- redstone mode (on/off/ignore on external redstone signal)

behaviour:
- check if no item in a space 3x3x3 above block
- get 1 item from input slots and drop it above block
- send a redstone signal to fire reconstructor 
- collect items from 3x3x3 space above block and put them in output slots
- wait till all are collected + at least 1s 
- next iteration

if something like item tagging is possible:
- add tag "input" before placing above block
- let create reconstructor items with "output"-tag
- only collect items with "output"-tag
- prevent external absorbtion only for items with such tags

**Comment by Ellpeck** [comment]
Or you could just put a filter item into the Ranged Collector :thinking: Or just use the ranged collector in "Ignore Meta" and "Ignore NBT" mode and just put any enchanted book in, that way it'll pick up any enchanted books.
Sorry, not a big fan of this idea, so closing it :(

**Comment by 4Magma** [comment]
filtering of enchanted books doesn't work because the place books as
also the converted books would match that criterion

alternative:
- filter which counts enchantments on an item or differ between single- and
  multi-enchanted items
- recipe 4 enchanted books around 1 paper
- gui <,>,=  {quantity}
