### ISSUE TITLE
[Suggestion] automatic "precision" dispenser

### ISSUE THREAD

**Issue by 4Magma** [Ellpeck/ActuallyAdditions#1001]
- mix of automatic precision dropper and dispenser
- fires only if items inside
- delay of at least n {ticks} (1s) between each
- recipe: "automatic precision dropper" + bow + ...

usage:
- throwing of chicken/hatchery-eggs

**Comment by Ellpeck** [comment]
This is really hard to do by the way that the Dispenser code works (or used to work, as I attempted this in the past). I still like the idea though, so keeping it open.

**Comment by 4Magma** [comment]
alternative:
- is there a block (or could you add one) which fires a redstone signal
  to the block in front as long it detects an item in its inventory
  (combination of redstone clock, comparator and so on)
