### ISSUE TITLE
[Suggestion] Add a Progress bar to the empowering process

### ISSUE THREAD

**Issue by derdotte** [Ellpeck/ActuallyAdditions#1002]
As you may know the empowerer is a really liked tool in many harder modpacks, usually the process takes millions of RF, usually its hard to tell how far the empowered block is. 
My idea would be to add a progress bar to the empowerer block itself that shows the accumulated power, once amount is reached the bar empties and the empowering process is done.

**Comment by roboderpy** [comment]
empowering takes 400 000 RF

**Comment by YasminEndusa** [comment]
That's not true. Each EmpowererRecipe can have (and most of the time has) different energy requirements and processing time, especially with changed or added recipes in some modpacks.

**Comment by ManMan36** [comment]
I think that it would cool if the empowering cost was displayed in JEI along with the recipe.

**Comment by Ellpeck** [comment]
Blaaaaaaaaaaaaaarg more progress bars, why is everything so crazy about this stuff

**Comment by derdotte** [comment]
> Blaaaaaaaaaaaaaarg more progress bars, why is everything so crazy about this stuff
I understand that from a developer view its not needed, it only adds extra code that might mess up something else but from an enduser view its incredibly useful to get this information. Wether this now means to add another progress bar or reworking the current bars on the display stands to show the crafting process instead of the internal CF, is a choice you have if you decide to implement this.

I do not quite understand the trend in many minecraft mods to go GUI-less, instead the goal should be to make a gui as comprehensive as possible without actually cluttering it but thats just my opinion.
Eitherway i stand behind adding a progress bar to the empowerer block itself.

**Comment by ktole1999** [comment]
is there an existing tool that could be used to query the status?

**Comment by Quarris** [comment]
I very highly doubt that an actual progress bar will be added, so you can stop asking really. However JEI showing the total CF required for a recipe I think is good and should be enough. You can with fair ease calculate how long it will take given the CF/t and the total CF.

**Comment by derdotte** [comment]
> You can with fair ease calculate how long it will take given the CF/t and the total CF.

That is not an arguement, as this would need actual ways inside AA to provide that since other significant measureing items are usually way more gated in harder modpacks, which is the entire reason i am asking.
I am simply not asking for much here, a quality of life improvement at best.

**Comment by Ellpeck** [comment]
I dislike the idea of the Empowerer having a progress bar, because I don't think everything should show you exactly how long it takes. It makes you do other things while waiting instead of sitting around thinking "Oh it's only 20 seconds for it to be done". I just dislike that kind of behavior.
I'm locking this thread for now because I don't really think this is the place for discussion on this. If @Shadows-of-Fire or @canitzp want to implement the progress bar, they can, as I don't work on the mod anymore either way.

**Comment by Shadows-of-Fire** [comment]
The reason people want a progress bar, from what I'm gathering, is because pack devs are implementing recipes that use millions of RF to empower, which makes it take ages...

**Comment by Ellpeck** [comment]
I'm just gonna make an executive decision here, cause I know that this'll linger around for ages otherwise: It's not happening, I'm sorry.
