### ISSUE TITLE
Oil Generator Incorrectly Reporting Burn Time

### ISSUE THREAD

**Issue by dannydjdk** [Ellpeck/ActuallyAdditions#1003]
Oil generator incorrectly records burn time as ticks, when it is really showing the number of seconds. For instance, when you place a bucket of empowered oil in the generator, it shows 120 CF/t for 400 t. The oil actually burns for 8000 ticks (400 seconds). Thus, when calculating how much CF you will get per bucket, your calculations will be off by a factor of 20.

Actually Additions r126 (and every previous version I've checked)
Minecraft 1.12.2
Forge 14.23.1.2555

**Comment by Shadows-of-Fire** [comment]
While currently it does display the value in seconds, it only consumes 50 mB at a time.  I may change it to reflect the burn time of 50 mB of fluid.

**Comment by Shadows-of-Fire** [comment]
Wait a second.  It already does that.

**Comment by dannydjdk** [comment]
I'm confused as to how a player would know this. It just says 120 CF/t for 400t. It doesn't say it will burn 50mB in 400t and that's definitely not what one would assume. Yes, it's a minor point, and now that I know, I can adjust my calculations. But, it's misleading and makes it appear these oils produce very little power. Would it be possible to simply add the text "per 50mB" or something like that?

**Comment by Ellpeck** [comment]
Actually, no. It displays the value per 50 millibuckets, but it should tell the user that.
You should add a text to the GUI that says "Per 50 millibuckets:" above or below the existing texts.
