### ISSUE TITLE
Farmer harvest enderlilys but destroys drops

### ISSUE THREAD

**Issue by kmork1** [Ellpeck/ActuallyAdditions#1004]
Minecraft 1.12.2
Actually : 1.12.2-r126
When a farmer harvested my ender lilysnit didn’t pick up anything. I made sure there was nothing pulling out of it and watched the whole growth cycle and when I broke I had nothing in the farmer and nothing on the ground

**Comment by Shadows-of-Fire** [comment]
This is an xu2 issue.
