### ISSUE TITLE
GreenhouseClass bug?

### ISSUE THREAD

**Issue by Metaz78** [Ellpeck/ActuallyAdditions#1005]
Just updated our FTB Direwolf20 server to 1.7.0 (from 1.4.0)
and got this message

[18:55:46] [Server thread/INFO] [STDOUT]: [de.ellpeck.actuallyadditions.mod.blocks.BlockGreenhouseGlass:func_180650_b:82]: debugg

This was coming in the server console a few times each second and no one could log in to the server.
I restarted the earlier version of the server (same world, config settings etc) with no problems.

**Comment by Shadows-of-Fire** [comment]
I mean, its not a bug, just a bit of a log spam I forgot to remove, but it wont prevent any logins

**Comment by CharZinta** [comment]
@Shadows-of-Fire - I know you said this isn't an issue but I didn't have this problem on the MC 1.12 DW20 Ver 1.7.1 until I started trying to use RFTOOLS worlds and now it happens non-stop. I'm not saying this is your bug, per say, just providing some information.
