### ISSUE TITLE
Inventoric Reconstructor

### ISSUE THREAD

**Issue by NicholasRC7** [Ellpeck/ActuallyAdditions#1007]
Add an atomic reconstructor (disable in config) that reconstructs in its inventory for 3x power. (AE2/RS ease of use, but **_really_** expensive recipe)

**Comment by Shadows-of-Fire** [comment]
Yeah.... not gonna happen

**Comment by canitzp** [comment]
What Shadow means is that all AA machines are easy to automate with only AA itself, so it would make absolutly no sense to add extra blocks for easy-to-use RS/AE
