### ISSUE TITLE
Greenhouse glass and ender lily interaction bug

### ISSUE THREAD

**Issue by Seadevils2** [Ellpeck/ActuallyAdditions#1009]
I did a search on this and I don't see it reported anywhere else but if you're aware of this already I apologize.  Love the mod and normally don't comment but this bug even I consider OP.
Greenhouse glass seems to short circuit the extra utilities cool down now.  I wasn't paying attention much before the new version came out so I'm not sure if it was always this way in 1.12 but I really noticed it after breaking and replacing the Greenhouse glass after the update.  Created a short 8 minute video documenting the bug and how to repeat it along with using scanners from extra utilities to show what was happening.

[Video](https://youtu.be/3L6c6VGpmmQ)

**Comment by Shadows-of-Fire** [comment]
XU2 is not supported.  I will not special case its nonsense.  That's already done for the farmer, and only still exists because it was written before I got here and I have not removed it.
