### ISSUE TITLE
[Suggestion] Phantom Fluidplacer

### ISSUE THREAD

**Issue by TheWolfJack** [Ellpeck/ActuallyAdditions#1011]
I've been playing more with Astral Sorcery and there is a specific multiblock structure, the Starlight Infuser, that requires full buckets of liquid to be placed around it. Unfortunately there is no current way to do this and keep the build 1) looking decent and b) accessible.

I tried a standard Phantom Placer and buckets, then read the manually seeing that it clearly states blocks being placed. I'd love if there was either an upgrade to the existing placer, perhaps empower it with a fluid placer and some buckets, or a new item to allow placing of fluids the way that you can currently place blocks.

**Comment by DigitalSketch** [comment]
Just an FYI, if you're playing in MC 1.12 with the latest version of Astral Sorcery, you can craft a Containment Chalice, put it just outside the infuser, pipe starlight into it, and it won't use the liquid in the multiblock.  Side note, I put a mechanical user behind it, put it on "Active Block With Item", fill it with Aquamarines, and just hold right click.  Doesn't take long to get a stack items :)
