### ISSUE TITLE
Food Configs

### ISSUE THREAD

**Issue by MarikCZ** [Ellpeck/ActuallyAdditions#1012]
Hi

Can you make AA food more configurable?
I have some complication with Harvestcraft hunger and saturation balance (see issue on GitHub bellow). In more details, HC makes amout of hunger points (and saturation) restored more balanced with other HC and Vanila food. But has not support for AA. I am able to balance it on my own, but I can't.
I need options to enable/disable food (one by one and everything), and options to decrease/increase restored hunger/saturation. Thats all.
HC Issue on GitHub
https://github.com/MatrexsVigil/harvestcraft/issues/128

Best regards

MarkShy

**Comment by Shadows-of-Fire** [comment]
https://github.com/Ellpeck/ActuallyAdditions/pull/926#issuecomment-331625065

**Comment by MarikCZ** [comment]
OK, I understand. No useless configs.
