### ISSUE TITLE
AA Worms and TCon Slimy Grass

### ISSUE THREAD

**Issue by ElvenChaos** [Ellpeck/ActuallyAdditions#1013]
If you take a hoe and spam right-click TCon's slimy grass (any variety of the 15), you can spawn as many worms as you want, as TCon slimy grass isn't tillable. Since the hoe doesn't actually do any tilling, it doesn't take durability loss and the process is infinitely repeatable.

If you take a worm and "plant" it on a slimy grass block, it will convert that block and any surrounding slimy grass blocks to regular farmland.

Edit: Does not affect slimy dirt.

**Comment by canitzp** [comment]
Lol

**Comment by ElvenChaos** [comment]
I'm sorry if I just opened a can of worms.

**Comment by Shadows-of-Fire** [comment]
Not really interested in adding a compile time dep on TiC to check if its specifically not that block...  TiC shouldn't extend BlockGrass if they don't want to be treated like one.

**Comment by ElvenChaos** [comment]
I'll post a ticket over there then, thank you for taking a look at this! :D

**Comment by canitzp** [comment]
@Shadow "&& !block.getRegistryName().getResourceDomain().startsWith(" tconstruct")" would be a really fast fix

**Comment by ElvenChaos** [comment]
@Shadows-of-Fire Would canitzp's suggestion or at least checking for successful tills be appropriate?
