### ISSUE TITLE
[suggestion] feature enabling/disabling config

### ISSUE THREAD

**Issue by soraphis** [Ellpeck/ActuallyAdditions#1016]
i think it would be awesome to have a way to disable sets of features (e.g. like it was solved in https://quark.vazkii.us/ ) 

since ActuallyAdditions adds a large range of different features that tend to overlap with stuff from other mods.

e.g.:
 -  i don't need the ore doubling if i use mekanism, ender I/O or tinkers constructs.
 - i may not need the different foods if i use pam's harvestcraft 

for my current modpack i'd love to keep the drill and the baubles stuff. but most of the other things would be disabled

**Comment by Shadows-of-Fire** [comment]
https://github.com/Ellpeck/ActuallyAdditions/pull/926#issuecomment-331625065

**Comment by soraphis** [comment]
oh, have not seen there was a PR ...

> I'm absolutely not a fan of the whole "put every little fucking thing into the config" thing, and I still have enough love for the mod to make this not happen.

sad to hear that, cause there are some cool features in this mod, but for me it violates to hard the unix principles "Write programs that do one thing and do it well." and "Write programs to work together.".

anyways, thx for the response.
