### ISSUE TITLE
Drill doesn't break limestone/marble in 3x3 pattern

### ISSUE THREAD

**Issue by Undeadbanana** [Ellpeck/ActuallyAdditions#1018]
Haven't gotten 5x5 pattern but guessing it's probably the same.

When breaking blocks with limestone within the 3x3 box, Limestone will not break. This even occurs when Limestone is the block you're breaking and there's adjacent limestone blocks; It'll simply break the targeted limestone plus any other non-limestone blocks.

Also affects marble. I'll update if I find more blocks.

**Comment by Undeadbanana** [comment]
![2018-01-30_10 24 45](https://user-images.githubusercontent.com/4379427/35583779-d9324662-05a7-11e8-95a7-78740bbc8a68.png)
![2018-01-30_10 24 47](https://user-images.githubusercontent.com/4379427/35583780-d960ec92-05a7-11e8-9e09-a8fab5d0aad1.png)

**Comment by Shadows-of-Fire** [comment]
AA ver?

**Comment by Undeadbanana** [comment]
r129

**Comment by Undeadbanana** [comment]
So far those are the only two I can find acting differently, only did a little bit of mining though so can't say for sure if those are the only two.

**Comment by Undeadbanana** [comment]
Obsidian is also affected.

**Comment by Shadows-of-Fire** [comment]
I feel like the nearby hardness comparison is missing an equals... Bleh.  I should have time to work on it soon

**Comment by Undeadbanana** [comment]
Working as intended in new update. Thanks!
