### ISSUE TITLE
Drill crashing while breaking block

### ISSUE THREAD

**Issue by tinbolw** [Ellpeck/ActuallyAdditions#1022]
Whenever I (or my friend) break a block with the drill, without any augments it breaks the block and it the game freezes, then crashes. If I do it with an unpowered drill, it doesnt crash. I tried it on my singleplayer mod in creative mode, and it still crashes. I am using ActuallyAdditions r128 and forge 1.12.2 with optifine. Can you please look into this?

**Comment by Shadows-of-Fire** [comment]
r128 is outdated and you haven't provided a crash log, so no.

**Comment by tinbolw** [comment]
Here,
[crash-2018-02-03_14.31.42-client.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1692254/crash-2018-02-03_14.31.42-client.txt)
