### ISSUE TITLE
Drill crashing

### ISSUE THREAD

**Issue by tinbolw** [Ellpeck/ActuallyAdditions#1023]
Drill crashing whenever I break a block.

My crash log: https://pastebin.com/E05fTU6d

My friends crash log: https://pastebin.com/06fDQWNp

We hosted a server on Aternos. That may be the case. I heard that r128 is also outdated but if I update the version will my progress be reset?

**Comment by Shadows-of-Fire** [comment]
You know, I just told you that r128 is outdated, so you've opened another issue...?
And what progress is there to even be reset?  AA doesn't have progress.
