### ISSUE TITLE
Drill still crashing

### ISSUE THREAD

**Issue by tinbolw** [Ellpeck/ActuallyAdditions#1024]
I updated to the latest version as you said, but I sill crash when trying to break a block.

Crash: https://pastebin.com/RAQea4S7
Using minecraft 1.12.2 with ActuallyAdditions r130, InventoryTweaks 1.63, jei 4.8.5.138, MouseTweaks 2.8, and optifine 1.12.2 HD_U_C8.

**Comment by Shadows-of-Fire** [comment]
Update forge.  You are almost 100 versions out of date.

**Comment by tinbolw** [comment]
k

**Comment by tinbolw** [comment]
thanks a ton!
