### ISSUE TITLE
[Bug?] Manual Does Not Detect Recipe Changes

### ISSUE THREAD

**Issue by ElvenChaos** [Ellpeck/ActuallyAdditions#1026]
If a basic crafting recipe from Act. Adds. gets changed via craft/mod tweaker, the change is successful, but is not reflected in the Act. Adds. manual. The manual should reflect the new, actual recipe instead of the old one. _(Sorry if this is a mod tweaker issue!)_

If you need an example case, here is the script used:
```
val diamond = <minecraft:diamond>;
val sharp5 = <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 16 as short}]});
recipes.removeShapeless(<actuallyadditions:item_more_damage_lens>);
recipes.addShapeless(<actuallyadditions:item_more_damage_lens>, [
	<actuallyadditions:item_damage_lens>,sharp5,diamond,diamond]);
```

MC: 1.12.2
Act. Adds.: r130
Craft Tweaker: 8.1.6
Mod Tweaker: 4.0.6

**Comment by Quarris** [comment]
Definitely not a bug. AA i has nothing to do with any recipes being changed. If AA changes its recipes then they will also changed the book to match them. It would be nearly impossible to predict all the things that CT could change and match the book to adapt all the changes.

**Comment by Shadows-of-Fire** [comment]
AA can't tell when you change a recipe for something.  That, and AA _also_ can't tell which recipe (if multiple were to exist) would be the one to display in the book.  The only real solution would be to add a zen method in AA to allow changing the recipe on the page.  But I'm not sure if I want to do that.

**Comment by Ellpeck** [comment]
Hey. If you want this issue fixed then ask the author of ModTweaker (which does the MineTweaker integration) to also add compatibility to change the recipes displayed on book pages. From our side, there's not really a fix available, I'm sorry.

**Comment by ElvenChaos** [comment]
Thanks for the replies! Much appreciated!
