### ISSUE TITLE
Conflict with AA and RFworlds  using twlight forest world gen items

### ISSUE THREAD

**Issue by CharZinta** [Ellpeck/ActuallyAdditions#1028]
I ran a DW20 VER 1.7.1 server for the longest time no issues but when someone started RFTOOLS worlds we started having issues.  I'm hoping you can take a look at this and see if you notice anything on youer end. I believe I will have to reach out to the forge team as well as the RFTOOLS Team

https://github.com/Ellpeck/ActuallyAdditions/issues/1005

The above ISSUE is marked closed and you mention the error isn't a problem.  We never had that error until someone started using RFTOOLS worlds.   We now get 6 "copies" of this error per second and the log grows exponentially non-stop    I'm trying to establish where this error originates and have found the above (in subject line) to be true.  I've tested this on an existing MP world and clean MP world,  SP works fineThe problem is its random and client crash/disconnect 90% of the time and only corrupts all worlds on the sever < 10% of the time

Replicate error:
RFTOOLS worlds basic setup (1 enscriber, 1 builder, 1 dialer, one destination anaylzyer, 1 matter transmitter, 1 matter receiver)
Take a blank tab, put it in the inscriber, name it  (I used randomblank for mine) save it
Place it in the dialer, check, then dial
If the world is clean and you don't client crash you hit the lucky 1% lotto.
If its a client crash, nothing bad happens just need to be moved back to the overworld by someone with "move others" powers or edit the player.dat file to change Dimension entry.
If its the world corruption bug roll back to previous backup. All the ID's will have changed and all world files are now corrupt.

**Comment by Shadows-of-Fire** [comment]
Its not an issue.  Stop using outdated versions and complaining.

**Comment by CharZinta** [comment]
DW20 is a 1.12.2 Server running Forge 14.23.1.2587 and is built by DireWolf. The version of AA is  ActuallyAdditions-1.12.2-r127.jar
So while I understand your saying we are, currently, 3 versions behind on AA we don't control what the pack author does..

Thank you for your time in this matter

**Comment by ktole1999** [comment]
so @Shadows-of-Fire you are saying this rftools issue is resolved in latest release of AA?

**Comment by YasminEndusa** [comment]
@CharZinta It is true that you don't control what the pack author does, but since the bug is fixed, complaining here won't change anything. It's not like the bug could be fixed remote in an existing instance of a server... well, technically it could but that's not the point.  
The right place to complain would be the modpack page on curseforge. Open an issue with the pack author to create a new version of the pack containing the updated mod.  
As a workaround, there is no rule saying you can't replace the AA jar file yourself.
