### ISSUE TITLE
[1.12.2] Extracting items from Farmer is to slow

### ISSUE THREAD

**Issue by Morpheus1101** [Ellpeck/ActuallyAdditions#1029]
Running a 15x15 growing MysticalAgri crops, i fin dno matter what method i use, i just cant seem to pull the items out fast enough form the farmer before it ends up filling an spitting items out the top.  Now considering it wouldnt have as much items or as fast compared to say the Builder used as a Quarry from rftools, i feel confident in saying there is a limitation somewhere in the farmer itself.

**Comment by Shadows-of-Fire** [comment]
Extraction speed is entirely dependent on the pipe that is requesting the extraction.  The farmer does not auto export, so you might want to consider getting a faster pipe.  As an inventory, the farmer isn't any different than a normal chest aside from automation can't pipe from the seed input slots or into the output slots, but it does not restrict export speed.
