### ISSUE TITLE
block don't drop

### ISSUE THREAD

**Issue by tryolivier** [Ellpeck/ActuallyAdditions#1031]
hello,

the block like atomic reconstructor, coalgenerator who are spawned with the engineer house can be break but when we break them they don't drop

but if i take one from creative and i place it the player in survival can break it and it's drop !
so the problem and when the house is generated

thanks to have a look ;)

thanks =)

**Comment by Quarris** [comment]
The point is that the auto generated machines from the house cannot be broken. It's intentional.

**Comment by tryolivier** [comment]
but we can change that ? I want the player can

thanks

**Comment by Quarris** [comment]
I'm fairly certain that you cannot change it in the configs. However I may be wrong on that one, but knowing Ellpeck you can't.

**Comment by raphydaphy** [comment]
Use a moving wand if you reallly want it , but the whole point of the house is that you can't remove the machines. They are really cheap to craft anyway.

**Comment by tryolivier** [comment]
ok thanks

**Comment by Ellpeck** [comment]
It.. literally says in the chat why it doesn't drop. Learn to read.
