### ISSUE TITLE
Sugestion- Phantum Energy Face

### ISSUE THREAD

**Issue by CTH999** [Ellpeck/ActuallyAdditions#1033]
So, the Phantom Energy Face has a limit. However, I think that limit should be the 64-bit integer limit. That way, it can work with draconic Evolutions energy orb.

However, that's just a thought.

**Comment by canitzp** [comment]
The energy system AA is using is the default Forge enegery and it is only capable of handling 32 bit int.

**Comment by Shadows-of-Fire** [comment]
I assume that's what he meant, as I think DE only uses a long for internal storage but is forced to use an int for transfer due to FE anyway, but I'm not a fan of the stupid inflated RF nonsense, so, not gonna do this.

**Comment by CTH999** [comment]
Well, could you-

A. Use The [Redstone Flux API](https://minecraft.curseforge.com/projects/redstone-flux)
B. At least the 32-bit integer limit?

Also, would making it use the 64-bit integer make the code much more complicated?
Just wonderinging

**Comment by Ellpeck** [comment]
A. No, it's outdated and a better version is integrated into Forge
B. It already uses the 32 bit integer limit

And yes, it would, because it's literally impossible to make it use the 64 bit integer limit for transfer lol
The Forge Energy API just doesn't allow that.

**Comment by CTH999** [comment]
ok, fair enough!

(Forge, I have an issue with you!)
I'm opening an issue for it!
