### ISSUE TITLE
Farmer dupe bug

### ISSUE THREAD

**Issue by TheHeavenOnMoon** [Ellpeck/ActuallyAdditions#1034]
One of my farmer keeps harvesting crops while not resetting the plants growth state to 0%. I used it in combination with mystical agriculture seeds. Atm i cant reproduce it but ill let you know when i can.

EDIT: btw im using r128 atm because thats the one our server uses atm. is that fixed in newer versions?

**Comment by Shadows-of-Fire** [comment]
Well you mentioned you can't reproduce it and there's been nothing else said here, so...
