### ISSUE TITLE
Suggestion: Config option to display other energy units

### ISSUE THREAD

**Issue by Ithronyar** [Ellpeck/ActuallyAdditions#1036]
Small suggestion. Converts the CF item/machine tooltips and readout text to whatever energy unit the user sets it to. This is for modpacks/environments that want to unify the game's power readouts. Options would be FE, Tesla, RF, etc.

Doesn't actually change the internal workings of the mod's energy, just the information the player sees.

**Comment by Shadows-of-Fire** [comment]
Those are all the exact same thing.  There's no point to add that.
