### ISSUE TITLE
Suggestion: Config option to disable manual

### ISSUE THREAD

**Issue by Ithronyar** [Ellpeck/ActuallyAdditions#1037]
When enabled, it removes the manual's recipe and its JEI integration. This is for when the manual isn't needed, due to either player experience or some other documentation method. It's kind of extreme to disable the entire manual, but the only other compatibility-friendly option would be for the manual to be completely editable via configs (XML, maybe). An option for disabling it is much simpler.

**Comment by raphydaphy** [comment]
This already is possible, simply turn off"Booklet Quick Opening Info" and "Give Booklet on First Craft" in the config.

**Comment by Ithronyar** [comment]
@raphydaphy That doesn't remove the JEI tab, though. Which means the manual is still technically there.

**Comment by raphydaphy** [comment]
why would you want to remove it from JEI? Disabling booklet iinfo and not automatically giving the player a booklet is more than enough, and you can even disable the recipe using CraftTweaker if you want to that badly.

**Comment by Ithronyar** [comment]
Fine, I'll say it. It's not very immersive, constantly acknowledges that you're playing a mod, and it's filled with webpage links that kind of defeat the point of an in-game manual. Since I doubt it will ever be possible to modify it with XML/cfg/txt/whatever, an option to completely disable it is the next best thing.

**Comment by raphydaphy** [comment]
Although that is a common thing that is present in many mods (botania lexicon much?), disabling the recipe and turning it off in the config will restore your immersion completely. If you want to be really immersive, you shouldn't be using a mod such as JEI in the first place as it takes away from the immersion by providing a list of items and a way to make them. If you are in fact not using JEI then you will never see the icon for the book, hence it may as well not be existant.

**Comment by Ithronyar** [comment]
JEI is a necessary evil. The vanilla recipe system is lacking, and without JEI there's no way of knowing what's in the game without tabbing out and browsing wikis for every mod you have installed. _That's_ unimmersive.

**Comment by raphydaphy** [comment]
So, JEI is alright but a tiny, nonfunctional icon of a booklet within one of the many pages of recipes is terrible and breaks your immersion?

**Comment by Ithronyar** [comment]
Yes, because it leads to the rest of the AA manual. Which isn't immersive to read/navigate. It may not even be wanted/needed in certain environments. So a config option to disable that manual would be useful. A good user experience relies on details and seamless integration with the game. JEI integrates well. The manual doesn't.

**Comment by Quarris** [comment]
Its ridiculous, You can disable the booklet on first craft; you can turn off the recipe with crafttweaker; you can even hide the icon from jei either using crafttweaker or jei itself, Its as if the booklet never existed. It *really* isn't necessary.

**Comment by canitzp** [comment]
Wut 🙄

**Comment by Ellpeck** [comment]
The fuck, why did you even hesitate @canitzp @Shadows-of-Fire?
Of course not.

**Comment by Ellpeck** [comment]
Also @Ithronyar:
No, you're wrong. The way the manual integrates with the game IS through acknowledging that it's part of a game. It's the kind of narrative I went for with it. That's not "unimmersive" or "a bad decision", it's a conscious design choice.
Actually Additions isn't Botania, and I don't want it to be.
