### ISSUE TITLE
[SUGGESTION] Config Experience solidifier

### ISSUE THREAD

**Issue by Okii35** [Ellpeck/ActuallyAdditions#1038]
Hello.
Can you add a config to disable the auto catch Xp of Experience Solidifer ?

**Comment by Ellpeck** [comment]
I'm pretty sure you can just give it a redstone signal to disable that, can't you?

**Comment by Okii35** [comment]
It's not for me but for a server. This is to avoid people recovers exp without being connected just with a factory to mob and a item chunk loader

**Comment by Ellpeck** [comment]
What's so bad about that? 👀

**Comment by Teibidh** [comment]
Sounds more like a chunk loading issue, to me. If you don't want people "playing the game" when they're not connected, don't use chunk loaders... otherwise you'll be having this conversation for automated farming (crops and mods), and everything else?

**Comment by Okii35** [comment]
At first I wanted to use the Solidifierjust to store exp. And not to automate something.

**Comment by Shadows-of-Fire** [comment]
Closing as non-issue
