### ISSUE TITLE
Breaking Bonsai Pot or Hopping Bonsai Pot with AA Drill duplicates them.

### ISSUE THREAD

**Issue by ftog-thorgal** [Ellpeck/ActuallyAdditions#1041]
Forge: 14.23.2.2611
AA: 1.12.2-r130
Bonsai: 1.0.1-b56

When breaking a Bonsai Pot or Hopping Bonsai Pot it drops two of them. I am reporting it in the AA Github because I tried other mods drills, pickaxes, and axes but was not able to replicate it with those, so I am guessing it is something in the AA code.

**Comment by Shadows-of-Fire** [comment]
Right so you can provide a crash report or I can close this issue

**Comment by Shadows-of-Fire** [comment]
Or maybe I cant read...  Anyhow... is that thing a multiblock of sorts?

**Comment by ftog-thorgal** [comment]
There is no crash. The Bonsai Pot or Hopping Bonsai Pot are one block structures used to grow trees. When I break them with the AA drill it drops two of them on the ground instead of only one - that was placed.

Let me explain further how the Bonsai Pots work: You place the Pot down, then right click it with a sapling. When it it grows a miniature tree, you can then manually harvest it (Regular Bonsai Pot) or it will automatically harvest the tree and put the items in a storage underneith it (Hopping Bonsai Pot).

When you want to remove the pot, you have to break the tree in it first (which returns the sapling) and then break it again to actually get the Pot back. With the AA drill, it just breaks the Pot, regardless if it has a sapling in it or not, and gives you two back (with or without sapling tested).

Hope this helps.

**Comment by Shadows-of-Fire** [comment]
Weird... the AA drill uses the exact same code that TiC uses for its hammer.  It sounds like the bonsai pot isnt properly reacting to a block break, but I'm not sure whats going on.

**Comment by ftog-thorgal** [comment]
I just tested it with a TiC hammer and can not replicate this issue (just wanted to save you some time testing it yourself as I did not test it with a TiC hammer when I opened the issue).

**Comment by Shadows-of-Fire** [comment]
Were these tests in creative or survival?

**Comment by Shadows-of-Fire** [comment]
*Might be fixed*

**Comment by SkippyMitch** [comment]
I'm able to replicate this problem with a TiC axe. Thought I'd comment here instead of making a new issue
