### ISSUE TITLE
Anyway to remove all recipes from the crusher?

### ISSUE THREAD

**Issue by truehunterethan** [Ellpeck/ActuallyAdditions#1046]
I want the people playing my pack to only be able to use the EnderIO sagmill, because the pack is loosely based on EnderIO, is there a remove all config or modtweaker script thing to remove them all?

I already disabled the recipe for the block itself, but the crusher recipe panel thing still shows up in JEI

**Comment by JuliusFreudenberger** [comment]
To sum things up which were discussed in discord: You have to disable every single crusher recipe.

**Comment by Shadows-of-Fire** [comment]
*how about you just remove the crusher recipe*

**Comment by truehunterethan** [comment]
>I already disabled the recipe for the block itself, but the crusher recipe panel thing still shows up in JEI

**Comment by Shadows-of-Fire** [comment]
So what, ignore it.
