### ISSUE TITLE
Option to change how often a village contains the engineer house

### ISSUE THREAD

**Issue by MarioSMB** [Ellpeck/ActuallyAdditions#1047]
These houses are a very easy source of the large chests and a lot of machinery related items and gear (even with the treasure chest loot turned off). 

It would be nice to have only a low chance to encounter these houses, much like villages can often appear without the blacksmith house.

**Comment by Ellpeck** [comment]
No, I'm sorry. The chance is already kind of low, but it doesn't really have as big of an impact on if they actually spawn as you might think.
Plus, you can't take the machines with you anyway, so it's honestly not a big deal.
