### ISSUE TITLE
Villagers breaking crops

### ISSUE THREAD

**Issue by MarioSMB** [Ellpeck/ActuallyAdditions#1048]
Farmer villagers will break and attempt to replant Actually Additions crops, but they can't collect any of the drops, so the items are left scattered around the farmland.

**Comment by Ellpeck** [comment]
This is unfixable because villager farming is hardcoded in Minecraft.
It might've changed by now though so I'll leave this open for now.

**Comment by Shadows-of-Fire** [comment]
So far no changes in that section.
Duplicate of #959
