### ISSUE TITLE
Crafting Table on a Stick Does Not Work on Servers

### ISSUE THREAD

**Issue by Darkosto** [Ellpeck/ActuallyAdditions#1051]
https://pste.me/#/yRy9j <-- is the output in the server log when trying to use it and the GUI does not come up to use the item.

MC: 1.12.2
Forge: 2367
AA: r132

Thanks

**Comment by Shadows-of-Fire** [comment]
Right.  I swear I tested it on a server but I've missed an `@SideOnly(Side.CLIENT)`.
Bleh.
