### ISSUE TITLE
help

### ISSUE THREAD

**Issue by demon57730** [Ellpeck/ActuallyAdditions#1052]
Hello I need help I have a server forge:
forge-1.12.2-14.23.2.2625-universal.jar
ActuallyAdditions-1.12.2-r132.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar

plugins : 

CatClearLag-0.8.jar
EagleFactions-1.12.2-v0.9.10.jar
InvSync-0.6.17.jar
LuckPerms-Sponge-4.1.15.jar
Nucleus-1.3.3-S7.0-MC1.12.2-plugin.jar
PlayerShopsRPG-2.1.0.jar
projectcore-7.1.0-0.2.2.jar
TotalEconomy-1.8.0.jar

the problem come sponge be a plugin because without sponge no problem

he has no error display

here is the concern with experience solidifier when we click on a figure consumes the XP but its does not give the solid experience

I do not find it plugins or if in sponge you have to put a config for it to work

I ask your help

**Comment by Shadows-of-Fire** [comment]
Sponge is not supported

**Comment by demon57730** [comment]
I know but I am asking for help for your mod

**Comment by demon57730** [comment]
So, since you have a problem file for your mod, I'll have to delete it from my server
