### ISSUE TITLE
[Request] config option to remove bio-mash recipes

### ISSUE THREAD

**Issue by xkforce** [Ellpeck/ActuallyAdditions#1053]
I am trying to use the actually additions knife in new food crafting recipes but any recipe that is added via crafttweaker is overridden by the default bio-mash recipes.  Furthermore I would rather the bio-mash mechanic not be in the pack I am making but I don't see a way to actually remove it in the config or otherwise.

**Comment by Shadows-of-Fire** [comment]
Crafttweaker is a thing
