### ISSUE TITLE
Water bowl in offhand becomes a bowl of ultimate destruction

### ISSUE THREAD

**Issue by TreeKittens** [Ellpeck/ActuallyAdditions#1061]
I put a water bowl in my offhand...

and it completely ruined my landscape, repeatedly creating water sources without emptying itself...AND while replacing the item in my first slot with a wooden bowl.

**Comment by canitzp** [comment]
lul wtf

**Comment by canitzp** [comment]
which mod, forge and mc version?

**Comment by Quarris** [comment]
that is... hillarious
