### ISSUE TITLE
Config resets

### ISSUE THREAD

**Issue by JohnC94** [Ellpeck/ActuallyAdditions#107]
The config file is reset whenever the client launches.

I couldn't find anything in the logs that would explain it.

**Comment by Ellpeck** [comment]
Are you making the changes in the file itself or in the Config GUI in-game?

**Comment by JohnC94** [comment]
The file itself. I'll change this to false. After I start up the game, it will be back to true.
# Show the 'Press Control for more Info'-Text on Item Tooltips
    B:"Advanced Info Tooltips"=true

**Comment by Ellpeck** [comment]
Try using the in-game config option and see if the bug still occurs.

**Comment by Ellpeck** [comment]
I can't reproduce, neither with the GUI nor the file directly.

**Comment by Ellpeck** [comment]
Actually, never mind. 
I *can* reproduce.
This is very odd.

**Comment by JohnC94** [comment]
I didn't want to waste your time or anything. But this has slowly been driving me mad.

I edited the config with the gui in game and then hopped intoa  single player world and the config change stuck (no tooltip). I'm restarting the game now to see if the edit stays.

**Comment by JohnC94** [comment]
Yeah, after restarting the client, the config is back to normal.
