### ISSUE TITLE
[Issue] Auto-Breaker dupes clay

### ISSUE THREAD

**Issue by Havanacus** [Ellpeck/ActuallyAdditions#1073]
Minecraft 1.12.2
Forge 14.23.3.2655
Actually Additions 1.12.2-r133

Issue:  Auto-Breaker mines 7 clay balls per clay block.  Only happens if Auto-Breaker inventory is empty.  If there is already clay in the Auto-Breaker, it mines only 4 as expected.

**Comment by Ellpeck** [comment]
the heck

**Comment by TheSnowyChickens** [comment]
Easy clay farm xD
It also work in 135.

**Comment by MaienM** [comment]
This seems to have reappeared at some point, I just ran into this using ActuallyAdditions-1.12.2-r151-2.
