### ISSUE TITLE
Crash with latest forge(1.12.2)

### ISSUE THREAD

**Issue by HotDelphox** [Ellpeck/ActuallyAdditions#1074]
I am getting this crash when running Actually Additions with the latest version of forge on 1.12.2 
[crash-2018-04-15_18.49.10-client.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1911985/crash-2018-04-15_18.49.10-client.txt)

**Comment by Shadows-of-Fire** [comment]
`reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`
https://github.com/Ellpeck/ActuallyAdditions/issues/1068
