### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by Stephenator0316** [Ellpeck/ActuallyAdditions#1076]
pastebin.xyz/p?q=b1IwM1Q

**Comment by Shadows-of-Fire** [comment]
wat
that's not even a link
and honestly, without looking at it, #1068

**Comment by Stephenator0316** [comment]
HOW IS THAT NOT A FUCKIN LINK GITHUB?

pastebin.xyz/p?q=b1IwM1Q
pastebin.xyz/p?q=b1IwM1Q
pastebin.xyz/p?q=b1IwM1Q

**Comment by Stephenator0316** [comment]
.-.

**Comment by Stephenator0316** [comment]
And yeah, that's it
