### ISSUE TITLE
The crafting table on the stick deletes items when closed

### ISSUE THREAD

**Issue by CrazyAboutMaths** [Ellpeck/ActuallyAdditions#1078]
MC Version: 1.12
Mod Version: 133
Forge Version: 14.23.2.2654

To recreate: Put items in the crafting table on a stick and close the table and those items get deleted

Why: In 1.12 it was changed so that when a vanilla crafting table is closed the items automatically go back into your inventory and I think this messed with the crafting table on a stick

**Comment by Shadows-of-Fire** [comment]
This only happens when RealBench is present.  I'll probably have to go PR something to them to fix this properly.

**Comment by Shadows-of-Fire** [comment]
This issue will be resolved by the next release of AA and FastWorkbench 1.3.2.  If FastWorkbench is present with RealBench and AA, this won't happen.  However, using just RealBench and AA this issue will still occur, and nothing can really be done about that.
