### ISSUE TITLE
[Compatibility Request] Farmer not getting Industrial Hemp Fiber from Immersive Engineering

### ISSUE THREAD

**Issue by winsrp** [Ellpeck/ActuallyAdditions#1080]
Well, as a seed it does plant it, but it does not collects it, it should be like sugar canes that it just cuts the top half of the hemp fiber plant, and leaves the bottom, this only grows to a height of 2.

Plz!

**Comment by canitzp** [comment]
I have seen this issue more than one time now, I think if Shadow don't implement it, I just make a addon mod to add this kind of compatibility

**Comment by winsrp** [comment]
shouldn't it be like something simple?

**Comment by Shadows-of-Fire** [comment]
It is simple.  It would be nice if IE implemented it, but I'll get around to it eventually if not.  Might bring it up with malte to see if IE will do it.

**Comment by Ellpeck** [comment]
Hey @BluSunrize please implement this because we know that you love AA <3

**Comment by BluSunrize** [comment]
How difficult is it? =P

**Comment by Ellpeck** [comment]
Just implement [this](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/api/farmer/IFarmerBehavior.java).

**Comment by BluSunrize** [comment]
There you go!

**Comment by winsrp** [comment]
ain't things cool when we all play nice XD
