### ISSUE TITLE
[Suggestion] Item recycler

### ISSUE THREAD

**Issue by winsrp** [Ellpeck/ActuallyAdditions#1081]
So once you have a farm for a spawner you start filling up on useless items, tons of armor, weapons, shields and tools that have no use and just stack up, so why not a recycler of some kind that can take items and break them into nuggets, strips, or something like it, could be crystals or what ever, the thing is just get rid of useless stuff without just tossing it around.

It could require RF, lava, empowered canola oil, or anything in between, it could require to be fully repaired as well, so we use the repairer, or several (a speed upgrade like the one on the drill on this thing would do wonders, and on other machines as well, btw).

The general idea just fits great with your mod, take normal stuff and transmute it into something else for a different purpose.

**Comment by canitzp** [comment]
I like this idea

**Comment by winsrp** [comment]
I'll add a little bit more to this, one interesting way to do it is that the recycler needs solid XP as well as power, so this is not something that is made so early on in a normal game, the recipe would require a double crusher and it requires items to be fully repaired so the repairer need to be done first as well.

This would become some sort of uncrafting thing, where it will return the materials of items so just a simple what was the recipe and return those instead of so much trouble making up stuff, if you do this on a enchanted item it will lose the enchantments since we already have the lens of disenchanting.

In config you could specify how much solid XP it is required, as well as how much it will cost in power to recycle an item, so lets say... 100 solid XP and 100.000 power per item (it needs to be expensive)

**Comment by PotatoFlavour** [comment]
Doesn't Immersive Engineering have a solution for this? I believe the mod has an ARC-Furnace that has a recycling function where it turns armor into ingots. This is assuming you're playing a modpack with IE though.
