### ISSUE TITLE
[1.12.2] Villagers ("bug"?) farmer interaction

### ISSUE THREAD

**Issue by TheSnowyChickens** [Ellpeck/ActuallyAdditions#1082]
Hello,

I created new world with a village next to the spawn and after a while I could see, that villagers can't plant your seeds from your plants. They can harvest it, but thats all.
So after a time, the whole field will be empty out of your seeds and be planted with normal seeds.

Can you maybe change there something, maybe a chest, where the villagers can storage the second output of your plants and the seeds can be re-planted?

![2018-04-28_23 59 54](https://user-images.githubusercontent.com/29357962/39401212-4ba556ca-4b40-11e8-8013-c7ed290b818d.png)

MC 1.12.2
1.12.2-forge1.12.2-14.23.3.2676
ActuallyAdditions-1.12.2-r134

**Comment by Shadows-of-Fire** [comment]
Vanilla bug.  Won't be doing anything about it.

**Comment by TheSnowyChickens** [comment]
Oh, thats bad.
:(
