### ISSUE TITLE
[MC-1.12.2 | AA-r134] NPE on server kick when viewing the booklet

### ISSUE THREAD

**Issue by hayesj1** [Ellpeck/ActuallyAdditions#1084]
[https://pastebin.com/Sw8px1hg](https://pastebin.com/Sw8px1hg)

My client suddenly crashed whilst viewing the guide book. I have an idle timeout on my server, and it's very possible the 7 mins were up, but I'm not 100% certain. Meaning its possible the crash is related to being kicked from a server with the book open. I was viewing the coffee chapter if that's of any use.

**Comment by hayesj1** [comment]
Just did another two tests: First I left the table of contents open in the guide book; same crash, after exactly 7 minutes(i.e. my idle timeout period). Second, I opened the book and kicked myself from via the server console: same crash.

This leads me to believe the NPE is related to being kicked in general, not just via idle timeout.

I forgot to mention this is with AA r134, on mc 1.12.2, with forge versions 14.23.3.2669 (server) and 14.23.3.2668 (client).

**Comment by Shadows-of-Fire** [comment]
Weird.  Only way that crash happens is if the gui tries to close when the client player is null

**Comment by hayesj1** [comment]
Just a hunch, but maybe some functionality is being executed at the wrong time? I should note that I don't crash immediately on kick; I get the dirt screen for a few seconds, but instead getting the "you've been kicked" text, I get a CTD. For example, maybe your gui cleanup is being executed later than it should be?
