### ISSUE TITLE
[suggestion] single inventory slot option for precision dropper.

### ISSUE THREAD

**Issue by Legion7766** [Ellpeck/ActuallyAdditions#1087]
I have a couple setups where for the precision dropper i use a random item (sticks) to block of inventory slots in the dropper so i can export only 1 stack of a type of item.  It would be nice to have either an option to only allow one slot to accept items or a different version of the dropper that only has one inventory slot.

**Comment by FlesHBoX** [comment]
Just found this today and wanted to add some support for it.  Either a single slot precision dropper, or a UI option to lock out all but one slot would be uhmazing!
