### ISSUE TITLE
[1.12.2] Lens of disenchanting

### ISSUE THREAD

**Issue by TheSnowyChickens** [Ellpeck/ActuallyAdditions#1091]
MC 1.12.2
AA: 135
Forge 1.12.2 - 14.23.3.2689

The Atomic reconstructor split enchanted books, without the lens, into 3 books (in my case)

![grafik](https://user-images.githubusercontent.com/29357962/39972021-d640d882-5706-11e8-913d-0ed86a957514.png)

I throwed 1 book (empty) and 1 book with 3 enchantments in front of the laser.

![grafik](https://user-images.githubusercontent.com/29357962/39972029-fbe6ea04-5706-11e8-820d-dfe7cd24e799.png)

With the infos from your book and 1 lens of disenchanting, nothing happend with the ench. book and the normal book.

**Comment by Shadows-of-Fire** [comment]
working as intended, as far as i can tell...
