### ISSUE TITLE
[BUG]] Using traveler sack to unload is content on inventory doesn't clear is content

### ISSUE THREAD

**Issue by NikkoScript** [Ellpeck/ActuallyAdditions#1092]
I don't know if this is a bug from Actually addition or Tinker construct .
I use my Traveler sack full of wood to replenish a seared furnace , the wood doesn't disapear from the Sack. 
Here some more information 
 Modpack FTB Direwolf20 1.12.2.
The traveller sack was renamed thanks to an anvil. ("Fourre tout").
Autoinsert off , default filter configuration.
Shitf right click into the furnace controller to emptying the content of the sack.
The furnace is loaded but the wood stay in the sack.

Foresty Foresting backpack doesn't have this issue

**Comment by Shadows-of-Fire** [comment]
SlimeKnights/TinkersConstruct#3777
