### ISSUE TITLE
[Question] How to add recipes to Empowerer via api

### ISSUE THREAD

**Issue by PanSzelescik** [Ellpeck/ActuallyAdditions#1093]
I have downloaded api, but I don't know how to add recipes via: [EmpowererRecipe.java](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/api/recipe/EmpowererRecipe.java)

**Comment by Quarris** [comment]
ActuallyAdditionsAPI#addEmpowererRecipe

**Comment by PanSzelescik** [comment]
Yeah, it's working, thanks :)
