### ISSUE TITLE
[Feature request] Config option to disable crafting the vertical digger

### ISSUE THREAD

**Issue by winsrp** [Ellpeck/ActuallyAdditions#1094]
Well it's just as the title says, an option to disable the crafting of the vertical digger, I want ppl on my server to actually get down to business in person and use the plethora of tools available in the game, instead of a machine that digs for them.

**Comment by Shadows-of-Fire** [comment]
crafttweaker is a thing

**Comment by winsrp** [comment]
ok, and how would go about doing it with crafttweaker?

**Comment by Shadows-of-Fire** [comment]
https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Recipes/Crafting/Recipes_Crafting_Table/

**Comment by winsrp** [comment]
hmm... I'll give it a try, tx

**Comment by winsrp** [comment]
excuse my ignorance, but I'm using this line in a script

recipes.remove(<actuallyadditions:block_miner>)

but it returns an error when loading the game

![image](https://user-images.githubusercontent.com/13665046/40322278-122ba690-5cef-11e8-9fca-44b2224b4ea7.png)

this is a single player test.??? any ideas what did I do wrong?
