### ISSUE TITLE
[Bug?] Lag with trying to import to a full Item Laser system.

### ISSUE THREAD

**Issue by Notawallplan** [Ellpeck/ActuallyAdditions#1096]
Actually Additions ver: 1.12.2-r135
Thermal Dynamics ver: 2.4.1.10

Reproduce:
Set up a AA item system with a full chest, two lasers, and an item interface. Place an itemduct on the item interface and try to extract to the item interface.

**Comment by Notawallplan** [comment]
XNet also causes this.

**Comment by Shadows-of-Fire** [comment]
Performance concerns should be accompanied with a profiler snapshot (.nps file)
