### ISSUE TITLE
[Bug] [Mod interaction] AE2 storage bus unable to extract from AA item laser network

### ISSUE THREAD

**Issue by Notawallplan** [Ellpeck/ActuallyAdditions#1098]
Title.

**Comment by Quarris** [comment]
Definitely not a bug, I am pretty sure that Ellpeck will never allow this interaction to happen to be honest,

**Comment by Notawallplan** [comment]
But the AE system can see all items that the Item Interface has spoofed, and insertion is possible. Just not extraction.

**Comment by Ellpeck** [comment]
Do you have the items in the Extraction side of the lasers (in case they're advanced) or have them set to an empty blacklist?

**Comment by Notawallplan** [comment]
Issue fixed due to problem between computer and chair. *facepalm*
