### ISSUE TITLE
Console spam filling the server log

### ISSUE THREAD

**Issue by Renadarain** [Ellpeck/ActuallyAdditions#110]
Hi :)

Is there a way to turn off the world saving or at least make it less often?  My server console is constantly spammed with this.....
http://pastebin.com/Z1THAPsM

and it makes it hard to scroll through to spot any errors if things go wrong.

Thanks :)

Regards,
Renada

**Comment by Ellpeck** [comment]
Just update the mod, it's been removed :)

**Comment by Renadarain** [comment]
Oh thank you :)  Appreciate that.

Regards,
Renada
