### ISSUE TITLE
Place-able Block Dupe with Auto-Placer

### ISSUE THREAD

**Issue by sesgoe** [Ellpeck/ActuallyAdditions#1100]
Relevant Info:

Modpack: Enigmatica 2: Expert

Actually Additions Version: ActuallyAdditions-1.12.2-r135
Forge Version: forge-14.23.3.2689

Unlisted Video Link of Replication: https://www.youtube.com/watch?v=5V0Gqws___c
(Apologies for the BG/breathing noises, just wanted to get a quick clip of replication)

I reached out to Ellpeck privately first and he suggested I post this here--I didn't know of another private channel to post this issue for server admin purposes, etc. but thought it was important to mention regardless.

Let me know if I can help out further.

Thanks!

**Comment by raphydaphy** [comment]
hey this happened to me too, in Foolcraft 3. I was using the placer to automate a pure daisy (botania), and the wood/stone got placed but also remained in the placer's inventory. It happened to all 8 of my auto-placers and the placed wood/stone is also a ghost block which cant be interacted with on the client - only the server.
