### ISSUE TITLE
[Bug] Lasers' beams don't show after using a Laser Wrench (even with Invisibility Upgrade and Infrared Goggles)

### ISSUE THREAD

**Issue by kenlauescuadro** [Ellpeck/ActuallyAdditions#1101]
Bug exists in version 1.12-r135.

The title pretty much says it all.

By the way, it even says "Laser connection modified!", like it (the Laser Wrench) did connect the two lasers, but the beam between them still isn't showing.

**Comment by ReiDaTecnologia** [comment]
I can confirm that this bug also occurs in version 134 that is being used in the modpack "All the Mods 3".

**Comment by kenlauescuadro** [comment]
Sorry for posting in a very old topic, but I think I just discovered why this occurs. When Laser A is connected to Laser B and Laser B is connected to Laser C, connecting Laser C and A doesn't connect it (or maybe at least show the laser beam) because Laser C is connected to Laser B, which is already connected to Laser A. Simply, I think the lasers prevent loops in laser connections.

Not sure about more than three lasers though; I haven't tested it with four or more lasers.

**Comment by Ellpeck** [comment]
Loops in laser networks are disallowed by design.
