### ISSUE TITLE
Farmer not harvesting as expected.

### ISSUE THREAD

**Issue by orville94Bailey** [Ellpeck/ActuallyAdditions#1102]
I've got the following farm setup:
![image](https://user-images.githubusercontent.com/6867200/40621726-f3c41a66-626b-11e8-84c9-d41e9911e86b.png)

Here's the typical inventory of the farmer:
![image](https://user-images.githubusercontent.com/6867200/40621740-09c27682-626c-11e8-8d0e-fb42db33ed49.png)

Here's what's happening:
When harvesting the right side of the farmer is filling with the products of the Immersive Engineering as expected.  The problem is the potatoes, the farmer is not putting the grown potatoes on the right side when they're harvested.

I would expect that any output harvested by the farmer would be output into the box on the right, however when harvested potatoes are being put on the left where the rest of their "seed" stack is.

**Comment by orville94Bailey** [comment]
As an update to this issue:

Once the Farmer fills it's seed slots with potatoes it functions as expected.

**Comment by Shadows-of-Fire** [comment]
working as intended

**Comment by orville94Bailey** [comment]
Thank's for the quick follow up.
