### ISSUE TITLE
Enervator not accepting energy

### ISSUE THREAD

**Issue by Tyranuss** [Ellpeck/ActuallyAdditions#1113]
Hello,

Like the title says Enervator does not accept RF/EF or whatever we call it these days. 

Minecraft 1.12.2 version
ActuallyAdditions-1.12.2-r135 version

I have tried EnderIO energy conduits (all versions), tried Laser relays both versions, tried Extra Utilites Wireless RF Transmitter. 
Nothing works.

I tried looking up if anyone else had this problem, but could not find anything.

**Comment by Quarris** [comment]
That's because the Enervator doesn't accept any energy, it drains energy from tools. The Energizer takes energy and powers the tools.
