### ISSUE TITLE
Ticking Tile Entity - Vertical Digger

### ISSUE THREAD

**Issue by grissly** [Ellpeck/ActuallyAdditions#1117]
I apologize if this isn't the mod's fault. I am still new to reading my crash reports and have never done any bug reporting before. Anyways I'm playing Foolcraft 3 v1.3.1. The title says the issue i found in the crash report. It happened to me twice (I reverted a backup the first time). Heres the logs:

[crash-2018-06-16_21.27.42-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2108630/crash-2018-06-16_21.27.42-server.txt)
[crash-2018-06-15_15.12.31-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2108631/crash-2018-06-15_15.12.31-server.txt)

Please help me to understand if it is something I'm doing on my end to cause these crashes.

**Comment by canitzp** [comment]
It is the fault of ftblib

**Comment by grissly** [comment]
can you elaborate on that? I don't really know if that means i should update something or what.....

**Comment by Ellpeck** [comment]
It means you should report the bug to FTBLib.
