### ISSUE TITLE
Energizer breaks Curse of Binding

### ISSUE THREAD

**Issue by TrueKuehli** [Ellpeck/ActuallyAdditions#1118]
Hi there, 
I found a bug in Version 1.12.2-r135 of the Mod (tested in a standalone pack with just Forge and AA). In the UI of the Energizer armor with the Curse of Binding enchantment can be removed, even in Survival, even though this should be prevented by the enchantment.

**Comment by Shadows-of-Fire** [comment]
Closed via ac2bc01
