### ISSUE TITLE
Access is denied(ActuallyAdditions)

### ISSUE THREAD

**Issue by KristjanKr** [Ellpeck/ActuallyAdditions#112]
ActuallyAdditions: ActuallyAdditions-1.9.4-r39.jar
Forge: 1954

ActuallyAdditions is throwing lots of Access is denied errors.

Log: http://paste.ee/p/Zyzm7

**Comment by canitzp** [comment]
Update you ActuallyAdditions to the latest version

**Comment by KristjanKr** [comment]
Happens in r40 aswell.

**Comment by canitzp** [comment]
Do you have enough rights to open the datas in the world folder? Is it with r40 the exact same error?

**Comment by Ellpeck** [comment]
This is probably due to you having your Minecraft Installation in the Downloads folder. Minecraft might not have the full amount of permission required to save to this location.
There is nothing I can do about this, sorry. Just move your installation to somewhere else or run it in administrator mode.

**Comment by XDjackieXD** [comment]
@KristjanKr Please try to create a new world using your modpack. If this works without any problems (no errors from actadd or anything else) then you have screwed something up regarding the folder permissions of the world folder. If it doesn't work and ActAdd still reports this problem please post the log here.

**Comment by KristjanKr** [comment]
Well, for some weird reason my world save was ticked as "read-only" so i unticked, tried also running as administrator but my world still does it, making new world tho fixes it. I have no idea what is going on anymore.
