### ISSUE TITLE
Tried to read NBT tag that was too big

### ISSUE THREAD

**Issue by sfxworks** [Ellpeck/ActuallyAdditions#1120]
A player of ours keeps having issues when they put ME drives into a travler's sack. They get the following error.

```
[16:47:16] [Netty Client IO #1/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097227bytes where max allowed: 2097152
```

Is there something you can do on your end to resolve this or should I report this to the author of Applied Energistics?

**Comment by Shadows-of-Fire** [comment]
Don't do that.  This is neither mod's issue.  You should blacklist that item in the config.

**Comment by sfxworks** [comment]
Blacklist your own item that you made?

**Comment by Quarris** [comment]
No. He means to blacklist the item to be prevented to be put into the Sack. Go to configs and blacklist the ME Drive in the Sack Blacklist.

**Comment by sfxworks** [comment]
Ah. That I can do. However I would like it that if in the future you could handle this exception as other mods do similar references too.
