### ISSUE TITLE
BlockWildPlant server crash with r136 hotfix1

### ISSUE THREAD

**Issue by Kriiks** [Ellpeck/ActuallyAdditions#1123]
Hello!

Just got 2 identical server crashes after updating to 136 hotfix version.

[crash-2018-06-23_14.03.58-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2129890/crash-2018-06-23_14.03.58-server.txt)

**Comment by Cyphall** [comment]
Same problem here with block_wild.
[crash-2018-06-23_14.36.11-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2129905/crash-2018-06-23_14.36.11-server.txt)

**Comment by JasonKillsUs** [comment]
same here:

https://pastebin.com/NTnUyK3Q
