### ISSUE TITLE
AA Farmer causing world crash with Agricraft Crop Sticks

### ISSUE THREAD

**Issue by Seyeght** [Ellpeck/ActuallyAdditions#1127]
This works fine in r135, but is broken in version r-136-hotfix2

Crash log:
https://pastebin.com/fhGkdQPx

**Comment by Shadows-of-Fire** [comment]
This support is on Agricraft's end, and the API has changed.  Agricraft will need to update their compat.

**Comment by Seyeght** [comment]
The reason I uploaded it here was because this was the only mod that changed, but I will upload the error to their github as well.
