### ISSUE TITLE
crash on generating world mc 1,12 lastest AA

### ISSUE THREAD

**Issue by macqo004** [Ellpeck/ActuallyAdditions#1129]
[crash-2018-06-24_18.53.28-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2131006/crash-2018-06-24_18.53.28-server.txt)

**Comment by macqo004** [comment]
ActuallyAdditions-1.12.2-r136-hotfix1

**Comment by Shadows-of-Fire** [comment]
update
