### ISSUE TITLE
coffee maker consumes ingredients but don't make correct coffee

### ISSUE THREAD

**Issue by monororo** [Ellpeck/ActuallyAdditions#1132]
mc version:1.12.2
mod version:1.12.2-r135
![screenshot at 2018-06-25 15-47-15](https://user-images.githubusercontent.com/15166609/41837192-643b918c-788f-11e8-83b2-e33f5e8d2d77.jpg)

this is coffee maker gui.
If put a bucket of milk at slot 1, 2 pieces of sugar at slot 3 and 4, and 2 magma creams at slot 5 and 6, the result is a cup of coffee with buff Fire Resistance 2(20s), Speed 2(30s)[expected Fire Resistance(2:20) and Speed (2:30)]. But if change the milk into slot 7, the result is correct.

**Comment by Ellpeck** [comment]
Working as expected
