### ISSUE TITLE
Server crash with AA 1.12.2-r136-hotfix5 with Farmer - IE Hemp

### ISSUE THREAD

**Issue by shortybsd** [Ellpeck/ActuallyAdditions#1135]
MC 1.12.2
Forge 2705
Actually Additions 1.12.2-r136-hotfix5

If you have an Immersive Engineering hemp plant inside the area that a Farmer scans, it will crash the server with the following error:
https://pastebin.com/D4DcSZjf

I haven't tested single player but will do so if needed.

**Comment by Shadows-of-Fire** [comment]
Ah, yeah, the API changed.  This is a beta for a reason.  Go ahead and roll back to r135 in the meantime.
@BluSunrize can you update your farmer support?  The changes were minimal, pretty much just removing the simulate bool and splitting into two methods.

**Comment by shortybsd** [comment]
Thank you very much!

**Comment by Shadows-of-Fire** [comment]
Opening a PR to IE for this.
