### ISSUE TITLE
Server crash IndexOutOfBoundsException

### ISSUE THREAD

**Issue by yaroslav4167** [Ellpeck/ActuallyAdditions#1137]
Server crash on startup. 
[Log](http://bit.ly/2tA9ebY)
ActuallyAdditions-1.12.2-r136 Hotfix-7

**Comment by Shadows-of-Fire** [comment]
Have you done anything that would cause there to be no `dustDiamond` in the game?  AA adds one, so its expected to exist.

**Comment by yaroslav4167** [comment]
Yes, we deleted it. We create our own recipes.
String in CraftTweaker
```
<ore:dustDiamond>.remove(<actuallyadditions:item_dust:2>);
```
In the previous version (r135), there was no error.
