### ISSUE TITLE
Random crash with ActuallyAdditions

### ISSUE THREAD

**Issue by RobZombie6** [Ellpeck/ActuallyAdditions#1140]
I was killing a llama with a noteblock hat from the Hats mod while in a bat morph from the Metamorph mod. I have 56 mods and haven't experienced any issues at all since this crash. Everytime I login to my world I'll hear the llama make a noise and then I'll crash. My crash report is attached. I reported this to the forge crash reports forum thingy because they're always very helpful. I was told that this mod was the problem. I don't want to remove the mod as I had alot of ores from the mod, but I still really want to play the modpack again sometime soon because I was kind of addicted :p. 
[crash-2018-06-29_02.52.16-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2150460/crash-2018-06-29_02.52.16-server.txt)

**Comment by Shadows-of-Fire** [comment]
You are using an outdated version of the mod.  update.
