### ISSUE TITLE
Possible villager Bug?

### ISSUE THREAD

**Issue by ArcaneFlash** [Ellpeck/ActuallyAdditions#1141]
[crash-2018-07-01_09.09.53-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2153090/crash-2018-07-01_09.09.53-server.txt)

**Comment by ArcaneFlash** [comment]
So, after removing AA, It didn't crash.

**Comment by Shadows-of-Fire** [comment]
Your villager profession registry is corrupted, this isn't an issue with AA.
