### ISSUE TITLE
[1.12.2-r135] farmer output slots used to replant, replaces crops

### ISSUE THREAD

**Issue by majijn** [Ellpeck/ActuallyAdditions#1142]
I thought I could disable the replanting by placing planks in the seeds/input slots of the farmer, but it still replants, it also replaces existing crops at times (especially sugarcanes seem to be favored over other crops)

the soil I'm using are fertile soil from rustic (sugarcane do not need water next to it to be planted on.)
and essentials' fertile soil (using wheat/carrot/potato soil) which plant the crops themselves, but can also accept other crops to be planted on them when they have no crops on them.

![2018-07-02_16 29 37](https://user-images.githubusercontent.com/18368034/42174147-9afa318c-7e21-11e8-93ea-40c4524aac74.png)
![2018-07-02_16 30 09](https://user-images.githubusercontent.com/18368034/42174148-9b31a7f2-7e21-11e8-9f89-abc1b074e315.png)
![2018-07-02_16 30 13](https://user-images.githubusercontent.com/18368034/42174149-9b63e03c-7e21-11e8-831b-ca92a4c26877.png)

**Comment by majijn** [comment]
also it harvest's the entire hemp plant, it would be better if it only harvested the second level upwards like it does for cactus/cane. instead of both layers at the same time (even if harvesting the bottom layer also yields hempfibers and seeds)
I tried setting the hemp plants one layer down but all that does it stop the farmer from interacting with the crops at all
![2018-07-02_17 24 42](https://user-images.githubusercontent.com/18368034/42174962-4208b5dc-7e24-11e8-9161-af0ca0d17988.png)

**Comment by Shadows-of-Fire** [comment]
So a couple things about this issue:

The farmer planting from the output slots has been fixed.  Not sure why it did that to begin with, but now it only checks the seed slots for seed candidates.

The farmer will no longer even attempt to plant a seed if the current block isn't replaceable (like air, or tall grass).  Previously most farmer behaviors were checking this, but not reeds, leading reeds to replace not only themselves, but anything else.

The hemp interaction is managed by Immersive Engineering, not AA.  Any complaints should be filed to them. 

As a final note:  The farmer is not designed to support multiple crops at the same time.  These bugs were valid, but know that certain oddities will arise from using multiple crops at once, and will not be supported.

**Comment by majijn** [comment]
fair enough!
