### ISSUE TITLE
Traveler's Sack Filled Slots Count Not Updating Properly

### ISSUE THREAD

**Issue by mengisman** [Ellpeck/ActuallyAdditions#1145]
**r136 HF8 and r137**
When picking up an item while a sack or multiple sacks is/are in the inventory with auto-insert on and whether or not a filter is applied, the filled slot count is only updated after opening the bag containing the picked-up item. Removing an item does not immediately update the count, but closing the bag results in the count being updated. Also tested with new singleplayer world and 0 other mods and same result. [Best mod evar, BTW!]

**Comment by Shadows-of-Fire** [comment]
Ah.  Yeah.  That's a result of the fix which makes it not crash if you shove too many NBT-filled items inside of it.  I should probably just remove that tooltip now.

**Comment by mengisman** [comment]
That's a shame, as that is a super-helpful feature when carrying multiple bags. Thanks for all you do, regardless!
