### ISSUE TITLE
r40 & r41 Fluid Collector...

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [Ellpeck/ActuallyAdditions#115]
Ever since moving from r36 the Fluid Collector refuses to connect to EnderIO Fluid Conduits. I keep trying the newest version of ActAdd and always rollback to r36 to get the conduit to connect.

**Comment by Ellpeck** [comment]
I.. seriously, I am going to make a macro for this at some point.

_It is EnderIO's fault, not mine. I have updated to the new Forge Fluid System like one is supposed to, but EnderIO hasn't yet. I neither can nor want to nor will do anything about it, it's not my business._

Sorry.

**Comment by Ellpeck** [comment]
Re-added the old system now because too many people were asking .-.
