### ISSUE TITLE
[suggestion] alternative recipe for EXP solidifier.

### ISSUE THREAD

**Issue by majijn** [Ellpeck/ActuallyAdditions#1151]
please consider adding the option to use EXP bottles in place of solidified EXP as an additional way to craft it by default

**Comment by Ellpeck** [comment]
No, I'm sorry.

**Comment by majijn** [comment]
not even when the config for the dropping of solidified XP from mobs is set to false?

is there a way of getting solidified XP I'm missing?

**Comment by Ellpeck** [comment]
Just don't turn off the config 🤔

**Comment by majijn** [comment]
I woudnt , if they werent affected by looting as much as they are.

**Comment by majijn** [comment]
I thought asking for an alternative recipe would be something smaller to ask for than a more complex configuration for what drops and how often solidified xp drops for the kitchen sink packs out there.
inbetween my farm animals and unlit desert I live next to, I basically wouldnt need to build and XP farm, just by how many SXP drops I'm getting, and it just doesnt feel right for me.

and defaults matter

besides it gives bottles o' Enchanting a use for when you find them.
