### ISSUE TITLE
Suggestion to stop generators from wasting materials

### ISSUE THREAD

**Issue by Thyriel** [Ellpeck/ActuallyAdditions#1152]
While using the bio reactor i noticed that it's burning through seeds/food etc. extremely fast despite that i was only using very small amounts of energy at that time. I watched the generator a while then and it seems they are starting to burn everytime the internal energy storage is lower then 100%.

How about a treshhold instead ?
Internal storage < treshhold (e.g. 80%) => start generating energy
Internal storage = 100% => stop generating energy until it drops below treshhold again.

That way they wouldn't generate a ton of energy going to the void just because something used up 5 CF

**Comment by Quarris** [comment]
I doubt something like that will be implemented in AA. But having comparator signal based on energy stored may be a good idea. You could then automate it with that.

**Comment by Thyriel** [comment]
That would work too, but would also require reactors to turn off when a redstone signal is supplied

**Comment by Ellpeck** [comment]
I thought all generators already do the comparator and redstone thing. @shadows-of-fire you'll just have to do some copy-pasting it looks like

**Comment by Thyriel** [comment]
I checked the coal generator and that seems to work with redstone to turn off & comparator to read out state.
Only Bio reactor seems either to be missing some code or it's intended to work in another way: The comparator signal seems to indicate how many different foods are in there and badly a redstone signal supplied to the reactor does nothing. (so you can't turn it off)

**Comment by Shadows-of-Fire** [comment]
I think its best here to make it so that we just don't generate if that energy would vanish into the abyss, especially with a high input generator like the bio reactor.  I'll be sure to write something about it in the book so that people don't think its a bug or something, and despite that I'm sure I'll receive at least one issue about it...  Then they'll figure out its beneficial and wander off.
