### ISSUE TITLE
Shift-clicking Stone Bricks in Resonator freezes game

### ISSUE THREAD

**Issue by ViRb3** [Ellpeck/ActuallyAdditions#1155]
It could be a mod conflict, I will hopefully find time to experiment later. There is no crash log since the game doesn't crash, only freezes forever.

Actually Additions version: 1.12.2 r138
Forge version: latest - *.2745

**Comment by Shadows-of-Fire** [comment]
You sure you reported this to the right issue tracker?  There's nothing called a resonator in AA

**Comment by ViRb3** [comment]
Sincere apologies, indeed that is Extra Utilities 2.
