### ISSUE TITLE
BlockWildPlant Crash 

### ISSUE THREAD

**Issue by WenXin20** [Ellpeck/ActuallyAdditions#1156]
Forge v14.23.4.2745-1.12.2
Actually Additions r138
I get this crash when generating a new world. Here's the [crash report.](https://gist.github.com/WenXin20/bff43a892c048ada63170ccac869f456) Seems to have come back again.

**Comment by Shadows-of-Fire** [comment]
So this isn't actually an issue I can reproduce, and the only way that crash report can happen is if another mod loads the variant enum before blocks are loaded, which is pretty bad...  I've added a check into the enum that should crash properly allowing me to figure out what mod is causing this issue.
