### ISSUE TITLE
[Bug] Farmer plants only oak saplings, no other vanilla saplings

### ISSUE THREAD

**Issue by Thorton101** [Ellpeck/ActuallyAdditions#1160]
Hi there,

I'm currently playing the Direwolf20 Pack and noticed, if you provide any vanilla sapling
to the farmer, the farmer plants oak sapling and not the other ones provided.
Packversion : Direwolf20 1.12 Version 2.2.0
ActualAddiction : ActualAdditions-1.12.2-r137.jar
Couldn't find an other issue reporting this bug.

So long
Thorton

**Comment by Ellpeck** [comment]
The farmer isn't supposed to plant any saplings at all. 
@Shadows-of-Fire please remove this functionality altogether

**Comment by Shadows-of-Fire** [comment]
I mean, I can try... but saplings don't have a classifier in code.  Only instanceof, and that'll probably only work for vanilla

**Comment by Ellpeck** [comment]
no u

**Comment by Shadows-of-Fire** [comment]
Yeah, gonna leave this as it is.  No real way to differentiate a sapling from anything else.
