### ISSUE TITLE
[Incompatibility]: with MinersAdvantage

### ISSUE THREAD

**Issue by DuelMonster** [Ellpeck/ActuallyAdditions#1161]
Hello there @Ellpeck,

I have an issue that is causing me some problems with my mod and was hoping that you could help me out.

One of the features of MinersAdvantage improves the use of a hoe to harvest and replant an entire patch of crops by using the net.minecraftforge.event.entity.player.UseHoeEvent.  However, I believe that due to your [BlockPlant#onBlockActivated](https://github.com/Ellpeck/ActuallyAdditions/blob/e4aa4a3b0b44df045062f58068e878dc493537f7/src/main/java/de/ellpeck/actuallyadditions/mod/blocks/base/BlockPlant.java#L92) override, the use hoe event is not getting fired when the crops metadata is >= 7. This is true for vanilla crops as well.

If you return false from the onBlockActivated event then the hoe event seems to get fired correctly.

Would it be possible for you to remove the "return true" or to specifically fire the UseHoeEvent if the players held item is a hoe?  If this is not possible for other reasons I'm unaware of within your code, could we maybe add something that would allow me to disable your override?

Any help you can give me would be greatly appreciated.

Many Thanks
DuelMonster

**Comment by Ellpeck** [comment]
I don't really see the point of this or understand the issue exactly, but I don't work on the mod anymore anyway so @Shadows-of-Fire will deal with this somehow.

**Comment by DuelMonster** [comment]
OK thanks for the swift reply.
I'll look forward to a response from @Shadows-of-Fire

**Comment by Shadows-of-Fire** [comment]
Is sneak right click not a valid option here?  Sneak bypasses the block use and delegates to the item directly

**Comment by Shadows-of-Fire** [comment]
No, that is intended behavior.  If the block performs an action, it should return true to onBlockActivated so the item use does not get called.  That's why sneaking goes directly to the item.

**Comment by DuelMonster** [comment]
Alright thanks for the help anyway guys.
