### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by kellixon** [Ellpeck/ActuallyAdditions#1165]
MC 1.12.2. ActuallyAdditions r140.
Crash reports - https://gist.github.com/kellixon/a562af84230ea33300101b9ea3cf6507

**Comment by Matchyman** [comment]
Also having this issue 
https://pastebin.com/UNv0sx30

**Comment by Matchyman** [comment]
i also had this problem are you using the newst enderio core that is in alpha? If so, go back one version to the realse one and it will all work fine :D

**Comment by Shadows-of-Fire** [comment]
Duplicate of #1162
