### ISSUE TITLE
Lush cave's generation interfering with basically all other mod's generation

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Ellpeck/ActuallyAdditions#1168]
for some reason the generation of the empty space inside lush caves completely ignores _anything_ modded, resulting in the caves being filled with stuff like ores, marble. limestone, etc. in bigger packs.

![](https://i.imgur.com/qZvaCop.png)

but why has this bug been in the mod for so long? i never even saw people acknowledge this.

**Comment by Ellpeck** [comment]
Yay it's back @Shadows-of-Fire
