### ISSUE TITLE
Auto-Placer not placing blocks, making block-placing sound

### ISSUE THREAD

**Issue by pizza4554** [Ellpeck/ActuallyAdditions#1169]
Modpack: Enigmatica 2: Expert

Actually Additions Version: ActuallyAdditions-1.12.2-r140
Forge Version: forge-14.23.4.2750

Video of reproduction: https://youtu.be/GLPYGF3exdc

At first I thought this may have been an issue with Industrial Foregoing, but it seems to be an issue with Actually Additions. I've tried to have the auto-placer place wood in front of my Tree Fluid extractor, but the auto-placer seems to get stuck in this loop of trying to place the block, even playing the block sound effect, but not placing anything. Not sure what else to add here, so let me know if you need anything else.

**Comment by Shadows-of-Fire** [comment]
Are you in a claim-protected area?

**Comment by pizza4554** [comment]
I am in a claim protected area, yes. That seems to explain the issue. After turning off the protections the auto-placer worked as expected. Incidentally, is there a workaround for this, other than turning off the protection?

**Comment by Shadows-of-Fire** [comment]
There should be a way to whitelist the fakeplayer - in this case it's the default fakeplayer, `[Minecraft]`

**Comment by pizza4554** [comment]
There was an option to set the fakeplayer's member status in the FTBLib settings, everything works as expected now.
