### ISSUE TITLE
r43 and r41 crashes

### ISSUE THREAD

**Issue by ftog-thorgal** [Ellpeck/ActuallyAdditions#117]
I updated from r41 to r43 today and the server keeps crashing shortly after it started without world interaction, I am just standing still. Report attached.
[crash-2016-06-11_15.19.08-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/310436/crash-2016-06-11_15.19.08-server.txt)

After rolling back to r41, now the server crashes with different report, also attached.
[crash-2016-06-11_15.24.14-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/310437/crash-2016-06-11_15.24.14-server.txt)

**Comment by ftog-thorgal** [comment]
I just updated Forge to 1957 and with r41 it crashed again.
[crash-2016-06-11_15.35.21-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/310439/crash-2016-06-11_15.35.21-server.txt)

**Comment by Ellpeck** [comment]
Hopefully crashed with latest commit.
