### ISSUE TITLE
BlockWildPlant Crash w/ Better Foliage

### ISSUE THREAD

**Issue by WenXin20** [Ellpeck/ActuallyAdditions#1170]
Forge v14.23.4.2745-1.12.2
Actually Additions r140
[Better Foliage](https://minecraft.curseforge.com/projects/better-foliage?gameCategorySlug=mc-mods&projectID=228529) v2.1.10
I get this crash when loading the game with Better Foliage. Here's the [crash report](https://gist.github.com/WenXin20/8260d52c6eed812ac30414451e985cf0). If `de.ellpeck.actuallyadditions.mod.blocks.BlockWildPlant` is removed from the CropWhitelist of Better Foliage's config file, it doesn't crash.

**Comment by Shadows-of-Fire** [comment]
Other mod's end, nothing in AA is going to cause our class to fail to init.
