### ISSUE TITLE
[1.12.2-r140] NoClassDefFoundError on client and server

### ISSUE THREAD

**Issue by kreezxil** [Ellpeck/ActuallyAdditions#1175]
client crash report: https://pastebin.com/R70QSYDm
server crash report: 
Issue:  1.12.2-r140 crashes dedicated server Forge 1.12.2 build 2760

Notes:
     NoClassDefFoundError

crash report:
https://gist.github.com/51ddae5878ad9a94dee0f8e6b39e93fa

fml server latest:
https://gist.github.com/a892bd991bc2cd25cf07bc2b6114d67c

**Comment by Shadows-of-Fire** [comment]
Uh wat.   Are you sure that aa jar isnt corrupted?

**Comment by kreezxil** [comment]
How did you investigate it? Did you start a server instance in the IDE with it or did you put it on a true dedicated server? Need to know so I can compare your "investigation" method with mine.

I downloaded it straight from curseforge into my server with wget btw.
