### ISSUE TITLE
Powered Furnace Crash

### ISSUE THREAD

**Issue by funfight22** [Ellpeck/ActuallyAdditions#1176]
Minecraft 1.12.2
Mod Version r140

https://paste.dimdev.org/evekuteqav.mccrash

Crashes internal server when finishing smelting an item.

**Comment by Shadows-of-Fire** [comment]
Well this is unusual.  I'll look into it soon.

**Comment by Shadows-of-Fire** [comment]
Can't reproduce this whatsoever, the field is no longer named `slots`, so the crash makes sense.  Somehow you've gotten a jar that's half r140 and half... something else.

**Comment by wec22** [comment]
also encountering this issue.
on newest version of additions and forge

https://paste.dimdev.org/parihuhizu.mccrash

The world will not start up now.  It will load and then immediately crash.

**Comment by AlienXtream** [comment]
happening on r151 too... wth is it making it mess up like this?! anyone found a fix?

**Comment by AlienXtream** [comment]
i doubt this has anything to do with it but i found several mentions for "slot" in the containerFurnaceDouble.class (apparently 7zip can open the jar and notapad++ can sorta read the class files). perhaps thats the class that is somehow merging with an older version? then again, idk much about programming so thats just a guess based off the mention of "slot"
