### ISSUE TITLE
Visual indication of Item Laser Relay transfer (Maybe by floating item above them)

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#118]

**Comment by NoobsterLP** [comment]
I have at least 1 idea.
You could add a function that the player can select with which slot of a machine the itemlaser interacts^

**Comment by SparkyZapper** [comment]
i thought of a good mod for mc a time based controller that you can set the length of time you want day to be and night to be e.g. 5 min nights and 30 mins days (realtime)

**Comment by Ellpeck** [comment]
..what?

**Comment by SparkyZapper** [comment]
so you can change the length of time of both day and night cycles

**Comment by Ellpeck** [comment]
This issue isn't the right place to post suggestions. Post them as their own issue.

**Comment by Rated01010010** [comment]
Like a holographic picture of the item's texture above the relays? I like that idea. And possibly a  change of color in the beam between when it's transferring items and doing nothing.

**Comment by Ellpeck** [comment]
Oh yea, that's a great idea too :D
