### ISSUE TITLE
[1.12.2] Exception ticking world

### ISSUE THREAD

**Issue by NickelHub** [Ellpeck/ActuallyAdditions#1180]
I got this two times, whilst I was walking through the world.
[crash-2018-09-26_18.27.21-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2420752/crash-2018-09-26_18.27.21-server.txt)
[crash-2018-09-26_18.50.38-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2420753/crash-2018-09-26_18.50.38-server.txt)

**Comment by sandalle** [comment]
ActuallyAdditions-1.12.2-r141a works for me, I can walk around with crashing now, thank you for the quick fix @Shadows-of-Fire . :)
