### ISSUE TITLE
[Suggestion] Make greenhouse glass work with crops that have transparent blocks above them

### ISSUE THREAD

**Issue by kenlauescuadro** [Ellpeck/ActuallyAdditions#1183]
If the title isn't comprehensible, here's an example:

``
            Greenhouse Glass
Chest   Torch (attached to Chest)
            Potato

In r140, the potato's growth isn't sped up Greenhouse Glass just because a Torch (a transparent block) is between them. I suggest that even with transparent blocks (Torch, in this example) between the crops (Potato) and the Greenhouse Glasses, it still should speed up the crops' speed of growth.

**Comment by Shadows-of-Fire** [comment]
@Ellpeck y/n on this one?
