### ISSUE TITLE
Coal Generators excessive tick rate

### ISSUE THREAD

**Issue by Yamza** [Ellpeck/ActuallyAdditions#1184]
Item: Coal Generator with coal inserted
Modpack: ATM3- Remix 0.0.2
Current Version: 1.12.2-r140
Forge: 14.23.4.2579

`[10:56:40] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] 983 micro-s/t: TILE_ENTITY: {WORLD_ID=0, BLOCK_NAME=Coal Generator§r, BLOCK_POS_X=-363, BLOCK_POS_Y=52, BLOCK_POS_Z=233, BLOCK_CLASS_NAME=de.ellpeck.actuallyadditions.mod.tile.TileEntityCoalGenerator, NANOS=1174873900}
[10:56:40] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] 944 micro-s/t: TILE_ENTITY: {WORLD_ID=0, BLOCK_NAME=Coal Generator§r, BLOCK_POS_X=-363, BLOCK_POS_Y=52, BLOCK_POS_Z=235, BLOCK_CLASS_NAME=de.ellpeck.actuallyadditions.mod.tile.TileEntityCoalGenerator, NANOS=1128273212}
`
https://i.imgur.com/7v9JeSW.png

**Comment by Shadows-of-Fire** [comment]
Alright, I've pulled something up that should be a significant fix.
However I don't just want to release it since it might break a bunch of things.  Mind testing it for a bit? https://1drv.ms/u/s!AoXVxSo6VrNfgZZ_1Ramh3gfL1dxVQ

**Comment by Yamza** [comment]
Yeah I can take a look at it. Anything specific that you're expecting to be broken? I don't have the ability to test in a server setting but I will see how it does in SP.

**Comment by Ellpeck** [comment]
Anything related to client/server syncing really (which should also be testable on the integrated server, meaning in singleplayer). Basically machines' energy storages and other dynamic values that might have to be sent to the client for display might not update correctly or as expected.

**Comment by Yamza** [comment]
Still a bit high but quite a significant improvement from what it was. Power seems to be showing properly.
https://i.imgur.com/f3Woy4D.png
