### ISSUE TITLE
[Issue] bugged Solidified Experience not gaining XP levels

### ISSUE THREAD

**Issue by PotatoFlavour** [Ellpeck/ActuallyAdditions#1185]
Hi,

I'm playing on a multicraft server with a friend. The server has FTB Revelation 2.5.0 running (updated) since yesterday.

In the basement of my base, I have a little XP farm running. After liquid XP piling up without being able to store it, I found a way to store a lot. I take the liquid XP from the tank, solidify it with the Experience Solidifier and let the Experience Solidifier transport the Solidified Experience to a YABBA Barrel through an EnderIO item conduit. Also, the Solidified Experience as mob drops also get transported to the Barrel. The system worked great, I recently passed 50k Solidified Experience.

As of just now, I wanted to gain some levels for enchanting. I took a few stacks out of the barrel and used them up. I then noticed I did not gain any levels. I then remembered I had a Tome of Knowledge in my inventory with auto-collect enabled. Not being sure whether the Tome gained any XP, I disabled the auto-collect and tried again, but I still gained no levels. I wasn't carrying any mending enchantments or other XP-using items. I went upstairs to get some Solidified Experience I remember getting from mob drops. I used them and they worked. I took the working Solidified Experience downstairs and mixed a bugged stack with a working stack. After this, none of the Solidified Experience worked. I also tried taking out Solidified Experience directly out of the Experience Solidifier and they did not work.

So, the Experience Solidifier seems to be creating unusable Solidified Experience. I hope I've been clear enough in order to be able to create a solution for this. If you have any questions I'll try to answer them. If you need any versions please explain where I can find which versions I'm using.

**Comment by Shadows-of-Fire** [comment]
Were you still standing next to the solidifier?  It'll pick up the orbs spawned by the solidifed xp, which would make it seem like it's not doing anything.  It's a design flaw, and I'll probably make it directly increment XP or something, but for now, just don't stand next to it.

**Comment by PotatoFlavour** [comment]
> Were you still standing next to the solidifier? It'll pick up the orbs spawned by the solidifed xp, which would make it seem like it's not doing anything. It's a design flaw, and I'll probably make it directly increment XP or something, but for now, just don't stand next to it.

Oof, I think you may be right. I'm going to check if it works out of range of the solidifier. I feel like I should've thought of that though, haha!

**Comment by Shadows-of-Fire** [comment]
You wouldn't happen to have the Clumps mod installed, would you?

**Comment by PotatoFlavour** [comment]
> You wouldn't happen to have the Clumps mod installed, would you?

The complete FTB Revelation 2.5.0 Pack. I checked and (unfortunately?) yes, it's installed: https://i.imgur.com/lWT1jXI.png. I assume this is causing the issue?

**Comment by Shadows-of-Fire** [comment]
Yeah, we mark xp generated from the solidifed XP with a tag so the solidifier doesn't pick it up, but when clumps merges orbs, the tag is voided.

**Comment by Shadows-of-Fire** [comment]
Default behavior is now to only spawn orbs if its detected a FakePlayer is using the item.  Otherwise, the player xp will be incremented directly.
There's also a config to make orbs always spawn, if anyone wanted that.
