### ISSUE TITLE
How do I activate duh_duh_duh_duuuh?

### ISSUE THREAD

**Issue by masonpinder** [Ellpeck/ActuallyAdditions#1189]
I found the audio using a SFX block (cyclic mod), and was pleasantly surprised by it. But can't figure out how to activate the sound. Couldn't even find the fact it exists anywhere...
Is there some block/item that I need to use, to make it, besides other mods playing the audio?

**Comment by Shadows-of-Fire** [comment]
It's used by nothing, so you can't play it short of accessing the sound registry directly like you did.
