### ISSUE TITLE
Laser Wrench mode switching

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#119]
Somehow switch by using the laser wrench between
- No laser relay particles
- Particles only with laser
- Particles always

**Comment by MrRiegel** [comment]
I had similiar ideas when I watched the videos from booty toast.
the particles should only be visible while holding the wrench

**Comment by Ellpeck** [comment]
Just change that in the config file..

**Comment by MrRiegel** [comment]
Oh.. ok, thx
