### ISSUE TITLE
Cheese made with eggs?

### ISSUE THREAD

**Issue by Ncrpts** [Ellpeck/ActuallyAdditions#1190]
Hello, i understand the recipe for cheese was changed to avoid a conflict with Harvestcraft, but making cheese by mixing milk with eggs feels a LOT wrong to me, this is really a very minor issue but cooking a bucket of milk in a furnace would be 10 times more plausible than mixing it with eggs, also i highly suggest to never try making cheese in real life by mixing it with eggs, you are gonna have a bad time.

**Comment by Shadows-of-Fire** [comment]
egg

**Comment by Ncrpts** [comment]
hmm what?
