### ISSUE TITLE
Greenhouse Glass doesn't work in r143

### ISSUE THREAD

**Issue by kenlauescuadro** [Ellpeck/ActuallyAdditions#1195]
I have noticed that in the newest update (r143), the crops below the greenhouse glass doesn't have their growth sped up. No green "bone meal used" particles showing either that signals that a crop has their growth sped up.

**Comment by Shadows-of-Fire** [comment]
What crop?

**Comment by kenlauescuadro** [comment]
Here is the list of the crops that I have, along with the time that I have observed the plants.

```
(Observed for ~1 minute, 80 blocks)
- Flax

(Observed simultaneously for ~30 seconds)
- Potato (80 blocks)
- Canola (320 blocks)
- Coffee (80 blocks)
- Red Orchid (81 blocks)
- Ender Lily (81 blocks)
- Wheat (160 blocks)
- Rice (80 blocks)
```

This list might not cover all affected crops.

I think it's better to say this, but I think it's any of the three:
- Greenhouse Glasses aren't working
- I came up with the conclusion with a short observation time
- Greenhouse Glasses' "rate of making crops grow" became slower

**Comment by kenlauescuadro** [comment]
Definitely had to do with r142/r143. I reverted back to r141 and the Greenhouse Glass works.

I am very sorry and I hope you fix this bug, but I'll revert to r141 until this problem is fixed. I'm very sorry.

**Comment by mrdeadlocked** [comment]
Same issue here. Greenhouse glass does nothing now. I'm on r143. Test with Wheat, potatoes, lettuce and other crops.

**Comment by Shadows-of-Fire** [comment]
Greenhouse glass was still working, but stacked greenhouse glass was not.

**Comment by kenlauescuadro** [comment]
No offense, but I think non-stacked greenhouse glass, too, doesn't work.

**Comment by mrdeadlocked** [comment]
I only have mine in single layers and my farm output is different from r141 vs r143. I'll try the new changes after you release them and report back.

**Comment by kenlauescuadro** [comment]
Nevermind, Greenhouse Glass works in r143-856.

**Comment by drogars** [comment]
I might be missing something, but my local server is using 1.12.2-r143 and I still seem to seeing no effects from a single layer of greenhouse glass above crops including:  potatoes and a variety of Pam's Harvest Craft (onion, zucchini, etc...).  The version most recently posted to CurseForge lists r143, but how do I know if I have the 856 build?

**Comment by mrdeadlocked** [comment]
I reverted back to r140 and greenhouse glass is working as it did previously.

**Comment by NeosGhost** [comment]
This was the same for me. Reverted to r142 and it started working.

Pack All the Mods
forge 14.23.5.2768
