### ISSUE TITLE
Laser relays' connections are randomly disappearing

### ISSUE THREAD

**Issue by KLaurence** [Ellpeck/ActuallyAdditions#1196]
Title,

**Comment by Dimentive** [comment]
You should probably add more information. What version of the mod are you using? What version of Minecraft are you playing (1.10.X, 1.11.X, or 1.12.X)? What modpack are you playing (or, if you’re not playing a modpack, what mods do you have alongside Actually Additions)?

If you’re not using the latest version of [Actually Additions](https://minecraft.curseforge.com/projects/actually-additions), you should download the latest version and replace the old one in your `mods` folder, in case this is a bug that’s already been fixed.

**Comment by Shadows-of-Fire** [comment]
Not enough information.
