### ISSUE TITLE
Phantom breakers not breaking

### ISSUE THREAD

**Issue by dedreckoning** [Ellpeck/ActuallyAdditions#1198]
i am having an issues getting Phantom Breakers to break blocks. it will break a shulker but not cobble or woot factory controller blocks. i am massively confused as i have watched direwolfs tutorial and followed it and still no breaking. is there a permission i need to give or a server config that needs editing? any help with this would be greatly appreciated

**Comment by PongoSapiens** [comment]
Is there any chance of this fix being released? Its was closed on October 28, and as of December 10th it's still broken.
