### ISSUE TITLE
[Issue] Crash on Startup

### ISSUE THREAD

**Issue by luisantonio98** [Ellpeck/ActuallyAdditions#1201]
I have been trying to play modded minecraft (1.12.2 since forge 1.13 wont be out for a while) but Every time I launch minecraft it crashes without even opening up the game. I have checked the crash reports and every time they say its a problem with the Actually Additions and I have no idea how to fix it
[crash-2018-10-28_13.32.18-client.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2523192/crash-2018-10-28_13.32.18-client.txt)

**Comment by Shadows-of-Fire** [comment]
Your forge version is horribly outdated.
