### ISSUE TITLE
Storage Crate Inventory Bug

### ISSUE THREAD

**Issue by Jbow11** [Ellpeck/ActuallyAdditions#1202]
I have been playing the stoneblock modpack by sunekaer. The pack features AA. 

The bug I am noting is a discrepancy with the inventory gui of Storage Crates. When the server crashes / stalls, the storage crate (any size) retains its inventory; however, the block's gui isnt fully interactable any longer. After both client and server reboots, the bug still seems to remain; it fades on its own - after random periods of time. I have noted this glitch for over a week - trying to track any events which might be causing it.

However the bug seems to be random. I have checked with other players as well and the issue seems to be present for them as well

https://drive.google.com/file/d/1Gc-5SBW9VVamEMD56BtUejm5KQqBjn31/view?usp=sharing

**Comment by Shadows-of-Fire** [comment]
I believe that's an issue with vanilla, when the game stalls it fails to cleanup the active gui/container, and wont open the crate since it thinks its already open until it catches back up and closes the container.
