### ISSUE TITLE
Server crash - actuallyadditions:fishingnet

### ISSUE THREAD

**Issue by ProsperCraft** [Ellpeck/ActuallyAdditions#1203]
https://gist.github.com/ProsperCraft/0437fc5f59d62797a5e9c81124a4952e

![fishing_net_on_stonebarrel](https://user-images.githubusercontent.com/4427684/47808728-a012e280-dd04-11e8-9666-bc61ef3e9551.png)

**Comment by canitzp** [comment]
It is the barrel that crashes
