### ISSUE TITLE
Re-constructor pulse converting placed fluid laser relay to item laser relay

### ISSUE THREAD

**Issue by rachel8973** [Ellpeck/ActuallyAdditions#1204]
I have placed a fluid laser relay close to a re-constructor.  When the re-constructor pulse is fired the fluid laser relay is converted to an item laser relay which breaks the system.  Although I can understand this happening for other blocks perhaps laser relays should only be converted when in item form and not in placed block form.

![2018-11-05_20 47 49](https://user-images.githubusercontent.com/7691541/48026262-79f2a580-e13d-11e8-88f5-74bfda7ae210.png)
![2018-11-05_20 47 59](https://user-images.githubusercontent.com/7691541/48026264-79f2a580-e13d-11e8-963a-03324f3a57b8.png)

**Comment by Shadows-of-Fire** [comment]
@Ellpeck relay conversion only as item y/n
