### ISSUE TITLE
[Suggestion] Player pickup preventing block

### ISSUE THREAD

**Issue by GeoTerra** [Ellpeck/ActuallyAdditions#1205]
I understand that there are mechanics in place to enable autocrafting with the Atomic Reconstructor, however trying to use item entities have produced issues for me, like the entity not actually being where the server says it is (this is an issue on my end).

I'd like to suggest allowing the player to place an item (or block) on a Display Stand and firing the Reconstructor at the Stand to transform the item.

This is not to make the existing methods obsolete however, as through this method you can only transform one item at a time while using the normal methods, you could easily batch craft and save energy as I believe power costs are activation cost + CF/RF cost per item. On top of this, it would help prevents magnets from other mods from unintentionally interfering.

Alternatively, this can be limited solely to recipes that take items, like Canola, to prevent players from getting around the infrastructure needed to transform blocks.

Thank you for your time. I am open to further discussion on this.

**Comment by Ellpeck** [comment]
No. If you want crafting mechanics that are lazy and boring, play a different mod.

**Comment by Ellpeck** [comment]
There is definitely a good suggestion in there though: It'd be nice to have a block that could make it so that items can't be picked up by players in a certain radius.
