### ISSUE TITLE
Renamed crate reverting when placed

### ISSUE THREAD

**Issue by Snowgods** [Ellpeck/ActuallyAdditions#1206]
I renamed a crate in an anvil, but as soon as I placed the crate, the name reverted to it's default'. 
running 1.12.2 r143

**Comment by Shadows-of-Fire** [comment]
Crates don't keep their name when placed, they do not implement `IWorldNameable`, so this is expected behavior.

**Comment by Dimentive** [comment]
Most blocks do not retain custom NBT data such as names when placed down.
