### ISSUE TITLE
Farmer places cotton instead of barley

### ISSUE THREAD

**Issue by HugeLol556** [Ellpeck/ActuallyAdditions#1207]
Playing All the Mods 3 5.11.2 and found that when placing barley seeds in the farmer, instead of placing barely seeds it actually uses up the seed but places cotton seed instead. Useful if you want to turn barley into cotton, not so much if you are trying to farm barley...
Both seeds are from the mod Natura.
This glitch doesn't happen the other way around, the farmer will successfully plant any cotton seeds put in its inventory.

**Comment by Shadows-of-Fire** [comment]
This issue appears to be on Natura's end.  They use IPlantable with a meta-item, which makes `IPlantable#getPlant` only ever return one plant (in this case, cotton).  You could ask them to register an [AA Farmer behavior](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/api/farmer/IFarmerBehavior.java), which is registered via `ActuallyAdditionsAPI.addFarmerBehavior`.
