### ISSUE TITLE
Atomic Reconstructor NBT issue

### ISSUE THREAD

**Issue by Sora-Canstavia** [Ellpeck/ActuallyAdditions#1208]
Hi there, 

I Don't know if there is anything you can do about it, but a friend recently showed me an "easter egg" with the reconstructor (I Won't explain it here, since I Don't know your stance on it being public here) where he can put items through to become other items. We found that if it turns them into a placable item and you place and pick up the item it will clear the NBT preventing it being changed again.

**Comment by Shadows-of-Fire** [comment]
non-issue
