### ISSUE TITLE
[Suggestion] Advancements For AA

### ISSUE THREAD

**Issue by Pinkytwigosh** [Ellpeck/ActuallyAdditions#1212]
I am an achievement hunter I guess you would say, but along with the manual I thought it would be cool to have advancements for players to also help guide them on how they can be progressing through the mod itself. From early to mid to late. Of course one of the glorious things about Minecraft is playing it the way you want, but I don't think that it would hurt to have some advancements to help along the way. Sorry if this has been mentioned before (made a github account just to come suggest this, love the mod!).

**Comment by Shadows-of-Fire** [comment]
I'm not very interested in doing the JSON work to add them, but I suppose if someone else did I wouldn't complain.
