### ISSUE TITLE
Bug with drills

### ISSUE THREAD

**Issue by Denis-Burmyshev** [Ellpeck/ActuallyAdditions#1215]
Minecraft: 1.7.10
Forge: 10.13.4.1614
Actually Aditions: 1.7.10-r21

All drills are tools, but the character is holding t
hem as if it were a thing, I hope that this bug will be fixed, although it is unlikely to be enough

![bug](https://user-images.githubusercontent.com/44982674/50826115-7a790980-1343-11e9-87f5-4ae417701e7d.png)

**Comment by Ellpeck** [comment]
why are you submitting a bug report for 1.7.10? This version is FIVE versions behind the currently supported one. What.

**Comment by Denis-Burmyshev** [comment]
I just wanted to play a classic, but here’s a bug.
