### ISSUE TITLE
Jei wont load and crashes when trying to start minecraft

### ISSUE THREAD

**Issue by thefeather16** [Ellpeck/ActuallyAdditions#1219]
Jei causes my Minecraft to crash whenever I launch it.
Gives me this message: "Just Enough Items is missing Mods that it depends on. Include the following mods or just uninstall Just Enough Items, Forge 14.23.1.2594 or above.: im downloading this mod for the latest version of galacticraft I have tried dozens of different versions of this mod but all of them give me the same error message.

**Comment by Shadows-of-Fire** [comment]
This has nothing to do with AA
