### ISSUE TITLE
[Suggestion]add flax seed to grass loot table or add recipe when Biomes o plenty is detected

### ISSUE THREAD

**Issue by Rubijox** [Ellpeck/ActuallyAdditions#1220]
Title is pretty much self explanatory, that mod adds a ton of biomes, in wich flax plants do not seem to spawn at all, making them super rare

**Comment by Ellpeck** [comment]
Biomes o Plenty doesn't affect the amount of flax that spawns randomly. You must have some other issue going on.

**Comment by Shadows-of-Fire** [comment]
It does, indirectly.
It fills everything with their plants which in turn reduces the number of possible spawn locations.

**Comment by Ellpeck** [comment]
So do plains biomes, that's not a good exucse. Just.. search for longer.

**Comment by Rubijox** [comment]
i have been looking for a few days for these plants for about 30 minutes a day using rtp, i generated about 200mb of world data without finding a single plant, surely you can look into this

**Comment by Quarris** [comment]
I just made 6 worlds on a custom AA+BoP pack and made brand new 6 worlds and managed to find flax seeds without moving from the spawn spot, so either you really are not looking hard enough, or the pack you are playing has modified the spawn chance or maybe even disabled them, or maybe even some other mod may have affect it, but alone these two work well together.

**Comment by Rubijox** [comment]
or perhaps the pack you are playhing has modified settings to make them spawn more, though i have so many mods the issue may come from another one, but when i generate a normal overworld map they spawn everywhere, its only when i make a BOP world that the plants dont seem to exist whatsoever

**Comment by Quarris** [comment]
I literally just said I have a custom pack, I just made the pack with default settings

**Comment by Rubijox** [comment]
then it might be  an interaction between  AA bop and another mod, but that doesnt change that i cant find a single plant if the world type is bop

**Comment by Ellpeck** [comment]
Cannot reproduce. 

Jesus Christ, people.
