### ISSUE TITLE
[Bug?]Lag while attempting to attach extreme energy laser relays to Thermal Dynamics cryo-fluxducts

### ISSUE THREAD

**Issue by NH4HCr2O7** [Ellpeck/ActuallyAdditions#1223]
The case suddenly occurred in my Multiplayer server while trying to attach an extreme energy laser relay to a cryo-fluxduct while the cryo-fluxduct is connected to a generator.The server suffered a significant TPS drop.

Actually Additions version:1.12.2-r144
Thermal Dynamics version:2.5.3.16

**Comment by Shadows-of-Fire** [comment]
It may be that laser relays aren't very receptive to being directly placed on a pipe...  I'll look into it and see if that is indeed the case.

**Comment by Shadows-of-Fire** [comment]
I don't really know what to do about this.  The laser system doesn't perform any special interactions, it's possible that maybe the TD pipe inserts more than once per tick.  But TD is not under active development for .12 anymore as far as I know.  

So uh, just don't put lasers on cables.
