### ISSUE TITLE
[Suggestion] Cross-mod Atomic Reconstructor and other materials

### ISSUE THREAD

**Issue by Collecter128** [Ellpeck/ActuallyAdditions#1224]
This might not be a good idea, but it's something I've never seen before so someone might find this interesting. The Atomic Reconstructor turns vanilla things like Iron and lapis into crystals, but I don't think anybody has made an add-on for copper or any other materials by other mods. This might be more of an idea for an add on than the actual mod, and I don't know if something like this would even be possible. I'm sorry if this isn't the right place for this idea.

**Comment by Shadows-of-Fire** [comment]
Anyone can add their own recipes to the Atomic Reconstructor with ModTweaker, and can add items similarly with ContentTweaker.

However, AA is not interesting in directly interfacing with things such as copper or other modded ingots directly.
