### ISSUE TITLE
[Suggestion] Provide an alternative way to obtain solidified experience

### ISSUE THREAD

**Issue by MarioSMB** [Ellpeck/ActuallyAdditions#1226]
The experience solidifier requires solidified experience to craft, which is unobtainable if solidified experience drops from mobs are disabled.

It would be nice if there was another way to obtain solidified experience, or perhaps use a substitute in the solidifier's recipe (vanilla enchanting bottles for example).

**Comment by Naxanria** [comment]
For alternate recipes, ask the pack developer. Or use something like CraftTweaker to do it yourself :)

**Comment by Quarris** [comment]
I believe if the solid xp can be disabled via configs then there should be an alternate way in the mod

**Comment by Shadows-of-Fire** [comment]
This is better left to an external recipe editing mod.
