### ISSUE TITLE
Changing Item Laser Network is Laggy

### ISSUE THREAD

**Issue by ConnorMiner** [Ellpeck/ActuallyAdditions#1228]
When editing connections of laser relays, it's possible for the active connections to be different from what the actual connections are, leading to situations where items are put into chests that appear completely disconnected from the interface.

Steps to trigger:
1. Build an Item Laser network (preferably with many storage slots)
2. Change some connections (may have to wait)
3. Insert items and watch them go into incorrect inventories.

https://drive.google.com/file/d/1HSsZja8pKB8V6tWcxTEXGeRW0HoHfZD8/view?usp=sharing

**Comment by Ellpeck** [comment]
Are you sure they're not just connected somewhere else? This looks like a pretty confusing system.
Try reproducing this in a test world.
