### ISSUE TITLE
[Bug] Cup of Coffee gets repaired by Cyclic's Diamond Powered Anvil

### ISSUE THREAD

**Issue by TheOddball** [Ellpeck/ActuallyAdditions#1233]
Free coffee for RF!
[GIF of reproducible steps](https://i.oddball.tf/XlxYHiF.mp4)

**Comment by Shadows-of-Fire** [comment]
@Lothrazar does your anvil properly check `Item#isRepairable()`?  The coffee item should return false to that method.

**Comment by Lothrazar** [comment]
I didnt even know that isRepairable existed, so thats a bug ill fix in the next release of cyclic

In the short term, there is also a blacklist for this block  "RepairBlacklist"  in the config file
