### ISSUE TITLE
Crash while ticking Ranged Collector

### ISSUE THREAD

**Issue by Radipon** [Ellpeck/ActuallyAdditions#1238]
Using Enigmatica 2 Expert modpack. Died within the collection area and crashed out. Trying to relaunch and enter world results in a similar crash.

[crash-2019-03-17_19.06.58-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/2975839/crash-2019-03-17_19.06.58-server.txt)

**Comment by Shadows-of-Fire** [comment]
This is a bug in randompatches.
