### ISSUE TITLE
Coffee restoring way more hunger and saturation than intended?

### ISSUE THREAD

**Issue by katubug** [Ellpeck/ActuallyAdditions#1241]
Hello! Firstly, thanks for the great mod! On to my issue: The Cup with Coffee seems to be bugged out for me. The tooltip says that it restores one shank of hunger and a half shank of saturation. However, AppleSkin shows it completely filling the saturation bar, and when drunk (just once), that's exactly what happens.

I am running ActuallyAdditions-1.12.2-r146.

Here is a link to my full modlist: https://docs.google.com/spreadsheets/d/1XS4oFqjvtOMSajuKgJ6v1MvM3L1FD6YEaLbAYtJertg/edit#gid=0

I'm not sure what it might be interacting with. I do have Pam's HarvestCraft, but it's currently config'd to not adjust vanilla foods.

**Comment by Shadows-of-Fire** [comment]
Nope that's working as intended.  Whatever mod is doing the tooltip may be incorrect.

The coffee item is supposd to restore 8 hunger points and 8 * 5 saturation points.
