### ISSUE TITLE
Phantom Breaker deleting NBT data

### ISSUE THREAD

**Issue by DustRaven** [Ellpeck/ActuallyAdditions#1242]
Hi,
i tried to build a woot controller switcher, but when the block breaker removes the controller, its NBT data is removed. 
ActuallyAdditions-1.12.2-r146 and woot-1.12.2-1.4.10

**Comment by Shadows-of-Fire** [comment]
The builder's implementation does not support tile entities like that.  Woot's controller (if TE-break sensitive) should not return anything in getDrops and should spawn the item in the world during breakBlock, which I'm assuming it does not.
