### ISSUE TITLE
laser auto disconnet

### ISSUE THREAD

**Issue by swear01** [Ellpeck/ActuallyAdditions#1243]
The laser disconnect when I AFK 
Both liquid laser and energy laser have the problem (I don't use item laser)
It seems only happening in an array

![2019-04-13_08 23 25](https://user-images.githubusercontent.com/49574926/56072063-c5cd0900-5dc5-11e9-9905-360d7ca05ee4.png)
Verson:r146
I use the morph tool to link laser

**Comment by Shadows-of-Fire** [comment]
Without a proper method of reproducing the error consistently, there's no way to debug this.
