### ISSUE TITLE
New update crashes my client

### ISSUE THREAD

**Issue by skingnet** [Ellpeck/ActuallyAdditions#1246]
After installing the update from a few hours ago my server loaded fine however, my client crashed and I had to rollback to the prior version to solve the problem.

[crash-2019-05-02_10.14.10-client.txt](https://github.com/Ellpeck/ActuallyAdditions/files/3138822/crash-2019-05-02_10.14.10-client.txt)

**Comment by Ellpeck** [comment]
Update Forge.

**Comment by skingnet** [comment]
Thanks, I guess I skipped over that as a requirement... I will try again later, not ready to update forge just yet.
