### ISSUE TITLE
Game not starting because of AA's newest update

### ISSUE THREAD

**Issue by GolfinhoVoador** [Ellpeck/ActuallyAdditions#1249]
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Actually Additions (actuallyadditions)" #1162

**Comment by Shadows-of-Fire** [comment]
no information provided

**Comment by GolfinhoVoador** [comment]
what information do you need?

**Comment by Shadows-of-Fire** [comment]
a crash report or a log or any actual information.  You're probably just using an outdated forge version and yes forge did provide the relevant info, you just decided to only copy a single line.

Go update forge before you post anything here
