### ISSUE TITLE
Item interface crash with Extra Utilities

### ISSUE THREAD

**Issue by Metalit** [Ellpeck/ActuallyAdditions#1250]
When I place an item interface and attempt to use an ender porcupine from Extra Utilities 2 to mimic it, the world crashes and continues to do so on reload.

The crash log is here: https://pastebin.com/T3VxuSkE

I'm playing in the Ultimate Alchemy modpack and using version 1.4.4 of Actually Additions because it crashes during startup with the newest version (which maybe deserves its own report) and version  1.9.9 of Extra Utilities.

**Comment by Shadows-of-Fire** [comment]
Old versions are not supported.  This looks like you broke yourself by pointing an item interface into itself anyway, and I can't really protect against xu being stupid.
