### ISSUE TITLE
[Bug] Wheat Duplication

### ISSUE THREAD

**Issue by XANA520** [Ellpeck/ActuallyAdditions#1259]
I've found a rather nasty duplication bug when creating dough in your inventory. Having 3 or more wheat in a stack in the crafting grid while making dough will cause the wheat to start duplicating exponentially as you make more. I started with around 23 wheat and ended up with over 800 in a single stack. Having 1 wheat will make the recipe work as intended. Having 2 will make it so you can have infinite dough; the wheat stack will never decrease.

To note: I'm using version 1.12.2-r147 as part of the Mech&Magic modpack on the ATLauncher.

I have screenshot proof if needed and can make a video if requested.

**Comment by Shadows-of-Fire** [comment]
does not appear to be happening anymore
