### ISSUE TITLE
GriefPrevention + Actually Additions Duplication Bug

### ISSUE THREAD

**Issue by Focamacho** [Ellpeck/ActuallyAdditions#1261]
**1.** Claim somewhere.
**2.** Place a block in the border of the claim.
**3.** Place what you want to dupe outside of the claim, close to the block in the border.
**4.** Tell to another player without permission in the claim place a Long-Range Breaker.
**5.** It's all, see the video for more info.

**Video: https://www.youtube.com/watch?v=NvNTE3dG114**
Reported too in: https://github.com/MinecraftPortCentral/GriefPrevention/issues/903

**Comment by Shadows-of-Fire** [comment]
Direct support for sponge/plugins is not provided by AA.
