### ISSUE TITLE
Tutorials for using the crushed and included new ores. 

### ISSUE THREAD

**Issue by BadKaiPanda** [Ellpeck/ActuallyAdditions#1265]
Long time no see Ellpeck, hope you are well, Rex and Toffee here.

Anyway back to what I was here to ask, I seem to have a problem getting my own ore to be used in your mod, do I need to make a ore and a dust for it? I am able to register my ore part of the ore directory.

My ore does not spelt in to a ingot, it first gets changed in to a raw ingot what I tried setting as the ore, but I am not sure if I meant to make a dust also, do you have any tutorials anywhere

**Comment by Shadows-of-Fire** [comment]
The crusher picks up ores with the oredict tag `oreX` and matches them to `dustX`.
Your ore itemblock should be registered as the ore, and you should make a dust item if you want the crusher to function normally.

**Comment by BadKaiPanda** [comment]
I just did that but not seeming to work right now what version was this the case from as I had to go back a few versions as the IRarity was crashing as it's seems to be bugged or not in the recommend forge build I was using.

**Comment by BadKaiPanda** [comment]
OK close this, I hope Ellpeck still sees it but I seemed to A forgot to compile the new changes and also forgot to state it was a .block but it's all working now.

**Comment by BadKaiPanda** [comment]
Didn't you read the edit I said don't clsoe it just yet, as ingots are also getting in to dust and I alike to know it's possible to get more then dust back
