### ISSUE TITLE
Ranged Collector cannot pickup items on pressure pads or trip wires

### ISSUE THREAD

**Issue by arceus179** [Ellpeck/ActuallyAdditions#1267]
I'm trying to make an automation system for the Atomic Reconstructor. Basically I drop an item on a tripwire and it pulses some redstone to transform the items. The problem is the ranged collector refuses to pick up any items on a tripwire or a pressure plate.

**Comment by Ellpeck** [comment]
The Ranged Collector gets disabled by redstone.

**Comment by arceus179** [comment]
Well I feel like an idiot.
