### ISSUE TITLE
crusher didn't register dusts

### ISSUE THREAD

**Issue by hehtime** [Ellpeck/ActuallyAdditions#1272]
So, I have Forestry, and it doesn't have dusts. So I installed Pulver, a mod that adds oredictionary dusts. So I have DustCopper, IngotCopper, i can smelt dust into copper, but i can't crush ore into dust. So why Crusher didn't registered? Tags are fine

**Comment by Shadows-of-Fire** [comment]
Pulver creates these items far too late into the loading cycle, so they are never detected by AA.
