### ISSUE TITLE
Greenhouse Glass can stack

### ISSUE THREAD

**Issue by FallenEagle1** [Ellpeck/ActuallyAdditions#1278]
Wondering about how hard it would be to have a config option for how many times greenhouse glass can stack. Been noticing lately that there have been a number of builds in the ATM packs that stack greenhouse glass fairly deep above a plant to speed up plant growth. I get allowing some stacking, but some of the builds just seem overzealous for trying to just speed up growth.

If a config option is somewhat easily done, another suggestion might be to have a tooltip saying how many can be stacked, to help with understanding how many is allowed between the different packs.

**Comment by Shadows-of-Fire** [comment]
You know, I'm pretty sure it's not supposed to be stackable :thinking: 
Would need ell to confirm tho but I recall hearing that.   May just be bugged

**Comment by FallenEagle1** [comment]
Sounds good. It did seem wierd for it to stack, so my two cents is to not have it stack, but that's just me ¯\_(ツ)_/¯

**Comment by Ellpeck** [comment]
It should most definitely not be stackable.

**Comment by Darkere** [comment]
Greenhouse glass was made stackable back in r143 https://github.com/Ellpeck/ActuallyAdditions/commit/1d56bfb86991cdd67fe309824a852f4d065bfe8f

**Comment by Ellpeck** [comment]
Yea please fix that @Shadows-of-Fire, that was a terrible change lol

**Comment by mrdeadlocked** [comment]
This is a terrible change. GG glass is great being stackable. Stacking the glass through using more of your resources allows it to be on par with other faster-growing methods.

**Comment by Ellpeck** [comment]
ok

**Comment by mrdeadlocked** [comment]
You commented too quickly! I made an edit above :-)

**Comment by Ellpeck** [comment]
no sorry I think it being stackable is absolutely terrible

**Comment by mrdeadlocked** [comment]
Alright. It is a very sad day. Bye Bye farm.

https://www.youtube.com/watch?v=ZVg5J4l1TBc&feature=youtu.be
