### ISSUE TITLE
Vertical Digger inventory

### ISSUE THREAD

**Issue by MrRiegel** [Ellpeck/ActuallyAdditions#128]
The digger just set the mined item into the next empty slot.
It would be better if it tries to merge with existing items.

**Comment by Ellpeck** [comment]
It.. it does.
That's how it works.

**Comment by Ellpeck** [comment]
I don't get what you're saying.

**Comment by MrRiegel** [comment]
this
https://drive.google.com/file/d/0Bxk8bebSTRk-cUUtOVV4LUhpcG8/view?pref=2&pli=1

**Comment by Ellpeck** [comment]
I don't want to "fix" this, sorry.
It is supposed to work in the way that it always starts checking at the top left.
Changing this would make the code way more complicated and performance intensive and I don't actually like the way that would work gameplay-wise.
