### ISSUE TITLE
recipes not working in DD and SS modpack

### ISSUE THREAD

**Issue by otterinkelpbed** [Ellpeck/ActuallyAdditions#1280]
I started playing the Dungeons, Dragons and Space Shuttles version 5.5a modpack (running Forge 14.23.5.2836, minecraft version 12.2) through the Twitch server and noticed I could not craft the 'Rice dough' recipe  given in the "Actually Additions" manual (which is simply three pieces of rice in the crafting grid). I was able to get around that by using a different recipe (a potato, a pice of rice and a crushing mortar). I have progressed quite far and enjoy the modpack very much and want to continue, but I ran the same issue when I needed to make a package of fries for an achievement (the recipe is a row of three 'fries' above a paper cone in the crafting grid). Again, when I put the ingredients in the crafting grid exactly as given in the AA manual, nothing appears in the crafting grid output window.
       I do not know if this recipe failure is occurring for all AA recipes or those just for food. I have tried the following things with no luck so far:
- reloading the modpack
- resetting control keybindings 
- crafting on the plain vanilla crafting table
- running Forge version 14.23.5.2838
      I cannot find any control options that may be causing the issue and do not know how to begin checking for causes from interactions with other mods because there are so many other mods in this modpack. Does anyone have any suggestions?
      If it helps, I am playing on a Macbook Pro Os High Sierra. I doubt any of my other specs are a problem as I haven't encountered any other issues with the modpack.
      I would be grateful for any suggestions to try to fix this!

**Comment by Ellpeck** [comment]
The recipe was probably changed by the modpack author.

**Comment by lrmerickel** [comment]
> The recipe was probably changed by the modpack author.

I’m having this issue and need help.
