### ISSUE TITLE
Farmer doesn't work well when combining pumpkins/melons with other seeds

### ISSUE THREAD

**Issue by superreg** [Ellpeck/ActuallyAdditions#1282]
I tried with pumpkins in particular. The pumpkin stems would be planted in a checkerboard as intended, but seeds would be planted where there's supposed to be air. This was done on FTB Academy 1.0.0 with AA version 1.12.2-r149.

**Comment by reifnotreef** [comment]
What I did was plant the pumpkin outside the farmer's range, so that it would the grow the plant in range.

**Comment by Shadows-of-Fire** [comment]
The farmer is not designed for multiple types of crops at once
