### ISSUE TITLE
Phantom Breaker deletes Enviro. Tech blocks when activated

### ISSUE THREAD

**Issue by Zapf1** [Ellpeck/ActuallyAdditions#1283]
Running modified DW20 1.12 pack

Enviromental tech version 1.12.2-2.0.19.1
AA version 1.12.2-r146

Trying to use phantom breaker/placer to swap out laser lenses and miner controllers remotely. Placing works as expected, breaker deletes any Env. Tech block it's used on.

**Comment by Shadows-of-Fire** [comment]
That makes it sound like the ET blocks are using some weird way of dropping themselves, as they'd be the outlier.  Likely an issue on their side.
