### ISSUE TITLE
Using Coffee Cup with Unbreaking Enchantment ignores Enchantment

### ISSUE THREAD

**Issue by Danekjovax** [Ellpeck/ActuallyAdditions#1287]
Version Info:
modpack-Dungeons Dragons & Space Shuttles v.6.3
forge-1.12.2-14.23.5.2807-universal
ActuallyAdditions-1.12.2-r150

Description:
The Coffee cup with Unbreaking Enchantment will ignore any durability bonus when used. To measure this, I crafted a coffee cup with several buffs and applied Mending and Unbreaking III and monitored the durability useage over a week of playing.  In all cases of drinking the coffee, the durability dropped by 1 point 100% of the time.

Either Unbreaking isn't intended to be placed on the item, or Unbreaking code is being ignored or is broken for it.

Thank you for your time, and for a great mod!

Screenshots attached:
![2019-10-26_23 28 07](https://user-images.githubusercontent.com/10191173/67634905-bdd34300-f897-11e9-8b0a-876706679575.png)

https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/442

**Comment by Shadows-of-Fire** [comment]
Coffee should not be enchantable, so no support provided here.  It will be marked explicitly as such in the next update to prevent this from happening at all.
