### ISSUE TITLE
You can destroy blocks instantly with Fertilizer by clicking RMB

### ISSUE THREAD

**Issue by XiltoA** [Ellpeck/ActuallyAdditions#1290]
Mod version: r150. Minecraft version: 1.12.2
Forge version: 14.23.5.2847. Modpack: my own

Fertilizer breaks blocks instantly by clicking RMB. Reloading Minecraft doesn't help at all.

![2019-11-02_21 19 54](https://user-images.githubusercontent.com/39626601/68072273-93f9af00-fdb6-11e9-828a-936aaf799614.png)

**Comment by Shadows-of-Fire** [comment]
cannot reproduce
