### ISSUE TITLE
problem with vertical digger on server

### ISSUE THREAD

**Issue by garath77** [Ellpeck/ActuallyAdditions#131]
This is the second time I've had this happen now. On my local server, with just me on it at the time, I go to move the vertical digger and the server crashes. The crash report [http://pastebin.com/9jqJLbG9] says something about the digger not being minable.  

Thanks for the help and all your hard work. I'm looking forward to what you have coming next.

**Comment by Ellpeck** [comment]
This has been fixed a while back already! :)
Update the mod.

**Comment by Ellpeck** [comment]
Oh, just noticed you're on 1.9 still.
Well, there's nothing I can do about it, I don't support 1.9 anymore. Sorry :(

**Comment by garath77** [comment]
Crud, I have so many mods that I'm still using that haven't been updated yet. I guess I'll have to put up with it until then. Thanks
