### ISSUE TITLE
Powered Furnace Crash when finished smelting  

### ISSUE THREAD

**Issue by marvercraft** [Ellpeck/ActuallyAdditions#1311]
Happens in Singleplayer and MP
Tried older Versions  
Up to version r135 no Issues
Crashes since version r136 (tried r136 Hotfix 8, r138, r140, r150, r152)
(version r136 won't even start)

Furnace is Powered by a Coal Generator next to it.
Related to issue #1176 and #1273 
Crash Report:
https://paste.dimdev.org/donefamosa.mccrash 
(all look the same from r136 Hotfix 8 to r152 maybe see the reports from the related issues)
Mod pack "A New Home" (customized from me with extra mods) 
maybe it's another mod witch causes an issue

**Comment by Shadows-of-Fire** [comment]
Either the jar you have is corrupt, or another mod is breaking AA, but this issue is not present with just AA or caused by AA
