### ISSUE TITLE
Auto-Placer

### ISSUE THREAD

**Issue by EAC51** [Ellpeck/ActuallyAdditions#1319]
Can't craft the Auto-Placer for some reason.

Project Ozone 3 A New Way Forward
Version: 3.2.55

Minecraft Version: 1.12.2

(modded) forge-14.23.5.2847
![Screenshot (13)](https://user-images.githubusercontent.com/9408573/78864885-7843a600-79f1-11ea-9775-87ccc1423473.png)
[latest.log](https://github.com/Ellpeck/ActuallyAdditions/files/4454432/latest.log)

**Comment by Ellpeck** [comment]
the recipe was probably changed in the modpack.
