### ISSUE TITLE
[Bug] 1.12.2, Localization Of Crystal Flux

### ISSUE THREAD

**Issue by CrankySupertoon** [Ellpeck/ActuallyAdditions#1325]
Hey, the localization for Crystal Flux doesnt work is there any way we can fix that. If not do you give me permission to fork the mod and change the variables myself and publish to curse with 100% of points going to Ellpek

**Comment by Ellpeck** [comment]
what

**Comment by CrankySupertoon** [comment]
Can we localize the word crystal flux like you would localize the word “machine” or “laser” for other languages so I can chance crystal flux to RF

**Comment by Ellpeck** [comment]
but it's called crystal flux lol

**Comment by CrankySupertoon** [comment]
That’s the point if you make crystal flux localizable you can rename it into Redstone Flux or anything. It is already done as it is in the .lang file but doesn’t work

**Comment by OneLemonyBoi** [comment]
wotm8

**Comment by CrankySupertoon** [comment]
> but it's called crystal flux lol

Well its actually called Forge Energy but ill close this now
