### ISSUE TITLE
I hate this mod now

### ISSUE THREAD

**Issue by D3Gamer** [Ellpeck/ActuallyAdditions#1327]
I was using the version from 2016 on 1.10 and I today I just moved over to 1.12.2 and the "new" version of this mod is terrible awful bad terrible. There are a lot of "new" features that I really like but I don't like how you downgraded the entire mod by making potion rings worthless and nerfing so much other things that it isn't even funny. This was my favorite mod of alltime. Keyword. WAS. How can you ruin a mod so thoroughly and completely I am surprised people still use this mod.

**Comment by Quarris** [comment]
hahaYes

**Comment by Shadows-of-Fire** [comment]
:ok_hand:

**Comment by Ellpeck** [comment]
what the fuck is your problem lmao

**Comment by Vazkii** [comment]
ok

**Comment by quat1024** [comment]
I was using the vewsion fwom 2016 own 1.10 awnd i today i juwst moved ovew tuwu 1.12.2 awnd the "new" vewsion of thiws mod iws tewwibwe awfuw bad tewwibwe. Thewe awe a wot of "new" featuwes thawt i weawwy wike but i down't wike how uwu downgwaded the entiwe mod by making potion wings wowthwess awnd newfing so much othew things thawt iwt isn't even funny. Thiws was my favowite mod of awwtime. Keywowd. Was. How cawn uwu wuin a mod so thowoughwy awnd compwetewy i am suwpwised peopwe stiww use thiws mod. uwu

**Comment by Vazkii** [comment]
I was using the version from 2016 on 🔛🔛🔛 1.10 and I today I just moved over to 1.12.2 and the "new 🆕🆕" version of this ⬆ mod is 🈶 terrible awful bad 📉📉📉 terrible. There are a lot of "new 🆕🆕🆕" features that I really like 😄😄😄 but I don't like 😄😄😄 how 🤔 you downgraded the entire mod by making potion rings 🔗🔗🔗 worthless and nerfing so much other things that it isn't even funny 😃😃. This ⬆ was my favorite 🔖 mod of alltime. Keyword. WAS. How 🤔 can you ruin a mod so thoroughly and completely I am surprised 😲 people 👫👫 still use this ⬆ mod.

**Comment by eutropius225** [comment]
This need to be addressed IMMEDIATELY or I will be removing this mod from my modpack. So far it has over 100 downloads, so this will greatly affect your income, leading to you being unable to feed your family. I hope you're happy.

**Comment by Ellpeck** [comment]
oh no my poor family whatever will I do

**Comment by thecodingchicken** [comment]
Sorry, but I need to join in the fun

Thith n-need to be addwessed IMMEDIATEWY o-ow I wiww be wemyoving thith myod fwom my myodpack. So faw it hath o-ovew 100 downwoadth, so thith wiww gweatwy affect y-youw income, weading to y-you being unyabwe to feed youw famiwy. I hope you'we happy.

**Comment by enderger** [comment]
Now I see why Ellpeck wants nothing to do with Actually Additions, good grief this place needs an issue template.

**Comment by Quarris** [comment]
holy fuck I got emailed about this and got REALLY confused

**Comment by MichaelHillcox** [comment]
Thanks for the feedback, as the new maintainer of the mod, I'll be sure to keep ruining it just for you ❤️

**Comment by thecodingchicken** [comment]
Lol, I remember this issue.  Loved it.
