### ISSUE TITLE
Vertical Digger Crash

### ISSUE THREAD

**Issue by unecesary** [Ellpeck/ActuallyAdditions#1335]
I'm working on a Pixelmon server, and using the vertical digger tends to crash the server when it attempt to mine a pixelmon ore. (im also talking with the Pixelmon group to see if its anything on their end), i have the digger on Ores only mode and here is the log that it sends to console: https://pastebin.com/2mVY9zsp

**Comment by unecesary** [comment]
Update: upon blacklisting the pixelmon ores, it seems to be working just fine. (not ideal, but a fine temp fix)

**Comment by Shadows-of-Fire** [comment]
pretty sure this is completely on pixelmon's end for not handling fake players (at least thats what it looks like)
