### ISSUE TITLE
[1.12.2] Farmer does not collect from Simple Corn properly

### ISSUE THREAD

**Issue by SteveHeist** [Ellpeck/ActuallyAdditions#1337]
I added Actually Additions to FTB Ultimate Reloaded on 1.12.2, and found that the Farmer does not collect the Simple Corn. It should work like Immersive Engineering Industrial Hemp, but instead breaks the block before it's fully grown and drops everything to the ground.

**Comment by Shadows-of-Fire** [comment]
It is up to other mods to integrate with the API provided for the farmer (which immersive engineering does).

**Comment by SteveHeist** [comment]
Oh, ok. Is that something that can be done from a cfg or something somewhere in a modpack, or is that a case of telling the other mod creator?

**Comment by Shadows-of-Fire** [comment]
Second one

**Comment by SteveHeist** [comment]
Ok, thank you. Sorry for bothering you about it. I'll let them know if I can.
