### ISSUE TITLE
Feature: Add 'drawbridge' block mimicking the function of old block from TiC

### ISSUE THREAD

**Issue by RacerDelux** [Ellpeck/ActuallyAdditions#134]
Two versions:
Basic: Has one inventory slot, it will place as many blocks in the inventory as it can (either until it runs out of blocks, or reaches another block that is already there) on redstone power. On restone off, it will retract these blocks.

Advanced: Has a line (old one has 5 slots I think) in which a pattern of blocks can be defined. will output a line based on this pattern (repeating if the gap it is filling is too long). Rest of the functionality is the same as basic.

**Comment by Ellpeck** [comment]
So what would be the uses?
I was thinking of making a long-range placer as a counterpart to the long-range breaker.
You'd just have to have a breaker opposite the placer to break the blocks again.
Would that suffice as well?

**Comment by RacerDelux** [comment]
It wouldn't be as compact. I tried using placers before, but it did not work. I had one block selected, but it kept placing two blocks.

The used would be to expand vertically or horizontally with blocks. Makes bridges efficiently.

**Comment by Ellpeck** [comment]
I don't really know about this.

**Comment by DRTR0** [comment]
@Ellpeck He's referring to the Tinker's draw bridge from 1.7.10.

**Comment by Ellpeck** [comment]
I know.
I didn't say "I don't know what you mean", I meant "I don't know if I should implement this".

**Comment by DRTR0** [comment]
The "basic" version he was describing sounds like it could be an advanced placer? These mods are updating soon anyways. No need to copy them entirely imo.

**Comment by Ellpeck** [comment]
Yea, that's what I think.
Also I don't like the idea of a drawbridge type block, sorry.
I won't do this :(
