### ISSUE TITLE
[Suggestion] Jetpacks

### ISSUE THREAD

**Issue by MrRiegel** [Ellpeck/ActuallyAdditions#135]
It would be nice if you add jetpacks or more precisely One Jetpack which is similiar to the drill.
Fuel is RF (or Tesla) and it can be upgraded with battery, thrust upgrade, etc.
For 1.9/1.10 there are actually no jetpack mods.

Edit: And protection upgrade

If you are interested, I worked on a jetpack month ago but never released it.
https://github.com/MrRiegel/Various-Items/blob/a58db6886b9f65d976da32d438175295376232a4/src/main/java/mrriegel/various/items/ItemJetpack.java#L85-L150

**Comment by radiocrack** [comment]
I like this idea. many of the jetpack mods in 1.7 are pretty boring.  I'm a fan of modular powersuits but i really like your simple upgrade system.  Hover, speed, control, mining bonus.  limited number of modules means you need to decide the configuration.  like the drill.

**Comment by Ellpeck** [comment]
Well, I hope you don't want to have the jetpacks in the 1.7 version of Actually Additions, because that's not going to happen, as I don't support that version anymore.

**Comment by Ellpeck** [comment]
So, I've come to the conclusion that I don't *want* Jetpacks in Actually Additions.
Sorry.

**Comment by MrRiegel** [comment]
nevermind. There are the wings of the bats anyway
