### ISSUE TITLE
#1351 continued - Disruption lens issue

### ISSUE THREAD

**Issue by vasquezusa** [Ellpeck/ActuallyAdditions#1352]
Thanks for the reply on the other issue, I deleted the config and let the game recreate a fresh one, and you were right that it is on by default, the beam is changing color but items I'm dropping onto the beam are not changing into random items. I

You can see on the video here I have the proper easter egg lens attached (indicated by the beam color) and I begin dropping items a variety of ways onto it, with no change:

https://user-images.githubusercontent.com/29961026/102721042-2c5a3800-42c6-11eb-8428-4f227b9327a9.mp4

**Comment by Ellpeck** [comment]
I locked conversation on the other issue because I don't want information about this **easter egg** to spread more than necessary. The laser has to hit the block space that the item is in and then hit a wall immediately after.
