### ISSUE TITLE
Power won't flow through farmer via EnderIO

### ISSUE THREAD

**Issue by flleeppyy** [Ellpeck/ActuallyAdditions#1353]
I'm trying to make my farm organized, so I want to be able to do this with the farmers, having power pass through them

![image](https://user-images.githubusercontent.com/18307183/103336820-2c78d700-4a2e-11eb-8410-b6c4cf439a61.png)

But that doesn't work, and power doesn't flow over to the next farmer, so I have to use more conduits and do this
![image](https://user-images.githubusercontent.com/18307183/103336852-461a1e80-4a2e-11eb-92a8-b3c4e05a2bf1.png)

Is this a bug or was it never implemented and if so, can it be implemented?

**Comment by Shadows-of-Fire** [comment]
Why would that ever work?  The farmer is not a power conduit nor a power source.

**Comment by flleeppyy** [comment]
jeez okay
