### ISSUE TITLE
Eating does not heal me

### ISSUE THREAD

**Issue by captinwill** [Ellpeck/ActuallyAdditions#1359]
After installing this mod, i get this glitch that where if i lose one piece of health i cannot regen it. And I have /gamerule naturalRegeneration = true (1.12.2)

**Comment by Ellpeck** [comment]
Do you have any other mods installed? If so, please try to reproduce this issue with just Actually Additions installed.

**Comment by MichaelHillcox** [comment]
Closed due to no response
