### ISSUE TITLE
Building spawning

### ISSUE THREAD

**Issue by GamerPi** [Ellpeck/ActuallyAdditions#1362]
I have had multiple worlds where the engineer building spawns either inside other village buildings or they spawn halfway in a mountain or underground. This conflicts with other mods that place in villages as well so I am bringing to their attention as well. Examples are Waystones and PixelmonGo.

**Comment by Ellpeck** [comment]
Can you reproduce this issue with just Actually Additions installed?

**Comment by GamerPi** [comment]
I think this is more of a pixelmon issue, it seems that it is just the placement of villages over unsafe areas or in oceans, I tested with only waystones, pixelmon and actually additions and it seems that out of all of the mods, yours is the safest of all of them for spawning locations. It still has issues depending on if the village is in the ocean but i've narrowed it down to just pixelmon

**Comment by Ellpeck** [comment]
Thanks for investigating! Please report this issue to the Pixelmon developers, then.
