### ISSUE TITLE
Minecraft failed to start, the problem is most likely caused by Actually Additions.

### ISSUE THREAD

**Issue by multiplexus** [Ellpeck/ActuallyAdditions#1363]
My Minecraft modpack failed to start and it displayed a message in which it said that Actually Additions was most likely the cause. 
Crash Report: https://paste.dimdev.org/ecunorezep.mccrash

**Comment by MichaelHillcox** [comment]
You have too many mods, it's not caused by any one mod. You've just run out of ids. You need to remove some mods that add items / blocks.
