### ISSUE TITLE
[BUG?] Medium and large storage crate wont switch pages

### ISSUE THREAD

**Issue by FuryZzyzx** [Ellpeck/ActuallyAdditions#1364]
I am playing AoE (Age of Engineering) in 1.10.2 and the medium and large storage crates are useless in the sense that they do not upgrade the small storage crate at all. There is an arrow which I assume is to change pages but it does not work even when I right click or left click on it. I am not sure if this is a bug or something like that or if I need to update to a newer version of actually additions.

**Comment by FuryZzyzx** [comment]
im on r105

**Comment by Ellpeck** [comment]
1.10.2 is not supported anymore.
