### ISSUE TITLE
Add a programer art resource pack to new versions.

### ISSUE THREAD

**Issue by Colonizor48** [Ellpeck/ActuallyAdditions#1368]
Title. Add a version using the old 1.12.2 textures for old blocks. Maybe giving new blocks old textures here but mabye not. Some of us prefer programer art and it wouldnt take that much effort to just put all the old 1.12.2 textures into a resource pack or config option.

**Comment by MichaelHillcox** [comment]
Huh? The mods only out for 1.12? Confusion

**Comment by Colonizor48** [comment]
When the mod eventually updates to 1.16.x or 1.17.x

**Comment by Colonizor48** [comment]
I dont know if this is feasable but could you just modify the textures a bit for said new models? I wouldnt imagine this would be too hard but it would depend on how different the model was.

**Comment by Ellpeck** [comment]
There are no plans for a feature like this at the moment, sorry!
