### ISSUE TITLE
Shock Suppressor

### ISSUE THREAD

**Issue by praetoras** [Ellpeck/ActuallyAdditions#137]
Shock Suppressor: Block that by feeding RF protects blocks from explosions or destruction within an upgradeable/configurable range. Alternate version may also protect against harvesting.

Option for Vertical Digger: Allow the Vertical Digger to be controlled by redstone, so that the user can turn it on/off.

**Comment by Ellpeck** [comment]
1. Awesome
2. It already is that way. Just power it and it'll stop digging :3

**Comment by praetoras** [comment]
I appreciate the head's up on the vertical digger :)

**Comment by Ellpeck** [comment]
Oh yes I did this yesterday.
