### ISSUE TITLE
Unable to create Crystallized Canola Seeds 

### ISSUE THREAD

**Issue by lolblockheadlol** [Ellpeck/ActuallyAdditions#1373]
It appears that in the last year, the atomic reconstructor has been removed from this modpack- and I am now unable to create crystallized canola seeds.  It appears that most items can be created using the "drop it in water" recipe (restonia crystals, etc.), however canola seeds do nothing.  Is there a workaround for this that I'm not aware of?  The in-game book is not updated, and says to use the atomic reconstructor.  This is game breaking.

**Comment by Ellpeck** [comment]
What modpack are you using? This seems like an issue with the pack and not the mod itself.

**Comment by lolblockheadlol** [comment]
@Ellpeck I'm using Infinity-Craft, everything seems to work fine- but there is no way I can find to craft crystallized canola seeds... it's not that nothing works, it's that there literally does not appear to be a way to do it without an atomic reconstructor- which I was told was removed from the mod because it was able to dupe items somehow.  Is dropping the seeds in water supposed to produce crystallized seeds?  In JEI and in the book, there is no other way to create crystallized canola seeds aside from using the atomic reconstructor.  Am I missing something?  I even tried taking the ,jar file from my working copy in FTB Revelation, and there was no change.

**Comment by Shadows-of-Fire** [comment]
If the atomic reconstructor has been disabled by that modpack, it is that modpack's responsibility to create alternate recipes for all content that requires it.

The atomic reconstructor is still very much a part of AA, and is enabled by default, so you'll need to take it up with the modpack.

**Comment by lolblockheadlol** [comment]
OH, I did not understand correctly.  I was under the impression it was removed by the author of Actually Additions.  My mistake.  Thank you!  @Shadows-of-Fire

**Comment by lolblockheadlol** [comment]
@Ellpeck confirmed problem, had to delete a script that the modpack author was running.  Do you want me to delete this entire thread or just leave it?  In closing- thanks so much for this amazing mod!!!  My friend and I both love it!!!  It's a MUST have.
