### ISSUE TITLE
Actually Addition crash 1.12.2

### ISSUE THREAD

**Issue by Nossimy** [Ellpeck/ActuallyAdditions#1388]
[crash-2023-09-06_16.47.20-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/12539717/crash-2023-09-06_16.47.20-server.txt)

**Comment by Ellpeck** [comment]
Minecraft 1.12.2 is not supported anymore, sorry. Please try to reproduce this issue in 1.20.4 and potentially open a new issue or comment on this one to have it reopened :)
