### ISSUE TITLE
1.20 Suggestion | Artificial Grass

### ISSUE THREAD

**Issue by DMJaxun** [Ellpeck/ActuallyAdditions#1392]
Just an idea for another block when porting is finished.

Artificial Grass

Found a place to base but the biome borders make grass look horrible?

Cover the area in Artificial Grass which can have a hex colour set to it.

**Comment by Ellpeck** [comment]
Hi, thanks so much for your suggestion! Unfortunately, there are no plans to add new features to Actually Additions at the moment.
