### ISSUE TITLE
[Request] Standalone Elements

### ISSUE THREAD

**Issue by ThePansmith** [Ellpeck/ActuallyAdditions#1394]
This one is a bit out there, but it would be greatly appreciated if considered.

Nomifactory uses the Empowerer and the Atomic Reconstructor in progression, and a port of the pack to 1.20.1 is being done. AA is a decently large mod, and thus will take some time to get the entire mod ported, but if just the Empowerer and Reconstructor could be finished and pushed into its standalone mod as a holdover for packdevs, it would be greatly appreciated.

**Comment by Ellpeck** [comment]
Hi! Given the 1.20.4 port of the mod is almost entirely completed, this is not something we're planning on doing. Sorry!

**Comment by ThePansmith** [comment]
Ah, good to hear. I assume that said features will be backported to 1.20.1?

**Comment by Ellpeck** [comment]
We're currently still in the progress of figuring out whether we're interested in releasing a 1.20.1 version of the mod :)

**Comment by Leclowndu93150** [comment]
> We're currently still in the progress of figuring out whether we're interested in releasing a 1.20.1 version of the mod :)

Would be pretty cool because it is one of the 2 missing mods for our project https://github.com/Nomi-CEu/Nomi-CEu-Modern

(the other one being draconic evolution)

**Comment by ThePansmith** [comment]
That, and it's a nice mod to have in general.
