### ISSUE TITLE
No spaces in the Manual

### ISSUE THREAD

**Issue by Protheus** [Ellpeck/ActuallyAdditions#14]
Using version 0.0.9.0 and the text in the manual doesn't have any spaces making reading it not pleasant 

http://imgur.com/J4bKPqU

**Comment by Ellpeck** [comment]
Probably because you're using a texture pack, I might not be able to fix that.
Go into your Language Options and turn Unicode Font on, see if any other text is missing spacing, if so, your texture pack is broken.

**Comment by Ellpeck** [comment]
(If not, it's probably my fault :( )

**Comment by Protheus** [comment]
I do apologies. Should have checked it without a pack.left for vacation so will not be able to check it but will close the issue

**Comment by Protheus** [comment]
well tried with and without texture pack, unicode on and off and still get the same problem - text is all without spaces

**Comment by Ellpeck** [comment]
What!? I don't know anyone else that's happening to.
Give me a mod list and the version of forge you're using, please.

**Comment by Protheus** [comment]
Below the info. It is readable but you need to check what words :-) all in all not really a high priority but goodluck with it.

Forge: 1448 (1.7.10)

Mods List:

ActuallyAdditions-1.7.10-0.0.9.2.jar
ae2stuff-0.5.0.56-mc1.7.10.jar
AOBD-2.8.4.jar
appliedenergistics2-rv2-stable-10.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar
bdlib-1.9.2.105-mc1.7.10.jar
BetterAchievements-1.7.10-0.0.2.jar
BetterFps-1.0.1.jar
BiblioCraft[v1.11.2][MC1.7.10].jar
BigReactors-0.4.3A.jar
BloodArsenal-1.7.10-1.2-3.jar
BloodMagic-1.7.10-1.3.3-13.jar
Botania r1.7-223.jar
BrandonsCore-1.0.0.7.jar
buildcraft-7.1.3.jar
Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
Chisel-2.9.1.7.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.0.4B1-308.jar
CoFHLib-[1.7.10]1.0.4B1-176.jar
compacter-1.1.0.12-mc1.7.10.jar
compactmachines-1.7.10-1.20.jar
CreativeCore v1.3.7 mc1.7.10.jar
Damageindicatorsmod-3.2.0.jar
dimensional-anchor-59.0.3.jar
Draconic-Evolution-1.7.10-1.0.2-Snapshot_3.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
Ender Enhancement-1.7.10-1.3.jar
EnderCore-1.7.10-0.1.0.24_beta.jar
EnderIO-1.7.10-2.3.0.415_beta.jar
EnderStorage-1.7.10-1.4.7.37-universal.jar
EnderTech-1.7.10-0.3.2.400.jar
enderutilities-1.7.10-0.4.3.jar
EnderZoo-1.7.10-1.0.15.32.jar
EnhancedPortals_1.7.10-universal-3.0.10.jar
ExtraCells-1.7.10-2.3.0b142.jar
ExtraTiC-1.7.10-1.4.5.jar
extrautilities-1.2.11.jar
fastcraft-1.21.jar
FlatSigns-1.7.10-universal-2.1.0.19.jar
forestry_1.7.10-3.6.9.28.jar
Galacticraft-Planets-1.7-3.0.12.357.jar
GalacticraftCore-1.7-3.0.12.357.jar
gendustry-1.6.0.125-mc1.7.10.jar
generators-0.9.18.115-mc1.7.10.jar
Guide-API-1.7.10-1.0.1-22.jar
ImmersiveEngineering-0.5.4.jar
immersiveintegration-0.5.3.jar
immibis-core-59.1.2.jar
InfiniBows-1.7.10-universal-coremod-1.3.0.20.jar
InGameInfoXML-1.7.10-2.8.1.73-universal.jar
INpureCore-[1.7.10]1.0.0B9-62.jar
InventoryTweaks-1.59-dev-156.jar
Ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.1a_1.7.10.jar
journeymap-1.7.10-5.1.0-unlimited.jar
LunatriusCore-1.7.10-1.1.2.21-universal.jar
magicbees-1.7.10-2.3.6.jar
malisiscore-1.7.10-0.12.9.jar
malisisdoors-1.7.10-1.10.jar
Mantle-1.7.10-0.3.2a.jar
mcjtylib-1.5.1.jar
Mekanism-1.7.10-8.1.7.252.jar
MekanismGenerators-1.7.10-8.1.7.252.jar
MekanismTools-1.7.10-8.1.7.252.jar
MicdoodleCore-1.7-3.0.12.357.jar
MineFactoryReloaded-[1.7.10]2.8.1B1-129.jar
Morpheus-1.7.10-1.6.10.jar
natura-1.7.10-2.2.1a2.jar
NBTEdit_1.7.10.jar
neiaddons-1.12.12.37-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.0.12.jar
NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar
NetherOres-[1.7.10]2.3.1B1-14.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
OpenBlocks-1.7.10-1.4.4-snapshot-665.jar
OpenModsLib-1.7.10-0.8-snapshot-393.jar
OptiFine_1.7.10_HD_U_B7.jar
Pam's HarvestCraft 1.7.10j.jar
PlayerAPI-1.7.10-1.3.jar
PneumaticCraft-1.7.10-1.11.13-135-universal.jar
practicalities-1.7.10-0.6.2.jar
pressure-1.2.4.124-mc1.7.10.jar
ProjectRed-1.7.10-4.7.0pre9.92-Base.jar
ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar
ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar
ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar
ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar
ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar
ProjectRed-1.7.10-4.7.0pre9.92-World.jar
Railcraft_1.7.10-9.7.0.0.jar
RandomAdditions Alpha 0.11.11 mc1.7.10.jar
RandomThings-2.2.4.jar
RedstoneArsenal-[1.7.10]1.1.1-89.jar
rftools-3.41.jar
roguelike-1.7.10-1.3.6.3.jar
Ruins-1.7.10.jar
Sanguimancy-1.7.10-1.1.9-33.jar
Schematica-1.7.10-1.7.6.128-universal.jar
SimplyJetpacks-MC1.7.10-1.4.1.jar
SoulShards-TOW-1.7.10-0.1-RC9-7.jar
StevesAddons-1.7.10-0.10.16.jar
Stevesfactorymanagera93.jar
swapper-1.0.4.jar
TConstruct-1.7.10-1.8.7.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.0.3B1-218.jar
ThermalFoundation-[1.7.10]1.2.0-102.jar
TiCTooltips-mc1.7.10-1.2.5.jar
TMechworks-1.7.10-0.2.14.100.jar
Translocator-1.7.10-1.1.2.15-universal.jar
twilightforest-1.7.10-2.3.7.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.1.jar
WailaNBT-1.7.10-1.4build121.jar
WAILAPlugins-MC1.7.10-0.1.2-19.jar
warpbook-1.7.10_2.0.36.jar
Wawla-1.3.1-1.7.10.jar
witchery-1.7.10-0.24.1.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
zz-backpacks 1.7.10 - 3.0.4.jar
OptiLeaves 1.4.zip

**Comment by Ellpeck** [comment]
Is that a Modpack or did you combine the mods yourself? Easier for testing! :D 
Try without Optifine. If it works then, I won't really be able to fix it. Optifine screws with basially everything in existance anyways sadly.

**Comment by Protheus** [comment]
My own Pack and will try it tonigjt and let you know

**Comment by Ellpeck** [comment]
It is OptiFine's fault, so I can't really do anything about it.
I might be able to do somehting about that in the future, but it's not really a priority. 
Just either don't use the Booklet or don't use Optifine. Sorry.

**Comment by Protheus** [comment]
Not too worry. It is readable. Tnx for the effort. Great mod
