### ISSUE TITLE
[1.20.4] Hopping Item Interface render issue

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/ActuallyAdditions#1401]
Mod: ActuallyAdditions-1.2.13+mc1.20.4

Block render breaks when against another block
![image](https://github.com/Ellpeck/ActuallyAdditions/assets/9543430/a7ef4db4-f7ae-49ca-b36f-1589863fa27b)

**Comment by Flanks255** [comment]
fixed in 1.2.14+mc1.20.4
