### ISSUE TITLE
[1.20.4] Lava Factory Controller is missing a tooltip

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/ActuallyAdditions#1402]
Mod: ActuallyAdditions-1.2.13+mc1.20.4

Lava Factory Controller is missing a tooltip
![image](https://github.com/Ellpeck/ActuallyAdditions/assets/9543430/4fae45ab-f30f-46ab-828e-09cad36d1197)

**Comment by Flanks255** [comment]
fixed in 1.2.14+mc1.20.4
