### ISSUE TITLE
[1.20.4] Coffee with Extra Milk is missing a tooltip

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/ActuallyAdditions#1403]
Mod: ActuallyAdditions-1.2.13+mc1.20.4

Coffee with Extra Milk is missing a tooltip

![image](https://github.com/Ellpeck/ActuallyAdditions/assets/9543430/77d3d685-68ff-49de-b22c-78663f009b5f)

**Comment by Flanks255** [comment]
fixed in 1.2.14+mc1.20.4
