### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by EgoTM1** [Ellpeck/ActuallyAdditions#1406]
![image_2024-06-14_000429443](https://github.com/Ellpeck/ActuallyAdditions/assets/163371893/05a0622d-962e-4050-b57b-4e59cc21946e)
[latest.log](https://github.com/user-attachments/files/15831388/latest.log)
Keeps crashing on startup

**Comment by EgoTM1** [comment]
Set pachouli as a required dependency

**Comment by Mrbysco** [comment]
Added patchouli as a dep on Curse/Modrinth
