### ISSUE TITLE
Daamge and Attack speed stats on the drill stack indefinitely [1.20.4 Neoforge]

### ISSUE THREAD

**Issue by Saereth** [Ellpeck/ActuallyAdditions#1407]
When equipping/mining with the drill the stats for Attack dmg and Attack Speed stack and remain permanently
They reset if you exit.

Steps to reproduce
Have a drill (check what attachments I'm using - if they matter)
Equip the drill / Mine or Attack with the drill
Check stats
Buff remains and stacks even if the drill is no longer equipped
Expected behaviour
Buffs should not stack and should not be permanent

originally reported to our tracker here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5333

**Comment by Flanks255** [comment]
fixed in 1.2.14+mc1.20.4
