### ISSUE TITLE
Storage Block Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [Ellpeck/ActuallyAdditions#1418]
1.21.1 Neoforge

Storage blocks are missing the `c:storage_blocks` item and block tag.

**Comment by Mrbysco** [comment]
A new version has been uploaded to CurseForge and Modrinth that add more storage tags (1.3.5+mc1.21.1)

**Comment by TheBedrockMaster** [comment]
@Mrbysco The storage blocks have the `c:storage_blocks/{material}` tags now but not the `c:storage_blocks` tags.
