### ISSUE TITLE
Laser fired from atomic reconstructor instantly crashes a dedicated server and make server unjoinable

### ISSUE THREAD

**Issue by Yukari7777** [Ellpeck/ActuallyAdditions#1419]
Was playing ATM10 in dedicated server environment. Placed atomic reconstructor on a powered cable. 
And server has crashed in about a half second - witnessed RF was charging up.

First crash was this: 
[crash-2024-10-19_15.50.31-server.txt](https://github.com/user-attachments/files/17444378/crash-2024-10-19_15.50.31-server.txt)

which indicates shooting that laser was the cause.

It'll keep crashing whenever player joins the server with following logs:
[crash-2024-10-19_15.56.11-server.txt](https://github.com/user-attachments/files/17444394/crash-2024-10-19_15.56.11-server.txt)

**Comment by Mrbysco** [comment]
A new version (1.3.5+mc1.21.1) has been uploaded to both CurseForge and Modrinth that should fix the issue
