### ISSUE TITLE
TiC tool repaired from broken, still broken after repair. 

### ISSUE THREAD

**Issue by demethan** [Ellpeck/ActuallyAdditions#142]
Hi,  

Thanks for your mod. I like it.  Now I'm not sure if its a TiC thing or your mod. I repaired a broken pick. the damage fill up full but the tool stayed broken. Now that the damage is full I can't repair it with an ingot.  I think we are latest on your mod and TiC. I appologize if this has been posted already. I didn't really look at the existing bugs.

Actually Additions: 1.10.2-r47
TiC: 1.10-2.3.3a

**Comment by Ellpeck** [comment]
This.
Is weird.

**Comment by Ellpeck** [comment]
Wait, you mean broken-broken, right? So it's at the broken state, and when you repair it it gets durability again like it should, but the broken state doesn't really go away, right?

**Comment by demethan** [comment]
> Wait, you mean broken-broken, right? So it's at the broken state, and when you repair it it gets durability again like it should, but the broken state doesn't really go away, right?

Yes.. that is it

**Comment by Ellpeck** [comment]
Okay.
I don't actually know if I can fix that.
For now, just try to only repair them if they're not completely broken °~°

**Comment by demethan** [comment]
ya.. figured that one out.. thx.. lol

I would think it is a flag in the entity data or something. I'm no Java programmer.

**Comment by Ellpeck** [comment]
Yea, it might actually just be a value set to the NBT that I can easily make go away.
I will try to solve this tomorrow :)

**Comment by demethan** [comment]
Many thanks
