### ISSUE TITLE
(1.21) AIOTs deal no damage/aren’t registered as tools

### ISSUE THREAD

**Issue by Inonedn** [Ellpeck/ActuallyAdditions#1420]

**Comment by Mrbysco** [comment]
Could you provide more info? What makes you think they're not registered as tools?

**Comment by Inonedn** [comment]
they have no item stats like no attack cooldown or damage and presumably missing tags. Preferrably, the actual stats should be that of a sword

**Comment by Mrbysco** [comment]
Fixed in `1.3.6+mc1.21.1`
