### ISSUE TITLE
[1.21.1] Breaker and Vertical Miner appear unable to break blocks.

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/ActuallyAdditions#1421]
The machines are placed outside of claimed areas (FTB Chunks claims). but do not break any block.

The Auto Placer, can place blocks in these same areas without issue. 

![image](https://github.com/user-attachments/assets/8a51c694-c82e-4f57-877a-72dc6d9dd551)

![image](https://github.com/user-attachments/assets/81016936-cd6d-4e34-b487-cb9ec9080020)

**Comment by Shadows-of-Fire** [comment]
Well, [this comment](https://github.com/Ellpeck/ActuallyAdditions/blob/1.21/src/main/java/de/ellpeck/actuallyadditions/mod/tile/TileEntityBreaker.java#L113) doesn't exactly inspire confidence about the breaker working correctly: `//TODO might double check this is right mikey`

**Comment by Mrbysco** [comment]
The issue lied in the `isCorrectToolForDrops` check... since the fake player of the Breaker doesn't have a tool it could only break stuff like dirt. 
The vertical digger didn't have a tool either, it was checking if the block it's breaking was able to break the block 🤔

**Comment by Mrbysco** [comment]
Fixed in `1.3.6+mc1.21.1`

**Comment by MuteTiefling** [comment]
This is working pretty well, I did notice it doesn't appear to want to mine dirt though.

Like, it dug or a huge area underground but left dirt Blobs wherever it found them

**Comment by MuteTiefling** [comment]
![2024-10-23_06 45 24](https://github.com/user-attachments/assets/ab6d619b-59b7-41de-acac-2de96b89d97a)

**Comment by JessAle07** [comment]
> Fixed in `1.3.6+mc1.21.1`

Yeah no, im currently on neoforge with this same version and its not working for me 

![Uploading Screenshot 2024-11-21 144603.png…]()

**Comment by Mrbysco** [comment]
Please don't reply to an old closed issue and make a new one with a reproduction case
