### ISSUE TITLE
[1.21.1] Coffee doesn't apply potion effects

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/ActuallyAdditions#1422]
Coffee doesn't apply potion effects
![image](https://github.com/user-attachments/assets/00128213-6514-46c8-9308-6e40eaef9e2f)

Brew Coffee with Magma Cream
Drink Coffee
No Fire resistance buff

Also, on a side note, I'm not sure it's meant to be doing this when using multiple ingredients:

![image](https://github.com/user-attachments/assets/565e4413-176b-4fb1-b64a-030de26bab17)

**Comment by MuteTiefling** [comment]
Small update, coffee works in Creative, not in Survival :D

And the machine doesn't appear to be consuming water either.

**Comment by Mrbysco** [comment]
Both issues have been fixed

**Comment by Mrbysco** [comment]
Fixed in `1.3.6+mc1.21.1`

**Comment by MuteTiefling** [comment]
Thanks!
