### ISSUE TITLE
Vertical Digger thinks that its mining blocks, but will not mine. 

### ISSUE THREAD

**Issue by Killermankey** [Ellpeck/ActuallyAdditions#1425]
![image](https://github.com/user-attachments/assets/153d929f-8446-438f-8424-a713d93a4afb)

Hello, 
The vertical digger when supplied with power will not dig a block but attempt to go through and dig said block, but will use no power and not dig the block.

Found on ATM 10 1.9, which has the most up to date version of AA of 1.3.6

**Comment by Mrbysco** [comment]
Are you a 100% sure? Have you checked underground?

**Comment by Killermankey** [comment]
Yes I did check underground and also check the flip of the coords incase. Somethings going wrong with mining thr block seeing how it consumes no power while in use

**Comment by Mrbysco** [comment]
Is it displaying a laser?

**Comment by SolidTears** [comment]
can confirm, happened to me as well

**Comment by Killermankey** [comment]
Ok.
I am pretty sure this is not a bug now, as it seems atm 10 modpack devs disabled, removed or broke anything that could be a quarry unless you use their special endtier quarry when you have no use for it.

So for the headache. Blame modpack devs for intentionally making their modpack worse

**Comment by Mrbysco** [comment]
Are you sure the chunk isn't claimed refusing the Vertical Digger from mining?

**Comment by SolidTears** [comment]
> Are you sure the chunk isn't claimed refusing the Vertical Digger from mining?

yeah chunk is unclaimed
