### ISSUE TITLE
With shaders, Atomic Reconstructor laser is invisible and relay lasers are barely visible

### ISSUE THREAD

**Issue by Nevrai** [Ellpeck/ActuallyAdditions#1433]
![Actually Additions shaders bug](https://github.com/user-attachments/assets/f58be46f-4f24-4a86-9fd1-3fe8a47db0ac)
![2024-11-03_10 17 01](https://github.com/user-attachments/assets/eb1a557d-a74a-4bfa-ac2f-6996ffa0b11c)

### Versions
* **Modpack**: [All the Mods 10](https://www.curseforge.com/minecraft/modpacks/all-the-mods-10) 1.15
* **Minecraft**: 1.21.1
* **NeoForge**: 21.1.73
* **Actually Additions**: 1.3.7
* [**Iris**](https://www.curseforge.com/minecraft/mc-mods/irisshaders): 1.8.0-beta.5
* **Shaders**: [Complementary Reimagined](https://www.curseforge.com/minecraft/shaders/complementary-reimagined) 5.2.2 + [EuphoriaPatches](https://www.curseforge.com/minecraft/mc-mods/euphoria-patches) 1.3.2

**Comment by Mrbysco** [comment]
🤷 Feels like an Iris issue, I've been unable to figure out how to get it to render when shaders are enabled
