### ISSUE TITLE
[1.21.1] Crash on worldgen when AA and Lithium are both active: "Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER"

### ISSUE THREAD

**Issue by Perseverance42** [Ellpeck/ActuallyAdditions#1434]
When both Actually Additions and Lithium are enabled on the server side the server crashes when generating villages.
Deactivating either one resolves the generation issue (using a fixed seed).

Logfile:
[crash.log](https://github.com/user-attachments/files/17610411/crash.log)

**Comment by Mrbysco** [comment]
Have you reported this to Lithium?

**Comment by Perseverance42** [comment]
No, should I? 

Further down the crash log there is a notice about the AtomicReconstructorClass specifically:
"-- class java.lang.RuntimeException when getting declared methods. --
Details:
	Analyzed class: de.ellpeck.actuallyadditions.mod.blocks.BlockAtomicReconstructor
	Analyzed method name: entityInside
	Analyzed method args: [Ljava.lang.Class;@286edb66"

so I thought It would be appropriate to report here.

**Comment by Mrbysco** [comment]
The issue is, the crash logs produced by Lithium are not useful at all

**Comment by Perseverance42** [comment]
Can confirm that the problem does not come up anymore.
Thanks for the fix.
