### ISSUE TITLE
The coal generator should use the normal list of furnace fuels

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/ActuallyAdditions#1435]
Assuming that you want to keep this to coal like fuels only, I'd recommend adding the following:

'#c:gems/lignite_coal', burn time: 8,
'#c:storage_blocks/charcoal', burn time: 80,
'#c:storage_blocks/lignite_coal', burn time: 80,
'#c:dusts/charcoal', burn time: 8,
'#c:dusts/coal', burn time: 8,
'#c:dusts/lignite_coal', burn time: 8,
'#c:tiny_dusts/coal', burn time: 0.8,
'#c:tiny_dusts/lignite_coal', burn time: 0.8,
'evilcraft:blood_waxed_coal', burn time: 16,
'justdirethings:coal_t1', burn time: 24,
'justdirethings:coal_t2', burn time: 72,
'justdirethings:coal_t3', burn time: 216,
'justdirethings:coal_t4', burn time: 648,
'justdirethings:coalblock_t1', burn time: 240,
'justdirethings:coalblock_t2', burn time: 720,
'justdirethings:coalblock_t3', burn time: 2160,
'justdirethings:coalblock_t4', burn time: 6480,

If you're able to read the number of items a piece of fuel can smelt, it'd also be quite possible to translate any fuel item into the generator.

Burn Time = Items Smelted  * 200
Total Energy = Items Smelted * 4000

**Comment by Ellpeck** [comment]
The coal generator should use the normal list of furnace fuels, there's no reason to have a custom registry for it imo
