### ISSUE TITLE
Machines being able to be picked up inside village houses

### ISSUE THREAD

**Issue by tigier** [Ellpeck/ActuallyAdditions#1436]
When breaking any AA machine inside the village house on a server using an osmium Paxel, the chat message indicating the block "shattered" is displayed twice and the machine is still being dropped.

the dropped machine is identical to a regular machine in any way.
![Bild_2024-11-04_234325687](https://github.com/user-attachments/assets/b33477dc-ebcf-42b6-ae3e-7b724020cf13)

Modpack Used: Enigmatica 10(1.12.0)

**Comment by Flanks255** [comment]
Fixed in 1.3.9
