### ISSUE TITLE
(1.21) Rework/Removal of Lava Factory

### ISSUE THREAD

**Issue by Inonedn** [Ellpeck/ActuallyAdditions#1439]
In 1.17, Pointed Dripstone was added, which allows you to renewably create lava using a pointed dripstone beneath lava over a cauldron, thus rendering the Lava Factory entirely obsolete. It should potentially be reworked or removed entirely
![2024-11-07_23 44 44](https://github.com/user-attachments/assets/874ac99a-fd7e-48d6-9dba-be5bf097209b)

**Comment by Mrbysco** [comment]
What is obsolete about it? Just because vanilla has a way doesn't mean mods can't have their own ways.
