### ISSUE TITLE
1.21.1 NeoForge - Drills breaks when its energy runs out if used with Ore Excavation or FTB Ultimine.

### ISSUE THREAD

**Issue by Zulussuu** [Ellpeck/ActuallyAdditions#1443]
Drills breaks when its energy runs out if used with Ore Excavation or FTB Ultimine. 
Just like a vanilla tool, it disappears when it runs out of energy.

**Comment by Zulussuu** [comment]
actuallyadditions-1.3.8+mc1.21.1

**Comment by Flanks255** [comment]
Thats been fixed already in 1.3.9

Duplicate with #1432

**Comment by Ellpeck** [comment]
This still happens on Enigmatica 10 with 1.3.9, so maybe there's a mod interaction issue happening or something. I can reproduce it consistently in survival with a drill that is barely charged through the energizer.

**Comment by Mrbysco** [comment]
Feels like some mod is trying to hurt the item which is funky

**Comment by Flanks255** [comment]
If you break blocks with ultimine and a non tool item like a stick, does it break the stick? maybe its punishment lol

**Comment by Flanks255** [comment]
I added explicit unbreakable to the drill in 1.3.11, if it still breaks at that point, id blame the other mods lol.
