### ISSUE TITLE
[Suggestion]: Allow in game adjustable area for the Farmer

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/ActuallyAdditions#1444]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I'd like it if I could whack the farmer with a compass to set its area. I don't always want a 9x9 farm for something. Perhaps a 3x3 would be enough. But since the size is fixed it means I absolutely cannot put two such farms in proximity to one another or they'll interfere with each other. 

If I could toggle it down to 3x3, then I could have a bunch of different crops all farmed in the same area by different farmers.

Alternatively, changing the farmer to gently harvest, or otherwise re-plant the same plant in a spot it just harvested as long as it has the seeds would serve a similar purpose.

**Comment by Flanks255** [comment]
b66af8446ccbe5ba5f9c75f8ebd0dc256a96774a
