### ISSUE TITLE
[Bug]: Exception loading blockstate definition

### ISSUE THREAD

**Issue by bookerthegeek** [Ellpeck/ActuallyAdditions#1445]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge/Neoforge version

21.1.75

### Minecraft version

1.21.1

### Mod version

1.3.9

### Java version

47.3.6

### Heyo!

Saw this in the log. thought you might want to know.

### Additional Information

```shell
[09:41:54] [Worker-ResourceReload-17/WARN] [minecraft/BlockStateModelLoader]: Exception loading blockstate definition: 'actuallyadditions:blockstates/crate_small.json' missing model for variant: 'actuallyadditions:crate_small#'
```

**Comment by Mrbysco** [comment]
We're aware. The crate hasn't been re-implemented yet
