### ISSUE TITLE
[Bug]: Unable to load model

### ISSUE THREAD

**Issue by bookerthegeek** [Ellpeck/ActuallyAdditions#1446]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge/Neoforge version

21.1.75

### Minecraft version

1.21.1

### Mod version

1.3.9

### Java version

1.20.1-47.3.6

### Issue Description

Saw this in the log. Thought you might want to know.

### Additional Information

```shell
[09:41:55] [Worker-ResourceReload-17/WARN] [minecraft/ModelBakery]: Unable to load model: 'actuallyadditions:block/crate_small' referenced from: actuallyadditions:item/crate_small: java.io.FileNotFoundException: actuallyadditions:models/block/crate_small.json

```

**Comment by Mrbysco** [comment]
Is basically related to the same issue as https://github.com/Ellpeck/ActuallyAdditions/issues/1445
