### ISSUE TITLE
Sort items with itemtweaks in crates

### ISSUE THREAD

**Issue by Xplendit** [Ellpeck/ActuallyAdditions#145]
When you sort items with itemtweaks in the small crate, you go to the last page(even if that doesn't excist in the small crate) And when u try to put an item in it, minecraft crashes

**Comment by Ellpeck** [comment]
Why would this even?

**Comment by Xplendit** [comment]
[crash-2016-07-08_13.52.38-client.txt](https://github.com/Ellpeck/ActuallyAdditions/files/354130/crash-2016-07-08_13.52.38-client.txt)
Maybe this can help.

**Comment by Ellpeck** [comment]
This is a hideous freaking bug and I'm stupid. lol
