### ISSUE TITLE
[Bug]: [1.21.1 neoforge] Vertical digger is not working at all. My  mod version is the latest. 

### ISSUE THREAD

**Issue by JessAle07** [Ellpeck/ActuallyAdditions#1451]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge/Neoforge version

21.1.73

### Minecraft version

1.21.1

### Mod version

1.3.6+mc1.21.1

### Java version

Java 21

### Issue Description

I tried using one of those vertical diggers on my server, and didnt work. Then i tried doing the same in a fresh new world in single player and is not working either. Im using a modpack called "Craftoria". 
![Screenshot 2024-11-21 144603](https://github.com/user-attachments/assets/60c5a26c-a0de-4dfc-9730-cae0e6adc36f)
![image](https://github.com/user-attachments/assets/2b6c78d3-1ba5-4273-b340-04539fe5b8f1)

**Comment by Flanks255** [comment]
perhaps something in the modpack is preventing it from working, because it definitely works.
![image](https://github.com/user-attachments/assets/c940d0d7-3997-4275-bd5e-0530717aa799)

**Comment by JessAle07** [comment]
Are there any known incompatibilities? Anyways, I don’t really need it anymore so I might just close this thread

**Comment by Flanks255** [comment]
only if something is blocking fakeplayers, like chunk protection mods etc.
