### ISSUE TITLE
[Bug]: Wild plants popping off

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#1458]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge/Neoforge version

21.1.74

### Minecraft version

1.21.1

### Mod version

1.3.10

### Java version

21.0.3

### Issue Description

Wild plants pop off when you touch anything next to them since they're just regular plants planted on the wrong soil; they should have a wild version like in old AA

**Comment by Flanks255** [comment]
Fixed in 38d6404b62d080dcd23ea4d202f8cd55f80fad00
