### ISSUE TITLE
[Bug]: Crops drop the wrong amount of items

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#1467]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge/Neoforge version

21.1.74

### Minecraft version

1.12.1

### Mod version

1.3.9

### Java version

21.0.3

### Issue Description

Canola, flax, and potentially the other crops, consistently drop 1 item (it seems, despite what i saw in the block drop loot table, hmm). In the old versions, this was [2 items at minimum, plus 2 or 3 depending on the plant](https://github.com/Ellpeck/ActuallyAdditions/blob/1.12.2/src/main/java/de/ellpeck/actuallyadditions/mod/blocks/InitBlocks.java#L180-L183). This means that making a canola oil farm is super difficult now :(

**Comment by Flanks255** [comment]
min + rand(0 to add)

**Comment by Flanks255** [comment]
Fixed in 506d481d3637b626fddc99a7a9eec3cd13178789
