### ISSUE TITLE
[Bug]: Breaking CC:Tweaked computers with drill destroys them

### ISSUE THREAD

**Issue by Moj-FPS** [Ellpeck/ActuallyAdditions#1469]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge/Neoforge version

NeoForge 21.1.81

### Minecraft version

1.21.1

### Mod version

1.3.10

### Java version

OpenJDK 21.0.4 (Red Hat)

### Issue Description

Breaking the Computer and Advanced Computer from CC: Tweaked destroys them. I have tried reproducing this with other blocks from CC: Tweaked (peripherals, etc.) and it appears the issue only affects the computers. Expected result of breaking the computer blocks is to be dropped and able to be recovered.

### Additional Information

Modpack is All The Mods 10 (with a few additional mods added). 

https://github.com/user-attachments/assets/3aaeea78-2d63-475e-ae71-b64a8713f527

**Comment by Flanks255** [comment]
This is fixed in dev already, and will be in the next release, CCTweaked is dropping their items in "playerwilldestroy", which they really shouldn't be, but regardless, its fixed next release lol.

**Comment by Moj-FPS** [comment]
Thanks for the info! Much appreciated

**Comment by Flanks255** [comment]
should be fixed in 1.3.11
