### ISSUE TITLE
problem with inventory tweaks

### ISSUE THREAD

**Issue by radiocrack** [Ellpeck/ActuallyAdditions#148]
1.10.2-R49
inventory tweaks 1.61-beta-57

i had a small crate.  click inventory tweaks sort and the small crate seems to "scroll" to a 3rd additional "page" and my items disappear.  an arrow appears letting me get back to the first "page"

i tried putting items into the new "page" and the following client crash
http://pastebin.com/vLDZ7gSC

possibly the small crate is reporting more  slots than it really has.  index out of bounds 234 / 13 columns = 18 rows.  small crate only has 9 rows.  appears inventory tweaks scrolled to a non existent 18th row when sort was clicked.

first time using this mod, just getting started and i am extremely impressed.  I love the no-nonsense progression without the grind and variety of capabilities.  keep it up!

**Comment by Ellpeck** [comment]
Update to the newest version.

**Comment by Ellpeck** [comment]
Oh, and thanks for that last part :)
