### ISSUE TITLE
Relay particle effect returns once client has been closed and reopened

### ISSUE THREAD

**Issue by utoc** [Ellpeck/ActuallyAdditions#149]
Hello!

In a server<->client environment I have shiftclicked with the AA laser wrench to "show particles when holding the AA wrench" but the particles return after completely exiting the client and reopening.  When shiftclicking the newly opened client, the setting itself is on "show particles when holding the wrench" but I have to cycle through the options to once again turn the particle effect off.

This does not appear to happen when you disconnect the client; you must do a full restart.

I am using:

    MC 1.10.2
    FML 1.10.2-12.18.0.2008
    AA 1.10.2-r50

Have a nice day :)

**Comment by Ellpeck** [comment]
So the setting stays, but the setting that's being applied always resets?
Odd.

**Comment by utoc** [comment]
Correct; it stays on "wrench in hand only" but there is a particle effect that appears.

**Comment by Ellpeck** [comment]
Yea, I found the bug.
And I had fixed it for 1.9 already, but apparently something broke again. Just great.
