### ISSUE TITLE
Annoying tooltips

### ISSUE THREAD

**Issue by Sirithil** [Ellpeck/ActuallyAdditions#15]
AA tooltips (the ones telling you to make or use a manual) appear on vanilla items. Also the red tooltip telling you to make a manual appears if the manual you already have is not in your inventory, even if you have one stored somewhere.

Please fix this and/or add a config item for these tooltip prompts.

**Comment by Ellpeck** [comment]
Already been fixed with https://github.com/Ellpeck/ActuallyAdditions/commit/e7a42b9dfe1212f6b1d9415c7dae0e41ad580b23

**Comment by Sirithil** [comment]
Thank you!
