### ISSUE TITLE
Server connection crash

### ISSUE THREAD

**Issue by JohnKrell007** [Ellpeck/ActuallyAdditions#150]
https://gist.github.com/JohnKrell007/988b1d9ce92a950120d50116545260ca
It seems to be a in-compatibility with JEI.

**Comment by JohnKrell007** [comment]
They said that they can't do anything, and it has to be fixed on this end.

**Comment by Ellpeck** [comment]
@mezz this doesn't make any sense to me.
Why would the registered name return null? I set the registry name of every item and register them, otherwise the items wouldn't even work o_o

**Comment by mezz** [comment]
I have no idea. All I can say is... at that point in the code for this player it's not registered.
I don't see anything wrong with your code either. Maybe a coremod conflicts in some way to break it?

**Comment by Ellpeck** [comment]
@JohnKrell007, does it happen to you all the time? Try to remove some of the mods and see if it fixes it.

**Comment by JohnKrell007** [comment]
It's fixed if I remove JEI, I even tried disabling my JEI addons and that didn't help.

**Comment by Ellpeck** [comment]
Yea, this doesn't make any sense. @mezz, any updates?

**Comment by Ellpeck** [comment]
Try with ONLY Actually Additions and JEI installed.
If that works, try slowly installing the other mods one at a time.

**Comment by JohnKrell007** [comment]
Soooo, I just updated all my mods and the problem dissapeared, guess some other modder fixed it or something? Dunno but problem solved.
