### ISSUE TITLE
[Suggestion] : Experience De-solidifier

### ISSUE THREAD

**Issue by LordHellscream** [Ellpeck/ActuallyAdditions#152]
request: experience de-solidifier can also reverse the effect to give you xp quickly (multiple stack at a time).

I love the solidified experience, but I am getting a hell lot of those and really hitting a storage problem, I would like a reverse machine to convert them back to xp so I can store them more easily on ender IO experience obelisk or liquid xp tank etc.

 

Right now my only option is use the solidified xp one at a time, when you are trying to do with several thousands of those.....

 

Thanks!!!

**Comment by Ellpeck** [comment]
Just... you know.. shift-right-click them to eat a whole stack like it says in the book.

**Comment by macks2008** [comment]
wait, that's the thing? That should really be in the tooltip...

**Comment by Ellpeck** [comment]
http://ellpeck.de/actaddmanual/#xpSolidifier
Reading skills are required.
