### ISSUE TITLE
State in booklet that Drill Upgrades need previous tiers

### ISSUE THREAD

**Issue by LocoMinerDad** [Ellpeck/ActuallyAdditions#155]
I am playing version 1.10.2-r50, I have upgrade the speed to 3 and mining to 2. Neither seem to be doing anything. I dont see a command anywhere other than to right click to get the the upgrade slots. Is this a bug or I just dont know the commands?

**Comment by Ellpeck** [comment]
You need the previous tiers.

**Comment by Ellpeck** [comment]
Actually, I should probably note that in the booklet.
