### ISSUE TITLE
ActuallyAdditions-1.10.2-r50

### ISSUE THREAD

**Issue by IchigoGames** [Ellpeck/ActuallyAdditions#158]
so im not sure  you can fix this but theres a bug where if some one takes crushed emerald from your mod and puts it into a furnace from tsoncraft it smelts it then if they put anything into the furnace like cobblestone it then turns it into emeralds and when you got projectE in your pack like i did thats not very good at all.

**Comment by Ellpeck** [comment]
Contact the Tsoncraft author.
