### ISSUE TITLE
Drill block break crash

### ISSUE THREAD

**Issue by AlphaChimaera89** [Ellpeck/ActuallyAdditions#160]
The Drill crashes you out to desktop when breaking a Soul Shards: The Old Ways soul cage block. I reported this issue to that mod author as well.

Pastebin link to crash log: [http://pastebin.com/z5QdsZmc](url)

**Comment by Ellpeck** [comment]
This appears to be a bug on Soul Shards' side.
If it turns out to be my fault for some weird reason, reopen this issue please.

**Comment by TehNut** [comment]
This crash is happening [here](https://github.com/Ellpeck/ActuallyAdditions/blob/1.9.4/src/main/java/de/ellpeck/actuallyadditions/mod/util/WorldUtil.java#L399). My state is [determined by Tile Entity data](https://github.com/TehNut/Soul-Shards-The-Old-Ways/blob/1.10/src/main/java/com/whammich/sstow/block/BlockCage.java#L59). If you're removing the tile before calling that line, then that would cause the crash.

**Comment by AlphaChimaera89** [comment]
He's found a problem in his code and is currently working on it. Thanks for
the help, I sent him the line you linked to me.

**Comment by TehNut** [comment]
@AlphaChimaera89 was confused. I am pointing out the problem code to you. Not the other way around.
