### ISSUE TITLE
Energy Laser Relay can't extract power from top side on PowerCell/CapBank

### ISSUE THREAD

**Issue by ftog-thorgal** [Ellpeck/ActuallyAdditions#164]
ActuallyAdditions-1.10.2-r51

I've tried this and can replicate it. When trying to extract power via a Energy Laser Relay from an RFTools PowerCell or EnderIO Capacitor Bank on the top face it doesn't work. When I place the Energy Laser Relay on the sides of the PowerCell or Capacitor Bank it works.

**Comment by Ellpeck** [comment]
Does this happen for conduits as well?

**Comment by Ellpeck** [comment]
Try with the latest version please

**Comment by ftog-thorgal** [comment]
Updating the pack and server today, will report back if it is still happening.

**Comment by ftog-thorgal** [comment]
Updated to r54 and the problem persists.
Here are 2 screenshots just to clarify. Both screenshots show the capacitor banks without the relays to show you the pull/push settings used.

This doesn't work:
https://imgur.com/1nxsFQK.png

This works:
https://imgur.com/UxSytHC.png

**Comment by Ellpeck** [comment]
That doesn't make any sense.
Does it happen with conduits as well?

**Comment by ftog-thorgal** [comment]
Yes, it also doesn't work with conduits. It seems that the down side of the relay doesn't accept power but can output.

**Comment by Ellpeck** [comment]
Does it happen with things from other mods? Because I don't get that :v
