### ISSUE TITLE
[Suggestion] Worms that can fertilize soil forever

### ISSUE THREAD

**Issue by BootyToast** [Ellpeck/ActuallyAdditions#165]
I have muli-layered farms with 1 block thick floors. Obviously it is impossible to place water and fertilize the soil without making the farms look ugly. Instead of implementing sprinklers like so many other mods have, worms that can be harvested from grass with a hoe and applied to soil to fertilize it would be a great addition to Actually Additions.
I'd like to thank my mother and God for giving me this great idea.

Sincerely, 
Booty Toast

**Comment by Ellpeck** [comment]
God is pretty awesome for thinking of that.
