### ISSUE TITLE
Suggestion: Harder Recipes (Mode)

### ISSUE THREAD

**Issue by DRTR0** [Ellpeck/ActuallyAdditions#166]
I love this mod, but when I throw it in my pack with mods like Ender IO, RFTools, etc. it can become quite OP, and cheaty 

For example, the fluid collector is basically a pump that doesn't require RF, and it only costs a bit of iron, cobble, etc. I've changed mine to include a block of redstone, 2 diamond pickaxes, a bucket of lava and water, and 4 obsidian. 

The coal generator produces almost twice as much RF as coal generators in other mods, while being much cheaper to craft. 

I've obviously fixed many of these things myself with MineTweaker, and it's not a huge issue, but have you ever considered making a "Hard Mode" in the config. It would beef up the crafting recipes. 

You could also add more items that could be used in crafting in general, such as things that only have a small chance to drop from killing mobs.

It's not a huge issue and I know you can just say "well don't play with ___". But it should be nothing that should be spent a lot of time on. A lot of recipes only require cobblestone. Maybe swap those out with iron, lapis, gold blocks, etc., require more iron casings in recipes, etc.

**Comment by Ellpeck** [comment]
1. The fluid collector only collects one block. It's _not_ a pump, and not even close.
2. The coal generator produces 40 RF/t, which is the amount almost every other coal-based generator uses, ie. RailCraft, Thermal Expansion, Progressive Automation, and it's even less than RFTools.
3. I wouldn't consider what you do "fixing", but rather "stealing the fun". I don't want recipes to be insanely hard, I want the game to be fun, and not repetetive or grindy. Sorry.

If you want harder recipes, just implement them with MineTweaker yourself, I am not interested in such a thing, sorry.

**Comment by Ellpeck** [comment]
Edit: 30 RF/t in fact, I remembered wrongly, so even less than most generators in other mods.
