### ISSUE TITLE
suggestion for adding more flowers to Minecraft

### ISSUE THREAD

**Issue by Hypsellis** [Ellpeck/ActuallyAdditions#167]
Hello, I just wanted to make a suggestion about the adding of 4 flowers. The first is the small paeonia wich is present in the minecraft jar but wich has never been included in the game. The 3 others are yellow, magenta and purple tulip. I made these tulips textures with the help of the 4 existent ones in Minecraft. I just find that these flowers miss to minecraft, and it would be awesome if you add them in the game. ;)
![flower_tulip_magenta](https://cloud.githubusercontent.com/assets/17103411/17069025/a056b968-5054-11e6-88e2-6ce3177e37d3.png)
![flower_tulip_purple](https://cloud.githubusercontent.com/assets/17103411/17069027/a05a0172-5054-11e6-9111-d180d754eaf3.png)
![flower_tulip_yellow](https://cloud.githubusercontent.com/assets/17103411/17069024/a0553214-5054-11e6-8b67-231b987d12ae.png)
![flower_paeonia](https://cloud.githubusercontent.com/assets/17103411/17069026/a05910c8-5054-11e6-989d-3588664100de.png)

**Comment by Ellpeck** [comment]
No sorry, this isn't a thing I want to do, it just doesn't seem like it fits the style very much :(
