### ISSUE TITLE
[1.10.2] Disconnect From Server (Large Storage Crate)

### ISSUE THREAD

**Issue by Stuart74** [Ellpeck/ActuallyAdditions#169]
Have recieved a report of a bug with actual additions Large Storage Crate  Refer to the issue raised on my curse issue page

Issue Raised -[Here](http://minecraft.curseforge.com/projects/empyrean/issues/3)

Actual Additions Version: -1.10.2-r54
Forge Version: 12.18.1.2014
Server Error Logged : [gist](https://gist.github.com/Stuart74/62119b025b01ac697da8146c6439cae6)

**Comment by Ellpeck** [comment]
"Large Storage Drawers". At least _pretend_ to know what you're talking about next time please. >_>

**Comment by Stuart74** [comment]
Is there any reason to be rude poor form for a mod dev
