### ISSUE TITLE
Actually Additions Villager House Loot Chest is Empty

### ISSUE THREAD

**Issue by WenXin20** [Ellpeck/ActuallyAdditions#170]
I also haven't seen the Actually Additions villager.

**Comment by Ellpeck** [comment]
I know.
I don't wanna have to deal with loot tables and the new villager system because both are hideous.
But now you reminded me :v 
I've had it on my to-do list though, so I'm going to close this. But it will get done.. eventually! :3

**Comment by WenXin20** [comment]
Ok, thanks
