### ISSUE TITLE
Compatibility: InvTweaks

### ISSUE THREAD

**Issue by geratheon** [Ellpeck/ActuallyAdditions#174]
The storage crates have a bug that you can only sort them once, then you have to reopen the gui.

InvTweaks prints the following to the chat:

```
InvTweaks: [ERROR] [3] Failed to sort container: null (l101 in HandlerSorting.java)
```

Because this won't happen with other mods item storage tileentities, I report it to your mod prior to InvTweaks (for now).

**Comment by Ellpeck** [comment]
Yea, I know. And I don't know why this is either because the InvTweaks documentation and code are kind of quirky and, at least for me, somewhat annoying to use.
For now, just use the Z-button-sorting, because it's the only one that doesn't look terrible anyways :p

**Comment by geratheon** [comment]
Well, now you have it documented so you do not forget about it. :p

**Comment by Ellpeck** [comment]
So I passed the issue on to the InvTweaks repo, as I have no idea how to fix this.
https://github.com/Inventory-Tweaks/inventory-tweaks/issues/373
