### ISSUE TITLE
1.10.2  updated from AAr55 to AAr56 / Small visual bug when looking into crates

### ISSUE THREAD

**Issue by Gayanfalor** [Ellpeck/ActuallyAdditions#177]
Hello,
I just seen that yesterday, when i'm looking into the gui of one crate ( in my case its a small storage crate)
if i'm waiting a bit, sometime it makes like the crate is empty with nothing in it.

but in fact the stuff is still in the crates but not visible.

I had this bug in the r55, i updated to see if it was fixed but it still here.

I can make a small vid showing whats happening if you want.

tell me what can i do to help you spotting the problem.

**Comment by Ellpeck** [comment]
You probably have a couple of other mods installed, right?

On a server, we pinned down that the issue was chunk update-based, however we noticed that it was happening to some other blocks and GUIs from other mods as well, thus, I ignored the issue because it didn't appear to be coming from ActAdd.
Please give me the modlist of the pack you got the issue with :)

**Comment by Gayanfalor** [comment]
Hey hello,

Yes i have many others mods intalled

Here is a pic taken from the server mods folder:

https://drive.google.com/open?id=0B9iNaLFrsdUpbExVSzQtcXJ3dTA

**Comment by Ellpeck** [comment]
Do you have EnderIO and/or RefinedStorage stuff in the same chunk (check with F3+G) as the storage crates in question? If so, try placing one in a chunk without either mod's blocks being present and look if it's still happening :)

**Comment by Gayanfalor** [comment]
Hmm, my crates are not in the same chunk as refinedStorage mod, but they are in the chunk next to it(diagonally), and i have moved the enderio tanks wich wera in the same chunk but i still get the problem.

But i moved into the dungeon far away from home (there is some crates here too, 1 small and  1medium) and it seems not bugging.

The one upstairs in the house in another chunk seems not bugging too, but this one is in the same chunk as enderio and refinedStorage stuff, its just higher than them

**Comment by Ellpeck** [comment]
Hmm, then maybe it's not actually that.
What else is different from the chunks it isn't bugging in?

**Comment by Gayanfalor** [comment]
Hmm, i have the tcon smeltery near the 3 crates wich are bugging

**Comment by Ellpeck** [comment]
Maybe that's the problem. Try disabling the smeltery and see if that fixes it.

**Comment by Gayanfalor** [comment]
By disabling you mean destoying it and put it away ?

**Comment by Gayanfalor** [comment]
Yep, when i remove the smeltery controler i can look into the "bugging" crates and its not doing the bug.

But when i put it back it wait a bit and go back to look into crates its doing the "bug".

By the way i cant say if its coming explicitely from only this mod or it can bug with others

**Comment by Ellpeck** [comment]
Yea, I don't really know what's going on there.
It'd be really lovely if you could pass the bug report on to the TiCon repository and just link this issue as well, as I have no real idea what's going on there :o

**Comment by Gayanfalor** [comment]
Ehh how i can do that ? i'm not really used to github features, fork , repository etc, i know its well used to report issues etc.

Sorry about that ^^

**Comment by Ellpeck** [comment]
So could you definitely pin this down to be caused by TinkerI/O? If so, please report it to their issue tracker :)

**Comment by Gayanfalor** [comment]
I cant ber sure if its from it but i think there is a big probability for that while the smeltery controler is not doing bug.

I've seen their github there not that much activity since the last opened issues is from 8 dec 2015, but i'll try to ask them.
