### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by SDUBZ** [Ellpeck/ActuallyAdditions#179]
1.it would be nice if the double furnace and double crusher got a bit of a speed because it requires more resources

2. could you add a block that separates adult animals from baby animals?

3. it would be nice if you had a milker to milk animals that we breed that can dump into a tank or other liquid storage items

**Comment by Ellpeck** [comment]
The Crusher and Furnace are pretty fast, do you really think they need to be faster? :v

**Comment by SDUBZ** [comment]
just a tiny bit more of a fasten with the doubled versions single versions seems just but doubles seem to run the same as single it seems to me

**Comment by Ellpeck** [comment]
They don't.

**Comment by Ellpeck** [comment]
I don't really want this mod turning into some sort of second MineFactory Reloaded, sorry. All of these ideas are great, but I think they just don't really fit the mod. Sorry. :(
