### ISSUE TITLE
Suggestions. 

### ISSUE THREAD

**Issue by Gebcrafter** [Ellpeck/ActuallyAdditions#180]
- Allowing the already-existing item filter to determine what the breaker & placer can break & place... I'm having a tough time automating my pure daisy.

**Comment by Ellpeck** [comment]
To be honest, I don't really see this making a lot of sense.
You could always just make an Etho Hopper Clock that runs at a interval good enough for the Pure Daisy to function.

Sorry. :(

**Comment by Gebcrafter** [comment]
thats fine, i managed to do it and im pretty proud of myself. :P
