### ISSUE TITLE
Suggestion: Ability to pick up worms (plus some other ideas for worms).

### ISSUE THREAD

**Issue by DRTR0** [Ellpeck/ActuallyAdditions#181]
I accidentally placed my worm in the wrong block and now my farm isn't square. I then come to realize you can't pick worms up. :/

Some other ideas would be: 

Higher tier hoes have a higher chance of finding a worm. As of right now it seems random. I just hoed my current 30x30 farm with a stone hoe and picked up 19 worms. When I discovered then what worms are, I just went in a field with a diamond hoe for like 10 minutes spamming right click everywhere and only got 6.

Worms don't live forever. They should die after a certain period or at just random.

**Comment by Ellpeck** [comment]
Just break the block the worm is on, and the worm will go away. They shouldn't be able to be picked up after placing :)

Yes, it is random and it's actually supposed to be that way.

I know worms don't live forever in real life, but I want them to live forever in-game. It'd just be annoying to have them die after some time and have to replace them.

Sorry, these are great ideas, but I'm happy with the worms the way they are. Thanks for sharing them anyways :)
