### ISSUE TITLE
Suggestion: Bags with item filters.

### ISSUE THREAD

**Issue by DRTR0** [Ellpeck/ActuallyAdditions#183]
A bag that can have an item filter placed in an upgrade slot that shows 9 slots to place items in for whitelisting. It automatically places whitelisted items in the bag when picked up.  Bags can be tiered with different inventory sizes or just the same as a single chest. Optionally a void bag, which does what the /dev/ null did in 1.7.10.

**Comment by DRTR0** [comment]
And please make a pump. There are no good pumps on 1.10. I don't feel like installing IC2 or Mekanism just for a pump. It's getting annoying having to cheat and use an infinite fluid mod for lava and your fluid collector.

**Comment by Ellpeck** [comment]
Use a Lava Factory from Actually Additions.
I'm not turning this mod into some sort of reincarnation of MineFactory Reloaded, sorry.
No Pumps.

**Comment by DRTR0** [comment]
Deja vu feeling like you've told me this already, yet I keep forgetting about the lava factory.

**Comment by DRTR0** [comment]
So what are your thoughts on the bag idea? I actually though of learning Forge to make it myself, because it sounds like an easy enough project.

This is sort of what I had in mind. Is there a better way of going about?

http://pastebin.com/wXEBL6sr

**Comment by Ellpeck** [comment]
I already finished them, look at the last commit! :D
I'll close this once I did the finishing touches and tweaks :)

**Comment by DRTR0** [comment]
Sweet. Can I download your mod when you add new commits, without waiting for you to update Curse Forge?

**Comment by XDjackieXD** [comment]
you can by going to https://ci.chaosfield.at or by clicking on the green tick next to the commit but keep in mind that these builds are directly from the commits and can (and probably will) be unstable sometimes.
