### ISSUE TITLE
Crash while hitting CTRL while looking into an EZ Storage 2 interface

### ISSUE THREAD

**Issue by DatrixTHLK** [Ellpeck/ActuallyAdditions#184]
I was looking up advanced information for an item I had  (basically any item from the Mo' Drops mod) in the EZ Storage 2 Storage Core and I CTD.

Crash Report: http://pastebin.com/PNb5jiCS
Forge 12.18.1.2043
Minecraft v. 1.10.2
mod version r-56

**Comment by Ellpeck** [comment]
Does this happen with every item?

**Comment by Ellpeck** [comment]
I don't get why this would be a problem with Actually Additions. From the crash log, it seems that the sorting or filtering mechanism of EzStorage somehow crashed the emeraldobsidianmod's Emerald Armor.
If this only happened once and you can still look up advanced information for items, then please report this to the emeraldobsidianmod and/or EzStorage.

**Comment by Ellpeck** [comment]
So did you manage to gather any information?

**Comment by Ellpeck** [comment]
I am closing this as apparently nothing is happening with this anymore.

It might be fixed now as I rewrote the CRTL code a bit.

**Comment by DatrixTHLK** [comment]
It has been fixed.
