### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SoccerScout1** [Ellpeck/ActuallyAdditions#188]
Whenever I open the AA manual, my game crashes.
It only does this with my account. Any other account that opens it, even on my computer, still works.
I have submitted the crash report by clicking the Submit Crash Report button. Is there anything else I need to do.

Sorry about last time, went on vacation and didn't have access to a computer.

**Comment by Ellpeck** [comment]
Yes.
Submit the crash report to *me*, not Mojang.

**Comment by SoccerScout1** [comment]
I did. It said that it was sending the crash report to the mod author and that I couldn't send a crash report to Mojang because it was modded.

**Comment by Ellpeck** [comment]
Just post the crash report to pastebin or gist or something. How would whatever said that even *know* where to send the crash report to? Why would the game automatically know which mod caused which bugs and which authors belong to which mods?

**Comment by Ellpeck** [comment]
Again, if you don't respond, I will just close this issue.
