### ISSUE TITLE
Feature request!

### ISSUE THREAD

**Issue by KristjanKr** [Ellpeck/ActuallyAdditions#19]
Okay so this is a really good and useful mod, but farming these is a pain in the neck, because i can't right click/auto-harvest/replant with these crops. Idk what mod does this, but it works for wheat/potatoes/carrots (so I can just right click MATURE crop and it automatically harvestes and replants it), it would be awesome if the ActuallyAdditions crops did the same thing.

**Comment by Ellpeck** [comment]
I will keep it in mind.
Either I'll add the feature myself or just add support for the mod that does that which I'll have to find out what mod it actually is though.
Thanks for the request though! :D

**Comment by Voidi** [comment]
Maybe Forestry or Hunger Overhaul.
