### ISSUE TITLE
Atomic Reconstructor  Red Mushroom -> Nether Wart  Not Working

### ISSUE THREAD

**Issue by Jacobeta** [Ellpeck/ActuallyAdditions#191]
I'm using the latest version of Actually Additions, r57. My reconstructor is powered and it has worked before, but when I attempt to reconstruct red mushrooms, nothing happens. I tried to place it down as block and item, and it has 140000 RF.

**Comment by Ellpeck** [comment]
When you throw down the item, is it near the place it actually hits a solid surface?

**Comment by Jacobeta** [comment]
I have a 1x1 small hole in the middle of a wall, where I throw my items for the reconstructor to blast. it was at the middle of the floor of the hole, but I threw other items similarly and succesfully.

**Comment by Ellpeck** [comment]
That's.. weird. Can you do a screenshot of you pressing CTRL and Shift at the same time on the mushroom you were trying to convert?

**Comment by Jacobeta** [comment]
Oh my gosh, I'm so sorry for wasting your time. I threw the mushrooms further back and it worked fine. Please forgive me!

**Comment by Ellpeck** [comment]
You didn't waste my time, there's nothing to forgive you :p
It's just a mistake, people do them.
