### ISSUE TITLE
Suggestion/Functionality: Link Bags to inventory.

### ISSUE THREAD

**Issue by Rated01010010** [Ellpeck/ActuallyAdditions#193]
It would be awesome if you could link bags to inventories. So say you have a bag to that auto-pickups whitelisted ores. You can shift right click that bag to a chest, or crusher/furnace and it automatically gets sent there.

**Comment by Ellpeck** [comment]
You just mean like if you right-click it to a chest, all the stuff in the bag goes into the chest?

**Comment by Rated01010010** [comment]
That would probably be more balanced. But I was thinking at first, the items get sent as you pick them up, if you bind it to an inventory. Like an ender bag sort of.

**Comment by Ellpeck** [comment]
Noo, I'm not doing that, that's way cheaty.
But I'd be up for the put everything into a chest thing!

**Comment by Rated01010010** [comment]
Could you add it for furnaces and other things as well that uses IItemHandler, and it remembers your inventory at the time you right clicked? Like a furnace can only accept 64 items, but you have 4 stacks of ores in your bag. You shift right click the furnace and it adds the first stack, and the rest as they have space? There would need to be a way for the items to not be taken out of the bag during the process, or if you, it cancels the event.

**Comment by Rated01010010** [comment]
If not, then chests would be more than fine. I could just create a chest next to machines as a buffer.
