### ISSUE TITLE
New crash with Mekanism after updating AA from r57 to r58

### ISSUE THREAD

**Issue by utoc** [Ellpeck/ActuallyAdditions#194]
Running:

FML 2046
Mekanism 9.1.1.290
AA r58
on Minecraft 1.10.2

Crash here: http://pastebin.com/E8HMMrDY

@aidancbrady fixed the previous crash due to Tesla mod changing to lowercase with https://github.com/aidancbrady/Mekanism/issues/3590 which was tested and working, however, we're experiencing a new crash with the same steps to repeat:

Aquire laser energy relay, place Mekanism universal cable on it.  The server crashes.  Let me know if this needs to be redirected towards the Mekanism repo instead.

**Comment by Ellpeck** [comment]
This is a Mekanism error again.
The modid is still uppercase here: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L347
