### ISSUE TITLE
[Suggestion] Powered Furnace and Double Crusher split the Items

### ISSUE THREAD

**Issue by Greg9711** [Ellpeck/ActuallyAdditions#196]
My idea is that there could be a button in the ui of both machines (Powered Furnace and Double Crusher)
that you can toggle on or off so the machine can automaticly split the items that get input into the machine in both sots (so you can use them better for automation in my oppinion).

**Comment by Rated01010010** [comment]
Round Robin mode?

**Comment by Greg9711** [comment]
Yes kinda, if you put for example a stack of cobble in the right slot it will automaticly get split so then there is half a stack in the right and half a stack in the left slot and if you would pull out like 16 cobblestones from one slot it would split again so there is always the same number of items in both slots (if possible like you cant split 7 items so in one slot 4 and in the other 3 items).
