### ISSUE TITLE
Empowerer Lagging when working

### ISSUE THREAD

**Issue by Greg9711** [Ellpeck/ActuallyAdditions#197]
As soon as i put an item in the Empowerer and the beams start working my game starts lagging so it becomes almost unplayable until its done empowering.
Hope it´ll get fixed soon.

**Comment by Ellpeck** [comment]
You.. you just reported it a second ago.

**Comment by Greg9711** [comment]
Sorry as soon as i created the other issue this one disappeared so i thaught it was a bug and got removes, thats wha i wrote it a second time sorry
