### ISSUE TITLE
Stick recipe disappears

### ISSUE THREAD

**Issue by WazWaz** [Ellpeck/ActuallyAdditions#20]
After playing for a while, the standard Minecraft stick recipe disappears. Quitting right out of MC then restarting and reloading the world, the recipe returns.

Only other mods are minor ones I use all the time (NEI, WAILA, etc.), nothing new besides AA.

**Comment by Ellpeck** [comment]
Stat still should not be ActAdd's fault.
Will investigate.

**Comment by Ellpeck** [comment]
Please show me the mod list and explain exactly what happens and why.

**Comment by WazWaz** [comment]
Forge 1492
Journeymap 5.1.0
OptiFine HD_U_C1
Waila 1.5.10
CodeChickenCore 1.0.7.46
NEI 1.0.5.111

All is fine, then I'll go to craft sticks from Dark Oak planks, and no sticks appear in the output slot. NEI shows the recipe fine, but only for plain Oak (normally it cycles through all wood types randomly).

There appears nothing interesting in the logs, but I can send them.

**Comment by canitzp** [comment]
Try to update all the Mods including Forge

**Comment by Ellpeck** [comment]
Please try to reproduce the bug with just ActAdd installed on the newest Forge version.

**Comment by Ellpeck** [comment]
Closed for now because of no response
