### ISSUE TITLE
Morph-O-Tool Mod Combined with the Laser Wrench

### ISSUE THREAD

**Issue by WenXin20** [Ellpeck/ActuallyAdditions#200]
If you combine the Morph-O-Tool with the laser wrench from this Mod and then look at a block from this mod, the Morph-O-Tool permanently becomes the laser wrench.

Reported to Morph-O-Tool Mod as well: Vazkii/Morph-o-Tool#18

**Comment by Ellpeck** [comment]
Can't fix this right now, but just as a reminder to myself: I am setting the NBT tag to a completely new one once clearing the storage it has instead of just deleting the X, Y and Z values.
