### ISSUE TITLE
Crash: JEI Failed to start

### ISSUE THREAD

**Issue by TehColt** [Ellpeck/ActuallyAdditions#201]
Got redirected here by mezz after attempting to post this crash on JEI's issues.

https://gist.github.com/TehColt/121e03349a42c5f2c94e954588992a59

**Comment by Ellpeck** [comment]
This is really weird.
Try removing mods one by one, but without removing JEI and Actually Additions, and see if that fixes it.

It seems some mod introduces an old version of the RF API.

**Comment by canitzp** [comment]
Some of these mods are very outdated. Try to use the 1.10 edition of mods who have these option and yes it's the fault of a very old RF API. Every other RF mod would crash too.

**Comment by TehColt** [comment]
I swear to god I was not in a right state of mind when I thought adding extra utilities 1.2 12 (for 1.7.10) was a good idea. Anyhow you can blame the big error on ExUtils as removing it fixes the crash.
