### ISSUE TITLE
XP Pickup machine (turns it into Solidified XP?)

### ISSUE THREAD

**Issue by kwpugh** [Ellpeck/ActuallyAdditions#202]
A really big missing in 1.10.2 mods is an XP collector machine.

sources:
- dropped XP orbs
- bottle of enchanting
- XP shards
- Solidified XP

The machine would have the ability to collect nearby xp orbs and provide the option to turn them into solids or turn them into liquids

Additionally, it would be nice to manually feed in XP shards and solified XP and it would turn them into liquid XP.   

Lastly, using bottle, be able to fill bottles of XP for drinking.

Thank you for listening

Regards.

**Comment by Ellpeck** [comment]
Uhm, I understand the picking up XP part, but the whole "eating experience" is already a feature in Actually Additions, so I don't know what you're on about..?

**Comment by kwpugh** [comment]
Sorry about the mist-mash.

I guess the main ask is for a way to turn solid forms of xp (dropped xp from mobs, solidified XP, XP shards, etc.) and convert them into liquid form.

**Comment by Ellpeck** [comment]
Why? I can't think of anything that'd be useful for.

**Comment by kwpugh** [comment]
Nevermind.

**Comment by Ellpeck** [comment]
What?
I still found half the idea good.

Whatever..

**Comment by thebravestkoala** [comment]
Hey I OP closed this, but as for an actual answer to your question, if you're playing with EnderIO (or possibly other mods really) you can import liquid xp into an experience obelisk and store everything there for easy and quick retrieval or even automation, so it would be SUPER useful if much like the xp solidifier, there was an xp liquifier. Obviously pretty low on a priorities list but it would be useful if you get a chance.

**Comment by bookerthegeek** [comment]
Or the ability to turn into mob essence when MFR updates.

**Comment by IDKZAL** [comment]
xp liquifier is needed for sure :D
