### ISSUE TITLE
Experience solidifier doesn't always draw XP in it

### ISSUE THREAD

**Issue by c0rn3j** [Ellpeck/ActuallyAdditions#203]
Server forge 2056, client 2050
Modlist: http://pastebin.com/28DvFgGX
To classify - this is not a function issue but a GUI issue, the output slot sometimes looks empty even though it isn't.

**Comment by Ellpeck** [comment]
I don't really understand what the problem is. Could you do a video/series of screenshots or something similar?

**Comment by c0rn3j** [comment]
http://i.imgur.com/aH2ar2x.png
nabbed a screen from random video with outdated mod to give you an idea. You see how there is 64x soldified experience in it? Well if I keep opening/dropping XP and opening it sometimes doesn't show there, it just shows as an empty slot. Clicking in the empty slot has the correct behavior though - I can still withdraw the XP perfectly fine.

The glitch happens at random.

Is video still needed?

**Comment by Ellpeck** [comment]
Does it happen with any other blocks from the mod?

**Comment by c0rn3j** [comment]
Didn't test, I might check a while later. Any suggestions?

**Comment by Ellpeck** [comment]
No, this doesn't make any sense to me.

**Comment by c0rn3j** [comment]
Video: https://www.youtube.com/watch?v=CC0iZ5Kjxsw
Seems to always happen right after game freezes for a tiny moment.

**Comment by Ellpeck** [comment]
This is the same bug as this https://github.com/Ellpeck/ActuallyAdditions/issues/177
I still don't know how to fix it as it doesn't appear to be an issue on my side.

Try removing all of the mods you have installed one by one and see if the issue persists.
To be sure, just make a copy of the world it is happening in right now and just try it in that copy.
Thanks :)

**Comment by c0rn3j** [comment]
That's gonna be annoying... I'll do so when I'll have time, possibly later today.

**Comment by Ellpeck** [comment]
I know it's annoying, but it's the only way to be able to track down the bug :(

**Comment by Kolatra** [comment]
Something you can do is keep halving the mod list. Take all of the mods you have, remove half of them, if the issue persists, remove half of the remaining, and then keep doing this until you can narrow down a set of mods that are causing the issue.

**Comment by c0rn3j** [comment]
Yeah that's what I am gonna do, but it's still as annoying ^^

**Comment by c0rn3j** [comment]
If you don't mind I'll just use this comment as a notepad as I try to debug this....

Problem: Game lags out for a moment and then the solidifier shows an empty slot...

Try #1 - Tanking the game down to 5~ FPS with 3K entities, new world and a solidifier - did not reproduce
Try #2 - Copying world where I can reproduce it and destroying stuff around until the issue disappears - in progress

**Comment by c0rn3j** [comment]
Alright so tracked it down to TConstruct, removing that makes the issue gone. What's the next step? 
The region folder in the save is 700MB, not sure if I should be uploading that anywhere.

**Comment by Ellpeck** [comment]
Ugh, I knew it.
Last time I talked to @bonii-xx he said it probably isn't an issue with TiCon.
But I can't figure it out either :v

**Comment by c0rn3j** [comment]
It definitely looks like an issue with Tcon. The glitch is gone if I break my smeltery in a specific way (it has 3 height blocks basically, if I remove the top one, nothing happens, but if I remove any block in the bottom 2, the glitch is back)

**Comment by c0rn3j** [comment]
Also the issue still exists even if I break the Solidifier. The issue repeats periodically about every 13~ seconds, and while that it resets lightning and lags the game a little, so it's noticeable. I'll remove all mods but Tconstruct and mantle to remove your mod from the equation and then make a bug report on TC github.

**Comment by c0rn3j** [comment]
So this is a Tconstruct issue, I used those 2 alone and the lightning issue is still occuring, making a report.
Mantle-1.10.2-0.10.4.jar
TConstruct-1.10.2-2.4.0.jenkins312.jar

**Comment by Ellpeck** [comment]
Thanks for going so in-depth with this. It really takes a lot of the weight off my shoulders when users are so supportive with helping fix issues. Thank you very much :)

I am going to leave this open for now until there is news on the TiCon tracker.

**Comment by bonii-xx** [comment]
I daresay your stuff is also missing when you're loading the world and only synced once the GUI is opened, which is why you never noticed it. You're missing a proper getUpdatePacket in your tile. The behaviour you experience looks a lot like missing synchronization on tile reset, which is caused by forge when many tile entities in one chunk are touched (aka multiblocks). TileEntity.shouldRefresh is the function that causes it, but that is working correctly.

**Comment by Ellpeck** [comment]
Ugh, I think I just actually noticed my error :v

Well, that's embarassing. Sorry @bonii-xx for wasting your time.. twice >_>

**Comment by c0rn3j** [comment]
Glitch still present.

**Comment by Ellpeck** [comment]
(ノಠ益ಠ)ノ彡┻━┻

**Comment by Ellpeck** [comment]
Ugh. 
You've been a huge help with this already, but it would be awesome if you could test if the problem persists with this version here: https://ci.chaosfield.at/job/ActuallyAdditions/job/ActuallyAdditions-unstable/73/
Just download the normal .jar without any special suffixes and try it out. It'd be amazing if you could try out some other machines as well, just if I messed up some other syncing while fixing that :v

**Comment by c0rn3j** [comment]
Well I'm doing all of this in survival and I lost solidifier for a reason, so I had to craft it again... apparently you're now using a new crafting system I can't figure out.
http://i.imgur.com/plggj1I.png
Considering the guide says items should be inserted ONTO the empowerer, I should be seeing the item on top of it?

**Comment by Ellpeck** [comment]
Hang on.

**Comment by Ellpeck** [comment]
No, the empowerer is working properly for me.

**Comment by c0rn3j** [comment]
Anything inherently wrong with my setup? 
https://www.youtube.com/watch?v=bT-vVfH3Iqs

**Comment by Ellpeck** [comment]
It works for me. Do you have the less particles option turned on? If so, you won't see the thing progressing. It takes 2000 ticks for one block.

**Comment by c0rn3j** [comment]
Particles: All
I broke the connection to my main power and there is no drainage from the Capacitor.
Are we on the same forge version? I should also note I have Tesla installed.

**Comment by c0rn3j** [comment]
Anyway I cheated a solidifier in, and the glitch is gone. TCon is still lagging every 13~ secs but it doesn't affect the solidifier.

**Comment by Ellpeck** [comment]
Thank goodness, at least that's fixed >_>
Could you downgrade to the old version again, as the one I sent you isn't really supposed to be used for normal gameplay :)

If the issue with the Empowerer persists with any actual release version that is on Curse, please submit a seperate new issue.

Also, thanks for the help :)

**Comment by c0rn3j** [comment]
I can't load the testing world back again with the curse version and I'm too lazy to set the Empowerer up again, I guess I'll check it some other time.
