### ISSUE TITLE
[1.10.2] Easy Infinite worms farming "bug"

### ISSUE THREAD

**Issue by Gayanfalor** [Ellpeck/ActuallyAdditions#204]
Hello,

 i wanted to get some worms from grass block and i tried to till a grass block with a jungle vines  just over it, i spammed the right click and it seems i can get some worms with the low chance of looting them without tilling the dirt or damaging the tool.

using forge 2046
and AA 1.10.2-r58

its working too when a door is on top of the grass block, here is some screens:

![2016-08-13_15 34 25](https://cloud.githubusercontent.com/assets/10771109/17643479/ab8eb9b6-616b-11e6-8ab2-7fc4dbcd38e9.png)
![2016-08-13_15 35 09](https://cloud.githubusercontent.com/assets/10771109/17643480/ab91372c-616b-11e6-8bdf-a372acaba272.png)

**Comment by Ellpeck** [comment]
Huh, that's very interesting.

**Comment by Gayanfalor** [comment]
lol you have already fixed this XD

Nice :p
