### ISSUE TITLE
Chests aren't identified by OreDict

### ISSUE THREAD

**Issue by ChromeMystic** [Ellpeck/ActuallyAdditions#206]
When using Chests added by other Mods (Like the Chests from Quark) they aren't recognized by ActuallyAditions Recipes, like the one for the Storage crate.

Can you please add the OreDict Call for Chests to your mod?

Thanks

**Comment by Ellpeck** [comment]
Ugh, that's the one thing I hate about Quark.
Will do. >_>

**Comment by Ellpeck** [comment]
Wait, what should they even be oredicted as? Just "chest"? Or "blockChest"? "chestWood"? :v

**Comment by Ellpeck** [comment]
Oh, it's in the OreDict by default, that's not even a custom mod thing :v never mind
