### ISSUE TITLE
Cannot place levers on Crates

### ISSUE THREAD

**Issue by DiscipleOfUrza** [Ellpeck/ActuallyAdditions#207]
As of the r59 update, I am no longer able to place redstone levers on at least the Large Crates (haven't tried the other sizes), preventing the use of redstone-activated transfer nodes/item conduits.

**Comment by DiscipleOfUrza** [comment]
v.1.10.2

**Comment by Ellpeck** [comment]
What? Just place them on the other sides of the transfer nodes/item conduits.

**Comment by DiscipleOfUrza** [comment]
That would be great accept for situations where the crate is standing alone and has no adjacent blocks to put a lever on.

**Comment by Ellpeck** [comment]
The crate is a transparent block, like a normal chest, thus, you can't place any lever on it.

That is _by design_.

**Comment by DiscipleOfUrza** [comment]
Very well. I guess I will just have to suffer from a bit of aesthetic loss ;)

**Comment by Ellpeck** [comment]
I'm very sorry for that, but that's just how it goes.
Awesome models = less levers :P

**Comment by DiscipleOfUrza** [comment]
Sorry, but I've been thinking on this for some reason. By "aesthetic loss," I meant I now have odd blocks with levers on them next to the snazzy looking new crates, not that I didn't update.

It bothered me for some reason to have you thinking Id stop updating/using AA because of something silly like that. Still is my go-to mod for most (all) playthroughs.
