### ISSUE TITLE
Couple suggestions (I post them here so I don't forget them :v)

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#209]
-Empowered armor makes it either RF-powered or gives it predetermined Enchantments (fire protection for restonia, water-based things for palis etc.)
-Block cannon that shoots blocks that you put into its inventory that have certain effects (restonia -> explosion etc?) or damage based on block hardness or price (maybe with upgrade to be able to shoot blocks that then get placed falling sand style)

**Comment by tigier** [comment]
Do you plan the same for swords?
