### ISSUE TITLE
Fluid Placer will hydrate the nether

### ISSUE THREAD

**Issue by utoc** [Ellpeck/ActuallyAdditions#210]
Hello!  Using the latest AA, r60, we're able to place water in the nether using the fluid placer.  You'd think the vanilla mechanics would evaporate the water.. but not so much.  Can you restrict this or rework how fluids are placed?  Or does this need to go to Forge for a fix?

**Comment by Ellpeck** [comment]
I can't believe no one ever found this so far :'D
