### ISSUE TITLE
Atomic Reconstructor Red Mushroom -> Nether Wart Working, sort of...

### ISSUE THREAD

**Issue by therealericbj** [Ellpeck/ActuallyAdditions#212]
First of all, I'm having lots of fun with your mod, keep up the great work!

The atomic reconstructor is working is working fine with every other thing that I have tried.

It just seems to be really picky when it comes to red mushrooms.  I can only get about 1 in 6 to change.

It is in front of a block.  I have even moved the block closer, just in case, no difference.

I even went as far as making the precision dropper, no difference.

I just cannot figure out what I'm missing...

I await your guidance...

![2016-08-19_10 06 39](https://cloud.githubusercontent.com/assets/8407817/17816587/1ece5262-65f7-11e6-9c8c-7ce870210f0a.png)

After 3 tries...
![2016-08-19_10 26 26](https://cloud.githubusercontent.com/assets/8407817/17816654/8a069f9e-65f7-11e6-9106-07baa65bd6a0.png)

**Comment by Ellpeck** [comment]
It needs 250000 RF.

**Comment by therealericbj** [comment]
Sorry, I know that.  It is receiving power from the bottom.  It has it's full requested power of 300000 RF.

Not to sound impolite, but "it works for all the other materials but does not work consistently for red mushrooms"...

**Comment by Ellpeck** [comment]
Huh. Then I have no idea. I've never encountered something like that before.

**Comment by Ellpeck** [comment]
I tried this about 20 times and it got converted every single time.
Please make a video of the problem.

**Comment by therealericbj** [comment]
I'll do my best.  I've never made a video before.  Ya, learning new things...

**Comment by 7OOTnegaTerces** [comment]
I was completely unable to get red mushrooms to convert to netherwart, but I had other mods that gave me netherwart, so I never bothered trying to figure out why the AR wasn't working.  Now, of course, AA is freezing my game, but as soon as it's running again, I'll test red mushrooms again and if they still don't work I'll try to figure out why.

**Comment by Ellpeck** [comment]
I still have no idea what this could be caused by, as I am unable to reproduce it.
But we are talking about 1.10.2, right? If not, please try it in that version.

**Comment by canitzp** [comment]
It is the newest version. At the pics you can see that there is a Travellers sack

**Comment by Ellpeck** [comment]
I will close this issue for now as I haven't heard back from it in a long time so I assume it has either been fixed or it isn't important anymore.
You can always reopen it if you want to though. :)
