### ISSUE TITLE
[Enhancement] Config update

### ISSUE THREAD

**Issue by bondgb** [Ellpeck/ActuallyAdditions#214]
With the current version the config seems out of date with the mod's content. No easy way to disable the tools etc

**Comment by Ellpeck** [comment]
Which tools?
All Crafting Recipes can be disabled in the config.

**Comment by bondgb** [comment]
Alright, maybe I have to reset my config

**Comment by Ellpeck** [comment]
If there is any items missing, just tell me. But I try to have one for every item. :)
If you find the thing you're looking for, just close this issue.
