### ISSUE TITLE
mekanism & actually additions crash 

### ISSUE THREAD

**Issue by DnTheMn** [Ellpeck/ActuallyAdditions#217]
issue Description: using universal cable, connecting to Laser Relay, causes server to crash, any time this chunk loads the server crashes.

What happens: Ticking block entity

What you expected to happen: provide power.

Steps to reproduce:

1.connect universal power cable to laser relay.

Version of All the Mods:13c

Added mods (Optifine, Fastcraft, etc.): none

crash report.
http://pastebin.com/m2tH74iU

i have reported this to the mekanism git hub too (https://github.com/aidancbrady/Mekanism/issues/3683)

**Comment by Ellpeck** [comment]
Same issue as here, still on Mekanism's side.
https://github.com/Ellpeck/ActuallyAdditions/issues/194
