### ISSUE TITLE
Game suddenly started freezeing...

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [Ellpeck/ActuallyAdditions#218]
I'd been playing Minecraft 1.9 modded with several mods, this one among them, for a while without a hitch when the game suddenly froze up on me.  Examining the error log revealed a null pointer exception being generated by something from this mod, though I don't honestly understand what.  All I know is that when I try to play the game I only get as far as the world loading and a few blocks rendering before the game freezes.  I'm using MultiMC, and it's active log only stated that "The state engine was in incorrect state".  I've uploaded the crashlog to paste.ee, here is the link: http://paste.ee/p/fewSR.

**Comment by Ellpeck** [comment]
Sorry, the 1.9 versions of this mod won't be updated anymore, so you are going to have to update to fix this. Sorry :(

However, I have located the source of the bug, but as you can see [here](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/tile/TileEntityItemViewer.java#L58-L59) (if you know Java), that this, in fact, is unable to happen anymore. I guess it just missed a null check at some point in 1.9.

**Comment by 7OOTnegaTerces** [comment]
GRRRR!!!!  I'm waiting on other mods before I move up to version 10, is there anything I can do to get this version working?  I do know programing, and I in fact learned in Java, so if you could just tell me where I need to insert those two lines of code, I'd GREATLY appreciate it!

**Comment by Ellpeck** [comment]
You are sadly going to have to look at that yourself. There is the old branch for 1.9 which you can always edit and then compile yourself.
As the entire Item Interface system worked differently (I am pretty sure) back then though, you are going to have to look at that yourself. But it isn't that hard, promise :)

**Comment by Ellpeck** [comment]
Actually, I just looked back at that quickly.
The check is in fact there in 1.9.
Huh, maybe I'll have to look at that a second time when. Whoooops.

**Comment by Ellpeck** [comment]
I tested this a bunch more and the bug never occured for me.
Could you try in 1.10.2 and see if it still happens?

**Comment by Ellpeck** [comment]
Closing because of no response.
