### ISSUE TITLE
Make the Empowerer use different items that relate to the crystal type

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#220]
So that automating the thing is more difficult >:3
For example netherrack, nether wart etc. for red crystal
Also maybe lower the time it takes because it's annoying

**Comment by tigier** [comment]
Ich würde ja für jeden Crystal einmal die passende Farbe als empowerer Material benutzen

**Comment by Ellpeck** [comment]
Great english though.

**Comment by tigier** [comment]
I would use the matching Color as an empowerer Material for the crystals.(sry.....My English just isn't that great)

**Comment by Ellpeck** [comment]
That suggestion is part of the actual issue. Read before you type..

**Comment by tigier** [comment]
*dye

**Comment by Ellpeck** [comment]
Yes, *that* I could do.
