### ISSUE TITLE
[Suggestion] Better End-Game Canola Power

### ISSUE THREAD

**Issue by Greg9711** [Ellpeck/ActuallyAdditions#224]
This is a kinda strange idea but maybe there could be a block (my suggestion for the name of the block: "Refined Crystallizer" or "Refining Crystallizer") that turnes 1000mb of Oil into some kind of fuel crystall that can be put into the Coal Generator to produce a lot more power (something like 100 to 200 RF/t) than the Oil in the Oil Generator, because normal Oil in the Oil Generator isn´t very good to produce much to power some mid to end-game machines and i would like to use the canola plants for end game power.

**Comment by Ellpeck** [comment]
Yes, I like this quite a bunch actually.

**Comment by Greg9711** [comment]
:) I love to hear that.

**Comment by Ellpeck** [comment]
Would you also think it's cool with there being a Reconstruction recipe that reconstructs the fluid into another one?
I think that'd be cooler as you would have to automate the fluid placing and breaking and also the reconstructor firing :D

**Comment by Greg9711** [comment]
That fluid reconstructor recipe thing sounds interesting, and that combined with my crystall idea could be cool so that you would have to first convert the oil into something like enriched oil and then put it into my Crystallizer thing to get the crystall :)

**Comment by Ellpeck** [comment]
Oh, that could be a cool thing too.
I don't know if that'd be too many steps though :o
I might also just use the Empowerer, as that doesn't really have anything other than the crystal recipes anyways ^-^

**Comment by tigier** [comment]
How about using the refined oil already as Generator fuel with a slight Power increase and the oil Crystal as a massive increase

**Comment by Greg9711** [comment]
Yeah that would be cool so its kinda that normal Oil is early to mid-game, "refined Oil" for mid game and the crystalls for late game and i find that the many steps are ok if the crystalls really give enough power so its worth it to really use them end game.

**Comment by Greg9711** [comment]
And i think you should use the reconstructer for converting the fluid and not the empowerer but another idea for the empowerer could be that you could empower machines with it so like a generator produces more power and uses less fuel when empowered and a RF using machine would use less Power and works faster.

**Comment by Greg9711** [comment]
So are you going to add the fuel crystalls too?

**Comment by Ellpeck** [comment]
No. I am going to stick to the plan of having only fluids like I have it set up now.
The Crystallizer is just going to turn it into another fluid probably :)

**Comment by Greg9711** [comment]
Aww, ok :) Still thanks for adding my idea.

**Comment by DiscipleOfUrza** [comment]
You know...adding in compatability with Advanced Generators for this new liquid sure would be super cool... :)
