### ISSUE TITLE
[bug] TileEntities doesn't get destroyed (r61)

### ISSUE THREAD

**Issue by ZigTheHedge** [Ellpeck/ActuallyAdditions#225]
When one's breaks any AA block with TE, TE doesn't get destroyed and stays where the block used to be. Block at new location doesn't work (you even can't open it's GUI). Placing any other block with TE in it at the old location causes a crash about impossible cast of TileEntities.

Forge: 2072
Mod version: r61

**Comment by Ellpeck** [comment]
What? That doesn't happen to me O_o

**Comment by Ellpeck** [comment]
Which blocks does it happen with?

**Comment by canitzp** [comment]
can you post the latest log and/or a modlist?

**Comment by ZigTheHedge** [comment]
Sure. Here's the crashlog (player tried to place ExUtil thing): http://pastebin.com/gTjGNxJ2
