### ISSUE TITLE
Issue with phantom liquidface and lava

### ISSUE THREAD

**Issue by ButtonBright0907** [Ellpeck/ActuallyAdditions#226]
When i link a liquid face to the input on a tinker smelter using a phantom connector it causes the following error.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  LoadingPlugin (Quark-beta-42.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.38-beta.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 9/1/16 10:46 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityPhantomLiquiface.drain(TileEntityPhantomLiquiface.java:59)
	at de.ellpeck.actuallyadditions.mod.util.WorldUtil.doFluidInteraction(WorldUtil.java:101)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.updateEntity(TileEntityBase.java:218)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityFluidCollector.updateEntity(TileEntityFluidCollector.java:132)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.func_73660_a(TileEntityBase.java:206)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityPhantomLiquiface.drain(TileEntityPhantomLiquiface.java:59)
	at de.ellpeck.actuallyadditions.mod.util.WorldUtil.doFluidInteraction(WorldUtil.java:101)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.updateEntity(TileEntityBase.java:218)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityFluidCollector.updateEntity(TileEntityFluidCollector.java:132)
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.func_73660_a(TileEntityBase.java:206)

-- Block entity being ticked --
Details:
	Name: actuallyadditions:fluidCollector // de.ellpeck.actuallyadditions.mod.tile.TileEntityFluidCollector
	Block type: ID #286 (tile.actuallyadditions.blockFluidCollector // de.ellpeck.actuallyadditions.mod.blocks.BlockFluidCollector)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-513,163,-48), Chunk: (at 15,10,0 in -33,-3; contains blocks -528,0,-48 to -513,255,-33), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Actual block type: ID #286 (tile.actuallyadditions.blockFluidCollector // de.ellpeck.actuallyadditions.mod.blocks.BlockFluidCollector)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['ButtonBright'/247, l='New World', x=-511.15, y=164.00, z=-49.47]]
	Chunk stats: ServerChunkCache: 1125 Drop: 117
	Level seed: 322371885372920411
	Level generator: ID 03 - amplified, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-200,64,-204), Chunk: (at 8,4,4 in -13,-13; contains blocks -208,0,-208 to -193,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 69445 game time, 69445 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 2536 (now: true), thunder time: 2536 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1674654224 bytes (1597 MB) / 3215249408 bytes (3066 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 28 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xrs -Xmx4G -XX:ThreadPriorityPolicy=42 -XX:+TieredCompilation -XX:TargetSurvivorRatio=90 -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=15 -XX:+UnlockExperimentalVMOptions -XX:+UseBiasedLocking -XX:UseSSE=3 -XX:+UseCodeCacheFlushing -XX:+UseThreadPriorities -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -XX:+ReduceSignalUsage -XX:+UseInterpreter -XX:+UseFastEmptyMethods -XX:+UseSharedSpaces -XX:AllocatePrefetchStyle=1 -XX:+AlwaysCompileLoopMethods -XX:SharedReadOnlySize=30m -XX:+UseConcMarkSweepGC -XX:+RewriteFrequentPairs -XX:+OptimizeStringConcat -XX:+CMSCleanOnEnter -XX:+UseSplitVerifier -XX:+UseInlineCaches
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: Minecraft 1.10.2 MCP 9.32 Powered by Forge 12.18.1.2014 81 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2014.jar) 
	UCHIJAAAA	Forge{12.18.1.2014} [Minecraft Forge] (forge-1.10.2-12.18.1.2014.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r50} [Actually Additions] (ActuallyAdditions-1.10.2-r50.jar) 
	UCHIJAAAA	JEI{3.7.6.231} [Just Enough Items] (jei_1.10.2-3.7.6.231.jar) 
	UCHIJAAAA	AppleCore{1.3.5} [AppleCore] (AppleCore-mc1.10.2-1.3.5.jar) 
	UCHIJAAAA	armorplus{1.9.4-4.0.1.0} [ArmorPlus] (ArmorPlus1.9.4-4.0.1.0.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.6} [Chameleon] (Chameleon-1.9.4-2.1.6.jar) 
	UCHIJAAAA	ChestTransporter{2.5.0} [Chest Transporter] (ChestTransporter-1.10-2.5.0.jar) 
	UCHIJAAAA	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UCHIJAAAA	cyclopscore{0.7.1} [Cyclops Core] (CyclopsCore-1.9.4-0.7.1.jar) 
	UCHIJAAAA	commoncapabilities{1.1.1} [CommonCapabilities] (CommonCapabilities-1.9.4-1.1.1.jar) 
	UCHIJAAAA	cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar) 
	UCHIJAAAA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJAAAA	DeathCounter{MC1.9.0v2} [DeathCounter] (DeathCounter-1.10.2-1.0.0.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.38-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.38-beta.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.67_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.67_beta.jar) 
	UCHIJAAAA	shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
	UCHIJAAAA	endertanks{1.4.1} [EnderTanks] (endertanks-1.10.0-1.4.1.jar) 
	UCHIJAAAA	ValkyrieLib{1.10-0.10.1} [Valkyrie Lib] (valkyrielib-1.10-0.10.1.jar) 
	UCHIJAAAA	EnvironmentalTech{1.10-0.10.1a} [Environmental Tech] (environmentaltech-1.10-0.10.1a.jar) 
	UCHIJAAAA	ezstorage{2.1.4} [EZ Storage 2] (ezstorage-2.1.4.jar) 
	UCHIJAAAA	fastleafdecay{v10} [Fast Leaf Decay] (FastLeafDecay-v10.jar) 
	UCHIJAAAA	fe{1.2.1} [Food Expansion] (FoodExpansion1.2.3-1.10.2.jar) 
	UCHIJAAAA	gravestone{1.5.1} [Gravestone] (GraveStone Mod 1.5.1.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	IronChest{7.0.6.794} [Iron Chest] (ironchest-1.10.2-7.0.6.794.jar) 
	UCHIJAAAA	jwin{univ_compat_filler} [Just What I Needed] (jwin-0.12.0_mc1.10.2.jar) 
	UCHIJAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.36} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
	UCHIJAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAA	MikeDongles{1.10.2-0.1.9} [Mike Dongles] (MikeDongles-1.10.2-0.1.9.jar) 
	UCHIJAAAA	MoreFurnaces{1.8.1} [More Furnaces] (MoreFurnaces-1.10-1.8.1.jar) 
	UCHIJAAAA	multistorage{1.2.1} [Multi-Storage] (multistorage-1.10.0-1.2.1.jar) 
	UCHIJAAAA	mychunkloader{1.9.4-1.10.2-03} [My Chunk Loader] (Mychunkloader-1.9.4-1.10.2-03.jar) 
	UCHIJAAAA	fodc{1.9.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.0.jar) 
	UCHIJAAAA	orespawn{1.0.3} [Ore Spawn] (OreSpawn_1.9.4-1.0.3.jar) 
	UCHIJAAAA	platforms{1.2.0} [Platforms] (platforms-1.10.0-1.2.0.jar) 
	UCHIJAAAA	prefab{1.1.0.5} [Prefab] (prefab-1.1.0.5.jar) 
	UCHIJAAAA	quantumflux{2.0.7} [QuantumFlux] (quantumflux-1.9.4-2.0.7.jar) 
	UCHIJAAAA	reborncore{2.5.5.3} [RebornCore] (RebornCore-1.10.2-2.5.5.3-universal.jar) 
	UCHIJAAAA	QuantumStorage{3.1.0} [QuantumStorage] (QuantumStorage-1.9.4-3.1.0.jar) 
	UCHIJAAAA	Quark{beta-42} [Quark] (Quark-beta-42.jar) 
	UCHIJAAAA	randomthings{3.7.4} [Random Things] (RandomThings-MC1.10-3.7.4.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.5.5.3} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.5.5.3-universal.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAA	StorageDrawers{1.9.4-3.2.0} [Storage Drawers] (StorageDrawers-1.9.4-3.2.0.jar) 
	UCHIJAAAA	refinedstorage{0.8.10} [Refined Storage] (refinedstorage-0.8.10.jar) 
	UCHIJAAAA	reptilemod{3.5.2} [Reptile Mod] (reptilemod-1.10.2-3.5.2-55.jar) 
	UCHIJAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAA	AS_Ruins{16.2} [Ruins Spawning System] (Ruins-1.10.2.jar) 
	UCHIJAAAA	Schematica{1.7.8.150} [Schematica] (Schematica-1.10.2-1.7.8.150-universal.jar) 
	UCHIJAAAA	shadowmc{3.4.1} [ShadowMC] (ShadowMC-1.10.2-3.4.1.jar) 
	UCHIJAAAA	SilentLib{1.0.11} [Silent Lib] (SilentLib-1.9.4-1.0.11-19.jar) 
	UCHIJAAAA	SilentGems{2.0.23} [Silent's Gems] (SilentsGems-1.10.2-2.0.23-52.jar) 
	UCHIJAAAA	SleepingBag{1.2.1} [Sleeping Bag] (SleepingBag-1.9.4-1.2.1.jar) 
	UCHIJAAAA	SolarFluxReborn{1.9.4_0.7b} [Solar Flux Reborn] (SolarFluxReborn-1.9.4_0.7b.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.3} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.3.jar) 
	UCHIJAAAA	Stackie{1.6.0.44} [Stackie] (Stackie-1.10.2-1.6.0.44-universal.jar) 
	UCHIJAAAA	substratum{1.6.0.1} [Substratum] (Substratum-1.10.2-1.6.0.1.jar) 
	UCHIJAAAA	supercraftingframe{1.2.0.85} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.0.85.jar) 
	UCHIJAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UCHIJAAAA	lteleporters{1.1.3} [Lemon's Simple Teleporters] (teleporters-1.1.3.jar) 
	UCHIJAAAA	tesla{1.2.1.42} [TESLA] (Tesla-1.10.2-1.2.1.42.jar) 
	UCHIJAAAA	thutcore{3.2.1} [ThutCore] (thutcore-1.9.4-3.2.1.jar) 
	UCHIJAAAA	thuttech{3.0.5} [Thut's Tech] (thuttech-3.0.5.jar) 
	UCHIJAAAA	tinker_io{release 2.3.1c} [Tinker I/O] (tinker_io-1.10-release 2.3.1c.jar) 
	UCHIJAAAA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJAAAA	transprot{1.2.0} [Transprot] (Transprot-1.10.2-1.2.0.jar) 
	UCHIJAAAA	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAA	VTweaks{1.4.9.4} [V-Tweaks] (VTweaks-1.10.x-1.4.9.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UCHIJAAAA	ICSE{1.1.0.0} [I Can See Everything] (Wawla-1.10-2.3.0.193.jar) 
	UCHIJAAAA	wawla{2.3.0.193} [What Are We Looking At] (Wawla-1.10-2.3.0.193.jar) 
	UCHIJAAAA	weaponsplus{1.9.4-3.0.0.0} [WeaponsPlus] (WeaponsPlus1.9.4-3.0.0.0.jar) 
	UCHIJAAAA	wuestUtilities{1.10.2} [Wuest Utilities] (wuestUtilities-1.10.2.0.jar) 
	UCHIJAAAA	xlfoodmod{1.10.2-0.1.1} [XL Food Mod] (XL Food Mod-1.10.2-0.1.1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Quark-beta-42.jar)
  vazkii.quark.base.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.38-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/ActuallyAdditions-1.10.2-r50.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/ActuallyAdditions-1.10.2-r50.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/ActuallyAdditions-1.10.2-r50.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/ActuallyAdditions-1.10.2-r50.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/ActuallyAdditions-1.10.2-r50.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/ActuallyAdditions-1.10.2-r50.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/ActuallyAdditions-1.10.2-r50.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/ActuallyAdditions-1.10.2-r50.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/EnderIO-1.10.2-3.0.1.67_beta.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Button%20Bright/AppData/Roaming/.minecraft/mods/EnderIO-1.10.2-3.0.1.67_beta.jar!/cofh/api/energy/TileEnergyHandler.class

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ButtonBright'/247, l='New World', x=-511.15, y=164.00, z=-49.47]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Ellpeck** [comment]
Could you try with this version if the bug is fixed?
https://ci.chaosfield.at/job/ActuallyAdditions/job/ActuallyAdditions-unstable/96/artifact/build/libs/ActuallyAdditions-1.10.2-r62-96.jar

**Comment by ButtonBright0907** [comment]
Thanks that worked!

**Comment by Ellpeck** [comment]
Awesome :)
