### ISSUE TITLE
[Issue/Question] Tesla dependency crash

### ISSUE THREAD

**Issue by accessdenied0** [Ellpeck/ActuallyAdditions#227]
Hey @Ellpeck,

sorry to bother you with that but I got recently a crash trying to plug your Coal Generator on a Universal-Cable from Mekanism. Here is the thing: I'm not sure on which side the issue might be and I guess that it could be Mekanism's version of Telsa.

I post this issue here because I feel like I get faster support here for my problem, it seem related to this mod and maybe it is easier to fix than I think.

do what ever you like to

I thank you for your support!

access_denied

**Comment by Ellpeck** [comment]
Give me the crash report.

**Comment by accessdenied0** [comment]
@Ellpeck 

*FailFish*... I'm so sorry I could swear I pasted it... totally my mistake... sorry

Here you go: http://paste.ee/p/JSlYx

sorry again.

**Comment by Ellpeck** [comment]
Stop apologizing for nothing, dude. It's a mistake. Humans do them. :P

Yes, this is the same as https://github.com/Ellpeck/ActuallyAdditions/issues/194, basically, only that the error is caused in another place.
The Tesla modid is still uppercase here, even though it should be "tesla". https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L347

If you care, please post the issue and my explanation to the Mekanism tracker. :)

**Comment by accessdenied0** [comment]
Thank you , @Ellpeck . I hope this get fixed soon.
