### ISSUE TITLE
Glitch with all machines

### ISSUE THREAD

**Issue by ErsatzIncline** [Ellpeck/ActuallyAdditions#228]
moving a machine seems to break it, causes it to remain where you first placed it but invisible. I cannot open its interface on the block unless I place it back where I first put it.  For the vertical digger, powering it in its new position causes it to run where it was first placed. help please

**Comment by canitzp** [comment]
Update ActuallyAdditions to the latest version

**Comment by Ellpeck** [comment]
Update to r62.
