### ISSUE TITLE
Crafting Empowerer

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#232]
New tier of empowerer that needs 8 display stands.
Normal crafting recipe can be put onto the display stands and the empowerer in the 3x3, and then the output item will appear on the empowerer in the middle.

**Comment by Greg9711** [comment]
Would that replace some existing recipes for items or is that going to be used for upcoming, more powerfull endgame items?

**Comment by Ellpeck** [comment]
It's like a Crafting Table.

**Comment by Greg9711** [comment]
But its used for crafting items right? Then what kind of items?

**Comment by Ellpeck** [comment]
Crafting Table Items.
It's an Autocrafting table.
Read the description..

**Comment by Greg9711** [comment]
That seems a bit to big for simple autocrafting and the missing middle part of a crafting recipe could be a problem.

**Comment by Ellpeck** [comment]
No, it couldn't, because there can ever only be one Item on an Empowerer anyways. And if it has a Container item, it'll just get dropped.

Also, I don't care. I started to absolutely hate blocks that can do everything for you in one block, so I like my idea and I don't care how many people are going to use it :P

**Comment by Ellpeck** [comment]
"Simple autocrafting" isn't a term for me. Autocrafting takes away HALF of the entire game, and so I think it is a huge thing that should also be huge in-world.

**Comment by Greg9711** [comment]
Ok but isn´t that the wrong issue?
