### ISSUE TITLE
Idea for a new Block

### ISSUE THREAD

**Issue by Greg9711** [Ellpeck/ActuallyAdditions#233]
I had this idea for a while now and i think it could fit into your mod. So the idea is a block that is used to automate some complicated machines like your empowerer or the runic altar from botania with logistics pipes/applied energistics(when they get updated) or other mods with autocrafting  in them.
Idea for the Gui (sorry for the bad picture, i did it in paint): 
![idea](https://cloud.githubusercontent.com/assets/20912744/18233357/989bb2d8-72e5-11e6-9256-d542d25d44a5.png)
So in the top left grid you could set all the item required for crafting the item in the complicated machine, the bottom left grid is the input of the machine where the items land when they get put in and the bottom right grid is where the items (that are specified in the top left grid) get put by the machine when certain conditions are fullfilled like receiving a redstone signal and all the required items are in the input of the machine. the top right grid is where you could set diffenrent conditions when the block should move the items into the output slot.
Idea for some Modes:
1.When all the required items are in the input slots and receiving a redstone signal move one set of items in the output slots.
2.When all the required items are in the input slots move one set of items in the output slots
3.When all the required items are in the input slots emitt a redstone signal out the back of this block and when receiving a redstone signal on any other side than the back move one set of items to the output slots.
Hopefully you like my idea.

**Comment by Ellpeck** [comment]
This sounds like a machine that is a single block but basically does everything for you that would be fun to automate in normal gameplay.
If I understand this correctly, then no, sorry.

**Comment by Ellpeck** [comment]
See, I *like* machines where you need tons of hoppers or pipes connecting the different parts and many logistics are required to set up the automating of it, so this just seems like it's going to make all of that go away, which I am personally not a huge fan of :(

**Comment by Greg9711** [comment]
I know what you mean i like that too but when i have to build that for 16 different recipes like the botania runes it gets boring after some time,but then maybe just a block that could read an inventory and put out an redstone siganl when a certain amount of an item is reached in any slot.

**Comment by Ellpeck** [comment]
That... that's what a comparator does

**Comment by Greg9711** [comment]
k

**Comment by Ellpeck** [comment]
Sorry :(
