### ISSUE TITLE
MT All In One Tool in Bronze has no texture

### ISSUE THREAD

**Issue by Allrick1** [Ellpeck/ActuallyAdditions#236]
No textures for any of the MT All In One Tools.

**Comment by Ellpeck** [comment]
Great you're bringing that up, cause I removed them entirely just yesterday. So you won't have them anymore next release anyways.
Sorry :(

**Comment by Allrick1** [comment]
Are you getting rid just the MTs, or all of the AIOTs?

**Comment by canitzp** [comment]
he removed just the special AIOTs like bronze or shiny
