### ISSUE TITLE
Worms cannot be removed once placed.

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ellpeck/ActuallyAdditions#240]
need a way to pick up worms once placed, since they cannot be removed once they are placed. if you place a block on top of them, the worm model disappears, but still continues to affect the area it was placed in, tilling soil at any level in the 3x3 area of effect. I suggest making it a right click with a hoe in hand. problem was noticed in r60, and is still present in r62.

**Comment by Ellpeck** [comment]
Just remove the block the worm is on.

**Comment by TheDarkPreacher** [comment]
I don't think you understand. I have tried that. it still tills the same 3x3 area, even AFTER removing the block that the worm is on, and has done so ever since version r60. I've removed every block in the 3x3 area, and the "worm" still digs the 3x3 area. Perhaps you should go to [https://youtu.be/sWkmdi-5E7o?t=77](url) and give this a look.

**Comment by Ellpeck** [comment]
I am unable to reproduce the issue. Did you really remove the dirt block that the worm is on top of?

**Comment by TheDarkPreacher** [comment]
yes. I have removed every block in the 3x3 area, and as soon as the top layer of dirt is removed, the layer under it gets tilled.

**Comment by Ellpeck** [comment]
Please submit the full log of a session where you tried to remove a worm and it didn't work.

**Comment by TheDarkPreacher** [comment]
https://youtu.be/sWkmdi-5E7o?t=77

**Comment by Ellpeck** [comment]
The _log_.

**Comment by Ellpeck** [comment]
What is the thing in the middle of your farm? Because it makes a tilling sound once the ground is tilled again, and worms don't make that sound.

**Comment by TheDarkPreacher** [comment]
harvest rod from reliquary, but I still had this issue before i added that to the farm.

**Comment by Ellpeck** [comment]
Go somewhere different where you haven't built anything yet and try placing and removing a worm.

**Comment by TheDarkPreacher** [comment]
https://youtu.be/BKPR5QW97sU

**Comment by Ellpeck** [comment]
You need to wait until the worm actually goes away before replacing the block...

**Comment by Vexatos** [comment]
@Ellpeck I think he is suggesting a way to be able to pick up worms (i.e. have them drop as an item) after you placed them. Right now there does not seem to be a way to drop the worm as an item once it has been placed. Is that intentional? It might be useful to have a way to collect worms, but I assume the lifespan of the worm should be stored in the item as NBT then (if lifespan is enabled in the config).

**Comment by Ellpeck** [comment]
Yes, it is intentional not to be able to collect them again, and I didn't think that was what he was referring to.
