### ISSUE TITLE
Lamp Turn on Bug

### ISSUE THREAD

**Issue by Cat3006** [Ellpeck/ActuallyAdditions#241]
The Manual says you could toggle the lamps by empty hand - right click, or via Lamp Controller
Toggle by Hand is not working on 1.10.2-r62 (actual Version)
- Bug found on MC All the Mods (1.10.2 v1.22)

Lamps can only be turned on via placing a Lamp Controller for each lamp, power via redstone and then you could break the Lamp Controller (not the Lever) and lamp stays on.

**Comment by Ellpeck** [comment]
Do you have something in your off hand? Also, it needs to be sneak-right-click.

**Comment by Cat3006** [comment]
No nothing in off hand. sneak-right-click did the trick. -> it works.

Just the manual should be edited ;)

btw. very quick response

**Comment by Ellpeck** [comment]
I never say in the manual wether it's sneak-right-click or normal right-click I noticed, I always forget.
Lots of people get annoyed about it with the Drill too, so I should really change it at some point, you're right :P
