### ISSUE TITLE
Knives can't be repaired in the Repairer, Glass block blocks solar generator. 

### ISSUE THREAD

**Issue by shikaku2** [Ellpeck/ActuallyAdditions#243]
The knife issue is pretty minor. You can just whitelist the knife in machine options(?) currently as a workaround.

I don't know how easy it would be to detect clear glass above a solar generator and work normally if it is just clear glass,  but logically it should work that way.

**Comment by Ellpeck** [comment]
The knife isn't supposed to be repaired. Also, the solar thing is by design too. Sorry :)

**Comment by Ellpeck** [comment]
Well, coming back to this.
The fact that glass blocks block solar panels doesn't really make any sense. :v

**Comment by tigier** [comment]
Greenhouse Glass could even enhance the energy Generation.....but that's just an idea
