### ISSUE TITLE
Solar Panels get less efficient with more blocks above them

### ISSUE THREAD

**Issue by xbony2** [Ellpeck/ActuallyAdditions#244]
from [541410be5e38a3d951c18c10e38a69d5df319a3e]- "it would be interesting if this made it work less efficiency; a Solar Panel with full access to the sun should generate more power than one just under a layer of glass."

**Comment by Ellpeck** [comment]
How about a proper title? :v

**Comment by xbony2** [comment]
skljgbfsg
