### ISSUE TITLE
Lush Caves sometimes make holes into Bedrock

### ISSUE THREAD

**Issue by psychofad** [Ellpeck/ActuallyAdditions#248]
Please add a dimension whitelist for Lush Cave generation, in the Utility Worlds mod there is a Garden Dimension that can be generated by a player with a portal block, it has 4 layers of dirt then bedrock and is meant to be a low lag area for farming, but the Lush Cave generator is creating holes in the worlds through the bedrock leaving gaping access to the void.  As these dimensions are created each time a player creates a new portal block to one, a blacklist is unfeasible to maintain which is why I am asking for a whitelist.  For now I have had to completely turn off their generation in order to prevent these void holes, but it would be nice if I could turn them back on for certain dimensions.

Thanks for the consideration, love your mod!

**Comment by Ellpeck** [comment]
That exists in the config already :)

**Comment by psychofad** [comment]
No it does not!
`
 # The IDs of the dimensions that Actually Additions OreGen (Black Quartz for example) is banned in. This also applies for other world gen like lush caves.
    I:"OreGen Dimension Blacklist" <
     >`

That is clearly a blacklist, I am asking for the complete opposite of that, please re-read my request.

**Comment by Ellpeck** [comment]
Why.. would you need that? That'd mean that you *have* to input every dimension into that. That'd make things more difficult and really annoying. So no, sorry, I'm not going to do that.

**Comment by psychofad** [comment]
Well, as I stated before, The Utility Worlds mod adds the ability for players to craft portals to their very own private mining, garden, or void worlds.  EVERY time that a new portal is created, so is a dimension, similar to mystcraft.  This is not such an issue with the mining worlds, HOWEVER, the garden worlds are only 5 blocks deep, 4 blocks of dirt/grass and 1 of bedrock.  Your mod is biting chunks out of those dimensions leaving gaping holes to the void when it tries to generate the lush caves because there is not enough depth for them to generate.  The Utility Worlds mod author is at a loss as to how it can be blocked.  I have seen mods in the past retain the ability to use either a whitelist or a blacklist so the server operators can decide which they need to use for their modpack servers based on the mods included in the pack, this is usually in the form of a simple config option that allows you to choose 1 for blacklist or 2 for whitelist and they utilize the same list in the config of dimensions for either one.  I am not asking you to remove the blacklist for players that need them, but it is not very useful for anyone using the Utility Worlds mod or any other mod that allows for dimensions to be added at any time.  As it stands, if I add say dimensions 5, 6 and 7 to the blacklist today, by tomorrow I may need to add 2 or 3 more and restart the server for the list to take affect, you want to talk about annoying, that's rather annoying as well.  Perhaps then if you can't be bothered to add a simple whitelist, then you can make it so that Lush Caves do not generate in dimensions added by Utility Worlds mod by default which would also solve the issue of the gaping holes in the ground.  It's ultimately your mod either way and at least I can turn them completely off for the server.

[Utility Worlds Mod](https://minecraft.curseforge.com/projects/utility-worlds)

[Other users with same issue](https://minecraft.curseforge.com/projects/utility-worlds?comment=54)

![2016-09-17_18 48 33](https://cloud.githubusercontent.com/assets/1578429/18611444/7d757d0a-7d07-11e6-8c62-8ef6a79e2f7d.png)

![2016-09-17_18 48 56](https://cloud.githubusercontent.com/assets/1578429/18611445/8b82bffc-7d07-11e6-9e1f-b2686586da11.png)

**Comment by Ellpeck** [comment]
Seeing as these worlds are just flat worlds, it might be best for the author of the mod to set its type to WorldType.FLAT, because most mods, including Actually Additions, block flat worlds from generating things like this.
I can't see how making a whitelist option would make this any less annoying, becasue you'd have to whitelist every other special world like mining worlds from Aroma's Dimensional World etc.,
however I should probably just write code to make caves not spawn when there is not enough space for them, so I'm going to reopen this issue for that.

**Comment by psychofad** [comment]
This also is an acceptable option, thank you!  I will also go and make the comment on the other mods page about the Flat worldtype since this is a good point!

**Comment by Ellpeck** [comment]
You don't need to, I just messaged the author myself! :D

**Comment by psychofad** [comment]
ok nice!
