### ISSUE TITLE
Storage Draws - ESD Not Working right.

### ISSUE THREAD

**Issue by alfw** [Ellpeck/ActuallyAdditions#249]
Hello, The lasers / ESD dose not work right with storage draws. After some testing it looks like it dsoent like to put more that 2 stacks worth of items into the draw itself. I have tested this and same thing happen on 2 setups, one witha Draw controller  and other with just a singel draw.

Setup 1:
Input Chest -> ESD -> Inventory Interface -> Item Laser Relay ->Item Laser Relay into a singel drive.

ESD Config: 
- Inbound: 0-27 ( nomral chest)
- Outbound: 0-2 ( This is what it auto config when automatic set. ) Altso tested to set it from 0-9999 with same resultats.

Setup 2:
Input Chest -> ESD -> Inventory Interface -> Item Laser Relay ->Item Laser Relay into a Draw Controller.

ESD Config: 
- Inbound: 0-27 ( nomral chest)
- Outbound: 0-130 ( This is what it auto config when automatic set. ) Altso tested to set it from 0-9999 with same resultats.

-Edit

Forgot to say that the item it can't place in is flickering in the ESD, and acutal doing the same on the tooltips of the draw.

**Comment by Ellpeck** [comment]
For future reference for myself: [This](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/tile/TileEntityItemViewer.java#L157) might be the cause of the issue. It could happen due to the drawer having more items in one slot than the max stack size of the item would allow so this system might be decreasing the stack size too much. Or something like that. Maybe.

**Comment by Ellpeck** [comment]
Oh, acutally: Does this only happen with an Item Laser Relay network, or are normal ESDs just directly connected to a Storage Drawer or Controller also broken?

**Comment by alfw** [comment]
Looks like it's the Laser Relay network. As when i placed the ESD next to the draw controller and it added the stuff just fine. It even worked when the draw was full and upgraded with a void upgrade to "void" the overflow of items.

**Comment by Ellpeck** [comment]
Okay, I need someone to test this.
Please download this version: https://ci.chaosfield.at/job/ActuallyAdditions/job/ActuallyAdditions-unstable/lastSuccessfulBuild/artifact/build/libs/ActuallyAdditions-1.10.2-r63-136.jar and try out your setup again.

**Comment by alfw** [comment]
@Ellpeck That fixes it! tnx!

**Comment by Ellpeck** [comment]
Great! It is also included in the latest official release, so it's best to grab that! :)
