### ISSUE TITLE
XP Solidifier broken?

### ISSUE THREAD

**Issue by Renadarain** [Ellpeck/ActuallyAdditions#250]
Hi,

When withdrawing XP from the solidifier it's giving it back in blocks but right-clicking on the blocks uses them up though it doesn't give you the xp levels.  

Minecraft 1.10.2
Forge forge-1.10.2-12.18.1.2092
ActuallyAdditions-1.10.2-r63

Regards,
Renada

**Comment by Ellpeck** [comment]
Step away from the XP Solidifier.
It picks up XP since one of the recent updates :)

**Comment by Renadarain** [comment]
Well well, so it does LOL!  Thank you for your help :)

Regards,
Renada
