### ISSUE TITLE
WARN console spam

### ISSUE THREAD

**Issue by C0rn3j** [Ellpeck/ActuallyAdditions#251]
I got tired of spammy console output. I've noted every single WARN and STDERR(just a single one, from Lootbags) during server startup. I've decided that I will not be making 63 separate issue descriptions, so I've added line numbers to each mod name which correspond to the server startup log line numbers. 

Some mods have more problems, so there will be numbers separated by a comma. 

I do realize that a lot of those are warnings when transitioning to 1.11, but it still throws a WARN now.

Forge 2092
Modlist: http://pastebin.com/aXWf0Cuq
Server launch: http://pastebin.com/gsyQ3YSb

Actually Additions: 1324
aroma1997 Core: 7, 86
Aroma1997sDimension: 96, 947
AromaBackup: 105
AutoRegLib: 126
AutoSapling: 135
AppleCore: 75-84
Baubles: 145
BetterAchievements: 163
BetterBedrockGen: 154
BetterFoliage: 8, 172
BetterSprinting: 182
BiomesOPlenty: 192
BloodMagic: 201
Botania: 210
Calculator: 219
Chameleon: 228
ChickenChunks: 237
Chisel: 1182
codechicken.core, codechicken.lib: 10 - 13
EnderIO: 249, 696, 1368, 1575
EnderStorage: 258
enchiridion: 1972
Evilcraft: 1179, 1382, 1970(actually cyclops core)
ExtraUtils2: 268
FloodLights: 278
Fluxed Redstone: 14
Forestry: 743 - might be TC fault
HoloInventory: 288
immersiveengineering: 578 - might be TC fault
Inventory Tweaks: 15
IngameAccountSwitcher: 298
InGameInfoXML: 308
IvToolkit: 16
JEI: 318
jurassicraft: 1969
LootBags: 1710 - STDERR - xxxKB of error logs, 1973
LunatriusCore: 328
MCA: 337
Morphtool: 348
Morpheus: 357
Neat: 366
nethercore: 375
OfflineSkins: 17, 376
OpenComputers: 378
OpenFM: 18
powerinventory: 386
Psi: 388
Quark: 19, 397
RadixCore: 406
Random Things: 20
roots: 1980
Roguelike: 415
SonarCore: 424, 980, 984
StorageDrawers: 433
Tconstruct: 578 - might be IE fault
TechReborn: 904
TinkersAddons: 442
trashslot: 450
UniDict: 452
VeinMiner: 461
Waila: 479, 1598
WailaHarvestability: 488
waystones: 497

**Comment by Ellpeck** [comment]
Do you mean the Crusher missing ores thing?

Uhm, that's just one output. It's a single line, and it's usually just for people that make modpacks and such.
So no, I'm not going to remove that one, sorry.

**Comment by C0rn3j** [comment]
Alright, np.
