### ISSUE TITLE
[Suggestion] Forestry canola?

### ISSUE THREAD

**Issue by UnNinja** [Ellpeck/ActuallyAdditions#254]
Would it be possible for you to add the ability to process canola via the forestry squeezer/still?

**Comment by Ellpeck** [comment]
I'll have to ask @mezz about that, as I recall that he told me the API was still going through a lot of changes and isn't really ready to be used much.
That might have changed, though.

**Comment by mezz** [comment]
The API for machine recipes is stable, go ahead.

**Comment by Ellpeck** [comment]
Great! Thanks :)

**Comment by Ellpeck** [comment]
I decided that I'm probably not going to do this as I don't think it's that good of a feature to have.
Sorry, but thanks for the suggestion though :)
