### ISSUE TITLE
AIOT bypassing harvest level

### ISSUE THREAD

**Issue by LemADEC** [Ellpeck/ActuallyAdditions#255]
As of ActuallyAdditions-1.10.2-r63, AIOT tools are bypassing harvest mining levels for modded ores.
For example, a wood AIOT can mine Silver ore from Druidry which normally requires iron+ level.

**Comment by LemADEC** [comment]
Is there a way to disable those from crafting?

**Comment by Ellpeck** [comment]
Yes, in the config.

**Comment by LemADEC** [comment]
It's actually named Paxels instead of AIOT
