### ISSUE TITLE
Planttech problems

### ISSUE THREAD

**Issue by Kaneka** [Ellpeck/ActuallyAdditions#257]
minecraft.curseforge.com/projects/planttech-first-buds/issues/8

**Comment by Kaneka** [comment]
fixed it, thanks a lot

**Comment by Mysteryem** [comment]
Nothing wrong with your code @Ellpeck, some of the biomes in Planttech didn't have any flowers, which meant that when your lush caves generator tried to make grass grow (https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/gen/WorldGenLushCaves.java#L65), it would lead to a crash when it tried to pick a flower to spawn on the grass block.

**Comment by Kaneka** [comment]
I removed the this.flowers.clear(). and changed plantflower instead, but I would recommend that you may check if the flowerlist is empty to avoid crashed like this
