### ISSUE TITLE
Add oil to ore dictionnary

### ISSUE THREAD

**Issue by demethan** [Ellpeck/ActuallyAdditions#259]
Would be nice if the oil could be burned in Advance Generators.

Just a humble suggestion.  Love the mod. keep up the good work.

**Comment by Ellpeck** [comment]
It is part of the fluid dictionary and it's called "oil".
That works for Buildcraft, Thermal Expansion and most of the other oil-consuming machines.
If that's not enough for Advanced Generators, then no sorry, I can't. :(

**Comment by demethan** [comment]
Ok thanks.. will post it on Advance Gen.
