### ISSUE TITLE
[Crash] Crash with worldgen

### ISSUE THREAD

**Issue by bondgb** [Ellpeck/ActuallyAdditions#262]
I've been running Actually Additions for a long time and never had a crash until today. I'm not seeing other mods in the list so I'm posting it here: https://gist.github.com/bondgb/6b21cbcf8d5ca6351d6c5d5b1acc75a7

It could be related to another mod though, as I've just added Minecolonies and updated Recurrent Complex to test it.

**Comment by Ellpeck** [comment]
This crash should already be fixed with one of the last few commits, so it'll be fixed in the next update! :)
