### ISSUE TITLE
[1.10.2] [Bug] Player probe spams chat

### ISSUE THREAD

**Issue by SnowShock35** [Ellpeck/ActuallyAdditions#265]
Hello,

I believe to have found a bug with Actually Additions for Minecraft 1.10.2, here are the details. . . 

### Important Information

* Minecraft 1.10.2
* Minecraft Forge 12.18.1.2094
* Actually Additions 1.10.2-r63

### Issue Description

In multiplayer clicking the player probe on another player seems to not only be delayed before you get an output but when you do get an output it spams the chat log. 

### Issue Media

![Issue Screenshot #1](http://image.prntscr.com/image/af60842c41f545b1847a43d614101f60.png)

**Comment by Ellpeck** [comment]
Already fixed.

**Comment by SnowShock35** [comment]
@Ellpeck Sorry. Was unaware that it was already fixed. May I ask, will there be a new build on CurseForge soon?

**Comment by Ellpeck** [comment]
Probably! :)

**Comment by SnowShock35** [comment]
Cool! Thanks a lot :-)
