### ISSUE TITLE
random crash while travelling the world

### ISSUE THREAD

**Issue by Hypsellis** [Ellpeck/ActuallyAdditions#266]
I got this crash randomly when I travel the world, not sure to know where it comes, but it seems that there are some problems of compatibility with Terraqueous. http://pastebin.com/A2XP1Bug

**Comment by BrisingrAerowing** [comment]
I'm getting the same issue.

**Comment by kwpugh** [comment]
Same issue here:  

https://gist.githubusercontent.com/kwpugh/b36f6812d43ef3b1d34e49d3f1607645/raw/176ee3b709cd754da18bcd8ed099b3d54216b6e7/ActuallyAdditions
