### ISSUE TITLE
Energy Laser Relay does not accept energy from generators, storage blocks, etc.

### ISSUE THREAD

**Issue by xbony2** [Ellpeck/ActuallyAdditions#267]
Or am I missing something?

**Comment by Ellpeck** [comment]
What have you tried it with? I can't reproduce this.

**Comment by xbony2** [comment]
Okay, so it works xD although The One Probe shows the Energy Laser Relay as storing no energy when hovered over, if or if not energy is flowing to it.

**Comment by Ellpeck** [comment]
Yes, because it isn't able to store any energy :)

**Comment by xbony2** [comment]
Hmm, I wonder if it's possible to make the energy storage bar disappear for that... might research.
