### ISSUE TITLE
Add option for completely disabling lush cave generation

### ISSUE THREAD

**Issue by BrisingrAerowing** [Ellpeck/ActuallyAdditions#268]
I don't really like the lush caves that much, but there isn't an option to disable them completely. Only the probability of them generating can be changed.

Could an option be added to disable their generation?

**Comment by Ellpeck** [comment]
There is an option for that, in the World Gen category.

**Comment by BrisingrAerowing** [comment]
I didn't see that in the old config I had, and a search for 'Lush' (without quotes) didn't find it. 😕 Weird.

I 'refreshed' my install by deleting the .minecraft folder, and the new config has it.

**Comment by BrisingrAerowing** [comment]
It appears that it does exist, but Notepad++ seems to skip the first instance of the search term for some reason. Odd.

Might as well check for an update.
