### ISSUE TITLE
[1.10.2] Loottable Crash caused by AA vers r64

### ISSUE THREAD

**Issue by Morpheus1101** [Ellpeck/ActuallyAdditions#269]
Testing the new update to the MMD -Dev server pack and SMP crashes on r64 of this mod, tested with r63 and it works fine.  crash log @ http://pastebin.com/EtaSC0ZR

Using forge *.2095

**Comment by Ellpeck** [comment]
The heck, I fixed this because this crash happened in r63.
But I guess the fix isn't one after all.

**Comment by Ellpeck** [comment]
Could you try to reproduce the issue with this version?
https://ci.chaosfield.at/job/ActuallyAdditions/job/ActuallyAdditions-unstable/139/artifact/build/libs/ActuallyAdditions-1.10.2-r64-139.jar

**Comment by Morpheus1101** [comment]
Everything seems fine, no crashes of any kind :)
