### ISSUE TITLE
Whatsthis!?!?!

### ISSUE THREAD

**Issue by b0bst3r** [Ellpeck/ActuallyAdditions#272]
16:02:40
 CONSOLE:
thread/INFO] [Actually Additions]: Creating new WorldData file for world -11325!
16:02:40
 CONSOLE:
thread/INFO] [Actually Additions]: Creating new WorldData file for world -9999!

**Comment by Ellpeck** [comment]
Uh, it's a console output.
How is this an issue?

**Comment by b0bst3r** [comment]
I wondered what these worlds are -11325 and -9999?

**Comment by b0bst3r** [comment]
urgh nevermind blonde moment
