### ISSUE TITLE
doesn't fully change the spawner to the new mob type.

### ISSUE THREAD

**Issue by DeathOfTime** [Ellpeck/ActuallyAdditions#274]
ActuallyAdditions-1.10.2-r65.jar
"pack": "Spilled Juice",
 "version": "0.2.2.1"

Used a spawner changer set to gaurdian on a rogue dungeon's(RoguelikeDungeons-1.10.2-1.5.4.jar) skeleton spawner. The spawner changed to spawn guardians. It didn't lose the settings for the rogue spawner. The gaurdians were dropping armor of the types normally dropped by the skeletons that the rogue spawner spawned before.

I have checked with others that use the pack and they don't believe guardians in the pack normally drop armor.

**Comment by Ellpeck** [comment]
Soooo... the mob changed, but its properties didn't?
Okay, that should be easily fixable.

**Comment by DeathOfTime** [comment]
no. it, it still dropped the regular guardian drops. It also dropped the armors. I think the armor added by the rogue spawner might actually be equipped to them by the spawner.

**Comment by DoomSquirter** [comment]
I've had this happen and made a ticket previously about same issue.  Any NBT data is carried over with spawner but vanilla spawners work just great (verified)
