### ISSUE TITLE
Wierd mod interaction with mekanism energy cubes

### ISSUE THREAD

**Issue by DoomSquirter** [Ellpeck/ActuallyAdditions#276]
So made a quintuple battery, set to charge items in inventory/hotbar, is enabled

grab up an empty ultimate energy cube from mekanism and it will fill 51.x million rf in about a second while using up very little energy from battery itself.

Tried with an EIO capacitor bank and didn't have any issues, same with draconic capacitor that was disabled to not charge anything.  it charged both of these items as expected.  It's just mekanism energy cubes.  

Used draconic capacitor to charge a mekanism ultimate cube and it worked as expected as well.  

Possibly seeing the ultimate cube as a basic one?  Maybe?  

Running  ActuallyAdditions-1.10.2-r66

**Comment by Ellpeck** [comment]
I have no idea what the heck is going on with Mekanism and its power system, but the only thing I know is that Actually Additions works with *every* mod that uses RF and Tesla, but it just doesn't with Mekanism.
I'd really love to try and fix it, but for one, Mekanism's code is a total mess, and also it is in such an unfinished and seemingly broken state that I don't really care about being compatible with it.

This might seem totally irrational, but I have had so many issues with Mekanism in the past that I reported to its author, with the result of them being either still broken and reported as being fixed, or being half-fixed but still broken enough to cause headaches.

I will close this issue for now, but I know about the bug and I will fix it at some point in the future.
Just not now. Sorry.

**Comment by DoomSquirter** [comment]
I can fully understand ur predicament.  Just wanted to let you know of the issue is all.  Appreciate the awesome mod btw, you and other modders are making 1.10 a blast to play with and I truly appreciate it.

**Comment by Ellpeck** [comment]
No problems! As I said, I'm still hoping this issue will be fixed soon-ish, as it's annoying to deal with when playing. :D

**Comment by b0bst3r** [comment]
Was thinking about this and wondering if there's anyway to blacklist the battery from charging Mek Energy cubes

**Comment by bezzaboyo** [comment]
I know this issue has been closed, but just wanted to add that I've noticed the same interaction with ender IO capacitors DOES cause energy duplication, though not on the scale of the mekanism cube (it's exactly 10x in the case of a double battery charging a Vibrant Capacitor Bank). 

Needless to say I'll be remembering to turn it off now c;

Tested with Actually Additions 1.10.2-r67 and Ender IO 1.10.2-3.0.1.120_beta

**Comment by Ellpeck** [comment]
So putting an Actually Additions battery into an EnderIO capacitor will dupe the power?
