### ISSUE TITLE
[1.10.2] Water Bowl not Compatible with Botania

### ISSUE THREAD

**Issue by SnowShock35** [Ellpeck/ActuallyAdditions#277]
Hello,

I believe I have found a bug with Actually Additions/Botania. Here are the details of the issue. . . 

### Important Information

* Minecraft 1.10.2
* Minecraft Forge 12.18.2.2099 (Recommended)
* Actually Additions 1.10.2-r66
* Botania r1.9-328

### Issue Description

So as it stands both of the mods add a Bowl of Water one places it in world and is used for some crafting applications I assume and Botania's one is used for filling the Petal Apothecary. However, as you can imagine when u right click water you're only going to get one or the other. Well since the Actually Additions one doesn't support putting water into the Apothecary it becomes a problem. I'm unsure if it's possible to remedy this your end however, thought I'd bring it up just to make you aware of it.

**Comment by Ellpeck** [comment]
Turn the ActAdd one off in the config.

**Comment by SnowShock35** [comment]
Does disabling it remove the item from being registered? If so I'd rather not disable it.

**Comment by Ellpeck** [comment]
No.

**Comment by SnowShock35** [comment]
Okay cool. Thanks @Ellpeck :)
