### ISSUE TITLE
Atomic Reconstructor doesn't transmute red mushroom to nether wart

### ISSUE THREAD

**Issue by Venom31** [Ellpeck/ActuallyAdditions#278]
Atomic Reconstructor doesn't transmute red mushroom to nether wart. Other recipes under "Reconstruction->Additional Recipes" chapter of the manual DO work though. Haven't found any option for that specific recipe in the config file, so I assume it's a bug.

Versions
Minecraft version is 1.10.2.
The mod version is 1.10.2-r65 (FTB HermitPack).
JRE version 1.8.0_101.
Windows 7 64 bit.

**Comment by Ellpeck** [comment]
Your Reconstructor needs to be full of power.
Is that the case?

**Comment by Venom31** [comment]
No. But it took 10 kRF for all other recipes. How would I know that is required???

**Comment by Ellpeck** [comment]
Through testing. Not everything has to be written down. Stuff can be achieved just by figuring out. That's what games are all about, right? ;)

**Comment by Venom31** [comment]
Right :). Just confusing behaviour ("how much RF do I need for this operation?"), never mind. Will be tricky to automate then, though...
