### ISSUE TITLE
Empowerer not working with any recipies

### ISSUE THREAD

**Issue by gerardguckian** [Ellpeck/ActuallyAdditions#280]
On the HermitPack from FTB, with Revision 65 and Revision 66

No particle effects and with the empowerer and recipes do not seem to work

In the setup below all 4 display stands are powered and fully charged, I have tried various configurations and order of placement of the items and nothing is working. Attempting to make an "Empowered Enori Crystal Block"

![2016-10-14_20 18 10](https://cloud.githubusercontent.com/assets/22844770/19399932/ceccc4d4-924b-11e6-85af-9b632828afa6.png)

**Comment by b0bst3r** [comment]
A question please as I'm using r66 (not with HermitPack) and this works no problem.

The item over the far right is that grey dye or gunpowder?

**Comment by gerardguckian** [comment]
Hi @b0bst3r 

Good spot, closing this off as it's working now :)

--
Gerry
