### ISSUE TITLE
Very low FPS with many Canola Press + Fermenter

### ISSUE THREAD

**Issue by codewarrior0** [Ellpeck/ActuallyAdditions#282]
ActuallyAdditions-1.10.2-r65.jar

An oil factory with 30 Canola Presses and 100 Fermenters drops my FPS from 90 to 4 when active.

I suspect it is because the canola press redraws the chunk each time it recieves an item, and both the press and fermenter redraw the chunk each time they process some fluid.

**Comment by Ellpeck** [comment]
They shouldn't.

**Comment by codewarrior0** [comment]
FWIW, this is on a multiplayer server. I don't know if it happens in single-player.

**Comment by Ellpeck** [comment]
At least in Singleplayer, I am unable to reproduce this issue. I placed 30 canola presses and 4 fermenting barrels around every single one. I activated all of them, and there is no more lag then before.

**Comment by Ellpeck** [comment]
TPS also doesn't drop.
Can you show me your setup?

**Comment by codewarrior0** [comment]
Can't show you a pic of the setup right now as the server is down for maintenance. But I can confirm there is now FPS drop in single-player, so it must only happen on a multiplayer server.

**Comment by Ellpeck** [comment]
That.. doesn't really make a whole lot of sense, but I guess I'll test that.

**Comment by codewarrior0** [comment]
This is basically what my setup looked like on the MP server. Getting 110 FPS in single-player (creative mode, with creative energy and item suppliers) with no observed slowdown. I also tried the setup you mentioned with only AA's blocks and some hoppers feeding canola into the presses, again with no slowdown. When the server comes back up, I'll try it again with only AA blocks and hoppers to try and rule out the conduits.

![image](https://cloud.githubusercontent.com/assets/307683/19413369/c6e3da3e-92c6-11e6-8959-3e6100a942ff.png)

**Comment by Ellpeck** [comment]
Yea, it might be the conduits because they cause lag pretty quickly on average or bad PCs. Also try removing the tank, maybe that's the cause.

**Comment by codewarrior0** [comment]
It's still a bit weird that the conduits would be dropping me to 5 FPS on the server, but not in single-player.

**Comment by Ellpeck** [comment]
Did you try the tank in SP though?
It'd also be weird if the fermenting barrels and presses would be dropping you only in Multiplayer.

**Comment by codewarrior0** [comment]
The picture above is in SP. No FPS slowdown while the setup is running. 

On the MP server, the tank is actually several chunks away and connected through a Mek entangloporter.

**Comment by Ellpeck** [comment]
Oh, I see.
Just try to figure out the differences between the MP and the SP setup and the things around it. Everything's helpful to try to find this issue.

**Comment by Ellpeck** [comment]
Any update on this?

**Comment by codewarrior0** [comment]
Sorry for the trouble.

I narrowed it down to the "Show Fill Level" upgrade on a StorageDrawer. Which should have been the first thing I checked, since I knew about https://github.com/jaquadro/StorageDrawers/issues/322#issuecomment-236106903.

**Comment by codewarrior0** [comment]
I also found out the presses and fermenters are a bit expensive to render, but that's mostly Forge's problem, not yours.
