### ISSUE TITLE
Some recipes don't work

### ISSUE THREAD

**Issue by Heroofsovngarde** [Ellpeck/ActuallyAdditions#285]
So, after spending literally hours trying to figure out how to build and power machines, getting the resources for EVERYTHING I need and creating everything. I tried making a redstone reception coil which apparently needs an entirely different mod that I'm guessing isn't up to date? It isn't working with 1.10.2 minecraft and 12.18.2014 forge. So, Im stuck. 
I gave up on the oil generator and fluid transposer and got to the coils. I made a basic and needed an advanced and the recipe doesnt work. Ive looked through the changelog for the update 6 days ago. Ive tried looking to see if this has been reported already. Through forums. Nothing there. I followed the recipe again. Tried exiting and reentering. Tried building it different ways and nothing works. Very sad and would love to know if the recipe on feed the beast is wrong or if Im missing another mod but Im sure Im not because the wiki says its apart of actually additions.

I also keep seeing screenshots of the blue manual having recipes and detailed descriptions and I can't figure out what to click on to view that...when I hold it "sneak" appears but when I do it says no info available so maybe thats my problem?

![2016-10-17_02 47 12](https://cloud.githubusercontent.com/assets/22881794/19429221/284f52d2-9414-11e6-8dcc-d411d92f84b2.png)
![2016-10-17_02 47 42](https://cloud.githubusercontent.com/assets/22881794/19429220/284e8618-9414-11e6-9e93-caebc2f487da.png)
![2016-10-17_02 47 54](https://cloud.githubusercontent.com/assets/22881794/19429219/284e1912-9414-11e6-9859-ad76e2962d87.png)

**Comment by tigier** [comment]
1.The reception doesn't belong in any way to actually additions(as far as I know).

2. The advanced coil is made by placing the basic one in the middle and surrounding it with 8 gold NUGGETS.

**Comment by Heroofsovngarde** [comment]
UGH thank you lol and yeah, I need thermal dynamics or something like that but its not updated I believe

**Comment by Heroofsovngarde** [comment]
Why I couldnt get it to work..wiki is wrong?
https://ftbwiki.org/Advanced_Coil

**Comment by tigier** [comment]
Np.
And wikis are rarely accurate enough to rely upon, so I would recommend installing just enough items to help you out.

**Comment by canitzp** [comment]
install JEI, it is good to look for recipes

**Comment by Ellpeck** [comment]
To view the booklet, you right-click it like any other item and then you can look at all of the chapters and pages and flip through them to see info about the items.
It works exactly like most other mod manuals, and it should be very intuitive and easy to understand usually :o
