### ISSUE TITLE
[Crash] Opening Actually Additions Creative Tab

### ISSUE THREAD

**Issue by AsmodeiXIII** [Ellpeck/ActuallyAdditions#286]
http://pastebin.com/uX7PuJXa

Tried to check out the mod in creative, but any time i open the tab, it crashes.
Am i missing something?

EDIT: Also happens when trying to see the items in JEI
Also Forgot to say, this is on r66

**Comment by canitzp** [comment]
one of your mods loads a to old rf api. update all your mods and it should crash again

**Comment by AsmodeiXIII** [comment]
I am a retard who had the 1.7.10 version of ender IO loaded. I am blaming
Curse's stupid download buttons, but don't get fooled, i pull this shit on
the regular.

Also you lied to me, i updated and it didn't crash, wth.

2016-10-18 1:55 GMT-04:00 canitzp <notifications@github.com>:
