### ISSUE TITLE
Adding bauble support to Wings Of The Bats

### ISSUE THREAD

**Issue by misterfixit** [Ellpeck/ActuallyAdditions#287]
pretty much what the title says, I was curious if you could add bauble support to the wings so I can equip them there instead of having them in my inventory.

**Comment by canitzp** [comment]
As far as I know Ellpeck don't want baubles support for any of it's items

**Comment by Ellpeck** [comment]
Sorry, I'm not really fond of baubles.

**Comment by misterfixit** [comment]
Fair enough, no harm in asking, thanks for the response.
