### ISSUE TITLE
Atomic Reconstructor - Quartz to Prismarine recipe not working

### ISSUE THREAD

**Issue by Balrog994** [Ellpeck/ActuallyAdditions#288]
Hi, as in the title I'm having troubles using the quartz to prismarine additional recipe.
Other additional recipies like sand to soul sand work fine, just this one seems to be not working.
This is actually doing nothing, the laser beam fires correctly but the quartz is not changed to prismarine.
If you need more information let me know :)

**Comment by Ellpeck** [comment]
Is the conversion happening near the wall that is hit by the beam?
It only works with items, too, and requires a lot of power in the Reconstructor :)

**Comment by Balrog994** [comment]
I have to try dropping the items near the wall then. Power is not a problem, the reconstructor is full and receiving 640rf/t via an EnderIO conduit. I'm dropping quartz (not blocks) in front of the reconstructor configured in pulse mode then giving a redstone signal via a button attached to the reconstructor. I'll let you know in a couple hours.

Thanks

**Comment by Balrog994** [comment]
Ok, my bad, near the wall the conversion worked correctly, so It's just a matter of distance from the impact point. I guess it would be a bit more intuitive if the check was made starting from the laser going toward the impact point for items, but anyway, it works as intended so... thanks for your help! :)

**Comment by Ellpeck** [comment]
It states in the book in red underlined text. So it's really very obvious ;P
