### ISSUE TITLE
Drill loses power when color is changed

### ISSUE THREAD

**Issue by AnZaNaMa** [Ellpeck/ActuallyAdditions#289]
not sure if this is intended behavior, but if you charge up the drill, then change it's color, you lose all the power in it. I'm playing on 1.10.2-r66

**Comment by Ellpeck** [comment]
Does this happen in a Vanilla Crafting Table?

**Comment by AnZaNaMa** [comment]
Yes. When you put it in the table, the outcome slot shows a full drill but
when you pick it up from the table it's empty

**Comment by Ellpeck** [comment]
Yea that doesn't make any sense
