### ISSUE TITLE
No worldgen on existing worlds.

### ISSUE THREAD

**Issue by Devestatio** [Ellpeck/ActuallyAdditions#291]
Your mod does not generate anything in the world on already existing worlds, need to add a retrogen option or make your stuff generate like normal on existing worlds.

We were looking forward to using your mod, but its not viable as we can't find any of your plants or world gen/spawn items.

**Comment by canitzp** [comment]
To find the new plants or black quartz ore you have to walk into ungenerated chunks and then everything is working. I don't know if Ellpeck want retrogen support

**Comment by Ellpeck** [comment]
No, as it's not normal Minecraft behavior.
It's normal to have to walk into new chunks to find new stuff. Sorry.

**Comment by Devestatio** [comment]
We have explored over 9000m worth of new chunks and NOTHING is spawning. So it has nothing to do with new chunks, you mod simply does not want to generate anything into the exiting world. Also we can't craft any of your items, they show up in JEI, but when we try to craft them nothing will give a finished product.

**Comment by canitzp** [comment]
your modpack have some serious issues if such things are happening. try to update everything and does ActuallyAdditions machines work in creative mode?

**Comment by Ellpeck** [comment]
Make a copy/backup of the world, and remove every mod except Actually Additions. Then explore new chunks. Does it still happen?
Try the same, but this time generate a new world without any mods installed. Then add Actually Additions and explore new chunks. Does it still happen now?

**Comment by Devestatio** [comment]
Sorry I didn't reply, have been busy with work. but to answer your questions yes it was on the server, I wouldn't post here is it was something that obvious. We went ahead and just started a fresh world and its generating fine, it's a shame your not willing to add retrogen.
