### ISSUE TITLE
Crusher blacklist not working

### ISSUE THREAD

**Issue by Rucoon** [Ellpeck/ActuallyAdditions#297]
The crusher blacklist seems to have no change on output.
Minecraft log:
http://pastebin.com/J1kTRnmw

Modlist:
ActuallyAdditions-1.10.2-r67
AdvancedRocketry-1.10.2-0.9.1
LibVulpes-1.10.2-0.1.5-universal

Configs:
AA: http://pastebin.com/WLPzQsQ5
All others are unchanged.

**Comment by Ellpeck** [comment]
That is very weird.
Judging by the Minecraft log, the things that you blacklisted didn't get added to the recipes.
Is the crusher still outputting them, though?
What about JEI? Is it still showing the blacklisted items as outputs?

**Comment by Rucoon** [comment]
Uses for iron ore show both dust types for both iron and gold and does not give AA dust for iron or gold. Gold ore seems to be giving AA dust so the black list is working for that.
(Sorry for the wait internet when down on Sunday.)

**Comment by Ellpeck** [comment]
So are you saying only the first thing on the blacklist is respected?

**Comment by Rucoon** [comment]
No, iron was number one on the list. Just to make sure I swapped gold to spot one and it had no change.
