### ISSUE TITLE
Phantomface and RefinedStorage

### ISSUE THREAD

**Issue by Towsty** [Ellpeck/ActuallyAdditions#299]
Not sure if this is because of something on your end or theirs, but it looks like (item) Phantomfaces do not work with RefinedStorage blocks. In particular, the Solderers. I tried a few different setups and things, but no dice. The Phantomface always has the error text about obstructions/range after linking with Solderers. Tested immediately beside, a few blocks away, no blocks between, and blocks between. No dice. 

No errors are thrown, logs are clear. 

Forge 12.18.2.2104
ActuallyAdditions 1.10.2-r67
RefinedStorage 1.1.3

**Comment by Ellpeck** [comment]
Hey @raoulvdberge, can you explain this? Do you do anything different than IInventory or IItemHandler Capabilities?
I'd love to try this, but somehow whenever I install RefinedStorage in my dev environment, it just crashes when I look at an item or block because something can't render properly :v

**Comment by raoulvdberge** [comment]
@Ellpeck It's because I'm using J8 lambdas all over the place, and the Forge deobfuscater or whatever it does doesn't like that in dev env. But the solderer blocks certain items from entering:

https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/com/raoulvdberge/refinedstorage/tile/TileSolderer.java#L47-L59

**Comment by Ellpeck** [comment]
But why would it show the obstruction error then? I don't know if you've ever used them, but they only show that if the inventory isn't compatible, so for the Item Phantomface that'd mean either not IInventory or no IItemHandler Capability :v

**Comment by raoulvdberge** [comment]
https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/com/raoulvdberge/refinedstorage/tile/TileSolderer.java#L196-L208

Should have the capability.

**Comment by Ellpeck** [comment]
Well I guess then this is on my side. Which isn't nice, because the Phantomface code is old and a whole big mess :D Thanks for the help anyways.

**Comment by Ellpeck** [comment]
@Towsty: If you have the time, please try it again with this build: https://ci.chaosfield.at/job/ActuallyAdditions/job/ActuallyAdditions-unstable/240/
(Just pick the one without any suffix!)
Both on normal chests and the solderers you had the problems with. Thanks a bunch!

**Comment by Towsty** [comment]
Forge 12.18.2.2122
RefinedStorage 1.2.3
JEI 1.10.2-3.13.2.360
ActuallyAdditions r70-240

Phantomfaces (and all other faces for that matter) work perfectly. Checked Phantomfaces using hoppers for item transfer. Checked them against Solderers, interfaces, crafter and regular chests. All working perfectly, thanks!

**Comment by Ellpeck** [comment]
Awesome! Thanks for testing for me :D

**Comment by Towsty** [comment]
Anytime, lookin forward to the release of this version. Thanks again!
