### ISSUE TITLE
Stone & better AIOTs have wrong mining level

### ISSUE THREAD

**Issue by Compegen** [Ellpeck/ActuallyAdditions#302]
It's important to note that this only happens on modded ores (stone can't mine diamond)
____
Stone and above AIOTs can mine higher than their supposed mine "tier"

Stone (tier-1) can mine cobalt (tier-4) from Tinkers' Construct & Draconium from Draconic Evolution (tier-3)

Iron (tier-2) can also mine these ores

Bug in-action: https://gfycat.com/DizzyHandmadeDingo

**Comment by Ellpeck** [comment]
Just to be sure of something I'm wondering: Try removing Tinkers' Construct and see if the issue persists.

**Comment by Compegen** [comment]
Stone AIOT can still mine incorrect tier even with tinkers' removed. 

(Tested on Draconium (tier-3) and Ruby from Tech Reborn (tier-2))

**Comment by Compegen** [comment]
To add as well:

In an isolated environment with only Draconic Evolution, Actually Additions, Waila, and Wawla...
This bug still persists
