### ISSUE TITLE
crashing issue with the Atomic Reconstructor

### ISSUE THREAD

**Issue by tonyrod15** [Ellpeck/ActuallyAdditions#303]
my game crashes as soon as i look at the block
i cant give u a detailed explanation because that's literally it i look at it and my game died
almost forgot to add its 1.10.2

[crash-2016-10-25_22.53.21-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/552430/crash-2016-10-25_22.53.21-server.txt)

[latest.txt](https://github.com/Ellpeck/ActuallyAdditions/files/552434/latest.txt)
(not sure if these can help you out but i added them anyways)

**Comment by canitzp** [comment]
Your Sterling Generator from EnderIO crashed the game, not the AtomicReconstructor. Try to update EnderIO and EnderCore
