### ISSUE TITLE
atomic reconstructor still crashes with coal gen

### ISSUE THREAD

**Issue by tonyrod15** [Ellpeck/ActuallyAdditions#304]
the atomic reconstructor crashes my game with the coal gen still and its from the mod i havent tried the oil gen but im pretty sure it will do the same thing

if u want crash reports and stuff tell me btw im using the 1.10.2-r67

**Comment by Ellpeck** [comment]
Everyone wants crash reports.
Always.

**Comment by tonyrod15** [comment]
alright ima reproduce the crash however if u download ur latest  67r i blieve u can do it ur self

**Comment by tonyrod15** [comment]
[crash-2016-10-26_14.06.30-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/556517/crash-2016-10-26_14.06.30-server.txt)

last time you said it was the sterling gen but this time it crashed while i was using its own power generation via coal generator

**Comment by Ellpeck** [comment]
Do you have Extra Utilities 2 in the pack?
If so, try removing that and see if that fixes the crash.

**Comment by canitzp** [comment]
Your forge enviroment loads a extra utilities mod for version 1.7.10. This crashes with 1.10. CLear you %appdata%/.minecraft/mods folder and try it again. Normally it is impossible that such things are happening, can you post a screenshot of the mods folder?
