### ISSUE TITLE
Item tooltips do not have digit separators for large numbers

### ISSUE THREAD

**Issue by mezz** [Ellpeck/ActuallyAdditions#305]
Numbers like 10000000 should be formatted with digit separators to make them easier to read, like 10,000,000 or 10.000.000 depending on locale.

**Comment by Ellpeck** [comment]
Should they?
See, I personally don't like that system, but I guess~

Is there an easy way?

**Comment by mezz** [comment]
I think you can just use `NumberFormat.getInstance().format(double)` and it will use the default locale automatically.

**Comment by mezz** [comment]
Separators help with questions like "about how much is this?": 
1000200040 
Is it over 100 million, 1 billion, 10 billion, 100 billion?

It's a lot easier to see the magnitude when you have separators: 
1,000,200,040
