### ISSUE TITLE
Spawner Changer One Time Use

### ISSUE THREAD

**Issue by richraid21** [Ellpeck/ActuallyAdditions#309]
No where in the in-game documentation says this item is one time use. Please update that. Very frustrated at the moment.

**Comment by Ellpeck** [comment]
Not everything needs to be mentioned in the manual, and this, in my opinion, is obvious enough not to be a problem.
Sorry.

**Comment by richraid21** [comment]
How is this at all obvious? It looks like and physically acts like a wand in the world. Wands don't disappear. It would take 10 seconds to add it to the in game book.
