### ISSUE TITLE
Client and server crash when greenhouse glass placed over magical crops in r10

### ISSUE THREAD

**Issue by kwpugh** [Ellpeck/ActuallyAdditions#31]
Hi,

There was no crash report on the server (it just hard stops), but with R10 loaded up, when a player gets near a crops that have greenhouse glass over top, both server and client crash.

We did not have any issues with the R8 version of the mod.

Regards,

Kevin

**Comment by Ellpeck** [comment]
Has already been fixed in https://github.com/Ellpeck/ActuallyAdditions/issues/30
