### ISSUE TITLE
Quick License Question

### ISSUE THREAD

**Issue by cjburkey01** [Ellpeck/ActuallyAdditions#310]
So, I'm currently working on a mod, and I saw your `FluidDraw` class, and I believe it would definitely help.  In the license, it is stated that I can use small pieces of code for other projects, but not classes.  I just wanted to make sure I was reading it correctly that I am, in fact, not allowed to use this class(unless I wrote it differently in my own way), in a project of my own.

**Comment by cjburkey01** [comment]
If not, it's totally fine, but it would be slightly easier to have it as a util class.

**Comment by Ellpeck** [comment]
FluidDraw? I don't know which class you mean right now :o

**Comment by cjburkey01** [comment]
Oops, I meant ActuallyAdditions/src/main/java/de/ellpeck/actuallyadditions/mod/inventory/gui/FluidDisplay.java, not FluidDraw lol.

**Comment by Ellpeck** [comment]
Mention in the class that I made it and link back to this repository.

**Comment by cjburkey01** [comment]
Sure thing, thank you so much.
