### ISSUE TITLE
Possiably Actually additions

### ISSUE THREAD

**Issue by DnTheMn** [Ellpeck/ActuallyAdditions#312]
im on a bug fordwarding spree! 
https://github.com/whatthedrunk/allthemods/issues/226
https://github.com/gcewing/ArchitectureCraft/issues/6
probably not your fault but on the topic of ghasts does you mod decrease spawn rates

**Comment by Ellpeck** [comment]
No, it doesn't decrease rates.

**Comment by Ellpeck** [comment]
I don't see how this would be my problem. It seems like an unchecked cast by that other mod.

**Comment by DnTheMn** [comment]
hey guys this is completely fine that you say its not your mods fault i understand that it mentioned actually additions ghast in the reports so i saw no harm in opening an issue here if you feel its nothing you can solve due to it being another mods fault just close this report and well leave it at that no harm in reporting it i also reported it to architecture craft thanks for your time :)
