### ISSUE TITLE
Empowered Oil in world Mismatch?

### ISSUE THREAD

**Issue by Towsty** [Ellpeck/ActuallyAdditions#313]
I'm not 100% sure what to call this. I'm working on an automated system for empowered oil, its been a fun challenge. Everything is going well until the importing of empowered oil. Any time I try and filter the picking up of empowered oil, the filter created using the bucket does not seem to match the actual fluid on the ground.

For example:
![image](https://cloud.githubusercontent.com/assets/5897643/19879262/ea4670f4-9fbe-11e6-897c-e201ed68dc48.png)

There are two RefinedStorage constructors (top and side)
The top one places the Oil, the side one places a crystallized canola seed.
The destructor  on the bottom picks up only the crystallized oil.

This works pretty flawlessly. So I setup the same thing for empowered oil. But it does not work flawlessly. 

![image](https://cloud.githubusercontent.com/assets/5897643/19879317/68c34826-9fbf-11e6-824b-871d17a8f9eb.png)

With literally the exact same setup it will not pick up the empowered oil. I've tried this a few different ways now. Even using the fluid collector from ActuallyAdditions, while it will pick up fluids, if I try and filter a pipe or importer to pump only empowered oil out of the collector (or out of an adjacent tank that the oil has been output into) it does not pump anything out. It appears as though it does not match the filter. 

I'm not sure if this is a bug or intended or something else. Happy to give any other info.

Forge 2116
ActuallyAdditions r69
RefinedStorage 1.2-beta-5

**Comment by Ellpeck** [comment]
This doesn't make any sense to me.

**Comment by Ellpeck** [comment]
So what you are saying is: Filtering, via whatever filterable device, Canola Oil, Oil or Crystal Oil works fine, but Empowered Oil never matches its filter?

**Comment by Ellpeck** [comment]
If you have  more mods than the ones listed installed, just try removing them. It might be some weird conflict. With Minecraft, you never know. :v

**Comment by Towsty** [comment]
Okay, so stripped down to just Refined Storage, ActuallyAdditions, and Forge. All same versions, the exact same setup, works perfectly. I'm going to start digging around some more to figure whats happening in my pack then. Its probably safe to close this now. Thanks for checking in!

**Comment by Ellpeck** [comment]
That's awesome. If it still appears to be a bug with Actually Additions, just reopen this.
Also, check your log, there might be something in there about fluid registries or something. :)
