### ISSUE TITLE
Can't upgrade Drill, Atomic Reconstructor problems, etc. (MC 1.10.2, Mod r69)

### ISSUE THREAD

**Issue by huzo111** [Ellpeck/ActuallyAdditions#314]
First of all, I really love your mod and thats why I really wish these problems could be fixed:

Drill: Right-clicking does not open the  Upgrade GUI for me => I can't upgrade it so.

Atomic Reconstructor does not work on many places. You turn it on, the laser shoots, but the drops dont get changed to the desired ones. Maybe has something to do with the coordinates?

Empowerer: Sometimes I can not take out the empowered item from the empowerer. I have to destroy it first to get the item.

Leaf Blower: Why does this one not require any kind of energy? That should be changed.

Oil Generators: They always use up all of their energy. Even if there is no device consuming. They should be able to save it up. Oil Generators are a cool and easy way to get lots of energy fast and cheap, but they are just not able to save up the energy and be able to used in a constant setup.
-------------------

Also I have some suggestions:

* The ability to use batteries instead of static energy in any device.
* Jetpack (instead of the overpowered bat wings?). I like the one in IC2, it seems very balanced.
* More electric tools. 
-------------------

Also, in general I think many things in this mod are way too overpowered. The Emeradic armor for example, the bat wings, the teleportation device

**Comment by Ellpeck** [comment]
Sneak-right click the Drill.
The Reconstructor needs to hit a wall, the items need to be inside of the white sparkling area. Also, as it says in the book, a lot of recipes require additional power. Try every recipe with the Reconstructor 100% filled with power.
You need an empty hand to take items out of the empowerer.
The leaf blower can't be changed just by how the way NBT and item usage works.
What? They don't use up all their energy. Once the buffer is full, they stop generating.

**Comment by huzo111** [comment]
Thanks for your answer.

I've tried everything out with the drill, even giving myself all kinds of the drills in any color, loaded, not loaded, but I have never tried to sneak while right clicking^^ Anyway, it doesn't say that in the book either.

I guess you should describe things better in the book.

Anyway, keep up your god work. Love your mod, and again: A jetpack would be cool ;)
