### ISSUE TITLE
Method for easily filling (& clearing?) sections of land

### ISSUE THREAD

**Issue by garantiertnicht** [Ellpeck/ActuallyAdditions#316]
A Block or Wand wich allows filling of Block sections, allowing quicker Building or clearing out of land. The Tool should be survival friendly (you need the blocks you want to place / energy or tool durability to destroy), and have (configurable?) limits to prevent griefing or performance issues.

**Comment by Joshwoo70** [comment]
sounds like a good idea... could be inspired by the terraformer from IC2.
