### ISSUE TITLE
Better (faster/stronger) magnet

### ISSUE THREAD

**Issue by YasminEndusa** [Ellpeck/ActuallyAdditions#317]
I feel the magnet still has some problems, mainly speed and range.  
The range is only a small problem, having a larger range is more a nice-to-have.  
The speed however is too slow. When i have items that a magnet needs to pick up and they are following me slower then i walk or fly, that magnet does not do a good job.

So i suggest to either add an upgraded version of the magnet or adding magnet upgrades for speed and range which affect the energy used.  
Maybe even the possibility to "warp" items directly in the players inventory, even through walls, when there is enough space in the players inventory.

**Comment by Ellpeck** [comment]
HARDER
BETTER
FASTER
STRONGER
