### ISSUE TITLE
Suggestion For the Drill.

### ISSUE THREAD

**Issue by HeavyDeception** [Ellpeck/ActuallyAdditions#319]
Could you add a Fortune 3 and silk touch upgrade for the drill were you can switch between the 2 in your hand.

Same for the size a way to change back to a single block and to a 3x3 or a 5x5.

I guess adding or removing the upgrade would work be having a hot key or a right click would be great.

**Comment by Ellpeck** [comment]
No, sorry. If you want silk touch and fortune seperately, just make two drills! :D

**Comment by HeavyDeception** [comment]
Would you kill me to ask why. Just wondering. Also have something to report about the magnet ring but I need to test some stuff for that first.

**Comment by HeavyDeception** [comment]
Ignore me asking why can't delete it on my phone.

JesseC.

**Comment by HeavyDeception** [comment]
This makes me sad but on be on of many modes that do that.......... Great mod still. Keep up the good work.
