### ISSUE TITLE
Negative Energy in GUI

### ISSUE THREAD

**Issue by MrRiegel** [Ellpeck/ActuallyAdditions#320]
![2016-11-04_17 48 32](https://cloud.githubusercontent.com/assets/13290261/20014403/20dfb59e-a2b7-11e6-831b-fb34d8141cdf.png)

after inserting some stuff into the reactor it is fine

**Comment by canitzp** [comment]
I have seen something in other mods, like Cyberware. Maybe it is a minecraft/forge syncing issue

**Comment by Ellpeck** [comment]
Is it the syncing or the actual energy amount? Don't really know how you'd figure out, but maybe you did.

**Comment by Ellpeck** [comment]
Please try to reproduce this with just Actually Additions installed.

**Comment by MrRiegel** [comment]
Sorry, I can't even reproduce it with other mods.
Maybe the problem only on servers.

**Comment by Ellpeck** [comment]
It's never happened to me before. Does it happen with other blocks?

**Comment by canitzp** [comment]
TUMAT has shown such things in my HL2 modpack at the Cyberware charger

**Comment by Ellpeck** [comment]
Closing this as it doesn't appear to be caused by Actually Additions.
