### ISSUE TITLE
Odd Crash with Achievements

### ISSUE THREAD

**Issue by ozhound** [Ellpeck/ActuallyAdditions#321]
Hi Ellpeck

Can you take a look at this error log and provide some feedback?

https://paste.ubuntu.com/23426549/

**Comment by Ellpeck** [comment]
Oh, yea. This is a common thing. If you scroll too high up or down or left or right in the Achievements GUI, you will just randomly crash. I can't do anything about that either sadly :(

**Comment by ozhound** [comment]
Damn, thanks for the feedback.
