### ISSUE TITLE
Make Farmer be able to plant Multiple Plants

### ISSUE THREAD

**Issue by garantiertnicht** [Ellpeck/ActuallyAdditions#322]
The Farmer is currently only able to plant one sort of plant for a whole field (https://github.com/Ellpeck/ActuallyAdditions/blob/11b7ecb172f0647a22582b7d6909c3742fcaa3d8/src/main/java/de/ellpeck/actuallyadditions/mod/tile/TileEntityFarmer.java#L152-L179). I think It would be quite usefull if the Planter can plant multiple plants, maybe in a simmilar way that dispensers/droppers shoot out items.

**Comment by Ellpeck** [comment]
No, sorry, I don't want this feature for the Farmer. Yes, it would be useful, but I prefer if they just use multiple ones :) It's not like they're super expensive or anything :P
