### ISSUE TITLE
[bug] compost deletes items

### ISSUE THREAD

**Issue by Inve1951** [Ellpeck/ActuallyAdditions#324]
picking up fertilizer from compost deletes item currently in hand
happened with TConstruct tools (shovel and pickaxe)

i also use [Client Tewaks](https://github.com/blay09/ClientTweaks)' torch placement option, might matter

**Comment by Ellpeck** [comment]
I can't reproduce this. Please try with just Actually Additions.

**Comment by Inve1951** [comment]
it's generally weird how you receive the fertilizer
imo it should just add it to the inventory like it was picked up or drop the fertilizer for picking it up

also when looting multiple composts in a row looting works fine with the looted fertilizer in hand but when attempting to loot it with fertilizer in hand from other source then it won't

**Comment by Ellpeck** [comment]
What do you mean "with fertilizer in hand from other source"? Explain exactly what you did to produce this error please.

**Comment by Inve1951** [comment]
when it deleted the tinker's construct tools i just had those selected when i looted the compost.

when it won't allow looting with fertilizer in hand then i switched slots inbetween last time looting and this time, did use some fertilizer acquired from last loot, or generally reorganized the inventory.
it only allows looting with empty hand or freshly acquired fertilizer. (not even bio mash works)

the way looting the compost is implemented it's asking for incompatibilities and also isn't user friendly.

**Comment by Ellpeck** [comment]
What?
Is there a bug now or is there none? This isn't about "user friendliness", it's about the issue you were allegedly having. 
So you right-clicked with Tinkers' tools and that gave you fertilizier and deleted the tools, but that doesn't happen with any other items in hand, correct?

**Comment by Ellpeck** [comment]
Because I can't reproduce that.

**Comment by Inve1951** [comment]
aight, i've tested it again and it seems to only replace the selected item when using client tweaker's torch-from-hotbar option.
my best guess is that client tweaker shuffles around the items to provide that functionality and that there's a race condition with actually additions checking the selected slot and filling it with fertilizer.
yes there is a bug.
i guess you want this reported over at client tweaker too so i gonna open an issue there now.

**Comment by Ellpeck** [comment]
Yes, this is most likely a Client Tweaker issue - Which is weird, but okay.
