### ISSUE TITLE
AIOT does not act as an axe when Better With Mods is installed.

### ISSUE THREAD

**Issue by garantiertnicht** [Ellpeck/ActuallyAdditions#326]
When Better With Mods is installed, the AIOT mine the log quickly, but it drops Planks, Barks and the Wood Dust Thingy. Issue at Better With Mods: https://github.com/BeetoGuy/BetterWithMods/issues/110

**Comment by Ellpeck** [comment]
What's the intended behavior though?

**Comment by garantiertnicht** [comment]
Better With Mod fixed it, so im going to close this issue.
