### ISSUE TITLE
support for Tough As Nails

### ISSUE THREAD

**Issue by Hypsellis** [Ellpeck/ActuallyAdditions#329]
It would be awesome to add a support for Though As Nails with all the drinks that would restore thirst.

**Comment by Ellpeck** [comment]
How would that work? Like, what does the mod do?

**Comment by Hypsellis** [comment]
I suggest to go to see to the mod wiki https://github.com/Glitchfiend/ToughAsNails/wiki. After if you want to know more, you can still ask to the devs. ;)

**Comment by Ellpeck** [comment]
Sorry, this doesn't really seem worth the times, as there's little drinks in the mod.
