### ISSUE TITLE
Filler should ignore the Facing/Turning of the blocks when looking for them in the inventory

### ISSUE THREAD

**Issue by garantiertnicht** [Ellpeck/ActuallyAdditions#330]
Now, you can not fill an area with logs facing sideways. It would be somewhat more usefull if the checking would ignore attributes such as axis, rotation, facing, maybe others. Would need some additionaly checks in https://github.com/Ellpeck/ActuallyAdditions/blob/add64ce9ea054711d7b1707905aae2a1722d2dd7/src/main/java/de/ellpeck/actuallyadditions/mod/items/ItemFillingWand.java#L212.

**Comment by Ellpeck** [comment]
This would be a pain to implement by the way BlockStates work, and I don't think it's really worth the effort. Sorry.
