### ISSUE TITLE
Water Bottle fills Coffe Maker by 1,000 mb

### ISSUE THREAD

**Issue by garantiertnicht** [Ellpeck/ActuallyAdditions#333]
The Water Bottle fills a couldron by only 3rd of a bucket, but if put into a Coffe Maker, it gets filled with the same amount as with a bottle, wich is 2/3rd more then its value is. Maybe it should only recieve about 333 mb.

*Sorry for the issue spam :)*

**Comment by Ellpeck** [comment]
That's not a bug. A Water Bottle, according to the Forge Fluid Dictionary, contains 1000mb.

**Comment by garantiertnicht** [comment]
Seems wierd... but ok.
