### ISSUE TITLE
Actually Additions together with Industrialcraft 2 Experimental

### ISSUE THREAD

**Issue by huzo111** [Ellpeck/ActuallyAdditions#337]
When using the mod together with IC2, you can't turn Diamond Dust back into Diamonds again. The ability to seems to be overwritten bei IC2. Don't know if this can be fixed.

A similar thing appears to solidified Experience, EXP doesn't go up when consuming it when the mode is being using together with IC2.

**Comment by Ellpeck** [comment]
The first thing can be solved by putting the dust onto the blacklist in the config.
The second one: You're probably too close to the Solidifier, meaning it picks it right back up again.

**Comment by huzo111** [comment]
Which config, and how do I do it?

**Comment by Ellpeck** [comment]
You go into the Config GUI and look into the "Other" tab. There, you will find it :) Hover over the text to see how it works.

**Comment by huzo111** [comment]
Thank you ;)
