### ISSUE TITLE
[1.10.2] [Discussion] Underground Biomes

### ISSUE THREAD

**Issue by SnowShock35** [Ellpeck/ActuallyAdditions#343]
Hi Ellpeck,

First off, apologies for the lateness of my message. I know I said I'd try get around to you as soon as, but like normal lots of things got in the way. 

So I just wanted to discuss a bit about the underground biome constructs e.g. ![](http://ss.snowshock35.com/2016/11/1478646467-82d18842.png) As you can probably see from the provided screenshot they're a little odd in how they generate currently. I'm not entirely sure how you're doing it but currently it doesn't remove everything when it clears the space to be replaced by grass etc. It would be nice if it checked for any block in that space and to remove it so it's not filled with floating blocks and other blocks like the chisel ones there. 

This is only a suggestion and I'd be interested to see what you have to say about it yourself. 

Kind Regards,
Snow. 😃

**Comment by tigier** [comment]
Could it be that chisel blocks generate after the room was cleared for the cave?

**Comment by SnowShock35** [comment]
What about the vanilla gravel? Either way, it should probably have an additional check for things.

**Comment by tigier** [comment]
The gravel could just have generated normally but the cave cleared the blocks beneath it so it dropped down....cause gravel

**Comment by SnowShock35** [comment]
Yeah that's more than likely what did happen. Still something I'd like to hear @Ellpeck 's input on :)

**Comment by Ellpeck** [comment]
Yes, I feel like the chisel stones generate after, because I clear everything that's in the way.

**Comment by SnowShock35** [comment]
Took almost a year but finally fixed in 2d3e90068fdc37f1de5eb3fe791f636a4462f858
