### ISSUE TITLE
[1.10.2] [Compatibility Issue] Growth >  0% on plants displays missing texture in Waila

### ISSUE THREAD

**Issue by SnowShock35** [Ellpeck/ActuallyAdditions#344]
Hi,

I believe to have found an compatibility issue with Actually Additions for Minecraft 1.10.2

### Important Information

- Minecraft 1.10.2 
- Minecraft Forge 12.18.2.2120
- Actually Additions 1.10.2-r70
- Other Mods:
  - Waila 1.7.0-B3

### Issue Description

Whenever any of the actually additions plants have a growth > 0% waila displays the tile icon as a purple and black texture (Missing texture icon). I have a feeling this isn't on Actually Addition's side but I'm just being cautious by reporting this anyway.

### Issue Media

![Issue Media #1](http://ss.snowshock35.com/2016/11/1478649181-f8fc18cb.png)

**Comment by tigier** [comment]
Dieses Problem wurde bereits gemeldet und zu kenntnis genommen:https://github.com/Ellpeck/ActuallyAdditions/issues/332#event-849147848

**Comment by SnowShock35** [comment]
No problemo :)
