### ISSUE TITLE
online wiki dead

### ISSUE THREAD

**Issue by leasoncre** [Ellpeck/ActuallyAdditions#345]
the online wiki is currently dead. forget to renew domain/web-services?
ellpeck.de/actaddmanual/

**Comment by leasoncre** [comment]
https://gyazo.com/7d05c31acc201f3ea278a9ec7ecff408

**Comment by canitzp** [comment]
The ellpeck.de homepage and the online manual are working fine for me

**Comment by Ellpeck** [comment]
Me too now. According to the hoster, it was fixed, and that's why I closed it.
Maybe something with your DNS?

**Comment by leasoncre** [comment]
i use google DNS. it might be a region issue? i'm in the US

**Comment by leasoncre** [comment]
yep. seems to back up now yay!
maybe it was delayed. (DNS server synchronizations)
