### ISSUE TITLE
Farmer Doesn't respect other mods soil

### ISSUE THREAD

**Issue by RenegadeElement** [Ellpeck/ActuallyAdditions#347]
Playing hermitpack 1.3
Soil is random things fertile dirt(edit soil. Farmer doesn't plant on modded dirt. 
For reference random things dirt works just fine with the ender io farmer included in the pack. so it is not on random things side

isn't there a bunch of forge calls for this? something some iplantable

**Comment by garantiertnicht** [comment]
This should be a fixed in https://github.com/Ellpeck/ActuallyAdditions/commit/66aec5cfdfe287762b35d065d4d06463055f9fac wich is intended to fix #346 and will likly be included in r71. Dont qoute me :)

**Comment by Ellpeck** [comment]
It is correct, yes.
