### ISSUE TITLE
[Suggestion] Add Crafting Table that retains inventory and can craft from all inventories it is attached to

### ISSUE THREAD

**Issue by Saphrym** [Ellpeck/ActuallyAdditions#349]
Add Crafting Table that retains inventory and can craft from all inventories it is attached to

**Comment by garantiertnicht** [comment]
Like the one from Tinkers Construct?

**Comment by Saphrym** [comment]
Yes. But without having to install TiCon. And I figure it can take advantage of the relay system.

**Comment by Shadowhunter82** [comment]
It would be nice to have a terminal like in EnderIO to access the items in the relay system

**Comment by KitKat31337** [comment]
Tcon Crafting Station next to an Item Relay does this already.

**Comment by YasminEndusa** [comment]
@KitKat31337 as you can see in Saphryms comment, the plan is to not install TCon ;)

**Comment by KitKat31337** [comment]
I saw that, but adding to one mod, something another mod already does....  I want TCON but I dont want TCON add it to a different mod.....

My point should become clear.

**Comment by YasminEndusa** [comment]
To make a counterargument: Why then, tell me, are there so many mods that have solar panels as a means of RF production?

**Comment by garantiertnicht** [comment]
Also, TConstruct + Item Interface is bugged out.

**Comment by Ellpeck** [comment]
This suggestion has already been approved as you can see by the labels. Please don't discuss it in here.
