### ISSUE TITLE
Weird Bug with Assembly Table and other Recipes

### ISSUE THREAD

**Issue by Watschman** [Ellpeck/ActuallyAdditions#35]
Da ich weiß das du Deutsch sprichst beschreib ich den Bug in Deutsch.
In meinem Modpack (Watschman's Questing Pack, Technic Launcher) verursacht Actually Additions einen komischen Bug wo Chipsets und einige andere Rezepte mit dem Achtfachen material angezeigt werden  Das komische ist im SinglePlayer benötigen die Rezepte auch diese Anzahl an Materialien und im Multiplayer nicht. Ich war nicht in der Lage dieses Problem mit entfernen und neu hinzufügen über Minetweaker zu lösen. Wäre froh wenn dem Problem mal nachgegangen werden kann. Installierte Version: ActuallyAdditions-1.7.10-r15 
Modliste gesamt: https://docs.google.com/spreadsheets/d/1IeEqce2KoZoAoa6eL_Ghtv9GVJgoiho8cf42myipm84/edit?usp=sharing

**Comment by Watschman** [comment]
/edit
tried version ActuallyAdditions-1.7.10-r16  - does not solve the issue

**Comment by Ellpeck** [comment]
Why are you so sure it's ActuallyAdditions causing the issue?

**Comment by Watschman** [comment]
because I removed Actually Additions and it was shown properly, my derp forgot to show the picture:
https://www.dropbox.com/s/l2c59qe9t1oy58w/Times%20Eight.png?dl=0
but it seems you figured it out already.
