### ISSUE TITLE
Crash on rendering Lamp bit from Chisels & Bits in Enchiridion editor

### ISSUE THREAD

**Issue by kd8lvt** [Ellpeck/ActuallyAdditions#351]
When in the Enchiridion item selection menu (to choose an item for a recipe element or item display element in the book editor) when scrolling through the bits from Chisels & Bits (as there is no search function) I crash and get this error log: [https://gist.github.com/kd8lvt/95d95d420de5001bc950ef5cf864dd38](https://gist.github.com/kd8lvt/95d95d420de5001bc950ef5cf864dd38)

It only crashes the client, not the server (I wouldn't expect it to crash the server, but it's good to know)

I'm not sure if this is Enchirion's fault, it very well could be, as they are the ones really doing the rendering, but, I wasn't sure so posted it here. Sorry if it's on the wrong mod's issue tracker, as I'm not sure where the root of the problem is. Figured the mod that the main block originated from is probably where I should put this. If this is the wrong issue tracker, I can put this elsewhere.

**Comment by kd8lvt** [comment]
Here is the full game log, I forgot to add that, just came home from school:
https://gist.github.com/kd8lvt/6f4e235b01c6431baaa2c3756b8a32db[https://gist.github.com/kd8lvt/6f4e235b01c6431baaa2c3756b8a32db](url)

**Comment by Ellpeck** [comment]
This absolutely doesn't make any sense. What even is the "Enchiridion Editor"?

**Comment by kd8lvt** [comment]
Enchiridion is a mod that lets modpack makers make books for their modpacks ingame, its like HQM, but without the quest aspect

**Comment by Ellpeck** [comment]
So what exactly is causing the crash? :o

**Comment by kd8lvt** [comment]
When scrolling down the list of items, and going through the Chisels and Bits items (because you have to scroll, there is no search bar) it crashes. The error log talks about your lamps, as well as C&B, so I figured that's the issue

**Comment by canitzp** [comment]
I do more think that this is related to, cause chisel and bits does render the lamps and this is why it crashes. does this happenes to if you chisel a actually additions lamp?

**Comment by kd8lvt** [comment]
Let me check, I need to launch the game again lol

**Comment by kd8lvt** [comment]
Thirteen minutes later -> It seems to be that chiseling a lamp manually is fine (though I only tried it on the white lamp) whether it be on or off.. Maybe it is Enchiridion's fault?

**Comment by canitzp** [comment]
no chisel¬bits render it, it isn't enchiridon. can you report it to chisel&bits

**Comment by kd8lvt** [comment]
Alright, will do. I'll just reference this, so all the 'figuring out of things' we've done here isn't repeated there :)
