### ISSUE TITLE
Farmer doesn't harvest and replant sugar cane or nether wart.

### ISSUE THREAD

**Issue by RenegadeElement** [Ellpeck/ActuallyAdditions#352]
Found another thing about the farmer, 
Farmer doesn't harvest and replant sugar cane, cactus or nether wart.

**Comment by Ellpeck** [comment]
It isn't supposed to do sugar cane or cactus, as you can read in the manual.
Nether wart wasn't fixed in a release yet, but has already been as said in the previous issue.

**Comment by RenegadeElement** [comment]
https://snag.gy/12HICQ.jpg
I did read the manual. no mentioning of not working with block crops.

**Comment by Ellpeck** [comment]
"crops like Wheat, Potatoes, Canola and more" is referring to exactly that - but you're right, maybe it's not worded clearly enough.
Though, to be honest, I don't consider sugar cane and cactus a "crop".

**Comment by RenegadeElement** [comment]
other farmers from other mods do, sugarcane is fairly standard, cactus is less often implemented.

**Comment by Ellpeck** [comment]
I know they do, but I didn't design this farm to be able to do it. I might tweak the description a little though to make that clear :)

**Comment by garantiertnicht** [comment]
@RenegadeElement Bit late, but If someone (or you) wants Sugercane/Cactus Farms, the long-range breaker is suited for that *perfectly*
