### ISSUE TITLE
Player Laser Relay

### ISSUE THREAD

**Issue by garantiertnicht** [Ellpeck/ActuallyAdditions#356]
On Servers, getting from one place to another is something thats often needed. I think of a Laser Relay Network wich can be used in the endgame to teleport yourself around quickly would do a good job in that and intigrate well with the mod. Maybe you could use *Player Interfaces* (Better name needed; I do not mean that one existing already; more something like the Item Interface used with Item Laser Relays) and *select* (Thats something I don't know how to do right, a simple GUI may not fit to well in the mod and something like waypoint-overlays meight more difficult to do) your destination you want to travel to. Other things that need to be considered are:
* It might be a little OP, so it must have a running cost (Like RF) or be difficult to make (Like Obtaining rare items, see Bat's Wing)
* I don't sure how Networks are implimented, it could be difficult to get around the unloaded chunks problem.

*Yes, I do know this is more them an average Feature Reuest, but I thougt it would fit the mod (its not the one-block-for-everything solution and is an Actually Additions people would use) so* ¯\_(ツ)_/¯. *Simply close the ticket if you dont like it or think thats not worth the time implementing it.*

**Comment by Ellpeck** [comment]
I was thinking about something Luminizer-esc for some time now, so maybe I'll do something like this.

**Comment by Quaiby** [comment]
Ok, It's was silly to create new issue, sorry :)
It's a system:
We place travel anchors (telepods or etc.) and connect they with player laser relays. Now we can travel between anchors with travel rod without spending energy.
But we can place teleport processor next to any anchor and connect RF to it. Then we need to right click with travel card on each anchor and insert it into processor (I think it will be simplest way). And for end - place travel monitors on each anchor.
Now all saved to card and linked with player lasers anchors will be visible in GUI of any travel monitor. We select desired anchor and system teleports us to it with spending some energy from processor.
Or thousand simply without processor and cards but with monitors :)

**Comment by darkshadow543** [comment]
Heres an idea, like energy transfer, some of your experience disappears.  Not much, but enough to have a noticeable impact.  The idea is that the moving of the player results in the loss of some "memories," since we are deconstructing and then reconstructing, but not perfectly.  Other ideas along the line include ender pearl damage, or loss of hunger.  Going to an unpowered "receiver" will result in, if there is no other powered "receivers", death, with items either dropped along the laser line or dropped at random "receivers".   All experience is lost in this case.  If there is a powered "receiver, the system safe guards you to that one.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
