### ISSUE TITLE
Add ore->gem crushing

### ISSUE THREAD

**Issue by Saphrym** [Ellpeck/ActuallyAdditions#359]
Add ore->gem crushing

**Comment by Ellpeck** [comment]
Add ore->gem crushing

**Comment by Saphrym** [comment]
Add ore->gem crushing

**Comment by Joshwoo70** [comment]
as4d ore --> DUST crushing...

**Comment by Ellpeck** [comment]
What? Why? That's been a thing in the mod for more than 1 1/2 years..!?
