### ISSUE TITLE
Tiny Charcoal recipe conflict with Charset

### ISSUE THREAD

**Issue by xenoflot** [Ellpeck/ActuallyAdditions#362]
Hi,

Discovered a recipe conflict with your Tiny Charcoal recipe and Charset's Graphite. Both are shapeless with a single piece of charcoal in the crafting grid. Since Charset has been around a long time, perhaps you could change your recipe to a shaped recipe? (not sure if that would resolve the conflict...)

AA 1.10.2-r71
Charset 0.3.0-pre15

Cheers!

**Comment by Ellpeck** [comment]
I don't understand why people always use the "the other mod has been around longer" excuse. In fact, Actually Additions has been around longer than Charset - which doesn't even matter in the first place.

But whatever, enough about my little lament :P
I don't really want to change the recipe, so I suggest using NoMoreRecipeConflict (to be found [here](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict)).
It's a pretty useful mod in that it allows you to click the little arrow and scroll through all of the possible recipe outputs that exist - so you can decide wether you want tiny coal or graphite! :D

**Comment by xenoflot** [comment]
> I don't understand why people always use the "the other mod has been around longer" excuse.

People are trying to be gentle. It might cause offence to say "xxx mod is more popular than yours". Can you suggest a better way to resolve such conflicts?

Installing another mod may be effective but it's a band-aid approach that masks the underlying cause without resolving it. Adding another mod also introduces more potential for bugs and unexpected interactions.

I'll check out NoMoreRecipeConflict (which I didnt' even know existed until now.) Thanks!

**Comment by YasminEndusa** [comment]
In my opinion, the best way to resolve that issue is exactly what NoMoreRecipeConflict does. The other possible "workaround" is adding your own recipes with minetweaker.
