### ISSUE TITLE
[1.10.2] Farmer request/bug fix - Extra Utils 2 

### ISSUE THREAD

**Issue by b0bst3r** [Ellpeck/ActuallyAdditions#363]
ActuallyAdditions-1.10.2-r71
extrautils2-1.10.2-alpha-1.2.2

Feature request please for Extra Utils 2 in 1.10.2, having spoken to you in IRC about Ender Lilly seeds I was correct in thinking that you thought this was a working feature in r71.

It could be the latest Extra Utils broke this I'm not sure but anyway can you have the Farmer work with Ender Lilly seeds on farmland and End stone (it works on neither currently) <extrautils2:EnderLilly>

Also if you could make it work on Extra utils 2 Red Orchids (plant which is planted on Redstone ore blocks and gives 1 redstone as produce). <extrautils2:RedOrchid>

http://i.imgur.com/NhzYxDl.jpg <- farmer against dirt with ender lily seeds in -> Gui http://i.imgur.com/h5zTqJ3.png

http://i.imgur.com/RqdljZM.png <- Extra Utils 2 Red Orchids.

**Comment by Ellpeck** [comment]
Don't you need the seeds?

**Comment by b0bst3r** [comment]
I use a resourcepack sorry but those are ender lily seeds in the GUI screen shot.

**Comment by Ellpeck** [comment]
They're not.
It says "Ender Lilly".

**Comment by Ellpeck** [comment]
Oh right, true.
Huh, that's very strange then.

**Comment by Ellpeck** [comment]
Ender Lilies and Red Orchids work a lot differently code wise from other plants, so I will not include them in the Farmer which is supposed to only work for very simple plants like Wheat, Carrots, Canola etc.
Sorry :(

**Comment by b0bst3r** [comment]
Ok well I noticed some randomly planted ender lillys near my wall and figured out they were planted by your farmer, they plant on ordinary dirt not farmland.  So they half work already.

**Comment by Ellpeck** [comment]
Yea, but they're sadly not going to harvest them because Ender Lilies justwork differently :(
