### ISSUE TITLE
What is the LATEST version that still supports 'Less Particles'?

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [Ellpeck/ActuallyAdditions#365]

**Comment by Ellpeck** [comment]
How is this an issue?
Check the changelog, it is listed in there :)
https://github.com/Ellpeck/ActuallyAdditions/blob/master/update/changelog.md

**Comment by Rumpelstiltskinny** [comment]
thanks...I guess. What you meant to say was 'r70'.

**Comment by Rumpelstiltskinny** [comment]
To answer YOUR question, it was an issue based upon the fact that the RELEVANT issue thread was locked. SMH, brilliant, just brilliant.

**Comment by Ellpeck** [comment]
I told you to stop being rude once already, so you had your chance.
You will be blocked now.
