### ISSUE TITLE
Option to disable laser rendering

### ISSUE THREAD

**Issue by YasminEndusa** [Ellpeck/ActuallyAdditions#368]
I know this feature has been removed due to the lasers being pretty now and because everyone should have them enabled at all times.  
First let me say this: they look pretty, you're right on that one.  
The problem i have is that even they look good, i don't like it that they are going all over the place, making looking at my base a mess.  
To make them look neat, i need to create "bridges" to go around corners and such which causes the energy loss to add up more then i really want it to.  
Could you please re-add the option to turn off the rendering of the lasers? Or at least the option so they are only visible when holding the wrench?

**Comment by Ellpeck** [comment]
The Energy Loss doesn't get higher when more lasers connect two machines. It's always the same percentage from machine A to machine B, no matter how many lasers are inbetween.
So no problem making corners ;)

**Comment by YasminEndusa** [comment]
Okay, perfect, my bad ;)  
Now you gave me a pretty grat idea how to integrate them in my base and make it all look awesome :D
