### ISSUE TITLE
With ActuallyAdditions-1.10.2-r72 all plants rendering as magenta dices

### ISSUE THREAD

**Issue by Gepett0** [Ellpeck/ActuallyAdditions#369]
Hi,

just updated AA to latest version (as in topic). Now all planted plants don't render anymore.
Instead they are rendered as magenta dices.

Forge: 2125

Greetz

EDIT: just noticed that all the blocks placed on my server aren't rendered anymore :-(
        e.g. double grinder, double furnace, atomic reconstructor

**Comment by Ellpeck** [comment]
That's.. weird.
Are you using a texture pack?

**Comment by Ellpeck** [comment]
Oh, duh. I know why.
How did I miss this?

**Comment by Ellpeck** [comment]
Fixed with r73.
