### ISSUE TITLE
Crash on malformed JSON on update check shortly after entering a world

### ISSUE THREAD

**Issue by mrtopf** [Ellpeck/ActuallyAdditions#370]
I just tried to search something in JEI after I just entered my world and the game crashed with the following report: https://gist.github.com/mrtopf/60f9e43cfb5a9b5fff4be2496c0b4649

From the log it does not seem to be related to JEI though but looks more like a broken json on update checks. 

Forge 2125, Actually Additions r72

**Comment by Ellpeck** [comment]
Did that ever happen again?
It's a really weird bug.

**Comment by Ellpeck** [comment]
Oh, I know why that happens. Update to r73 and it should be gone :)

**Comment by mrtopf** [comment]
I now switched off update checks ;-) Will update on next restart and enable it again and see what happens. thanks for the fix already though :-)

**Comment by Ellpeck** [comment]
Yea, r72 was pretty much a complete bust. It was the first version I actually had to pull from Curse because of my failure which is pretty annoying.
So please update ASAP! :)
