### ISSUE TITLE
TravlerSack "spitting Stone" when AutoInsert is enabled

### ISSUE THREAD

**Issue by wadabum** [Ellpeck/ActuallyAdditions#373]
Have empty Travlers Sack, turn on AutoInsert
throw a single DirtBlock on the ground
and collect it without the sack "in Hand" (so its active)
-> Travlers Sack now holds the item + a random amount of Stone
sometimes a few stoneblocks even leak out into the players inventory/hotbar

**But a GIF says more than thousand words**....
 http://imgur.com/a/WCTaA

Running ActuallyAdditions-1.10.2-r74.jar
Forge 12.18.2.2124 with Optifine on Java Version: 1.8.0_111
(Hermitpack 1.4.0 with "bleeding edge manual mod updates" + a few Ads)
((full modlist from another issue i reported, dont mind the exception in there, has nothing todo with this here https://gist.github.com/wadabum/cc4582ae6a2badf3303a01805b4bf449 ))

**Comment by Ellpeck** [comment]
This is the weirdest thing.
