### ISSUE TITLE
EnderIO Not charging

### ISSUE THREAD

**Issue by HeavyDeception** [Ellpeck/ActuallyAdditions#374]
**Issue Description:**

The battery dose not seem to charge the armor or tools.

**What happens:**

RF is not put into the tools or armor when you have a battery in charge mod

**What you expected to happen:**

for it to charge the items.

**Steps to reproduce:**

1. Have Battery form Actually Additions
2. Have item form enderio that needs to be charged
3. Turn battery on.

...
**Affected Versions (Do not use "latest"):**

- EnderIO :3.0.1.126
- EnderCore: 0.4.1.58
- Minecraft: 1.10.2
- Forge: 12.18.2.2124
-  ActuallyAdditions-1.10.2-r75

**Comment by HeavyDeception** [comment]
@Ellpeck I fount this out in the DireWolf20 pack.

**Comment by mrkmg** [comment]
Also experiencing this issue, Also in DireWold20 Pack.

**Comment by Ellpeck** [comment]
Should be fixed through introduction of Forge Units.
