### ISSUE TITLE
Farmer deletes seeds when inventory is full

### ISSUE THREAD

**Issue by YasminEndusa** [Ellpeck/ActuallyAdditions#376]
I have a simple setup:  
9x9 Canola farm with a single water in the middle to keep it all hydrated.  
The farmer has, as i understood it, 2 sides: input and output.  
Once the output side is full with canola, there is no place for the seeds to go.  
The next time the farmer harvests a plant, it restocks one of the canola stacks in the ouput inventory but just deletes the seeds (or so it seems).

**Comment by Ellpeck** [comment]
Actually, this is not a bug. Sometimes the plants don't drop any seeds, but it's pretty rare.
What's happening here is the farmer tries to harvest the plant constantly and just "waits" until the dice rolls in such a way that only a canola would drop from the plant - and then it's able to harvest. 
Just a little thing with how Minecraft works. You should probably just pipe them out :P

**Comment by Ellpeck** [comment]
Just to clarify: If the canola output is full as well, no harvest will occur. Right?

**Comment by YasminEndusa** [comment]
If it is completely full, the harvester does not harvest, that is true.  
Thanks for the clarification, didn't know that was a thing.  
I am piping the output out, but at some point my target storage is full :P  
At least i can transform canola into seeds ^^
