### ISSUE TITLE
Add crafting option for Lenses

### ISSUE THREAD

**Issue by LemADEC** [Ellpeck/ActuallyAdditions#377]
Lens of certain death and Lens of the killer are bypassing PvP protection as of ActuallyAdditions-1.10.2-r70.jar .
Also, I can't find an configuration to disable players interaction, nor disable Lens of certain death recipe.

**Comment by Ellpeck** [comment]
Well.. the Lens isn't PvP, so there's nothing to bypass there.

But yes, the Crafting Option is indeed not present.

**Comment by LemADEC** [comment]
The Lens do kill other players, hence it's PvP.

**Comment by tigier** [comment]
But it's a machine not a player which kills

**Comment by Ellpeck** [comment]
No, I consider PvP a player actively killing another player, that's why it's called "Player versus Player".
To me, your theory would also mean that lava is PvP. Sorry, but I don't think the lenses should be affected by any PvP option.

**Comment by LemADEC** [comment]
Players are very imaginative when it comes to bypassing PvP protection.
A laser can be placed by players to kill them inside a protected area, for example spawn.
Lava won't do that.

**Comment by Ellpeck** [comment]
I don't care. I don't consider it PvP, so I won't change it.

**Comment by LemADEC** [comment]
That's your mod, I'm just telling you this part of your mod will remain disabled on most servers.
