### ISSUE TITLE
Crash on chunk gen

### ISSUE THREAD

**Issue by YalithKBK** [Ellpeck/ActuallyAdditions#378]
A crash report
[crash-2016-11-19_18.46.48-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/601798/crash-2016-11-19_18.46.48-server.txt)

**Comment by Ellpeck** [comment]
Did that only happen once or is it a recurring thing?

**Comment by Ellpeck** [comment]
Did you change the config for the chance of Lush Caves? 
If you want to turn them off, there is a seperate config for that.

**Comment by YalithKBK** [comment]
I happened just once. I changed the spawning option to false so maybe that will fix things.

**Comment by Ellpeck** [comment]
You don't have to turn it off. But the issue happened because of a config option which, if you didn't change it, is pretty weird.
I'll close this for now, but if you manage to reproduce it, please re-address this issue!
