### ISSUE TITLE
1.11-Glitched Villager

### ISSUE THREAD

**Issue by WenXin20** [Ellpeck/ActuallyAdditions#381]
Mod v76
Forge 2153
The villager texture is showing up as a purple and black texture. 
![2016-11-20_00 49 35](https://cloud.githubusercontent.com/assets/12000593/20461190/933c966a-aebb-11e6-8495-bb825e48fcd6.png)

**Comment by Ellpeck** [comment]
Closed by https://github.com/Ellpeck/ActuallyAdditions/commit/659d42446706430cae66a648838eb75480053b8a
