### ISSUE TITLE
Tinkers' Crafting Station shows internal name of Item Interface

### ISSUE THREAD

**Issue by UlfNorell** [Ellpeck/ActuallyAdditions#383]
Version: 1.10.2-r75.

Placing a Tinkers' Crafting Station next to an Item Interface is super useful since it lets you craft using all the items hooked up to the interface. However, the crafting station prints the name of the item interface as `container.actuallyadditions....` which isn't very nice.

![image](https://cloud.githubusercontent.com/assets/447950/20461590/15e45cbe-af03-11e6-8c10-664881f09d80.png)

Not sure if this is a problem with Tinker's or AA, but reporting here for now. For reference vanilla chests show up as `Chest` and the chests from `Iron Chest` show up as `IRON`, `GOLD` and `DIAMOND`.

**Comment by Ellpeck** [comment]
Ugh, I just never localized the names because you can't see them within the mod. :D
