### ISSUE TITLE
Oil generator Redstone control

### ISSUE THREAD

**Issue by Bellwar** [Ellpeck/ActuallyAdditions#384]
I'm using AA for my power gen. and using Ender IO for power storage and so I can read the amount of energy I have. What is annoying that I can't stop the generator from wasting so much power when I use 50 RF and the generator kick off, it would be nice to have it no waste all that power.

**Comment by johantovesson** [comment]
Any possibility to get this change to the 1.10.2 branch? 
Thanks for an awesome mod!

**Comment by Bellwar** [comment]
Well, I feel like 1.11 isn't ready for modpacks yet, and many mods are going over to it and some are still not getting first releases for 1.10 it is so huge window that mods are having now and its annoying. So, it would be nice have support for 1.10 still but, would understand not having it.

**Comment by Ellpeck** [comment]
No, sorry.
This is imy take on trying to make other people update their mods because they see more mods updating.
If I have all the stuff from 1.11 in the 1.10 branch, no one is going to feel like they have to update. Which everyone should have to feel that way! :P
So other modders: UPDATE YOUR MODS!! :D

**Comment by Bellwar** [comment]
Annoying is that there is huge people that started Direwolfs20 pack. I want to see what Dire himself will say to this he want Thaumcraft and it looks like Thaumcraft will be just for 1.10, same for Railcraft mods that are sooo SLOW.

But I totally understand you and maybe would do the same thing, it make sense, not like being stuck for 1.7.10 for 2 years this is the cost for that now.

**Comment by Ellpeck** [comment]
Direwolf told me that it's okay that I'm moving to 1.11, because he knows that I'll still be doing bugfixes and stuff for 1.10.
But I'd do it the way I'm doing it even if he didn't approve. It's my decision :P
