### ISSUE TITLE
Dupe Bug - Empowerer

### ISSUE THREAD

**Issue by Slither88** [Ellpeck/ActuallyAdditions#386]
When holding an empowered item/block in your hand and right clicking on the same empowered item/block on/in the empowerer the item/block is added to you inventory without removing the item/block from empowerer. This was on a SMP server. It happened with diamantine but I think it would happen with all the crystals.

Modlist:  http://pastebin.com/iAWEscEH

**Comment by Ellpeck** [comment]
Are you sure you're on r75?
I fixed this bug in r75 because it happened in r74.

**Comment by Ellpeck** [comment]
If it actually still exists in r75, could you make a quick video showing it? I know it's a simple thing, but there's lots of tiny things that could make it go wrong, so that'd be really helpful.

**Comment by Slither88** [comment]
It was in r74. I will make video for you and post it for you.

**Comment by Slither88** [comment]
Oh I updated the mods before I sent the list that is why it says r75. busy making that video.

**Comment by Slither88** [comment]
I miss read you message. I will first test if it is still present in r75 because it happened it r74 and I have not played with r75 yet. Sorry if it turns out that I logged this issue for nothing...

**Comment by Ellpeck** [comment]
I fixed this in r75, so the bug is very likely gone.
Don't worr about it, but you should always try things out with the newest version before reporting bugs anywhere :P

**Comment by Slither88** [comment]
I agree and usually do. Today is Monday though so I am just going to blame it on that. :-) Thanks for the patience and quick response though!

**Comment by Slither88** [comment]
So I feel really stupid now. Of course it is fixed.

**Comment by Ellpeck** [comment]
Everyone makes mistakes :P
So stop feeling stupid!

**Comment by Slither88** [comment]
I will try. Thanks again for the awesome mod and the quick response to a false alarm! You have an awesome day now!
