### ISSUE TITLE
Front faces accepting  redstone signal!

### ISSUE THREAD

**Issue by iEnergyX** [Ellpeck/ActuallyAdditions#387]
My suggestion is that Atomic Reconstructor, placer and breaker shoul not accept redstone signal because whe you're working with redstone blocks, that is a pain in the ass! xD

**Comment by Ellpeck** [comment]
This is really annoying to implement, and I don't really think it's worth it.
So sorry :(

You can just use a full block and a repeater if you want to place a redstone signal.. or whatever you're doing! :P
