### ISSUE TITLE
GUI Issues

### ISSUE THREAD

**Issue by darkshadow543** [Ellpeck/ActuallyAdditions#388]
Theres a small bug with the GUI, from time to time, the GUI stops letting me interact with it, such as I can not configure ESD's and can not change pages in the storage crates.  I am not sure of the cause, but once it happens you cannot interact with anything in the mod.

**Comment by Ellpeck** [comment]
Ugh I know, and I don't know why it happens. I've never encountered it myself, but a couple of people have told me about it.
Can you send me the full log of an instance of where this happens?

**Comment by P3rf3ctXZer0** [comment]
Its caused by Bookshelf

**Comment by Ellpeck** [comment]
In which way is it caused by bookshelf? O_o

**Comment by P3rf3ctXZer0** [comment]
Hmm let me see if I can find the log... one second.

**Comment by Ellpeck** [comment]
Huh, this is weird.
Could you report it to bookshelf then?

**Comment by P3rf3ctXZer0** [comment]
he already fixed it. Its from the version just before the most recent.

**Comment by Ellpeck** [comment]
Well then I'll close this.
