### ISSUE TITLE
[Suggestion] Upgraded Crafting Table

### ISSUE THREAD

**Issue by vKILLZONEv** [Ellpeck/ActuallyAdditions#390]
Create a crafting table that shows you everything you can craft from the items currently in your inventory. Optionally, add the ability to process multiple steps.  Example:  Say I have coal and oak logs in my inventory. If I open the crafting table I will see oak planks, sticks, wood tools, and torches.  If I choose a wood sword, it will craft the logs, sticks, and sword, all in one go. Of course any resource that it created but did not use (i.e the left over sticks) will be placed in a small inventory which the table comes with.

**Comment by Ellpeck** [comment]
No, sorry. I feel like this misses the point of crafting in Minecraft.
