### ISSUE TITLE
Drill Augments not taking effect

### ISSUE THREAD

**Issue by TheChickenCrispy** [Ellpeck/ActuallyAdditions#391]
I have been playing a survival game with some friends for a few days and made a drill. The drill itself worked perfectly. I decided to add a speed III augment and the drill mining augment II. Ever since I did that, the drill is not acting any faster or digging a bigger hole. I am playing version 1.10.2.

**Comment by tigier** [comment]
Did you use the Speed I. And II. As Well?

**Comment by YasminEndusa** [comment]
What tigier means is: For the augments to take effect, every previous level of augment has to be installed too. So if you want to use Speed 3, you also need to install Speed 1 and Speed 2 in that same drill. Same goes for the mining augment: You have to put in the level 1 and level 2 if you want to have the effect of level 2. And yes, that will completely fill all your drill slots, leaving no space for further augments.

**Comment by TheChickenCrispy** [comment]
Ohh. Thanks a lot! I guess I should have read the guide more carefully then.
