### ISSUE TITLE
[Suggestion]  Vertical Digger Augments

### ISSUE THREAD

**Issue by HeavyDeception** [Ellpeck/ActuallyAdditions#392]
Could we have a way to add the Drill Augments for silk touch and Fortune to the Vertical Digger.

This is more of a question but is there a way to turn on/off the mining augments I know you can hold shift but is there a toggle.

Thank you.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
