### ISSUE TITLE
[Superflat] world does not generate AA ores or lush caves

### ISSUE THREAD

**Issue by donqixot** [Ellpeck/ActuallyAdditions#393]
Using forge 1.10.2-12.18.2.2099 and ActuallyAdditions-1.10.2-r75, standard supeflat settings for Overworld, no AA ores underground is generated. Flowers on surface are fine. Is there any setting in config I can change to enable ore generation in superflat?

**Comment by Ellpeck** [comment]
Not in superflat, no. Why would you want this anyways?

**Comment by donqixot** [comment]
Superflat is the perfect testing setup. Also allows to create unique survival environments. Also allows easy control of single biome. If ore generation is the same for standard or superflat world, why not? If it's different and creates technical challenges, then ok, I can work around using "Lonely Biome" mod or some other tricks.

**Comment by Ellpeck** [comment]
But.. vanilla ores don't generate in Superflat either, that's why I turned mine off. On purpose.

**Comment by Ellpeck** [comment]
Sorry, I'm not going to implement this as I don't see the point.
