### ISSUE TITLE
[1.10.2] Atomic Reconstructor with items

### ISSUE THREAD

**Issue by b0bst3r** [Ellpeck/ActuallyAdditions#395]
ActuallyAdditions-1.10.2-r75

Have a strange thing occuring in that the atomic reconstructor will not change items dropped in front of it unless it's against the last block.

For example, take this row of canola seeds http://i.imgur.com/2LMvmKD.jpg I was very careful to place them in the same row as the atomic reconstructor.

Fire the Atomic Reconstructor and it only changes the last one against the last block like this - http://i.imgur.com/83gXCFi.jpg completely ignoring what's directly in front of it and all those along the row.

I don't have any issue with blocks placed down as it has to hit those it's just items like this.  It took me ages to figure out why it wasn't working and I couldn't change any seeds :)

**Comment by Ellpeck** [comment]
I love how you're pointing out a feature.
Do you see the white particles? They indicate where it's going to conver blocks.
It also states directly and clearly in the book. *Read it please.*

**Comment by b0bst3r** [comment]
Ahh that changed somewhere it didn't always do that :p

**Comment by Ellpeck** [comment]
It did always do that, since the Reconstructor first came out.
Sorry to disappoint you, but there's no excuse :P

**Comment by b0bst3r** [comment]
I'm old that's my excuse and I'll stick to that, sorry for wasting your time :)
