### ISSUE TITLE
Incompatibility with Rainbeau's Realistic Survival

### ISSUE THREAD

**Issue by bloodyraoul** [Ellpeck/ActuallyAdditions#397]
I play with the 1.10.2 version
Rainbeau's Realistic Survival avoid players to break a block if you dont have the good tool.
It seems that Actually Additions drills are not seen as pickaxe because I cannot break any block with it.
I dont know if it is something you can fix, as register drill as a pickaxe or if it can only be fix on the Realistic Survival side ?

**Comment by Ellpeck** [comment]
You probably have to pass this on to the mod's creator because I set the harvest level of the drill to include "shovel" and "pickaxe".

**Comment by Ellpeck** [comment]
Please close this or leave a note when the issue is resolved and update me on what the dev said :)

**Comment by bloodyraoul** [comment]
Sorry to have not answer. I have tried to contact Rainbeau's Realistic Survival author about this bug, but no answer :(

**Comment by Ellpeck** [comment]
Yea, that's fine. I just didn't want to have this lingering around my tracker because it's not really my bug :)
