### ISSUE TITLE
Double Crusher can't crush certain ores. 

### ISSUE THREAD

**Issue by raflnatorr** [Ellpeck/ActuallyAdditions#398]
I play the 1.10.2-r75 version of the mod. 

The crusher can't crush Mekanism ores ore the ones from Extreme Reactors. The Powered furnace accepts them though. 

My first submit on Github ever, so just write if you need more info.
![Example with Extreme Reactors.](https://cloud.githubusercontent.com/assets/21206813/20540477/a573bc24-b0f9-11e6-82b3-57d33ba01648.png)

**Comment by Ellpeck** [comment]
Does the normal Crusher crush them? Does JEI show it?
What's the OreDictionary entry for the ore, and what's the one for a respective dust?

**Comment by Ellpeck** [comment]
I can't reproduce this.

**Comment by raflnatorr** [comment]
The normal crusher can't crush them either. And no, the JEI doesn't show it. 
My Forge version is Forge-12.18.2.2151

**Mekanism Copper ore:**
OreDictionary entry: oreCopper
Respective dust: dustCopper

**Mekanism Tin ore:**
OreDictionary entry: oreTin
Respective dust: dustTin

**Mekanism Osmium ore:**
OreDictionary entry: oreOsmium
Respective dust: dustOsmium

**Extreme Reactors Yellorite ore:**
OreDictionary entry: oreYellorite & oreYellorium
Respective dust: dustYellorium & dustUranium

Anything else you want to know?

**Comment by Ellpeck** [comment]
Please send the full log :)

**Comment by raflnatorr** [comment]
Sorry, i don't know which log you want, so i will give you them all :) 




[logs.zip](https://github.com/Ellpeck/ActuallyAdditions/files/607606/logs.zip)

**Comment by Ellpeck** [comment]
Oh, I see what's happening here.

**Comment by raflnatorr** [comment]
Am i being stupid?? :)
