### ISSUE TITLE
[Suggestion] Config for mining lens blacklist

### ISSUE THREAD

**Issue by al132** [Ellpeck/ActuallyAdditions#399]
It would be lovely if the mining lens could have a blacklist for which ores it can generate in the config much like the vertical digger and crusher do.

**Comment by TheOldOne822** [comment]
I was just about to ask about a way to add ores to the mining lens in 1.10.2 to see it's already been addressed.

**Comment by Ellpeck** [comment]
Also already added :D

**Comment by TheOldOne822** [comment]
Yes a very nice addition to 1.11 now I just need the rest of the mods to update.
