### ISSUE TITLE
[Suggestion] Allow right click on advanced laser item relay

### ISSUE THREAD

**Issue by jpmitche11** [Ellpeck/ActuallyAdditions#400]
I was unable to open the filter config gui for the advanced item relay. Updated to .75 release, same issue.
After doing a bit of research, found a video on youtube that said to shift right click to open. That worked.

Would it be ok to allow normal right click? Most blocks in the game behave this way.
If not, perhaps add something to the manual, or add a tooltip?

**Comment by jpmitche11** [comment]
I love the mod so far. Thanks for your hard work @Ellpeck.

**Comment by Ellpeck** [comment]
Thanks :)
