### ISSUE TITLE
Toggle Laser Relay Visuals no longer working?

### ISSUE THREAD

**Issue by GhostSnow** [Ellpeck/ActuallyAdditions#402]
Maybe this has already been brought up or perhaps it is by design, but I just updated from the version that came with the direwolf20 pack. I enjoyed the particle effects that you previously had which seem to have changed too a solid laser line. 

The biggests problem I have is that the ability to toggle being able to see the lasers seems to be gone. Is this a bug or is this by design?

 I can't stand all the lasers shooting around my base anymore and may switch to ender conduits or something until this feature is added back?

**Comment by Ellpeck** [comment]
It's intended, and I won't be adding it back.
There's no excuse anymore now for making them look ugly. You gotta lay them out in a way that makes them look nice.

**Comment by GhostSnow** [comment]
Aha, good to know! thanks, looks like I need to mess a bit with my laser organization now that they are visible!!
