### ISSUE TITLE
[Suggestion] Change Magnet Ring Off Switch

### ISSUE THREAD

**Issue by LewisHolt** [Ellpeck/ActuallyAdditions#403]
Right now the only way to disable the magnet ring is to shift which is slightly annoying. Could we have an improved way of turning off by shift & right clicking or something like that? 

Shift right click to turn it off, shift left click to turn it on perhaps?

The animation could stop spinning while it's off for example.

Perhaps even in the future this toggle feature can be extended to all the rings. **Especially** the ring of liquid banning, I've lost many liquids by just having it in my inventory. :(

**Comment by garantiertnicht** [comment]
Espacially now when Rings have a permanent cost, I would also like the idea to `can be extended to all the rings` part. But it meight not what you wanted to archieve with the change.

**Comment by Ellpeck** [comment]
Which permanent cost?

**Comment by garantiertnicht** [comment]
Didn't you wanted them to cost Blaze Powder?

**Comment by Ellpeck** [comment]
Closed by https://github.com/Ellpeck/ActuallyAdditions/commit/65e443e13b0a937348b86d58754ff3e35cdfe1f7
