### ISSUE TITLE
Feature Add-Ons And Improvements For The Player Interface

### ISSUE THREAD

**Issue by 2211kp** [Ellpeck/ActuallyAdditions#405]
Got An Idea For You Man. Could You Make It That When The Player Interface Gets A Splash Potion Effect Applied To It, It Will Apply The Effect To The Bound Player. And Also Include If The Block Is Placed In The A.O.E. Of A Potion, Like If Its Placed Near A Beacon, A Lingering Potion, Or A Machine Block That Applies An Effect.

Also Another Idea Would Be To Make Different Sides Of The Player Interface Interact With Different Slots Of The Inventory. Like The Bottom Being The Armour Slot, The Top Being The Hot Bar, And The Sides Being The Rest.

**Comment by Ellpeck** [comment]
Sorry, I don't really want to implement either idea. They're both cool, don't get me wrong, but:
1. I think the potion effect thing is a little too powerful and also pretty hard to actually make happen by how the Minecraft codebase works. You could use Potion Rings though :P
2. I don't really like Sidedness with machines. I think it's just a hastle to have to work with that as a player, and plus: There's ESDs, so you can specify the slots yourself! :)
