### ISSUE TITLE
Phantom Placer maybe bug/request

### ISSUE THREAD

**Issue by Greg9711** [Ellpeck/ActuallyAdditions#406]
[1.10.2]
The Side Placement in the phantom placer is kinda strange with normal blocks, when i set it for example to UP then when i activate it the block goes 1 above the block space i linked the placer to and when activating it a second time it places the block in the same block space i linked it to. It feels like its intended, if it is it would be nice if there would be anothe Side Placement setting that only places the block exactly where i linked the phantom placer to.

**Comment by Ellpeck** [comment]
That's not how placement works, and that's explained in the button's tooltip.

**Comment by Greg9711** [comment]
Ok and i guess you don´t want to add another placement in addition to the others. :/ k then
