### ISSUE TITLE
[Suggestion] Traveler's Sack showing item count on tooltip like Forestry bags

### ISSUE THREAD

**Issue by number5** [Ellpeck/ActuallyAdditions#407]
like `3/25` or just the number of items in it.

When using multiple sacks, it's hard to find out which one have been sucking items

**Comment by number5** [comment]
Hmm, the fix didn't get into 1.10.2 branch...

**Comment by garantiertnicht** [comment]
1.10.2 only gets important updates for the most part, new features will be rare (if any).

**Comment by number5** [comment]
1.10.2 bug-fixing mode already?
