### ISSUE TITLE
Coal Generator misleading text in the book

### ISSUE THREAD

**Issue by TvL2386** [Ellpeck/ActuallyAdditions#408]
Hi,

When I've read about the Coal Generator in the Actually Additions in-game Manual, it says: 'Note that it only starts burning something up if there's enough space for the energy generated'.

I interpreted it like this: Only if there is sufficient space in the Coal Generator buffer, it will start burning up a piece of coal. 

This would actually be great because I've just started and hooked it up an (EnderIO) Alloy Smelter which uses 20rf/t while the Coal Generator produces 30rf/t. Now it is continually burning coal and thus wasting 10rf/t? 

Anyway: I would remove the note since it's kind of default behavior or implement this feature request and adjust the note accordingly :-)

Oh and let me say: Nice mod!!! Keep up the good stuff!!!

**Comment by Ellpeck** [comment]
Huh. I didn't know it was still in the book.
See, WITH the feature people were complaining about an alleged bug where the Coal Gen wouldn't burn up Coal Blocks. :v

**Comment by garantiertnicht** [comment]
<insert facepalm reaction here> :/
Why do people complain about saving recources?

**Comment by TvL2386** [comment]
Hi Ellpeck,

Thanks for the quick fix!

@garantiertnicht 
I was not complaining. I was indicating that I found the Manual misleading.
And yes: I care about not wasting resources, especially early game. But again: it's not a complaint.

**Comment by garantiertnicht** [comment]
@TvL2386 I was not complaining about you, but about the people `complaining about an alleged bug where the Coal Gen wouldn't burn up Coal Blocks`
