### ISSUE TITLE
[1.10.2] General drill weirdness

### ISSUE THREAD

**Issue by phit** [Ellpeck/ActuallyAdditions#409]
We had a few instances now where breaking things with a drill caused weird behavior

>break a EnderIO Vaccum Chest with it, the block disappeared and didn't drop and you could place other blocks in it's place, but the vacuum effect was still happening

>sometimes crashes the server when breaking a rftools timer https://github.com/SpongePowered/SpongeForge/issues/1059

>https://forums.stonebound.net/topic/823/bug-items-would-disappear

I'm not sure if any of this an issue on your end or Sponge's, but I thought I would let you know. Since none of these things happen with other tools.

Pack is Direwolf20 1.0.0
Forge 12.18.2.2123
ActuallyAdditions-1.10.2-r70
spongeforge-1.10.2-2123-6.0.0-BETA-1878

**Comment by Ellpeck** [comment]
Does it happen with just Vanilla and Forge?
I don't support Sponge.

**Comment by phit** [comment]
No clue, still haven't found a proper reproduction and don't have the time to test normal forge for hours.
Anyway, if you think it's sponge fault that's fine and since it wasn't reported here that's probably true, I just figured I would document it here, since it only happens with the drill.

**Comment by Ellpeck** [comment]
The code for the drill is not exactly the vanilla one. I copied the method to be able to modify it for things like 3x3 mining, but it's just the vanilla code modified a little. Maybe Sponge changes something in Vanilla somewhere.

I'll close this for now, but it'd be cool if you could keep me updated on the issue still :)
