### ISSUE TITLE
[Bug] Manual: "All Items and Search"

### ISSUE THREAD

**Issue by Kristian295** [Ellpeck/ActuallyAdditions#41]
[Using r20 on 1.7.10-Forge10.13.3.1395-1710ls]

Sometimes, when having the ActAdd Manual in players inventory, the search function and 'all items' list does appear not to work. This means, the list is completely empty and the search function cannot be used either.

Unfortunately, I could not exactly figure out when this bug appears; in most cases, I could fix it by throwing the booklet away, restarting the game and getting a new one.

**Comment by Ellpeck** [comment]
Already fixed.
Won't be fixed with a 1.7 version ever, though, probably.
