### ISSUE TITLE
handheld filler does not work with Chisels & Bits blocks

### ISSUE THREAD

**Issue by rahangar** [Ellpeck/ActuallyAdditions#412]
Handheld filler seems to have issues when used with Chisels & Bits blocks (i.e. custom blocks made using C&B).   When using the handheld filler, I hear the blocks being placed, but no blocks are actually placed.  Also the number of blocks in my inventory is reduced, so the blocks are gone.

Here are the versions:

minecraft: 1.10.2
ActuallyAdditions-1.10.2-r81
chiselsandbits-12.7
forge-12.18.2.2124

I'm running HermitPack version 1.4.0, but it comes with an older version of ActAdd which doesn't have the handheld filler.  So I upgraded ActAdd manually to ActuallyAdditions-1.10.2-r81 in order to get the handheld filler.

Thanks,

**Comment by Ellpeck** [comment]
This is not a C&B issue, but also I don't think that there's that much I can do about it. The Filler only works based on Blocks and metadata, and I suspect that C&B blocks are far more complicatedly structured than that.
Do you think it's that important?

**Comment by rahangar** [comment]
Thanks for the clarification.

I'm making a giant structure with a lot of rows and columns made that are only one-block wide/high.  Builder's wands don't seem to extend blocks out radially from a block.  So to answer your question, for me it is pretty important since I don't know of any other way of creating single-block rows/columns as easily as the HH filler makes it.  If you're aware of such a tool, please share that info.  

BTW, I have not tried World Edit, and don't know if that would work with C&B.

**Comment by Ellpeck** [comment]
I only know that making this work with the handheld filler isn't really worth the effeort in my opinion, so I think I'm not going to implement this.
Sorry :(

**Comment by garantiertnicht** [comment]
@Ellpeck If it would just be a check for NBT, maybe a config Option for Blocks using it would do it. Would you mind looking into it and work on a PR if I've got time and find a solution?

**Comment by Ellpeck** [comment]
No, because I think making it work with NBT is very difficult because there's a lot of blocks that store additional NBT, so it wouldn't be clear if watching out for the NBT is necessary or not. And especially, what NBT needs to be watched out for and what doesn't.

**Comment by rahangar** [comment]
Not sure if this helps, but there is a somewhat related issue that I raised - a bug with the "NotEnoughWands" swapping wand.   The comment from Algo (C&B author) was that NBT data needs to be taken into account.  We'll see if the NotEnoughWands issue ever gets fixed.  

https://github.com/AlgorithmX2/Chisels-and-Bits/issues/182

Given the popularity (at least perceived by me) of C&B, it seems that there would be a lot of value in a tool (like the HH filler) that could deal with custom C&B blocks.

**Comment by Ellpeck** [comment]
Ugh, I guess I might.

**Comment by rahangar** [comment]
Yay :-)

Thanks for considering it.

**Comment by Shadows-of-Fire** [comment]
So the way the filler works, this is entirely impossible, and I don't really want to rewrite the entire thing to support C&B.
I could always write some sketchy shit to save the name of the tile class but uh. nah.
