### ISSUE TITLE
Tweak? isRepairable() vs getIsRepairable() in Item Repairer

### ISSUE THREAD

**Issue by Aedda** [Ellpeck/ActuallyAdditions#415]
I've recently run into a small problem where a mod with armor items returned getIsRepairable() as false but didn't also override isRepairable() to return the same, the author was unaware of there being two similar methods. As a result placing their armor in the Item Repairer caused a crash...

```
java.lang.ArithmeticException: / by zero
	at de.ellpeck.actuallyadditions.mod.tile.TileEntityItemRepairer.getItemDamageToScale(TileEntityItemRepairer.java:129)
```

Would it be a lot of trouble and if not would you consider checking for both methods prior to performing a repair? It may prevent a bug report or two in the future. :)

**Comment by Ellpeck** [comment]
I didn't know there was two variants either.
