### ISSUE TITLE
Firework Box causes client crashes

### ISSUE THREAD

**Issue by Clorith** [Ellpeck/ActuallyAdditions#416]
We discovered that leaving a firework box in a chunk loaded area (using Chunk Loading Wards from ExtraUtils2) it appears to "save" the effects until an actual player loads the chunk.

After being in an unloaded area for 12 hours, someone chanced upon the area, causing their client to crash, and the server to globally lag, the lag would not decrease over time (>180 seconds of lag before we removed the block and restarted the server).

Starting the server back up without any players in the area everything was as expected until the person chancing upon it logs in and is close enough to load the firework chunk again.

**Comment by Ellpeck** [comment]
What was the crash report?
