### ISSUE TITLE
Request: Turn off generator with redstone signal.

### ISSUE THREAD

**Issue by eslachance** [Ellpeck/ActuallyAdditions#418]
From other tickets I gather that it's desired effect that coal and oil generators waste resources by turning on even if there is not enough energy space for the fuel to completely burn (btw potential halfway solution for this: pause the burn when there is no space!)

So how about this: if it were possible to turn off generators using a redstone signal, we could more easily control this waste. Using the Power Monitor and turning off all generators when a capacitor is more than 90%, turning them back on when they're lower than 20%.

The generator would finish, of course, whatever it was currently burning. This could even be controlled from a redstone torch (disable, pulse for one burn! Lol).

Honesty the whole Canola oil system is one of the most interesting and unique (not to mention realistic, except for the magic seed parts) power systems I've seen out there, and I'd love to be able to continue using it later game, but it feels like there is SO much waste going on in oil gens, it's insane.

**Comment by eslachance** [comment]
To put this into perspective:

Assuming maximum output with energized oil in 10 generators, for a total of 3500 Rf/tick. Knowing that most power conduits pull from sources equally (distributed), if a system like AE2 or Refined Storage is pulling 10rf/tick for wires and maintenance, that is literally 3490rf/tick wasted, lost, down the drain, never to be seen again.

**Comment by Ellpeck** [comment]
It is possible in 1.11 as someone requested that already :)
Not in 1.10 though, so if you don't want to update yet, sorry. I don't think it's necessary to release an update for 1.10 just to implement this one feature, I hope you understand that :P
Mabye I'll remember to sneak this in when I get a significant bug report for 1.10 that has to be fixed!
