### ISSUE TITLE
Laser Relay incompatibility with EnderIO machine side config

### ISSUE THREAD

**Issue by Unatan63** [Ellpeck/ActuallyAdditions#420]
When using lasers relays with Ender IO machines you can no longer see the input/output configuration option on the machines, take the lasers off and can use/see them again.

**Comment by Ellpeck** [comment]
Still don't know what causes this.
Gotta forward this to someone like @HenryLoenwind - Is this on my side? What can I do to fix this?
[This](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/blocks/render/RenderLaserRelay.java) is the Laser Relay renderer, and [this](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/util/AssetUtil.java#L213) is the actual method that renders the laser.

**Comment by HenryLoenwind** [comment]
Do you have a screenshot how it looks with the lasers?

**Comment by Ellpeck** [comment]
Inside of the GUI? The screen just goes either grayish-blue or sky colored, depending on (something..?).
Pressing ESC is the only way to get out of that.

**Comment by HenryLoenwind** [comment]
ok, "screen going bluish-gray" is a known error pattern for me. If I just could remember what's causing it ;)

**Comment by Ellpeck** [comment]
It *has* to be something related to one of the GL things being disabled. But I have so little of a clue about rendering code - that's also why I outsourced the Laser Renderer to someone else as you can see at the top of the method :P

**Comment by HenryLoenwind** [comment]
Which TESR renderpass are you rendering in? I'd expect pass 1 (second pass) for transparency? Then try to reset state with:

```
          GlStateManager.enableBlend();
          GlStateManager.depthMask(false);
          GlStateManager.blendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
```

**Comment by Ellpeck** [comment]
There are different TESR render passes? I didn't even know that.
But I'll try doing that.

**Comment by HenryLoenwind** [comment]
yes, 2 passes, so you can render transparent stuff over solid stuff, just like with blocks.

**Comment by Ellpeck** [comment]
How do I tell it which pass to render in?

**Comment by HenryLoenwind** [comment]
```
        if (tile.shouldRenderInPass(pass)) {
```

**Comment by Ellpeck** [comment]
Thanks for the help. Will see later if that fixes the issue

**Comment by HenryLoenwind** [comment]
Which btw, is pure speculation on my side...

If that doesn't help, try to comment out the cleanup gl statements one by one...
