### ISSUE TITLE
Dupe Glitch w/ Bags

### ISSUE THREAD

**Issue by Puzzledlight** [Ellpeck/ActuallyAdditions#421]
Playing DW20's 1.10 pack, version 1.0.0, modified with AA r 75. While holding a magnet ring in my inventory and a bag set to auto pickup in my hotbar, I can dupe items by ensuring I have an incomplete stack of the target item in both my inventory and the bag, and picking up the item from the ground. Any items picked up this way appear in both the bag and my inventory.

**Comment by Ellpeck** [comment]
I can't reproduce this with the newest 1.10.2 version.

**Comment by Puzzledlight** [comment]
So it only exists in r75? Nevermind then! =D

**Comment by Ellpeck** [comment]
I don't know. Maybe I'm doing it wrong. 
So.. you should test it :v

**Comment by Puzzledlight** [comment]
Roger, downloading newest version now.

**Comment by Ellpeck** [comment]
^ Meaning this is still a thing?

**Comment by Puzzledlight** [comment]
Okay. As much detail as possible. Using AA r81 inserted into DW20 1.10.2 modpack, version 1.0.0. Fresh world. Spawned in a bag, spawned in a stack of baguettes. Placed half a stack of baguettes into the bag, turned bag to auto-pickup, placed bag in hotbar, slot 1. Moved main hand to slot 2. Dropping any amount of baguettes and picking them up places them into both my hand and my bag.

**Comment by Puzzledlight** [comment]
*Correction, any amount is wrong. Try one or five at a time - it behaves oddly if you pick up enough to complete a stack of 64 in the bag.

**Comment by Ellpeck** [comment]
Try with just Actually Additions installed.

**Comment by Ellpeck** [comment]
I still cannot reproduce this.

**Comment by Puzzledlight** [comment]
Isn't present with only AA... Would you like me to start adding mods in chunk at a time until I can identify which combination is needed to trigger this?

**Comment by Ellpeck** [comment]
Yes.

**Comment by Puzzledlight** [comment]
Starting and stopping minecraft has never been so much fun. I've got it narrowed down to about 15 possible mods. Expect to be done in 10 minutes or so.

**Comment by Puzzledlight** [comment]
Okay! Took the DW20 pack and gutted all mods, readded forestry_1.10.2-5.2.16.323 and ActuallyAdditions-1.10.2-r81, bug is present.

**Comment by Puzzledlight** [comment]
Additionally, bug only requires the bag to be set to auto-pickup, and an incomplete stack in your inventory to trigger. Magnet ring/stack present in bag are irrelevant. Anything else I can do to help out?
