### ISSUE TITLE
Make the Farmer be able to farm special case stuff like cactus and modded stuff -> API implementation?

### ISSUE THREAD

**Issue by VaiN474** [Ellpeck/ActuallyAdditions#422]
Currently it seems to "work", but it's extremely slow to harvest. I've seen anywhere from 30 seconds to over 3 minutes between each harvest even when all plots are fully grown.

**Comment by Ellpeck** [comment]
Is it slower than with other plants? This doesn't seem like a bug.

**Comment by VaiN474** [comment]
yes, significantly slower. here's a [screenshot](https://dl.dropboxusercontent.com/u/80789157/2016-11-29_15.59.06.png)

**Comment by Ellpeck** [comment]
But it still works?
Because then I don't see this as an issue.

**Comment by VaiN474** [comment]
harvesting one plant every few minutes when there are 9x9 plants fully grown isn't an issue?

**Comment by Ellpeck** [comment]
The farmer isn't even supposed to support plants like this, as it's said in the manual it's only supposed to be used for basic plants like Wheat and Potatoes.
But there's nothing I can do about this either. It has to be something with the way these plants work that makes them not be usable in the farmer like other plants are.

**Comment by Ellpeck** [comment]
You know what? Changed my mind. I'll implement this at some point.

**Comment by garantiertnicht** [comment]
Will this also include Nether Wart?
