### ISSUE TITLE
Crusher Recipes still show after being disabled in Config

### ISSUE THREAD

**Issue by katur239** [Ellpeck/ActuallyAdditions#423]
All the recipes made in the crusher are still being registered and shown in JEI after I disabled the crusher in the configs.

Can it be made to not register the disabled blocks and it's recipes or at least not be shown in JEI?

Thanks

**Comment by Ellpeck** [comment]
No, sorry. The config only disables the crafting recipe, not the feature.
Disabling features is not something that I want.
You can use JEI's hide mode to hide the Crusher though.

**Comment by Ellpeck** [comment]
By the way, you can use [ModTweaker](https://minecraft.curseforge.com/projects/modtweaker) if you're in 1.10 to disable Crusher Recipes.
