### ISSUE TITLE
Is there a way to reboot a laser network?

### ISSUE THREAD

**Issue by charlesbevans** [Ellpeck/ActuallyAdditions#424]
I set up a basic item sorting system with laser relays and filters. An iron chest hoppered into an ESD connected to a network. I removed the hopper so the ESD can access the chest directly and the ESD now lists 0 slots for the relay network and nothing moves. I've tried restarting the game (SSP) and removing all the relays and rebuilding the system, but I've still got no slots.

**Comment by Ellpeck** [comment]
Did you re-assign the ESD to that side? By default, the ESD switches to the amount of slots that are available from the container it first gets attached to, but when you don't reassign it, it won't change its values. I'd suggest setting the limits of any ESDs that interact with Item Interfaces to 0 - 999999 to avoid problems like that.

If this is indeed the problem, please close the issue. If not, please provide more information, like screenshots and the game and mod versions you're using :)

**Comment by charlesbevans** [comment]
Doh! Yes, I tried cycling through the sides, manually assigning 999 as the max slot, etc.
![screen shot 2016-11-30 at 11 58 34 am](https://cloud.githubusercontent.com/assets/15851438/20768876/794187ca-b6f4-11e6-9b33-029bbdbe5172.png)
I've moved a chest and second basic relay next to it for a picture. Just the two are connected and the target chest is empty.
![screen shot 2016-11-30 at 11 58 54 am](https://cloud.githubusercontent.com/assets/15851438/20768879/7afd2f24-b6f4-11e6-8a44-7bed67b6c7c4.png)
I'm using the DW20 pack, unmodified. It includes ActAdds 1.10.2-r70.

**Comment by Ellpeck** [comment]
You need an Item Interface. Read the Manual.

**Comment by Ellpeck** [comment]
Sorry, that might have sounded a little harsh. Not meant that way. But you should definitely read the manual because you missed a vital part of the way that Item Laser Relays work :P

**Comment by charlesbevans** [comment]
Got it. I was going off memory and when I went to the manual my brain conflated the ESD and item interface.
Thank you.
