### ISSUE TITLE
Energy Laser Relays factor the block energy was input from as a possible output and divide the available power wrongly

### ISSUE THREAD

**Issue by vengpjer** [Ellpeck/ActuallyAdditions#425]
I am feeding 1000 rf/t into the tier 1 energy laser relay, however it only accepts and transfers 320 RF/t, which is half of the conduit's transferable energy, which would be 640rf/t for the basic conduit.

[Picture ](https://puu.sh/szUb6/243ac5a40f.png)

The weird thing happens when I use this same setup but simply switch from basic conduits(640rf/t) to enhanced conduits(5120rf/t), then the relays start accepting 1000rf/t, which is their maximum transfer rate. 

The same thing happens with relays of higher tiers, for example using an advanced relay and enhanced conduit, it should be pulling 5120rf/t but it only goes up to 2560rf/t.

ALSO to note, when using the advanced relay and enhanced conduit, if I set the avaliable power up to 2559, it will split the power transfered in half, BUT setting the conduit to INPUT on one side and EXTRACT on the other side will transferr 2559rf/t without any problems.

 Setting it to 2560 or higher will then only transfer up to 2560 rf/t and not a single bit higher, considering this should be able to transfer up to 5120rf/t because the conduits and the relays are capable of doing so.

This bug was spotted on the version 1.10.2-r70

**Comment by Ellpeck** [comment]
Note to self: This is hard to fix as just not checking the entire relay energy was input from would cause it not to output into other sides of it - maybe somehow check the list of connected tiles and remove that? Dunno.
