### ISSUE TITLE
Jam trading issue with Villagers

### ISSUE THREAD

**Issue by Tyler799** [Ellpeck/ActuallyAdditions#427]
I recently found a villager in r84 that traded 1 GroMeKi (or whatever it is, the bright green jam) for 1 emerald.

He also trades 2 emeralds for 4 GroMeKi Jam.

See the issue?

Infinite emeralds. I may have abused it just a little.

**Comment by Ellpeck** [comment]
I don't think it's that big an issue because *no one uses Villagers anyways*.
But also, it's semi-rare for this trade combination to happen.

But yea, it's an issue still.

**Comment by tigier** [comment]
Maybe a possible solution for now is making this combination unable to appear with just one villager(if it works tho.... No idea how villagers work). That way you would at least have to find a second villager and that way it reduces the chance of the combination happening.
