### ISSUE TITLE
Non white list items wont sort to item laser relay

### ISSUE THREAD

**Issue by AshJMA** [Ellpeck/ActuallyAdditions#429]
![sorting layout](https://cloud.githubusercontent.com/assets/24321492/20844473/dc04cdd0-b8b7-11e6-8856-642303fa5399.png)

Using the above layout as an example, the crate on the far left will receive any ores that have been white listed in the advanced item relay. 
However, if items that have not been white listed are placed in the input chest they are moved to the slot in the ESD, this jams the system. I would have expected these items to go to the crate with a basic item laser relay. 
The item laser relay in the centre is also set to a higher priority than the item laser relay on the item interface but lower than the advanced item laser relays (in case this makes a difference).

![jamed esd](https://cloud.githubusercontent.com/assets/24321492/20844819/9e90027e-b8b9-11e6-9806-586ef7c71ace.png)
The image above shows what happens when furnaces are placed in the input chest (they've not been white listed). But Iron ore for example would go to the appropriate chest.

![functioning layout](https://cloud.githubusercontent.com/assets/24321492/20845068/1336e7ae-b8bb-11e6-86e5-71cd6e9bf3c9.png)
When disconnecting all the item relays and only connecting the crate in the centre to the item interface it will receive items just fine, as long as the receiving chest is set to a higher priority.

Using an advanced item relay set to black list won't fix this either.

Please let me know if I'm missing something very simple.

I haven't added anything or changed anything in the Direwolf20 1.10 pack.
here's the curse profile for the pack  I'm using
I don't how how to copy a mod list from the curse launcher so sending this is easier than typing each mod version :)

[FTB Presents Direwolf20 1.10-1.1.0.zip](https://github.com/Ellpeck/ActuallyAdditions/files/627971/FTB.Presents.Direwolf20.1.10-1.1.0.zip)

**Comment by Ellpeck** [comment]
Try making the Laser Relay on the Item Interface not connect to the Iron Chest.

**Comment by Ellpeck** [comment]
Actually, this is not the issue. Reset the ESD's slots by assigning the side again or set the upper bound to a really high number.
The ESD will only define its slots once first connecting to an inventory, but never again afterwards, so it'll only "see" the first couple of slots in your system. :)

**Comment by AshJMA** [comment]
Resetting the ESD fixed it!! Fantastic :)

**Comment by Ellpeck** [comment]
As I said, best solution here is to just click the input text field and set the number to something like 999999 so that you won't have to reset it again :D
