### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by Myknakryu** [Ellpeck/ActuallyAdditions#430]
Minecraft version: 1.11
Forge version: 2178
Actually Additions version: 1.11 r83
CompatLayer version: 1.11 0.0.39beta
McJtyLib version: 1.11 2.2.0 beta 1
RFTools version: 1.11 5.62 beta 1

I have no idea what happend. I accidentally placed Item Interface on energy laser relay which was connected to canola press and power source from powercell from RFTools. It crashes only server. World at this point cannot be loaded, unless you remove Actually Additions or load from backup but some of progress were lost. Retrying to do same thing on singleplayer gives  the same result.

*Powercell must be charged*

Logs from server:
http://pastebin.com/K3a37Pym
Logs from recreating same thing on singleplayer:
http://pastebin.com/nHspw1vG

**Comment by Ellpeck** [comment]
Actually, this has been fixed already, just not in the newest release.
There will most likely be one by tomorrow :)
