### ISSUE TITLE
Make Filters be consumed when placing them into Filter Slots

### ISSUE THREAD

**Issue by Belgabor** [Ellpeck/ActuallyAdditions#432]
It would be great if there was a way to copy an item list from an advanced laser relay (or ESD) to a filter so you can easily "upgrade" it if you run out of filter slots.

**Comment by Ellpeck** [comment]
What I was thinking is making it so that if you place Filter Items inside of Filter Slots, they would actually be consumed and you could also take them out.
So I guess this would half-solve your problem anyways, if that's okay :D

**Comment by Ellpeck** [comment]
My way to sorta solve this was closed in the latest commit °~°

**Comment by Belgabor** [comment]
Well, that's not bad, but I was specifically looking for a solution if you run out of filter slots in the relay/esd UI and want to transfer the information to a filter (item) to extends the filtering capacity =)
In particular if you're dealing with an item relay on a machine in a processing setup so you can't use the smart filter button.

**Comment by Ellpeck** [comment]
Yea, I got that, but I don't think there'd be a nice way to make that happen. You should just use a filter from the get go though! :P

**Comment by Belgabor** [comment]
Ah ok =)
I must have forgotten due to tiredness, but I was thinking of allowing you to click (or right-click) on the smart filter button with a filter item on the cursor to copy it. Not great, but an option :p

**Comment by Ellpeck** [comment]
Not really. None of the filtered machines except for the Item Interface have the Smart Filter button ;)

**Comment by Belgabor** [comment]
Doh! That makes sense =)

**Comment by Belgabor** [comment]
How about just right-clicking with the filter on the block? Should only work if the filter is empty so people don't accidentally overwrite the contents.
