### ISSUE TITLE
Advanced ESD whitelist Doesn't block hoppers/hopper conveyers from force adding Items to it

### ISSUE THREAD

**Issue by KialDaDial** [Ellpeck/ActuallyAdditions#433]
If you place a hopper on an ESD the ESD won't stop the hopper from adding its items into the internal buffer even if it has a whitelist or blacklist,this creates a problem with hopper conveyers which uses the style to push items into inventories.

**Comment by Ellpeck** [comment]
It's not supposed to.
The whitelist/blacklist is only for the ESD actively pulling/pushing.
