### ISSUE TITLE
Feeder Question

### ISSUE THREAD

**Issue by spiderkitten** [Ellpeck/ActuallyAdditions#434]
What is the range on the feeder? I have two pens next to each other, one with cows and one with sheep, the sheep pen doesn't have a feeder yet. The sheep keep eating from the cow's feeder. Even though the cows are standing closer to the feeder than the sheep, the sheep eat the wheat before the cows can. So I guess I was wondering what the range is. Thanks.

**Comment by canitzp** [comment]
takeba look into the actually addition manual you received

**Comment by Ellpeck** [comment]
5 Blocks radius :)
