### ISSUE TITLE
Cant interact with advanced item relays

### ISSUE THREAD

**Issue by Fr0mi** [Ellpeck/ActuallyAdditions#438]
First thing, cool mod.

Yet, I tried building a storage system and I cannot interact with the advanced item relays. No interface is showing up..

**Comment by Ellpeck** [comment]
Sneak-right-click with an empty hand.

**Comment by Fr0mi** [comment]
I just wanted to add. Shift+Right click, with an empty right hand does not interact with the advanced item relay, as long as you have a shield in your left hand.

**Comment by Ellpeck** [comment]
Oh, yea, that's a vanilla thing though. Can't do anything about that :(
