### ISSUE TITLE
Compost accepting too many items

### ISSUE THREAD

**Issue by joris0127** [Ellpeck/ActuallyAdditions#439]
I was playing direwolf20 modpack and wanted to make use off the hundreds of useless seeds i had. So i made a huge amount of bio-mass and made some fertilizers. Here is a imgur album with (i think) all pictures needed and some comments to explain it all.

http://imgur.com/a/4BWlO

Anyone knows what is happening?

PS: the thing that auto extracts the fertilizer are hoppers chain linked to a chest

**Comment by Ellpeck** [comment]
This actually has nothing to do with Extra Utils.

**Comment by joris0127** [comment]
it does because the node in extra utilit is suddenly capable of holding more then 1 stack of items. if i break it at 2000 internal items it also drops those 2000 items. So somehow it keeps adding items to its internal buffer over the supposed max amount limit

**Comment by Ellpeck** [comment]
It's still a bug on Actually Additions' side though.
The bug has nothing to do with Extra Utilities, it just happens *to* one of Extra Utilities' items.
