### ISSUE TITLE
Item Filters acting strange in the Advanced Item Relays

### ISSUE THREAD

**Issue by FluffyGoaty** [Ellpeck/ActuallyAdditions#440]
Love the mod!  The item filters seem to be acting strange in the latest Direwolf 20 pack.  If i put one into an advanced item laser relay, it seems to make a copy of itself, so there's one in the inventory of the relay and one in my inventory.  It also doesn't seem to filter.  Thanks again, and thanks for the cool mod!

**Comment by Ellpeck** [comment]
Filter slots only copy the item you put into them. That's not a bug.
Them not filtering is, however. Are you putting filters inside of filters? Because that doesn't work.
If you can't figure out the filtering bit, show me a couple of screenshots.

**Comment by FluffyGoaty** [comment]
Okay!  I figured out a better way to phrase it.  I'm trying to put the filter on a relay that's attached to a chest.  I was trying to put the filter into inventory of the relay, so i could use the smart filtering.  It's not using the filter though, it seems to be just leaving an imprint?  Maybe that's working as intended, and I don't understand.  Would I have to make an individual item filter for each relay?

**Comment by Ellpeck** [comment]
What?
It copies the item filter into the filter slot. And if you want to use that filter for the smart whitelist then, you just click the smart whitelist button. You can't take the copied item filters out of the slots if that's what you're asking. They're just copies. :)

**Comment by FluffyGoaty** [comment]
I understand now!   I thought I'd have to make a filter for each relay!  Kind of like an upgrade for each relay.  I was making it way harder than it is.  ;)  Thanks for the quick response, and the great mod (and being patient!)  I'm going with a canola powered base now!  Thanks again.
