### ISSUE TITLE
Sorting with "default" chest - Priority issue

### ISSUE THREAD

**Issue by Fr0mi** [Ellpeck/ActuallyAdditions#443]
I have a sorting system with advanced item relays on iron chests and one normal item relay also on an iron chest. 

This system works the way I imagine (Advanced item relays having a higher priority) when I connect the item relay from the input interface to the first advanced relay and then connect each of the relays on top of the chest with each other, ending with the "default" chest.

However if I connect the Laser from the input interface with the "default" chest laser first and then all the others, every item gets dumped into the "default" chest.

Is this intended?
I am playing on the direwolf20 pack newest version.

**Comment by Ellpeck** [comment]
Take screenshots showing this please.

**Comment by Fr0mi** [comment]
![setup2](https://cloud.githubusercontent.com/assets/9303498/20866200/5a73cc8c-ba27-11e6-93af-1242e2257f68.jpg)
![setup1](https://cloud.githubusercontent.com/assets/9303498/20866201/5a77519a-ba27-11e6-8e13-c29544f622a1.jpg)

Adding to this:
I have tried to break and rewire. Now I have the problem, that items from the iron chest on top of the esd, dont get sorted at all. As it does not seem to recognise the default chest.

All advanced item relays have filters in them. (Filters seem to get duplicated when put in the advanced item relay & destroyed when removing them)

**Comment by tigier** [comment]
Did you reassign the side config for the esd?
And the dublication is intended for now.

**Comment by Ellpeck** [comment]
1. Did you reassign the side config for the ESD or put its bounds to a really high number?
2. The Input Laser Relay is also trying to connect to the iron chest, which could cause an infinite loop of items instead of them going into one of the chests at the back.

**Comment by Fr0mi** [comment]
Yes i did. Nothing changes. What seems to fix it: Reconnect all laser relays with the one on top of the item interface, individually.
![setup3](https://cloud.githubusercontent.com/assets/9303498/20866230/4bf1503e-ba28-11e6-9561-10bb23fc3a4d.jpg)

**Comment by Ellpeck** [comment]
Update the mod to the newest version and see if that fixes your problem.

**Comment by Fr0mi** [comment]
Everything seems to be fixed. However, (I dont know if intended), but in the version r87 i cannot disable the laser visibility anymore.

**Comment by tigier** [comment]
It is intended since the lasers are pretty.
