### ISSUE TITLE
AOIT Crafting error and crusher output

### ISSUE THREAD

**Issue by 5kedone** [Ellpeck/ActuallyAdditions#444]
no output on stone AOIT recipe, plus crusher no longer pushes output to adjacent powered furnace  ? not sure if last one is a bug or memory is failing me lol

this is in mc 1.11 on ActuallyAdditions-1.11-r86

there i reported it on here ;-p

**Comment by tigier** [comment]
I can't remember the crusher doing that lately.

**Comment by Ellpeck** [comment]
"No longer"? It never did.
Do the other AIOT recipes work? Are all the input items at full durability?

**Comment by 5kedone** [comment]
See that's what I mean by my memory failing lol, and yeah others work so far and yep this is with full fresh made tools ?

**Comment by Ellpeck** [comment]
Is this in a modpack? 
Something makes shapeless recipes not work for some reason - do any other shapeless modded recipes work?

**Comment by 5kedone** [comment]
My own pack and other recipes are fine tried diamond iron versions of it and there fine , cant see anything else that should stop it ?

**Comment by 5kedone** [comment]
Woops lol

**Comment by Ellpeck** [comment]
Does it show in JEI?

**Comment by 5kedone** [comment]
Yep even adds the stuff to crafting grid , but no output lol

**Comment by Ellpeck** [comment]
Could you take a screenshot of the stone one and any other one in the crafting grid?

**Comment by 5kedone** [comment]
Don't worry just checked now and it's fine it was either a wierd mod int bug , (did updates few hours ago) or it was a config error (refreshed them) hummm sorry , I'm really trying to win that twat badge ain't I lol
