### ISSUE TITLE
Cross-mod crash w/ Translocators and Cooking for Blockheads

### ISSUE THREAD

**Issue by MrPipperz** [Ellpeck/ActuallyAdditions#446]
Using latest AA release (r88), Translocators 1-8 latest release (2.1.3.34) and latest CCC libraries, and latest Cooking for Blockheads release (4.2.26). Using latest forge #2171 (same crash results with #2099)

Attaching a Translocator to an Item Phantomface which is already bound to a CfBH kitchen multiblock (any of them seemingly, have tested several, same result) results in a crash a few ticks later.

Have tested in a new custom instance with only the required mods and libraries loaded (well, plus Blood Magic by mistake, but I doubt it matters), same result.

It is worth noting that Translocators seems to check whether it can properly interact with a container before allowing the block to place; they cannot normally be placed on the CfBH blocks.

Within the same instance and session I checked that the Phantomfaces were able to route items to the CfBH blocks with vanilla hoppers prior to attempting to place a Translocator on the Phantomface, this was successful each time.

Attempting to reload the world results in the same crash, effectively resulting in a "bugged" save.

I realize this is an odd corner case and that Translocators is most likely responsible, but given the unique nature of the Phantomfaces interactions I thought you'd appreciate a report.

Happy holidays!
[crash-2016-12-04_08.39.07-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/629646/crash-2016-12-04_08.39.07-server.txt)
[crash-2016-12-04_09.53.18-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/629647/crash-2016-12-04_09.53.18-server.txt)

**Comment by Ellpeck** [comment]
This is annoying. Another one of those bugs that got subtly introduced when changing the logic of the Phantomfaces. Meh. :v

**Comment by Ellpeck** [comment]
Fixed by https://github.com/Ellpeck/ActuallyAdditions/commit/79fce5c8795c30527cc17e47226bcf87694b18ed

**Comment by MrPipperz** [comment]
Good gravy, that was a fast fix! Looking forward to that release.

**Comment by Ellpeck** [comment]
There was a problem with r88 and so I had to reupload that to Curse and I snuck this fix into the version as well. Usually bad practise, but I had to reupload the file anyways so.. whatever :P
Just wait until it's approved and download it, and then you should be fine :)
