### ISSUE TITLE
Advanced Tooltips no longer seem to work?

### ISSUE THREAD

**Issue by al132** [Ellpeck/ActuallyAdditions#448]
Version: 1.10.2-r88
For the last version or few i've noticed that the advanced tooltips no longer seem to show up, even though I have them enabled in the config.
![capture](https://cloud.githubusercontent.com/assets/16395640/20868669/b6f62208-ba26-11e6-92d7-e5186c80a2ef.PNG)
![untitled](https://cloud.githubusercontent.com/assets/16395640/20868678/e72740b0-ba26-11e6-8800-50fdb3f5a263.png)

**Comment by Ellpeck** [comment]
Activate F3+H.
It says in the changelog.
