### ISSUE TITLE
hopper continually adds to compost bin 

### ISSUE THREAD

**Issue by 5kedone** [Ellpeck/ActuallyAdditions#449]
as above i have attached  screen shots and this one i think is a bug lol 

![2016-12-04_19 46 55](https://cloud.githubusercontent.com/assets/2697002/20868757/e88d6bf8-ba5a-11e6-87c8-490605a3be09.png)
![2016-12-04_19 46 58](https://cloud.githubusercontent.com/assets/2697002/20868758/e982e18c-ba5a-11e6-8ea3-2e3b7c0e158c.png)
![2016-12-04_19 47 02](https://cloud.githubusercontent.com/assets/2697002/20868759/ea862bca-ba5a-11e6-9bef-aae497351445.png)

**Comment by Ellpeck** [comment]
Already fixed :)

**Comment by 5kedone** [comment]
That's cheating lol
