### ISSUE TITLE
Particle effects on Empowerer kills fps on intel integrated graphics cards 

### ISSUE THREAD

**Issue by HenrikDK** [Ellpeck/ActuallyAdditions#455]
Hi, love the mod, it has a lot of neat ideas :)

I've been combining Refined Storage and Actually Additions to automate canola production, but i've noticed that the empowerer generally destroys my framerate when its running. I have attached 4 screenshots to illustrate the problem, usually I'm getting 30-40 fps on direwolf20's 10.2 pack. But when producing empowered canola, the framerate drops to 1-2 fps. Even when particles are set to "minimal":
All Particles
![particles all - 2016-12-05_23 27 58](https://cloud.githubusercontent.com/assets/1023686/20905441/1713138a-bb44-11e6-8bdd-3035f8dc4ac0.png)
![particles all - 2016-12-05_23 28 02](https://cloud.githubusercontent.com/assets/1023686/20905442/1713e5ee-bb44-11e6-8036-abe802e60775.png)

Minimal particles
![particles minimal - 2016-12-05_23 36 21](https://cloud.githubusercontent.com/assets/1023686/20905455/2662e2ac-bb44-11e6-877b-bd2fd78e0e37.png)
![particles minimal - 2016-12-05_23 36 24](https://cloud.githubusercontent.com/assets/1023686/20905456/26864b52-bb44-11e6-9344-36307d3d3c6c.png)

I've noticed that the "P:" value on the 5th line jumps to 2.5k, I assume that this is the number of particles that the animation generates, normally I haven't had problems with animations in modded MC, and 10.2 has in general been better performing than 1.7.10 on my system.

**Comment by Ellpeck** [comment]
Are you on the newest version? WIth particles set to minimal there should hardly be any rendering at all.

**Comment by HenrikDK** [comment]
Hi, Sorry for the late response, im running r70 which seems to be outdate. The action to turn down the particles is appreciated, though I'm still wondering why im not having the same kind of issue with effects heavy mods like azanor's thaumcraft.
