### ISSUE TITLE
Version update?

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [Ellpeck/ActuallyAdditions#457]
I am playing the 1.7.10 minecraft version 1.7.10-r21 of ActuallyAdditions and it's the most recent version for this pack for 1.7.10. Although it does give me a notification that there is an update for 1.11-r89. 
Which is pointless since I am playing on a 1.7.10 pack? 
Can this be removed?

**Comment by Ellpeck** [comment]
No, it can't be removed, but it can be disabled in the config via the "Version Specific Update Checker" option.
