### ISSUE TITLE
[Suggestion] Auto-Smelt addon for the drills

### ISSUE THREAD

**Issue by vertex101** [Ellpeck/ActuallyAdditions#458]
i would love to see an auto smelt addon for the drills :)

**Comment by Ellpeck** [comment]
This gives me a reason to, again, have to touch the awful Drill code from about 1,5 years ago and consider rewriting it all. So thanks for that.
But I like the suggestion, so I'll try to do it :P

**Comment by vertex101** [comment]
well if i knew java well enough i would help but i dont sorry :(

**Comment by bookerthegeek** [comment]
You could "borrow" some ideas from Tinkers I'm how they handle it. Seems to work pretty well.

**Comment by PapiDimmi** [comment]
What is the point of auto-smelt? It seems cool at first, but you should definitely crush your ores to double them, and auto-smelt makes this impossible. I unintentionally ruined a great pickaxe of mine by adding the Auto-Smelt achievement to it (Auto-Smelt is added by one of the mods I use, but I have no idea which).

**Comment by vertex101** [comment]
well actually if you look into auto-smelt with the use of fortune you can make alot more than you can by just crushing the ore to double it just FYI

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
