### ISSUE TITLE
[Suggestion] Improving Crusher & Furnace

### ISSUE THREAD

**Issue by homemmakako** [Ellpeck/ActuallyAdditions#460]
Although the double furnace is fast, it is not fast enough. Feel like it would be cool to have some kind of upgrade to the machines, as an item added to a specific slot (which would make it possible to add all sorts of upgrades such as energy, speed, efficiency, and so on) or add upgraded versions of the machines (crusher and double furnace) that worked like the induction furnace from IC2 (the longer it runs, the faster it works). Of course those are just some simple ideas, if anybody could come up with something more innovative would be much appreciated.

**Comment by OcAMD** [comment]
I use this mod to supply the RF for Furnus mod for just that reason with the furnace and crusher. The furnus mod starts with one slot and is upgradeable to 4 in both. It also allows for bonus, efficiency, xp, and speed upgrades to name a few. It allows to spread to cost out so it is useful in mid game to very efficient in late game.

**Comment by Ellpeck** [comment]
Closing this because #663 contains it and also has some more stuff
