### ISSUE TITLE
[BUG] Manual's font size is too small to see.

### ISSUE THREAD

**Issue by TartaricAcid** [Ellpeck/ActuallyAdditions#461]
### Just like the picture show.
![picture](http://i.imgur.com/4N8gBxv.png)

**Comment by 3TUSK** [comment]
@oldjunyi

**Comment by Ellpeck** [comment]
It.. it doesn't LOOK small?
Can't you just turn up your GUI size?

**Comment by Ellpeck** [comment]
How would I deal with this anyways? I mean, it's fine with the normal font.

**Comment by TartaricAcid** [comment]
It's full screen. (screen size: 1366×768)   
And it seems that occur only in Chinese.

**Comment by oldjunyi** [comment]
Minecraft does not have anti-aliasing font rendering method. Using non-integer GL scale ratio will break the font. A line with 0.9 pixel width may be 0 width when rendering.
This issue will be more obvious when you turn on the unicode font in language settings (or you are under some unicode-only language like Chinese), with the game's window height less than 960 px.

To fix this, my suggestion is: Please use 1.0x or 2.0x scale ratio when rendering the font.

**Comment by Ellpeck** [comment]
I can't.
I might add special case languages where the font is scaled at 1.0 though, if you tell me which that would be. That's the only possibility.

**Comment by 3TUSK** [comment]
Um, I remember you @oldjunyi use language file to control scale ratio in OpenBlocks? Could that also apply here?

**Comment by Ellpeck** [comment]
Oh, that's actually a good idea. I'll just do that.

**Comment by 3TUSK** [comment]
Ref: https://github.com/OpenMods/OpenBlocks/pull/655

**Comment by 3TUSK** [comment]
@TartaricAcid So you just need to update the `zh_CN.lang` now... Long missing update since BTM 16.2.

**Comment by TartaricAcid** [comment]
yes, you are right.    
But I be busy for my final. I will update the zh_CN file in January.

**Comment by 3TUSK** [comment]
![](https://thechive.files.wordpress.com/2014/12/finals-are-here-and-so-are-the-memes-xx-photos-7.jpg?quality=85&strip=info&w=600)

^ me irl
