### ISSUE TITLE
Item Distributor, Ranged Collector & ESD+Phantom Face Bugs

### ISSUE THREAD

**Issue by homemmakako** [Ellpeck/ActuallyAdditions#466]
Maybe I should create one issue per bug, but I feel like I would annoy Ellpeck too much by doing so 😝 

### Major Bug
1)  Item Distributor, as soon as the output inventories are full, will keep one item in it's buffer and won't stop importing items from the top inventory, **voiding all items it imports**. 

### Minor Bugs

2) Ranged Collector will stop collecting items as soon as all its slots were used, even if not entirely. For instance, if you put one single piece of cobblestone in every slot it won't pick up cobble neaby, even though one slot should be able to hold up to 64 items.

3) To put it simply, ESDs and Phantom Faces do not work together at all.  You can't push items into a Phantom Face using a ESD nor extract from it, even when the tooltip says "connection is fine and working" 

Anyways, these are all the bugs for todays, hope I helped 😄 (although I feel like I'm doing the opposite of helping 😅 )

**Comment by Ellpeck** [comment]
Are you talking about 1.10 or 1.11?

**Comment by Ellpeck** [comment]
If you're talking about 1.11, please test this in 1.10 and vice versa. Just to make sure. :v

**Comment by homemmakako** [comment]
All the bugs were found in 1.10. Will test them in 1.11 as soon as curse updates. For now I will close this issue and split it in three new ones, as requested
