### ISSUE TITLE
Advanced Item Information not working on latest edditons.

### ISSUE THREAD

**Issue by Oort-Cloud** [Ellpeck/ActuallyAdditions#467]
Last Three updates (r85 to 88) for 1.10.2 seems to have broke the ctrl Advanced Item Information.  It's simply not working.  I tested this on a fresh install with only AA.  The 11/29 file r84 works fine.

Forge:  12.18.2.2179

**Comment by tigier** [comment]
Use f3+h.
Should be doing it then

**Comment by Ellpeck** [comment]
Please always read the changelog before posting issue reports.
This was changed not too long ago, you now require the F3+H Vanilla Advanced Information to be enabled :)
