### ISSUE TITLE
Item Distributor Voiding Items

### ISSUE THREAD

**Issue by homemmakako** [Ellpeck/ActuallyAdditions#469]
Item Distributor, as soon as the output inventories are full, will keep one item in it's buffer and won't stop extracting items from the top inventory, voiding all items it extracts.

**Versions:**
MC: 1.10.2
Forge: 12.18.3.2185
AA: 1.10.2-r88

**Comment by homemmakako** [comment]
Was testing on 1.11 and the bug is still there. In fact I found somthing else as well. If there are more than two stacks on the top inventory, the distributor starts extracting from both stacks, but won't output the correct amount to the blocks it is connected to. If you put 2 stacks at the same time, it will only output 1 of the stacks. Same would happen whatever the number of stack you put in, as if it was counting the time it takes to extract the items and not the amount of items extracted.

**Comment by Ellpeck** [comment]
I am fixing it right now. Apparently this thing is totally broken :^)

**Comment by Ellpeck** [comment]
I know it isn't 1.10, but could you see if the issue is fixed in this version? Just download the one without any suffix :)
https://ci.chaosfield.at/job/ActuallyAdditions/job/ActuallyAdditions-unstable/446/

**Comment by Ellpeck** [comment]
Sorry, but for 1.10 bugfixes I'm worried I make an issue worse so I need a second opinion :P

**Comment by homemmakako** [comment]
ok, will download it (btw, I think I just found a crash. We will be best friends by tonight, trust me 😝)

**Comment by homemmakako** [comment]
Well.....it kinda worked, except it now duplicates a few items 😅 

![image](https://cloud.githubusercontent.com/assets/7462905/21026935/e8909328-bd75-11e6-808c-261d63aa2c0b.png)

![image](https://cloud.githubusercontent.com/assets/7462905/21026942/f39dd898-bd75-11e6-9279-c0f2248d09de.png)

![image](https://cloud.githubusercontent.com/assets/7462905/21026923/da5addae-bd75-11e6-91cd-abbe4161a4d7.png)

![image](https://cloud.githubusercontent.com/assets/7462905/21026972/0b1fc026-bd76-11e6-9f89-0a437690252b.png)

![image](https://cloud.githubusercontent.com/assets/7462905/21026989/189f12e2-bd76-11e6-9a95-20c7f6e968d0.png)

![image](https://cloud.githubusercontent.com/assets/7462905/21027017/345d9bde-bd76-11e6-9d30-6e3099daf9a0.png)

**Comment by Ellpeck** [comment]
Ugh. Fixed that too. :v

**Comment by homemmakako** [comment]
LOL
Thanks, bro. You rock!
