### ISSUE TITLE
ESDs+Phantom Faces do not work...at all

### ISSUE THREAD

**Issue by homemmakako** [Ellpeck/ActuallyAdditions#471]
To put it simply, ESDs and Phantom Faces do not work together at all. You can't push items into a Phantom Face using a ESD nor extract from it, even when the tooltip says "connection is fine and working"

**Versions:**
MC: 1.10.2
Forge: 12.18.3.2185
AA: 1.10.2-r88

**Comment by homemmakako** [comment]
Just tested on 1.11 and it works fine

**Comment by Ellpeck** [comment]
They DO work, they just won't assign their slots appropriately by default, so you need to set them yourself, and then it's fine.
But this works in 1.11?

**Comment by homemmakako** [comment]
ohh, ok. And yes, in 1.11 the esd sets the slot number automaticaly
