### ISSUE TITLE
Crash when connecting ESD to a laser network [1.11]

### ISSUE THREAD

**Issue by homemmakako** [Ellpeck/ActuallyAdditions#472]
![image](https://cloud.githubusercontent.com/assets/7462905/21027545/5f3b2cb6-bd78-11e6-8295-32331bf8f1fc.png)

(I've been rather annoying lately, haven't I)

I just crashed on 1.11 after trying to connect a ESD to an Item Interface linked to a chest by Item Laser Relays

[Crash Log](http://pastebin.com/1GwcN8Vd)

I swear I won't create a new issue for a few days

**Comment by Ellpeck** [comment]
Is this 1.11 only?

**Comment by Ellpeck** [comment]
Oh, this was introduced by a fix I suggested to Forge. Great job, me :'D
