### ISSUE TITLE
drill acting somewhat erratic

### ISSUE THREAD

**Issue by DoomSquirter** [Ellpeck/ActuallyAdditions#473]
ActuallyAdditions-1.10.2-r88
forge-1.10.2-12.18.2.2171
playing MechMagic pack on ATL

Used the drill with 3 speed upgrades, silk touch and 3x3 mining.  worked fine. used it for hours earlier.

I removed the third speed upgrade and added the 5x5 mining.  If I mine a solid block it works fine.  but if I hit gravel, it mines just the single gravel, not 5x5.  what's even weirder is if I hit the gravel from a different angle, it mines it just fine.  note that this is gravel that falls down after mining a 5x5 area, this part might be important.  

so to try to reitterate, the specific gravel that is at your cursor where you just mined blocks, but then a group of gravel fell, using the 5x5, it just mines the single gravel not a 5x5 area.  

Even if I place a normal block down (solid block) it won't mine it 5x5 either.  I have to clean up the gravel with another pick and continue on.

Did not have any issues whatsoever doing 3x3.

I have 2 speed upgrades, silk touch, 3x3 and 5x5 mining all on drill when this behavior manifests itself.

**Comment by DoomSquirter** [comment]
ok, so can something like this be intermittent?  I had tested this for 30-40 minutes and checked your changelog and looked up issues regarding 'drill' and then posted the issue.

Went immediately back and used the drill again and now it's working just fine, same scenarios that I listed above.  The only thing I did was I had put the drill in my bag while testing and pulled it out again to try one more time.  

I'll leave it up to you to close issue if you feel it's needed.  If it happens again, I'll post here.

**Comment by Ellpeck** [comment]
Doesn't have to do with the angle. What's happening here is that the 5x5 upgrade is targetting the block above the one you hit, so that it can create the 5x5 hole at the height your player is standing. This creates the problem that if you harvest a block that has no one above, proper harvesting won't occur. Or something like that.

But to be honest, I don't really feel like fixing this because so many people annoyed me about the fact that the drill should mine one block higher with the 5x5 upgrade that I just think it's funny that this is happening.

**Comment by DoomSquirter** [comment]
oh I see what you're saying.  yeah, draconic does it same as you, mine directly in front of you but it can go up to 9x9x9 or so, which would make mining at the center spot pretty hard to accomplish.

If I were you, I'd stick with the eye height level to aim for.  tbh, it makes it so much easier to mine that way, but then you have to deal with other circumstances (pointing up/down) where I think you still go for center block there, which I think you should.

My opinion tho is that's a much better way to do it versus going for middle of block when you're mining non vertically.
