### ISSUE TITLE
Farmer - Seeds pop out of the ground

### ISSUE THREAD

**Issue by Hirsu** [Ellpeck/ActuallyAdditions#474]
I'm trying to use a farmer to work on a 9x9 area, kept fertilized by worms. The farmer should plant canola seeds and harvest the canola when fully grown. 

For some reason, about half of the seeds which get planted immediately pop out of the ground. It's easier to visually represent what I'm trying to describe here, so I recorded a [short video](https://youtu.be/LmK0JODpHuA) of the issue. Carrots, potatoes or regular seeds gave the the same issue.

The modpack I'm playing is All The Mods version 1.50, which is currently running Actually Additions 1.10.2-r88. Please let me know if you need more info.

**Edit:**

Right after writing up this report, I put light sources all around the farming area and the seeds got planted correctly, without them popping out. So apparently, the area needs to be lit up correctly for the farmer to work. Is this vanilla behaviour (in which case I apologise for derping up) or is this just how the farmer works?

**Comment by Ellpeck** [comment]
This is Vanilla Behavior. Seeds can't be planted in a light level below, I think, 5 or 6.

**Comment by Hirsu** [comment]
Then I'm terribly sorry for bothering you with this report, it looks like I had a serious case of direwolfitis :)

**Comment by Ellpeck** [comment]
Mistakes happen. Don't beat yourself up over it :P
