### ISSUE TITLE
Farmer 

### ISSUE THREAD

**Issue by vertex101** [Ellpeck/ActuallyAdditions#476]
i have made the farmer to setup a farm for canola for making oil for my power gen and i have notice that when the farmer harvests the crops that the seeds go into the export slot even though the seed inventory is not full and it makes it a pain to have to keep moving the seeds over to where they need to be instead of it doing it on its own

**Comment by Ellpeck** [comment]
I have noticed that people report issues with outdates mod versions and it makes it a pain to manage this issue tracker.

Update the mod.
