### ISSUE TITLE
Energy lasers not placing on tile entities

### ISSUE THREAD

**Issue by HEtsunami** [Ellpeck/ActuallyAdditions#478]
Actually Additions 1.10.2-r87
Direwolf20 1.10 pack 1.1.2

When I try to shift place a energy laser relay (I've only tried it with energy lasers) on a tile entity the item places then disappears instantly and when i open the GUI of the tile entity it goes back into my inventory. So far I've been able to repeat this with vanilla chests as well is Iron Chests, energy capacitors from Ender IO and the farmer from actually additions.

**Comment by Ellpeck** [comment]
Try to reproduce this with just Actually Additions installed.

**Comment by Ellpeck** [comment]
Do you have an iron back pack on? 
If so, remove it and try again.

**Comment by HEtsunami** [comment]
haven't tried to recreate it with just actually additions but taking off my back pack makes it stop plus it does it with every tile entity being placed on another tile entity, must be a problem with iron backpacks, sorry for wasting your time dude XD
