### ISSUE TITLE
Add Battery Box block

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#479]
- Input ONLY batteries into it to make it store energy depending on the storage capacity of the battery
- Make the Crafting Recipe require an Energizer and an Enervator

**Comment by IamAlathe** [comment]
Storage for power?  I like it!

**Comment by AntonLTea** [comment]
good idea, very need batterys

**Comment by Ellpeck** [comment]
wait I did this
