### ISSUE TITLE
ActuallyAdditions directly spawns in EntityItems during LivingDropsEvent

### ISSUE THREAD

**Issue by Aaron1011** [Ellpeck/ActuallyAdditions#480]
Currently, ActuallyAdditions directly calls `Entity#entityDropItem` in [several LivingDropsEvent handlers](https://github.com/Ellpeck/ActuallyAdditions/search?utf8=%E2%9C%93&q=entitydropitem). This is breaking mods such as [SpongeForge](https://github.com/SpongePowered/SpongeForge/issues/1102) which rely on EntityItems being added to the `LivingDropsEvent#getDrops` list by other event listeners.

If you could change the listeners I linked to add `EntityItem`s to the event drops list, rather than immediately spawning them in, I'd be very appreciative.

**Comment by Ellpeck** [comment]
I talked to a lot of modders about this and most of them said that both ways are fine.
Also, I don't support SpongeForge normally.

Is this really necessary?

**Comment by Aaron1011** [comment]
While both ways will produce the desired result with plain Forge (the entity will be spawned into the world), avoiding using the event is generally discouraged.

**Comment by Ellpeck** [comment]
Ugh. I will update this, but not for 1.10 because it's not a major important bug. So sorry.
Plus, my opinion still is that this is also partly a Sponge issue that should be fixed, because it alters the Vanilla/Forge behavior.
