### ISSUE TITLE
Shift-clicking block of charcoal out of Tinker's crafting station, charcoal disappears

### ISSUE THREAD

**Issue by Ricket** [Ellpeck/ActuallyAdditions#481]
Put 3x3 of charcoal into tinker crafting station. Shift-click the block of charcoal. Expected it to go into inventory but instead it disappears. Tried the exact same with a normal crafting station and it worked fine.

Playing Direwolf20 1.10 pack version 1.1.3 (forge 2171, Actually Additions r88, TConstruct 2.5.6b).

**Comment by Ellpeck** [comment]
Do you have a storage container next to the Crafting Station?
Shift-clicking prioritizes that over the inventory for some reason.

**Comment by Ellpeck** [comment]
I will close this as there was no response. Reopen this issue if it's still a problem.

**Comment by Ricket** [comment]
Thanks, maybe that was it. I had it between a trash can and a Mekanism machine. Not sure which one was eating the charcoal, maybe the trash can would steal it.

**Comment by bookerthegeek** [comment]
That would suck... I'll have to ask on how to block prioritization of a garbage can from the table.
