### ISSUE TITLE
Books deleted with disenchanting lens

### ISSUE THREAD

**Issue by Darkere** [Ellpeck/ActuallyAdditions#482]
When dropping more than one book on the ground when disenchanting items with the Disenchanting lens any excess books will get deleted.

**Comment by Ellpeck** [comment]
Which Minecraft version does this happen on?

**Comment by Darkere** [comment]
Oh forgot this again. On 1.11.

**Comment by Simon-Bitdiddle** [comment]
Can confirm this on 1.10 minecraft, ver 1.10.2-r88 of ActuallyAdditions, as part of the Direwolf20 1.10 modpack, version 1.1.3

**Comment by Justie1220** [comment]
I have also had this happen on the FTB HermitPack 1.10.2. I would place three books down to remove 3 enchants off a piece of armour and would end up with one book with one enchant on it and the other books were deleted.

**Comment by Ellpeck** [comment]
Please stop posting in this issue report :v
If it's the same mod version, the same issue will obviously also occur :P
