### ISSUE TITLE
[Balance] Coal Generator more efficient than other mods' equivalent

### ISSUE THREAD

**Issue by Compegen** [Ellpeck/ActuallyAdditions#484]
Was testing efficiency of different tech mods to see what combination of Generator, Crusher, and Furnace would be the most efficient and found out that this mod's Coal Generator produces 3x the amount of RF of most other mod's equivalent.

Mod | Machine | RF from 2 sticks
------------ | ------------ | ------------
This mod | Coal Generator | 6000RF
EnderIO | Stirling Generator | 2000RF
ExtraUtils | Furnace Generator | 2000RF
Draconic Evolution | Generator | 5712RF
TechReborn | Generator | 2000RF

On a side note, the Crusher & Powered Furnace is the same efficiency as most other mods (4000RF & 2000RF per operation, with only EnderIO beating this slightly with 3600RF & 1600RF respectively)

**Comment by canitzp** [comment]
have you tested rftools? their coal generator produces 60RF/T so thisbis nothing and as far as I know does the actadd coal gen 40RF/T and this would equal 48000RF per coal

**Comment by Compegen** [comment]
Just tested RFTools. They're machine actually produces _less_ than Actually Additions (2x rate, instead of 3x).

(Also have no idea now how Draconic Evolution decides to produce energy)

Mod | RF from 1 coal
---- | ----
This mod | 48K RF
EnderIO | 16K RF
ExtraUtils | 16K RF
TechReborn | 16K RF
Draconic Evolution | 50.6K RF
RFTools | 36K RF

**Comment by Ellpeck** [comment]
You used the right word: "Efficient". It also generates less per tick than most other generators.
I don't see an issue here.
