### ISSUE TITLE
Suggestion, allow boomerang to be enchanted.

### ISSUE THREAD

**Issue by Jenral** [Ellpeck/ActuallyAdditions#485]
As the title says, allow the Boomerang to be enchanted with the bow enchantments.  This would make the pretty awesome boomerang, totally super duper awesome :)

**Comment by tigier** [comment]
Well....what would Infinity do then?

**Comment by bookerthegeek** [comment]
You know how hard it is to get a boomerang to come back on the first throw? Infinity just make you an expert right off the bat of course. ;)

**Comment by Ellpeck** [comment]
...Boomerang..?

**Comment by Jenral** [comment]
Sorry my bad, I was mistaken the Boomerang is from Extra Utilities 2, not your mod.
