### ISSUE TITLE
Loot chest item balance

### ISSUE THREAD

**Issue by xenoflot** [Ellpeck/ActuallyAdditions#486]
Hi Ellpeck,

Is there anything that can be done (at my end or yours) about the balance of loot in village chests, etc. ? More than once in my current game I've found a chest containing 3 or 4 AA manuals and 5 or 7 stacks (containing 1 or 2) of black quartz.

I'll never need that many manuals and it'd be nice to see a broader range of mods represented in a chest.

Thanks!

**Comment by Ellpeck** [comment]
Ugh, making loot is such a pain. I specified it to be only one book at most per thing, but apparently I did it wrong >_>
