### ISSUE TITLE
farmer not compatible with crops?

### ISSUE THREAD

**Issue by popps73x** [Ellpeck/ActuallyAdditions#488]
A little disappointed that the farmer is not compatible with many crops in minecraft.  I understand there are too many mods to add support for them all.  here are a few that i think need to be added however.  Netherwart.  this is vanilla man.  ender lilys and red orchids from extra utils 2.  Pams harvestcraft although that is a big job.  Would you consider an advanced farmer?  that could do 9 separate rows of crops?  I find i rarely need a full 9x9 of anything and I think this could be really useful.  also it does not seem to generate the crop drops from roots.  thanks for your consideration.  keep up the great work.  :)

**Comment by Ellpeck** [comment]
I won't be adding any more features into 1.10.
1.11 already supports Nether Wart, and when the mods you are talking about come out for 1.11 (It's taking them their sweet time! :P) I will definitely try to add support for them. I couldn't before as I never had a proper API for the Farmer and I only implemented it in 1.11.
It'd be nice if you could open another issue for when that time has come though, if you think about it, as I don't really want to have this issue waiting around until then :)

**Comment by popps73x** [comment]
Good to know.  I did not realize your 1.10 was feature complete.  I will try to remember when 1.11 reaches that point.    thanks again.

**Comment by 7OOTnegaTerces** [comment]
So, just to be clear, the farmer in 1.10 does not do nether wart, but the farmer in 1.11 does?
