### ISSUE TITLE
connecting to any machines in AA

### ISSUE THREAD

**Issue by JerryAZ** [Ellpeck/ActuallyAdditions#489]
i have just upgraded to .90 and it was happening in .89
trying to connect to a few AA machines won't accept the block

tried to place a hopper on a canola press won't not connect
tried to place energy relays on a capacitor back would not connect
tried to place a capacitor bank on a coal generator with 2 other machines on either side would not connect
tried to put a button on a atomic reconstructor would not connect

**Comment by Ellpeck** [comment]
Modpack, other mods, logs, crash reports, screenshots, a video?
I need something like to be able to fix bugs :)

**Comment by Ellpeck** [comment]
Do you have Iron Backpacks installed?
If so, try to remove the backpack and try again.

**Comment by JerryAZ** [comment]
was in the direwolf 1.20 modpack - i teleported away and back and it was connecting to everything i was trying before

**Comment by Ellpeck** [comment]
Okay..? Then I guess it's just a desync bug. Doesn't seem like an issue on my side.
