### ISSUE TITLE
Item lasers not not working.

### ISSUE THREAD

**Issue by HeavyDeception** [Ellpeck/ActuallyAdditions#490]
I have a Sorting system with item Lasers but things seem to get stuck and don't go anywhere.

(also I could be a dummy)

**Comment by HeavyDeception** [comment]
http://puu.sh/sOGKI/d2fb47311c.mp4

**Comment by Ellpeck** [comment]
Is the Input Laser Relay connected back to the ESD or the input chest by any chance? Is the Last Resort chest Laser on an empty input blacklist? Did you read the manual to confirm that this is actually an issue?
Because I cannot reproduce it.

**Comment by HeavyDeception** [comment]
http://puu.sh/sP9h3/948965ea2a.mp4

**Comment by Ellpeck** [comment]
Is the ESD set to the right amount of slots? It seems like there's way more available space than just the ~700 slots you have set.

**Comment by HeavyDeception** [comment]
That was it. Sorry about that I was thinking it would update itself.
