### ISSUE TITLE
crash when breaking furnitures from furnitures mod

### ISSUE THREAD

**Issue by Hypsellis** [Ellpeck/ActuallyAdditions#492]
I get sometimes this crash when trying to break some furnitures from Furnitures mod. http://pastebin.com/3Gn8vjwM

**Comment by Ellpeck** [comment]
FROM Furnitures mod? With which item? What's in the surrounding area?

**Comment by Hypsellis** [comment]
Wait, I will try to provocate the crash again.

**Comment by Hypsellis** [comment]
It happens with cabinets.

**Comment by Ellpeck** [comment]
That didn't answer my questions.

**Comment by Hypsellis** [comment]
It happens anywhere, it doesn't depend of what there is around, neither with which tool I break it.

**Comment by Ellpeck** [comment]
Uninstall OptiFine and try again.

**Comment by Hypsellis** [comment]
It doesn't change anything. :(

**Comment by Ellpeck** [comment]
Does it happen with any other blocks?
The crash log you sent has to do with a Black Quartz Slab.

**Comment by Hypsellis** [comment]
I use an unofficial build since MrCrayfish still didn't update it officially for 1.10.2. The mod is a bit unstable but still works fine. I get another crash linked to furnitures with draconic evolution, maybe both crashes come from the same problem. https://github.com/brandon3055/Draconic-Evolution/issues/488

**Comment by Hypsellis** [comment]
No it doesn't, but now I think about it, when I break the furnitures, the particles and noises aren't the good ones, surely a bug from furnitures.

**Comment by Ellpeck** [comment]
This very much seems like a Furniture Bug. I will close this for now as it seems not reproducable without Furniture.
