### ISSUE TITLE
Dropped Item Conversion Failure

### ISSUE THREAD

**Issue by ph1x3r** [Ellpeck/ActuallyAdditions#501]
The atomic re-constructor fails to transform items when they are dropped in-world  in front of it.

In order for the conversion to work, the items have to be a maximum of two blocks in front of a solid block of some sort and the laser fired towards that block. The block type is irrelevant.

To reproduce, place a dirt block 3 spaces away from the re-constructor and then drop coal/canola in front of the re-constructor. Nothing happens. Drop the item in the middle space or up against the dirt block and it will convert as expected.

**Comment by Ellpeck** [comment]
Read the book.
