### ISSUE TITLE
[1.11] ActuallyAdditions version 1.11-r91 - Pickaxe voids Atomic Reconstructor & Fermenting Barrel

### ISSUE THREAD

**Issue by shortybsd** [Ellpeck/ActuallyAdditions#502]
Forge version 2188
ActuallyAdditions version 1.11-r91
Not for sure if a wrench should be used, as I know the laser wrench is only for lasers. When trying to break an Atomic Reconstructor, Fermenting Barrel and a few of the lasers. I will let you know exactly which lasers it is. This was tested with an Iron and Diamond pickaxe. Also tried an axe on the barrel, same issue.

**Comment by Ellpeck** [comment]
Can't reproduce.
Modlist?

**Comment by Ellpeck** [comment]
Are you trying to mine the ones inside the Villager house? If so, please read the book.

**Comment by shortybsd** [comment]
It was another mod messing with it! Sorry about that,
