### ISSUE TITLE
[Bug] fermenting barrel entity tick when placed next to a bottler

### ISSUE THREAD

**Issue by MvanRietschoten** [Ellpeck/ActuallyAdditions#503]
Hello, I had to remove the fermenting barrel with a nbt editor to make the world playable again, (I actually deleted the whole chunk for it to work again...). Here is my bug report: http://pastebin.com/Lf1MPQ1f

It looks like the null pointer exception is from the fermenting barrel while it says the forestry bottler is involved here.

Awesome mod btw 👍

**Comment by Ellpeck** [comment]
This might be a bug with Forestry so @mezz might be to blame, but I am not 100% sure. :P

**Comment by mezz** [comment]
Looks like a Forestry issue, I pushed a fix for it today. 
I recommend you add a check on your side too even though it was probably Forestry's fault
