### ISSUE TITLE
Traveler's Sack = duplication

### ISSUE THREAD

**Issue by shellbobell** [Ellpeck/ActuallyAdditions#504]
The traveler's sack is duplicating items.  If you break an item and it's designated to go into the sack, it duplicates it.

**Comment by canitzp** [comment]
Which mc version are you on and which Actually Additions version. Can you upload a log file too?

**Comment by shellbobell** [comment]
I'm on a server, running direwolf20, actually additions version 1.10.2-r88, 
[ActuallyAdditions-1.10.2-r88.zip](https://github.com/Ellpeck/ActuallyAdditions/files/664019/ActuallyAdditions-1.10.2-r88.zip)

**Comment by Ellpeck** [comment]
Some mod is screwing with the ItemPickupEvent. Remove mods until the issue is gone to find out which one it is.

**Comment by shellbobell** [comment]
Sorry, I was just reporting the bug.  I don't have time to sit there figure out which mod is interfering.  Good luck!
