### ISSUE TITLE
Make the auto feeding of the farmer optional

### ISSUE THREAD

**Issue by Tridon343** [Ellpeck/ActuallyAdditions#506]
The farmer is a very neat block - it used to put all harvested seeds into the output buffer and not feed directly into the seed buffer if it could.
Now it places all seeds into the internal buffer

Please make this behavior optional. (with a redstone torch or with a config in the folder.

Reason:
Making a multi purpose farm - that changes what seeds are planet according to the needs is very hard to pull of. If you can rout all harvested seeds into the output and have an automation decide what goes into the buffer that would be great.

**Comment by Ellpeck** [comment]
No, sorry.
