### ISSUE TITLE
item id conflict and a feature request

### ISSUE THREAD

**Issue by Tenchu98** [Ellpeck/ActuallyAdditions#508]
First:
The crystallized canole seed and the canola oil show as a misc item when trying to use rftools filter module. This is causing sorting errors in the system.

I would like to request a fluid storage tank of some sort, as I am trying to limit the number of mods I run and prefer to keep the features flawlessly working together.

**Comment by Ellpeck** [comment]
The first thing is a problem with RFTools. They *are* both a misc item, you just need to filter them by metadata.
And you don't need a fluid storage tank for using Actually Additions and I don't currently plan on adding one, sorry.
