### ISSUE TITLE
Axe upgrade for Drill

### ISSUE THREAD

**Issue by Zettt** [Ellpeck/ActuallyAdditions#509]
This is probably already on the roadmap but I wanted to request it anyway. I'd love to have a simple "axe" upgrade (for trees and wood-based items) on the drill. I don't really like the AIOT's, but the drill is right up my alley. It would be helpful if I could ditch the axes, I carry around, too.

**Comment by Ellpeck** [comment]
This has been requested a couple of times, but it's on the list of features I don't want. Sorry.

**Comment by tigier** [comment]
How about a little compromise: you could add a second RF powered tool. E.g. "the farmers tool" combining axe and hoe ( maybe even adding something like a watering can), and upgradeable with augments.

It's just an idea.

**Comment by Zettt** [comment]
I'd like that.

**Comment by Ellpeck** [comment]
No.
