### ISSUE TITLE
[Bug]Laser relay server crash

### ISSUE THREAD

**Issue by MysticAura** [Ellpeck/ActuallyAdditions#510]
MC: 1.10.2
Forge: 2185
Mod: ActuallyAdditions-1.10.2-r90

Multiple server crashes all morning.
[Crash Log](http://pastebin.com/si0Lgkpx)

**Comment by Ellpeck** [comment]
This probably isn't Actually Additions at all. It's in the log because this is what was running when the Server Watchdog noticed a stall. It isn't necessarily connected.
Please try to pinpoint this to Actually Additions, and if you can't, please close this issue :)

**Comment by Ellpeck** [comment]
I'm closing this because there was no response. If this issue occurs again, reopen this please.
