### ISSUE TITLE
Farmer can't harvest many crops

### ISSUE THREAD

**Issue by ShadwDrgn** [Ellpeck/ActuallyAdditions#513]
It would be nice if the farmer supported any crop that can be right clicked to harvest. I've noticed so far it does not support:
Nether Wart
Ender Lily
Red Orchid

Also it would be nice if it would NOT auto till the dirt, so that I can have farms of custom size as long as it's within there range without having to remove any tillable land. Perhaps a configurable size would work, too,

**Comment by Ellpeck** [comment]
This is all a feature in 1.11 and won't be in 1.10. Sorry.

**Comment by TomyLobo** [comment]
The farmer still can't farm Ender Lilys in 1.12.1-r119 :)

**Comment by TomyLobo** [comment]
hrm, hold on, now it stopped working on redstone orchids as well...

**Comment by TomyLobo** [comment]
Oh, never mind, it only operates on stuff in front of it.
