### ISSUE TITLE
[1.10.2] [Suggestion] Black Lotus should give 1 dye instead of 2

### ISSUE THREAD

**Issue by SnowShock35** [Ellpeck/ActuallyAdditions#515]
Hi Ellpeck,

Just wanted to quickly feedback/suggest something within Actually Additions. . . 

In the current version, the black lotus, a substitute for ink sacks in the form of a 1-block-tall flower that crafts into black dye. However, currently it gives two black dye which if you look at all the other single block  tall flowers they give a single dye. Personally, I feel it would be better to keep with consistency. They generate fairly often as well so it's not as if you're in lack of them and as an alternative to ink sacks it is still great even if it gives one. 

Anyway, just a personal suggestion on my part :heart:

**Comment by Ellpeck** [comment]
Meh, I never really liked the change with flowers giving only 1. I know it'd be inconsistent, but I'll leave it like it is.
