### ISSUE TITLE
[1.10.2] [Possible Bug] Empowerer Item Take/Place Handling

### ISSUE THREAD

**Issue by SnowShock35** [Ellpeck/ActuallyAdditions#516]
Hi Ellpeck,

A quick minor-ish issue with Actually Additions in Minecraft 1.10.2, here's the details. . . 

### Important Information

- Minecraft 1.10.2
- Minecraft Forge 12.18.3.2185
- Actually Additions 1.10.2-r90

### Issue Details

In this version of Actually Additions, when you remove an item from the empowerer block you require an empty hand. So, if you're wanting to craft more than one, you make one then stick it in your inventory and the hope is that when you take the second one off the stand it **should** stack with the one already existing in your inventory. However this isn't the case. It just puts it into the slot on your hotbar that you clicked with. This might not be seen as a bug from your perspective, hence why I labelled it as _possible bug._

**Comment by Ellpeck** [comment]
It's not a possible bug. It requires *either* an empty hand *or* the exact item to be already present in your hand. This is the way that it makes sense to me.
