### ISSUE TITLE
Server craches

### ISSUE THREAD

**Issue by dinoking1711** [Ellpeck/ActuallyAdditions#517]
I keep having a server crash after using the spawner changer (WitherSkeleton).
The spawner has no mob inside (rotating one in the cage) and it type says air.
I have a small amount of time to do stuff before i crash.
I'm thinking this is because it only crashes when it (tries to) spawn a mob.
Here are some fotos the seconds before it went wrong
http://imgur.com/a/b2L8w
Ps: I have used not enough wands to transport a spawner, but haven't done so after changing the type.

**Comment by Ellpeck** [comment]
Crash Report..?

**Comment by dinoking1711** [comment]
I can't give you a crash report because its not my server and when i try and replicate it in singleplayer nothing happens the spawner only becomes the air spawner.

**Comment by Ellpeck** [comment]
I can't do anything without a crash report.

**Comment by tigier** [comment]
Whose is it then?

**Comment by dinoking1711** [comment]
Akernator
