### ISSUE TITLE
[Bug] Mechanical User and Solid. XP

### ISSUE THREAD

**Issue by Bellwar** [Ellpeck/ActuallyAdditions#519]
I wrote about it on ExU site and sorry I have no idea how to tag you or reference it here better then sending link to that report. I have no idea who's problem it is.

https://github.com/rwtema/extrautilities/issues/1182

**Comment by Ellpeck** [comment]
This is an ExUtil problem that has been reported before. But judging by the issue tracker over there, it'll probably take ages to fix. :v

**Comment by Bellwar** [comment]
Nice so I lost my world \o/ any idea how can I get rid of the block? Tried forge didn't help. And yes I saw something about it before though it got patched...

**Comment by Ellpeck** [comment]
Did you try Forge's removeErroringTileEntities option? If so and it didn't work, you will have to use MCEdit.

**Comment by Bellwar** [comment]
I tried it and it sent me crash with comparing or something with "...= "P" " I didn't care. Ok, will try to get MCedit on this PC. Thanks.
