### ISSUE TITLE
[Minor] Click for download sends to wrong link

### ISSUE THREAD

**Issue by PWTordenskiold** [Ellpeck/ActuallyAdditions#520]
When informed of a new version available it gives "Click for download".  Redirect from ellpeck.de/actadddownload sends you to minecraft.curseforge.com/mc-mods/228404-actually-additions/files("We were unable to find the page or file you were looking for."), while correct link now is minecraft.curseforge.com/projects/actually-additions/files.

**Comment by Ellpeck** [comment]
I didn't even know this was changed.

**Comment by Ellpeck** [comment]
There we go, fixed! :D Thanks.
