### ISSUE TITLE
[1.10.2] Some errors loading SMP in server logs - no crash so far

### ISSUE THREAD

**Issue by Gepett0** [Ellpeck/ActuallyAdditions#524]
Hi Ellpeck,

just updated to r93.
After finishing laoding up the server i got the following lines in the log:
http://pastebin.com/Ls8556sU

Maybe u could have a look at this?
No crash so far.

Frohe Weihnachten,
Gepetto

**Comment by Ellpeck** [comment]
This is weird. Does it happen every time? And does it only happen with the Oil Generator? (Looking at the TileEntityOilGenerator part of the log)

**Comment by Ellpeck** [comment]
Also, does it happen on Singleplayer? And before r93?

**Comment by Gepett0** [comment]
Hi again,

didn't see this on r90.  Haven't treid SP.
Maybe its some problem with the FTB Util chunklaoding feature, cause i updated this also.
Server runs fine so far, no problems, oil generator working fine, no further error logs.
I will report back when i restart the server the next time ( don't want to bother the players when its doing fine :-) )

G.

**Comment by Ellpeck** [comment]
This is sort of important to me. Is it possible for you to do further investigation on a different server? Maybe try with and without other mods you think could produce this.

**Comment by Ellpeck** [comment]
Were you able to reproduce this?

**Comment by Ellpeck** [comment]
If you manage to reproduce this, please reopen this issue. For now, I will close this as it appears this might have been a one-time thing :)
