### ISSUE TITLE
Redstone Flux Arsenal charger not charging stuff from the mod

### ISSUE THREAD

**Issue by LocoMinerDad** [Ellpeck/ActuallyAdditions#525]
Hi There,

I used to be able to charge armor and weapons from Redstone Flux Arsenal  with your charger. Now it doesn't work. Can you fix it?

Thank you

**Comment by Ellpeck** [comment]
Minecraft version, mod version etc.?

**Comment by Ellpeck** [comment]
Is this 1.11? If so, RF isn't supported anymore in 1.11.

**Comment by LocoMinerDad** [comment]
OK well it worked on a older 1.11 minecraft world. Yes Minecraft 1.11, forge .2189. Your mod 1.11-r92. Their mod -1.1. Maybe I am not using the correct terminology. Their mod lets you make stuff that can get charged, like your drill. Their stuff doesn't charge in your charger.

**Comment by Ellpeck** [comment]
When did it stop working?

**Comment by LocoMinerDad** [comment]
Today? I just made the armor set and it wont charge in the charger.

**Comment by Ellpeck** [comment]
With which version..

**Comment by LocoMinerDad** [comment]
The version I already posted above.

**Comment by Ellpeck** [comment]
But you said it worked on 1.11 before. So switching from which version to which version makes it stop working?

**Comment by LocoMinerDad** [comment]
yours r91 his -1.1. I went back there after being gone a month its not working there now either. cant you add a code to accept his armor and weapons

**Comment by raoulvdberge** [comment]
I'm confused

**Comment by Ellpeck** [comment]
Not if you tell me which Actually Additions version this worked with, and then which one it stopped working with. Answer my questions and I fix your bug. Don't answer and I can't fix.

**Comment by LocoMinerDad** [comment]
I am going back several versions with no luck. I dont know why is matters what version it is, unless your just going to cut and paste some code.

**Comment by Ellpeck** [comment]
I don't know why you would care about what version this is. If it didn't work in 1.11 before, then it's because RF support was dropped with 1.11. If this is actually the reason, there is nothing I can or am willing to do about this issue.

**Comment by LocoMinerDad** [comment]
do i have to delete your config file after I roll back the version?

**Comment by Ellpeck** [comment]
No.

**Comment by LocoMinerDad** [comment]
Ok I deleted the config file anyway.  your mod version 1.11-r78 chargers the other mods stuff. Whether RF support was dropped or not it was working 11/22/16

**Comment by LocoMinerDad** [comment]
You made a lot of changes and I like them. Please don't just say roll back. Your one of my core MC mods

**Comment by Ellpeck** [comment]
RF Support was dropped in r82. So yes, this is the issue. Sorry.

**Comment by LocoMinerDad** [comment]
might be time for a new tech mod

**Comment by Ellpeck** [comment]
I can recommend TechReborn and RFTools. They're both great mods. :)
