### ISSUE TITLE
[Suggestion] Implement cross-compatibility with Reliquary's Bat Wings

### ISSUE THREAD

**Issue by starg09** [Ellpeck/ActuallyAdditions#526]
So, it seems both mods include "Bat Wing" as a drop from bats. And while in [Reliquary](https://minecraft.curseforge.com/projects/reliquary-v1-3?gameCategorySlug=mc-mods&projectID=241319) the item is used on many different recipes, the one from AA seems to only work for making "Bat's Wings". Would it be possible to implement a detection of Reliquary, such that if the mod is present you remove your Wing and replace it with theirs on your recipe? :)

**Comment by Ellpeck** [comment]
I don't really think this'd be great because Actually Additions' bat wings should be harder to obtain than Reliquary's ones, but there's a mod out there called Fluidity which adds this compatibility, so you can just install that! :)
