### ISSUE TITLE
Chests not rendering while looking through lasers.

### ISSUE THREAD

**Issue by KoenHoogendoorn1994** [Ellpeck/ActuallyAdditions#527]
I noticed that in the latest version of the mod (haven't tested previous ones) that chests do not render when looking through lasers, much like ice doesn't render when looking through water in the vanilla game. Lasers also do not render when looked at through another beam. 
![2016-12-23_17 33 47](https://cloud.githubusercontent.com/assets/15976525/21460711/a4218756-c94b-11e6-80c6-bdb1f0b508b3.png)
![2016-12-23_17 33 55](https://cloud.githubusercontent.com/assets/15976525/21460712/a427d44e-c94b-11e6-807a-85874405c35b.png)

**Comment by Ellpeck** [comment]
This is a Minecraft problem, nothing I can really do about that.
