### ISSUE TITLE
Phantomface Crash

### ISSUE THREAD

**Issue by mpferraro** [Ellpeck/ActuallyAdditions#531]
I placed a phantomface under an energy laser relay connected it to a different energy laser relay and it crashed, will not let me log in, looping.

[crash-2016-12-24_14.28.59-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/671925/crash-2016-12-24_14.28.59-server.txt)

**Comment by Ellpeck** [comment]
If you actually want to continue using the world, turn removeErroringTileEntities on in the Forge config, that should remove it.

**Comment by mpferraro** [comment]
THANKS SO MUCH!

**Comment by Ellpeck** [comment]
So I'm presuming what you mean is that you connected two Laser Relays that were already connected with a Phantomface?
Why did you even do that? :'D

**Comment by tigier** [comment]
I thought they weren't connected..... But he could have done that to allow only one way transport in that part of a system, what could be useful.

**Comment by Ellpeck** [comment]
No, it wouldn't be useful because it doesn't make any sense. The only way to fix this problem, by the way, is to blacklist Laser Relays from being connected with a Phantomface, which is what I will be doing.

**Comment by mpferraro** [comment]
It totally was an error on my part, I shouldn't have set it up like I did.  Thanks again for the Forge config tip.

**Comment by LocoMinerDad** [comment]
Hello again, I just did something similar. My charger wasn't charging so I added a energy relay to the energy phantom and it crashed. I can get in at least now

**Comment by Ellpeck** [comment]
Could both of you post a screenshot to the setup you crashed with?
Obviously the direct setup would crash you, but some sort of visualization should work. This still doesn't make sense to me fully.
