### ISSUE TITLE
Issue with Mod Mode

### ISSUE THREAD

**Issue by EtherImperial** [Ellpeck/ActuallyAdditions#534]
Currently running 1.10.2-r88 from the Direwolf 20 pack.  This may just be ignorance on the proper method to implement Mode mode on the advanced laser item relays.  When the Mod mode is turned on, smart filtering does not add items to an inserted item filter, and sorting does not respect the mod of an item manually added to the filter. IE: Restonia Crystals added to filter and inserted into while list. Priority is set to 11 on the mod sorted chests, when sorting Black quartz, it is sent into a general chest with priority 10 instead of the mod sorted chest. In game manual does not have any information on Mod Mode features and procedures, so i'm not sure where to go from here. Maybe bug?

**Comment by Ellpeck** [comment]
This is a problem with Actually Additions items, because the Filter Item already counts as an item from Actually Additions. So the mode should be working for every modded item except for Actually Additions WITH an Item Filter, and should work like expected without an Item Filter item present, though. 
If this is the behavior you are occuring, please close this issue, as this is already known and has been fixed in dev.

**Comment by EtherImperial** [comment]
The behavior i have is as follows now with Ender IO items.  With no filter, set to white list and an item from EIO in the grid and chest, any other items from EIO get stuck in the ESD with no where to go.  In fact even with a default chest for unsorted items, it doesn't even go there.  Its like it gets stuck with the logic of the mod set relay and won't move down the priority, as soon as the mod mode relay is removed it immediately drops into the default chest.

**Comment by EtherImperial** [comment]
![esd](https://cloud.githubusercontent.com/assets/17486746/21487662/8601afda-cb94-11e6-88e3-e4ed17d079dd.jpg)
![grid](https://cloud.githubusercontent.com/assets/17486746/21487663/865da45c-cb94-11e6-8162-d463fd7ebe8d.jpg)

**Comment by Ellpeck** [comment]
Just to confirm that this is not a user error: Is the ESD set to the right amount of slots? Meaning, did you set down the ESD next to the Item Interface after placing additional chests, or did you update the ESD's slot count after placing additional chests? I know this is a common mistake people make so I want to make suee that this is not the actual cause of the problem :)

**Comment by Ellpeck** [comment]
Also, you might not want to match meta data with mod mode enabled, as that means only items that have the metadata the conduit binder has will be accepted. That might also be part of the problem :)

**Comment by Ellpeck** [comment]
Yea, I just tested this. I think there is two things going on: 1. When placing the mod chest, you aren't updating the ESD, meaning it won't "know" about the slots of the last resort chest anymore. Also, because Conduit Binder has metadata 1, nothing with metadata 0 like the conduit will go into the chest. You gotta click the second button from the top to goggle metadata mode off so that that won't happen anymore :)

**Comment by EtherImperial** [comment]
Yeah it was the metadata that was preventing Mod mode from working, would recommend either updating the book with that tid bit or forcing metadata off when Mod mode is turned on, as its not exactly the most obvious of things to cause a problem.  and updating the ESD did fix the default chest issue as well.  I now know that the inventory slot number is calculated based on priority of chest since the default is closer to the ESD both by number of blocks and by the laser's visible path. Good to know

**Comment by Ellpeck** [comment]
If you hover over the mod mode button, this exact thing is explained ;)

**Comment by EtherImperial** [comment]
Must have been updated in a version after the one currently in the pack since it currently says "if this is enabled the filter will compare the mods items come from instead of comparing the items themselves.  This can be useful for storage systems with mod-based chests. Can also be combined with the other options, but that normally isn't very useful" So nothing about the metadata switch needing to be off for functionality.

**Comment by Ellpeck** [comment]
"Can also be combined with the other options" = Metadata, NBT and Oredict. But maybe that's not clear enough? :v

**Comment by EtherImperial** [comment]
It says was it does, "Can also be" not "Metadata on will only allow the item set for filtering to go into the chest not the entire mod's items" so yeah i would say could be clearer haha
