### ISSUE TITLE
Spawner changers doens't work with wither skeleton

### ISSUE THREAD

**Issue by CriticalClaw** [Ellpeck/ActuallyAdditions#535]
Not sure if this is a bug or not, but reporting it anyway.

Picking up a wither skeleton with a spawner changer results in a spawner changer with a normal skeleton instead.

**Comment by Ellpeck** [comment]
Already fixed, just wait for the next release :)
Wait - is this only 1.11 or 1.10 as well?

**Comment by CriticalClaw** [comment]
1.10,
In the Direwolf20 pack verion 1.14 I think.

**Comment by Ellpeck** [comment]
Dangit. Okay, then I gotta backport that fix.

**Comment by Ellpeck** [comment]
I don't think I can fix this in 1.10 to be honest, because in 1.10 Wither Skeletons worked differently from how they work in 1.11 so I'd have to do a sort of complicated workaround which would be very annoying.
Sorry :(
