### ISSUE TITLE
[Suggestion] Allow Lens of Disenchanting to work on multi-chanted books

### ISSUE THREAD

**Issue by Wntermute** [Ellpeck/ActuallyAdditions#543]
So far in the 1.10 packs I haven't seen a way to split off enchants from books that have multiple enchants on them, like those from the Fishing Net. I've tried the Lens Of Disenchanting by throwing a multi-chant book and a plain book down in front of it, but nothing happens to either book. It'd be nice if I can split them off into individual books. Now that throwing down multiple plain books doesn't result in a loss, maybe it could be a way of doing more in one go.

**Comment by Ellpeck** [comment]
I don't really want to do this. I think there should still be some limitation in the world of enchanting and what you can do with books, so I think it's a good compromise to make already enchanted books not be disenchantable. 
Sorry, but thanks for the suggestion anyways :)
