### ISSUE TITLE
Fluid Laser Relay refusing to transport Deep Resonance "Resonating Crystal Liquid"

### ISSUE THREAD

**Issue by wanghealerr** [Ellpeck/ActuallyAdditions#544]
Deep Resonance has its own push/pull indicators: orange / blue, output / input

I set up a laser at the bottom of one tank with resonating crystal liquid inside and another at the top of an empty tank. Set the push/pull indicators, linked the lasers, nothing. Used a compass on lasers to no avail.

Strangely, their modpack's valves work but not with the lasers. Maybe it's a value issue. I messed with valves as well...

If you want to see what in the world I'm doing, I'm at the ATM2 server ( same name ). Looks like it's a value issue, not sure if it's on your end or Deep Resonance's.

**Comment by Ellpeck** [comment]
Do any other fluid transport methods transport this fluid?

**Comment by wanghealerr** [comment]
RFTools Control apparently does. I'll test Pressure Pipes.

**Comment by Ellpeck** [comment]
It seems like the liquid isn't even supposed to be able to be transferred via pipes and stuff like that.

**Comment by wanghealerr** [comment]
It would be interesting to see if values could be saved via transfer. This is probably an issue with Deep Resonance itself then.. thanks for trying to help, though

**Comment by Ellpeck** [comment]
I will be closing this for now as it seems not exclusive to Actually Additions.

**Comment by McJty** [comment]
Deep Resonance RCL is special in the sense that it is a liquid that has NBT data associated with it in the FluidStack. That isn't commonly done. Most tanks + fluid transport systems seem to be able to cope with this though.

Also something to keep in mind: RCL with (for example) strength equal to 87% is not the same liquid as RCL with strength 88%. Only the Deep Resonance tank knows how to mix RCL and distribute the stats. Other tanks will see liquids with different stats as different liquids. So if your laser extracts a 87% liquid and suddenly the liquid changes its stats slightly it will be seen as a different liquid

**Comment by Ellpeck** [comment]
Okay. @wanghealerr, were you able to extract any liquid into a different, empty tank, and if so, did it keep its NBT?
