### ISSUE TITLE
Proper localization

### ISSUE THREAD

**Issue by xbony2** [Ellpeck/ActuallyAdditions#545]
[Fix it](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/inventory/GuiFireworkBox.java#L40) bad boi 🦊

**Comment by Ellpeck** [comment]
Too lazy

**Comment by xbony2** [comment]
Do it for the fox 🦊

**Comment by Ellpeck** [comment]
:fox_face:

**Comment by xbony2** [comment]
狐狸 🦊

**Comment by Ellpeck** [comment]
Stop posting here or I will lock this thread :fox_face:

**Comment by xbony2** [comment]
Don't make me send a PR boi 🦊 .i lo lorxu cu badri
