### ISSUE TITLE
[Issue] ESD causing severe tick issues

### ISSUE THREAD

**Issue by MysticAura** [Ellpeck/ActuallyAdditions#546]
MC: 1.10.2
Forge: 2185
Mod: ActuallyAdditions-1.10.2-r94

Tps had gotten severly low on the sub-server so I ran some profiling. Narrowed the bulk of the issue to TileEntityInputter. After removing AA from the pack the tps went from 13 back to 20.  Of course I'd prefer not to lose this mod if it can be avoided.

[Profiler log](http://pastebin.com/aXmE8BJ6)

There was nothing about it at all in the fml/latest and of course no crash report.

**Comment by Ellpeck** [comment]
What was the setup that caused the lag..?

**Comment by Ellpeck** [comment]
I also don't know what you mean by "New inputter class", because this class is like 2 years old O_o

**Comment by MysticAura** [comment]
Just misspoke due to googling too much on the issue, and saw when you said it was a new class. The rest stands though :blush:

**Comment by Ellpeck** [comment]
My question does too, and without an answer to it I can't do anything about this issue.
What was the setup this Tile (the ESD) was involved in that caused this lag?

**Comment by MysticAura** [comment]
I could give you a link to the pack involved and the world folder if it would help.

**Comment by Ellpeck** [comment]
It would help most if you were able to pin down the issue. 
I have never heard of any problem with the ESD causing tick lag ever before, and I can't really think of why it would be causing any either, so this is on you.

**Comment by MysticAura** [comment]
After spending the last 3 hours in level dat and using custom mods to track down the coordinates of the offending ESD's on the server, the one causing the biggest issue was pulling from a large crate and pushing into your dropper. It was holding one item in inventory waiting for space. It was part of someones disenchanting setup. The instant I broke the block the tps went back to decent levels.  
I wasn't trying to insult you, or make up problems. I reported thinking it's something you'd want to know about.

**Comment by Ellpeck** [comment]
Well now we have an issue to work out.
Thanks for investigating :)

**Comment by Ellpeck** [comment]
The thing that's weird about this is the fact that while the ESD already has items in it, it shouldn't be scanning the inventory it pulls from (the large crate in this case) for any items, which would be causing the most lag here.
I can't reproduce this either, but I guess I'll try adding a cooldown to the ESD to try to reduce the load it creates. That'd be a little better gameplay wise anyways. :v

**Comment by Ellpeck** [comment]
The latest commit should've fixed this.
Thanks for the help :)

**Comment by Ellpeck** [comment]
I hope the latest release fixes your problem. The thing with something as big as the Large Crates is that obviously it searches the entire crate for items if there aren't any in there, which is going to be happening with any item transport mechanic, so there is only so much I can do. But I hope the changes I made fix the issue :)
