### ISSUE TITLE
GENERIC_CLICK on solidified experience crashes the server

### ISSUE THREAD

**Issue by Pekkhum** [Ellpeck/ActuallyAdditions#547]
In Minecraft 1.10.2 Direwolf20 Modpack we attempted to desolidify solidified experience from a mob farm in an automated manner by placing it in an Extra Utilities 2 Mechanical User. This mechanical user is attempting a GENERIC_CLICK with RIGHT_CLICK on the air and crashes the server (which means we can no longer start the server).

Attached is our server startup/shutdown log. I've asked the admin for the crash report in case you need it and will provide it once it is available.

[2016-12-29-4.log.gz](https://github.com/Ellpeck/ActuallyAdditions/files/678122/2016-12-29-4.log.gz)

**Comment by Ellpeck** [comment]
You can temporarily fix this by turning the config option removeErroringTileEntities on in the config.
It has already been fixed for 1.10, I just need to do a release. °~°
