### ISSUE TITLE
[BUG] All the blocks' & items' localization file can't work

### ISSUE THREAD

**Issue by TartaricAcid** [Ellpeck/ActuallyAdditions#548]
## Key is the same.
![pic](https://i.imgur.com/YeMfoL7.png)
## But can't work in game.
![pic](https://i.imgur.com/IQeQxnc.png)
## There is no problem with the manual localization entries
* version: 1.10.2-r97
* forge: 2185

**Comment by Ellpeck** [comment]
The line you are viewing isn't the item's name.

**Comment by TartaricAcid** [comment]
Sorry for my carelessness, I found out that I got mixed up with 1.10 and 1.11.
