### ISSUE TITLE
(1.10/r90/direwolf20(1.2.1)) Two different adjacent oils are always flowing

### ISSUE THREAD

**Issue by tigier** [Ellpeck/ActuallyAdditions#549]
It's not directly an issue but I don't think it is supposed to happen, or is it?

Just place two oils,e.g. oil and crystallized oil, adjacent to each other and drop an item inside or even jump inside.

**Comment by Ellpeck** [comment]
It's Forge's way of handling fluids. I don't know why that happens either, and frankly, I don't really care.
