### ISSUE TITLE
Add Crushed Quartz to dustNetherQuartz ore dict.

### ISSUE THREAD

**Issue by Aarronmc** [Ellpeck/ActuallyAdditions#552]
Helps compatibility with AE2 and your Crusher.

**Comment by Aarronmc** [comment]
Helps compatibility with AE2 and your Crusher.

**Comment by Ellpeck** [comment]
That doesn't make sense though. It's in the Ore Dictionary as "dustQuartz", because the ore is in it by default as "gemQuartz" and the ore is in it as "oreQuartz". Adding "nether" to the dust doesn't seem logical to me.

**Comment by Aarronmc** [comment]
AE2 also has dustCertusQuartz tho. Likely the reason why they are differentiated in the oredict.

**Comment by Ellpeck** [comment]
Ugh. :v I guess I'll do this then.

**Comment by Aarronmc** [comment]
Awesome thanks. It'll help with QOL.
