### ISSUE TITLE
Add a Config Option for the Booklet's font size

### ISSUE THREAD

**Issue by ZXYENGINEER** [Ellpeck/ActuallyAdditions#554]
Yesterday I was updated my mod version to r97, and I was found that the mannul book's font is very small and un-clear, I think it was caused by small unicode font :). Here is a 1.7.10 mod that fixed Thaumcraft  issue, Hope to be helpful.
https://mods.curse.com/mc-mods/minecraft/233069-unicode-font-fixer#t1:description

**Comment by Ellpeck** [comment]
I don't understand the problem here. Post a screenshot of the book.

**Comment by ZXYENGINEER** [comment]
![y849 cj nov qph vk k ng](https://cloud.githubusercontent.com/assets/11711492/21681581/cc85fb8e-d38a-11e6-9421-b6fbabb38116.png)
ok,

**Comment by ZXYENGINEER** [comment]
![ridpzl1e0fb _o1qvwp 0 b](https://cloud.githubusercontent.com/assets/11711492/21681648/1187172c-d38b-11e6-9737-b7d97ab1ce92.png)
I'm going blind (╯‵□′)╯︵┻━┻，hope you can fix it , thanks~~~  ;)

**Comment by Ellpeck** [comment]
I guess I'll add a config option then >_>
I don't believe in Resource Packs, so I've never really thought of ones screwing with the Font Renderer.

**Comment by ZXYENGINEER** [comment]
I just test the config of my minecraft pack (it's only used by myself) and trying to use TTFR(Better fonts mod) change the font and it seems no use. .. ╮(╯▽╰)╭I thought this information might be useful.
