### ISSUE TITLE
[1.10.2]Font size is too small in the manual in Simplified Chinese

### ISSUE THREAD

**Issue by SihenZhang** [Ellpeck/ActuallyAdditions#556]
Hi, Ellpeck! I'm the reposter of ActuallyAdditions. I had requested a license in CurseForge. Did you remember?

A few months ago, some players told me that the font size is too small to see. Even some Chinese players who played All The Mods or FTB Infinity Lite also found me and asked me about this. But I was busy with deadline so I didn't have time until now.

Here is a group of screenshots from a player.
![Manual](http://i.imgur.com/FZOuk0N.jpg)
![Version](http://i.imgur.com/Z7oS1F6.jpg)

I saw #461 had discussed this problem and have been solved in 1.11-r91. 

So I really want to get a reply for me and other Chinese players. Will it be solved in 1.10.2? If it will ,when will it be solved?

**Comment by Ellpeck** [comment]
It won't be solved in 1.10.2, unless there is another critical issue that makes it important to do a bugfix release for 1.10.2.
Sorry if this seems ignorant, but I don't think a language-related issue is enough to release an entire new update for a mod.
The 1.11 version has two localization keys in the en_US.lang file to change the font size language-dependent. This will be backported to 1.10 in the next update, if there ever will be one. If not, sorry.

**Comment by Ellpeck** [comment]
[Also side note: That screenshot is of no use to me. It has the same amount of readability for me as every other chinese text: Absolutely none :P]
