### ISSUE TITLE
Phantom Redstoneface doesn't work?

### ISSUE THREAD

**Issue by jeridan** [Ellpeck/ActuallyAdditions#562]
Pack version: Direwolf20 1.10-1.10.2-1.3.2
Actually Additions version: ActuallyAdditions-1.10.2-r97

I have tested first setup like it reads in the book where the linked block receives the redstone signal that the phantomface should replicate but there is no state change.  Just for sanity I tried it the other way around without any success.

Setup with redstone off.
![2017-01-10_18 58 35](https://cloud.githubusercontent.com/assets/5779504/21831159/6b5457e4-d767-11e6-9554-a4fda80d4bb7.png)

Redstone on.
![2017-01-10_18 58 42](https://cloud.githubusercontent.com/assets/5779504/21831175/80f0c844-d767-11e6-8663-c1e469443c0b.png)

Other way around.
![2017-01-10_19 01 02](https://cloud.githubusercontent.com/assets/5779504/21831182/88464862-d767-11e6-874a-d15b828f393d.png)

**Comment by Rakinare** [comment]
From what I have found out, you can't connect it to the stone the lever is attached to. If you connect it directly to the lever or to the redstone on top of it, it should work just fine.

I am not playing Direwolf but I am not the same mod version.

**Comment by Ellpeck** [comment]
You need to connect it to an actual redstone power giving device, not a device that is powered by Redstone. So basically, it needs to be connected to a Redstone wire or the lever directly.

**Comment by jeridan** [comment]
Thank you for the explanation.  Confirmed it does work as explained here.
