### ISSUE TITLE
Special case skulls to be placed in the right place by the Placer

### ISSUE THREAD

**Issue by Rakinare** [Ellpeck/ActuallyAdditions#563]
Pack Version: Sky Factory 3

Mod Version: 1.10.2-r97.jar

Issue: If there is space, the Auto-Placer places mob skulls 1 block below it instead of infront of it, thus making it a pain to setup wither farms.
It took me a long time to figure out why my farm kept glitching out until I noticed that issue.

What do I expect: I expect the Auto-Placer to place whatever it does place infront of it and not somewhere else.

Thanks for taking your time and looking into it.

Sincerely,
Rakinare

**Comment by Ellpeck** [comment]
Fake players and the direction they look. To be honest, I haven't found a way to really fix this other than special casing it, but I guess I'll do that.

**Comment by Rakinare** [comment]
Hey Ellpeck,

thanks alot for the fast answer. From looking at this github you seem to be a really awesome developer!
Thanks for taking the time making this mod better and better,  you are doing a great job :)


Having it to actually work would be great, would make stuff so much easier. 
Since I am also always interested in how stuff works, what is actually causing it to place skulls one block below but normal block where they belong to?
Also is this hard to "fix" or a rather easy change?

Thanks for your answer!

Regards,
Rakinare

**Comment by Shadows-of-Fire** [comment]
I think im gonna leave it as it is now.  It's been that way for so long changing it would just confuse people.
