### ISSUE TITLE
Make Laser Relays actively pull when in Only Out Of Adjacent Blocks mode

### ISSUE THREAD

**Issue by Bimahi** [Ellpeck/ActuallyAdditions#564]
Using the Direwolf 1.10 modpack on version 1.2.2, fluid lasers do not move steam in and out of reactors and bug the display as well.

**Comment by Ellpeck** [comment]
Can steam even be moved out of reactors?
How do they bug the dispay?

**Comment by Bimahi** [comment]
You move the steam out of the reactors using reactor coolant ports and into turbines using Turbine fluid ports. The turbine turns it into water and transfers it back using the same types of fluid ports, but different spot. It does neither. The display bug is where it sticks a semi-random transfer amount that persists even when breaking all lasers and needs a server restart to fix.

**Comment by Ellpeck** [comment]
Please take some screenshots of your setup and the display bug.

**Comment by Bimahi** [comment]
Working Setup with Ender IO Conduits
![2017-01-12_04 49 07](https://cloud.githubusercontent.com/assets/17985395/21890522/f66ac478-d882-11e6-8418-49a2f9d4a1a3.png)
Replacing the output conduits with a fluid laser, not pulling any fluid at this point
![2017-01-12_04 50 41](https://cloud.githubusercontent.com/assets/17985395/21890555/11bfb3aa-d883-11e6-831e-98eab4685b1f.png)
Bugged output with laser still connected
![2017-01-12_04 50 48](https://cloud.githubusercontent.com/assets/17985395/21890569/23979f02-d883-11e6-90e1-9a2ff3453841.png)
Bugged output with laser disconnected
![2017-01-12_04 50 58](https://cloud.githubusercontent.com/assets/17985395/21890600/48bba9ae-d883-11e6-8aa1-d38c286dbfc6.png)
