### ISSUE TITLE
[Suggestion]Add a "Use first slot only" button to Auto Placers

### ISSUE THREAD

**Issue by Rakinare** [Ellpeck/ActuallyAdditions#565]
I'd like to also see the "first slot only button" on the Auto placers since this feature can be really helpful in some setups. 
Would be glad if you could have a look into that!

Regards,
Rakinare

**Comment by Ellpeck** [comment]
The Auto-Placer will use the first slot only, as long as there are items in that. Just put sticks or something else that can't be placed into the other slots :)

**Comment by Rakinare** [comment]
Ah right, I didn't think about using non placeable items. That makes it actually easier. Thanks!
