### ISSUE TITLE
Config option to disable sounds

### ISSUE THREAD

**Issue by Zaflis** [Ellpeck/ActuallyAdditions#566]
There could be optional configs when people want to disable sounds from crusher machine for example, it can be very noisy. But also sounds can sometimes be a cause for lag, so adding a way to test those things would help eliminating possible causes. So simply setting volume to 0 is not same thing as not loading and using a soundfile at all, but currently there is not even volume option.

Even better if you could config them from ingame mod options.

People should also be able to join server with different configs for sounds.

**Comment by Ellpeck** [comment]
I don't understand how sounds could cause lag, but to be honest, I personally don't think that a config option to turn off sounds makes a lot of sense, sorry :(
If you want to turn off the Crusher in particular, you are going to have to turn off the entirety of Block sounds.
