### ISSUE TITLE
Drill Speed Augment III Issue

### ISSUE THREAD

**Issue by user1498** [Ellpeck/ActuallyAdditions#568]
-- AA version 1.10.2-r97 (FTB Skyfactory 304) --

Inserting the Drill Speed Augment III increases power cosumption from 225 to 400 RF but doesn't make the drill go noticeably faster.
Tier I and II are installed.

**Comment by Ellpeck** [comment]
Please take a video of this happening, I can't reproduce it.

**Comment by Quaiby** [comment]
I have the same problem, but it was only out of sync because I launched too much apps

**Comment by Ellpeck** [comment]
What do you mean by "too much apps"? :o
But what you're saying is that this wasn't an Actually Additions problem?

**Comment by Quaiby** [comment]
Yes, Minecraft don't have enough RAM when this and similar issues happens

**Comment by user1498** [comment]
RAM wasn't the issue here..
I just tried the drill on normal stone and it works fine.
If I use it on cobblestone or ores (or some other materials) there is no speed difference between II and III though.
I'm not sure if this is a bug or if it's intended

**Comment by Ellpeck** [comment]
Try it with only Actually Additions installed.

**Comment by user1498** [comment]
Tried stone, cobble stone and iron ore with only AA installed with the same results.
Speed III breaks stone instantly (like grass) but there is no difference between II and II when I break cobble or iron ore.
Since I don't have any recording software installed, here is a link to direwolf20's mod spotlight: https://www.youtube.com/watch?v=4kz27FiMmOo&feature=youtu.be&t=7m17s

**Comment by Ellpeck** [comment]
There *is* a difference, it's just too slight to notice on a block with a similar hardness to cobblestone.
This is the same difference as between Efficiency IV and V on a diamond pick.
