### ISSUE TITLE
Alloying

### ISSUE THREAD

**Issue by Quaiby** [Ellpeck/ActuallyAdditions#570]
I think alloying will be cool. Machine can be similar to empowerer (can use display stands too). And it will be logically correct if empowered things cannot be alloyed.

**Comment by Ellpeck** [comment]
...which Alloys? O_o

**Comment by Quaiby** [comment]
Hmmm... e.g. Enori + Emeradic = Gemmy metal, used as component for crafts (maybe electric armor?)

**Comment by Ellpeck** [comment]
Sorry, but I don't want to add more crafting components to the mod.
