### ISSUE TITLE
Ideas for farmer improvement

### ISSUE THREAD

**Issue by Sandstroem** [Ellpeck/ActuallyAdditions#571]
Hi,

first of all I like your mod, it adds really nice features to the game.

I have some suggestions how to improve the farmer. 
First of all, I haven't looked at the code, but it seems that the farmer scans the whole field line by line. It checks for empty spaces and then puts a seed or breaks a mature one. Could you switch that around and make it so that it directly places a seed on a field it just broke? Right now it will only place the seed in his next visit of this block.
I have a 9x9 field set up, with a water block in the middle, and it seems that from my 80 seeds there are 20-30 most of the time in the farmer.

Another thing I noticed is the way it sorts  broken seeds into the left side of the farmer. Let's say I have coal and diamond seeds on my field. If it breaks a diamond seed, it will be put into slot 1. If it breaks a coal seed it will be put in slot 2. Now if it breaks diamond again and slot 1 still has seeds in it, it will not add to slot 1, but put them into slot 3.
So with 2 or 3 seeds on the field, you will come very fast to the point where the whole left side clutters up and it starts to put seeds into the right, which usually gets output somewhere else.
A solution might be to check whether seeds of one type are already in the system and then use that slot.

Hope my suggestions are understandable.
Have a nice day
Sandstroem

**Comment by Ellpeck** [comment]
The farmer is supposed to only work with one type of seed on the field. If you want multiple plants, just make a second farmer :D

Sorry, but I am happy with the way the farmer works right now. Your suggestions aren't bad, I just don't personally think the farmer needs any change. Sorry :(

**Comment by Sandstroem** [comment]
Ok only one seed. That is fine to me. That solves the problem with the cluttering. But still the way it breaks seeds and do not replant them direclty makes it less efficient. So what is the number of seeds I actually need for a field of 80 crops?

**Comment by Ellpeck** [comment]
What? If you have 80 farming spaces, you need 80 seeds. Why would it be different?

**Comment by Ellpeck** [comment]
Efficiency isn't always what is key in design. I think the way it breaks the plants, then leaves the space free and only replants the seed when it next cycles through to that field is visually more interesting, which is why it's the way the farmer works.

**Comment by Sandstroem** [comment]
Ok thanks for your answers.

**Comment by Sandstroem** [comment]
What I meant with the 80 seeds is that in one cycle it breaks a lot of seeds, but since it only replants them in the next turn, the field will never be full. Even with enough power I most of the tiem have 20-30 seeds in the farmer which havent been planted yet.

The only way to fix that for me would probably to speed up growth so fast, that the farmer can harvest a whole field which is already completely grown. But if I don't go nuts with growth accelerators and similar stuff mostly 50-6ß seeds is more than I can have on the field at any point in time.
