### ISSUE TITLE
Applied Energistics' ME systems are not accepting power from AA energy lasers.

### ISSUE THREAD

**Issue by xenoflot** [Ellpeck/ActuallyAdditions#573]
Hi,

I've found that Applied Energistics' ME systems (controller and power-acceptor) are not accepting power from AA energy lasers. 

I reported this to the AE2 team and they responded that there may be an issue with AA's detection of their blocks as power acceptors.  https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2750

Would you please have a look?

    Minecraft Version: 1.10.2
    AE2 Version: appliedenergistics2-rv4-alpha-11
    Forge Version: 2185
    compatlayer-1.10-0.1.7
    rftools-1.1x-5.76
    actuallyadditions-1.10.2-r97

Cheers!

**Comment by Ellpeck** [comment]
Do Applied Energistics machines support RF and/or Tesla?
Because Actually Additions doesn't support Forge Units.

**Comment by xenoflot** [comment]
Hi,

I'm afraid I can't answer that question as I'm not a modder. It works fine with Immersive Engineering's capacitors and wire connectors but that doesn't answer your question directly.

Would you please check with Yueh via the link above?

Cheers!

**Comment by Ellpeck** [comment]
Closing this for now as I am keeping track of the issue on the other tracker that you posted, also I am pretty sure that this is not an Actually Additions issue anyways.

**Comment by xenoflot** [comment]
Yep, I agree. McJty set out the problem pretty clearly. Thanks for looking into it!
