### ISSUE TITLE
+ to Player laser relays 

### ISSUE THREAD

**Issue by Quaiby** [Ellpeck/ActuallyAdditions#574]
I saw idea about Player laser relays, and if you will implement it into mod I want to suggest a way how to realize it.
It's a system:
We place travel anchors (telepods or etc.) and connect they with player laser relays. Now we can travel between anchors with travel rod without spending energy.
But we can place teleport processor next to any anchor and connect RF to it. Then we need to right click with travel card on each anchor and insert it into processor (I think it will be simplest way). And for end - place travel monitors on each anchor.
Now all saved to card and linked with player lasers anchors will be visible in GUI of any travel monitor. We select desired anchor and system teleports us to it with spending some energy from processor.
Or thousand simply without processor and cards but with monitors :)

**Comment by Ellpeck** [comment]
There is an issue for this already, just add a comment to that.
