### ISSUE TITLE
Pocket furnace

### ISSUE THREAD

**Issue by Quaiby** [Ellpeck/ActuallyAdditions#575]
When I go to the shaft with my silk touch I really needed something like this. Maybe it will works on RF(Tesla) or tiny coal? It may have only slot for non-smelted items and smelted items will be placed into player's inventory. And it will be cool if there will be upgrades (like drill upgrades), e.g. speed or resource doubling

**Comment by Ellpeck** [comment]
I thought about this before, but decided not to do it. Sorry :)
