### ISSUE TITLE
Turning canola into oil using multiple seeds eats all seeds

### ISSUE THREAD

**Issue by b0bst3r** [Ellpeck/ActuallyAdditions#576]
R97 1.10.2

Place more than 1 Crystallized Canola seed down - place canola oil on seeds, all seeds are used if more than 1 seed existed before oil is dropped.

Same happens with Crystallized to Empowered, makes for automated systems a little tricky.

For example place a stack of crystallized seeds in a hole, place canole oil in hole all 64 seeds are used.

**Comment by Ellpeck** [comment]
That is intended behavior I am afraid to say.
You can use something like the Precision Dropper to only drop one seed once you know the fluid is there.
I have made a[ video on my channel ](https://www.youtube.com/watch?v=E3krUdD8o6g)explaining an easy way to automate it :)
