### ISSUE TITLE
Magma block as additional heat source for the heat collector

### ISSUE THREAD

**Issue by Samtrion** [Ellpeck/ActuallyAdditions#578]
It would be great if the heat collector can also be operated with a magma block.
For each block +5 RF / Tesla, in total a maximum of 30 RF or 1x Magma Block + Lava +50 RF / Tesla.

**Comment by PapiDimmi** [comment]
That would be neat. It would add an actual use for the magma blocks.

**Comment by darkshadow543** [comment]
Atomic reconstruction to obsidian would be better.
