### ISSUE TITLE
ForgeThis: Can not Fly with Wings

### ISSUE THREAD

**Issue by DoughnutDev** [Ellpeck/ActuallyAdditions#58]
Sense we updated yesterday the wings will not allow you to fly.

Updated Mods:
JEIAddons
NeoTech
BloodMagic
JEI
BookShelf - Core mod for NeoTech
OpenComputers

Added:
AutoTech
OpenRadio
ThaumicInfusion

**Comment by Ellpeck** [comment]
Will the wings do anthing else?
Is there something in the console about it?
What happens when you re-enter the world, restart the server etc?

**Comment by DoughnutDev** [comment]
The allow you not to take fall damage, there is nothing in console, and I
have tried leaving the world and restarting.

**Comment by Taliel81** [comment]
I am unable to fly with the 'wings of the bats', am I supposed to do something special? I'm playing on the Arisen modpack.
