### ISSUE TITLE
1.11.2-r96 Farmer eventually has only one type of crop planted.

### ISSUE THREAD

**Issue by Kriptikz** [Ellpeck/ActuallyAdditions#580]
I used the farmer to plant multiple crops like wheat, canola, coffee, flax, and rice. When a plant is fully grown it harvests the plant by breaking it leaving the space open for the moment. When it performs the next cycle it plants seeds in available space from the first slot in its inventory that has seeds. So if in the first slot has 64 wheat seeds, the second slot has 64 canola and the other slots have other seeds. The farm only has 81 spots to plant in. After it runs through and harvests all fully grown crops it then cycles to plant new seeds except since there is 64 wheat seeds in the first slot and 64 canola seeds in the second slot, it plants all 64 wheat seeds followed by 17 of the canola seeds leaving the other 3 crops not being planted. My farm went from 5 different plants being grown down to 2, even though it has the other seeds in its inventory it never gets the chance to plant them.
In order to grow more than one crop I have resorted to creating a dedicated farmer for each crop I want to grow.
Is the farmer intended to grow only two types of crops max? If so, why does it have 6 slots and not just 2.
To fix this I think you could make the farmer cycle through the slots as it plants ensuring that all 6 crops will be planted. You could dedicate the slots to certain parts of the farm. You could make it 9 slots where each slot plants down each row or column. Or whatever you can think of. 

This came up because I really like your mod and wanted to use solely actually additions stuff whenever possible on my current server. I appreciate all your hard work!

**Comment by Ellpeck** [comment]
The farmer is only intended to grow one type of crop.
