### ISSUE TITLE
Charge Battery if part of drill

### ISSUE THREAD

**Issue by Samtrion** [Ellpeck/ActuallyAdditions#581]
If the drill contains a battery, the Energizer should charge the battery too.
Alternatively, the internal energy storage of the drill should be expanded with the capacity of the batteries.

**Comment by Ellpeck** [comment]
The feature of the Drills being able to hold batteries has been removed.
Just put the battery in discharge mode.

**Comment by Samtrion** [comment]
Hi,
i'm playing on version 1.10.2 r98, and can still add a battery to my drill. The batterie is losing energy while mining until it is empty, then the drill is losing energy.

**Comment by Ellpeck** [comment]
Yes, this is a 1.10 feature that has been removed in 1.11.

**Comment by Samtrion** [comment]
Okay, thanks. 👍
