### ISSUE TITLE
Drill breaks both double double half-slabs

### ISSUE THREAD

**Issue by shabble** [Ellpeck/ActuallyAdditions#584]
## Type:

Bug?

## Description

Where a block is comprised of 2 slabs in the same block-space, using the drill to break one will cause both to be broken.

## Steps to reproduce

1. place 2 slabs to form a single block (tested with vanilla oak slabs & smooth-stone slabs)
2. targeting with tool shows a bounding box around either upper/lower slab
3. breaking with most tools (vanilla pickaxe/axe, TiCon tools, or AA AIOT) will only break the targeted slab
4. when broken with drill (seems independent of upgrades, including silk touch), both slabs in the block are broken.

## Expected

Only the targeted half is broken.

## Actual

Both slabs break, and then a horde of tiny zombies escapes through the resulting gap and brutally murder me<sup>*</sup>.

<sup>*</sup> Actual zombie-murdering not repeatable. May require zombies. Terms & Conditions apply.

## Versions

* MC: 1.10.2
* Forge: 2202
* AA: 1.10.2-r97
* Pack: SF3 3.0.4

## Sad Trombone

I am reliably informed the minecraft slab-handling logic is pure distilled madness, and this issue may not be worth the time, money, or potential insanity risked in fixing it.

**Comment by Ellpeck** [comment]
Uh.. this is vanilla behavior?

**Comment by shabble** [comment]
I could just be being an idiot then, but I'm fairly certain some tools were selectively breaking adjacent slabs. It might just be that in every case I thought it was 'working', one slab was at the top of a block, and the other at the bottom of the block above.

I'll test and see.

**Comment by shabble** [comment]
Mystery (probably) solved: https://mods.curse.com/mc-mods/minecraft/241895-kleeslabs is part of the SkyFactory 3 pack.

**Comment by Ellpeck** [comment]
Note for myself: Maybe I am missing an isCancelled() check in the custom breaking code's break event call.

**Comment by Quaiby** [comment]
You also can press shift and break only one slab in vanilla (added in 1.7.4)
