### ISSUE TITLE
1.11.2-r96 Crafting tables now delete items when you leave the gui

### ISSUE THREAD

**Issue by kreezxil** [Ellpeck/ActuallyAdditions#588]
Running on Forge 1.11.2 build 2223, your crafting table now deletes items from the gui when you leave the gui with items on the grid.

Dedicated server console lists no errors
Client console also listes no errors

**Comment by Ellpeck** [comment]
"Your crafting table"..?

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by tigier** [comment]
I guess he means the pocket crafting table

**Comment by kreezxil** [comment]
nope sorry, wrong mod. please close this. It was random things crafting table.
