### ISSUE TITLE
Buckets consumed when crafting rice slimeballs? (v 1.10.2-r98)

### ISSUE THREAD

**Issue by Rudy2D2** [Ellpeck/ActuallyAdditions#590]
Is this a bug or is it intended?

**Comment by Ellpeck** [comment]
Can't reproduce, it doesn't happen for me.
What are you crafting them in?

**Comment by Rudy2D2** [comment]
Both regular and Tinkers tables. I do have several other mods installed.

**Comment by YasminEndusa** [comment]
Could you try with just AA?  
If that works, could you try adding mods until it "breaks"?  
I know this is a somewhat lengthy process but it would make it reproducable and helps getting it fixed.

**Comment by Rudy2D2** [comment]
Okay, conflict is definitely a mod called Calculator. Honestly haven't used it, so it's not a huge issue for me, and if I had to guess I'd say the problem is on that end (since it seems to use a new crafting mechanic). But if you want to look into it for your own peace of mind, be my guest.

**Comment by Ellpeck** [comment]
It probably just removes the container item of the bucket for some reason.
This is not an issue on my side then.

**Comment by AEnterprise** [comment]
@Rudy2D2 what version of calculator and sonarcore you using? i know this has been fixed before so eighter your version is outdated or it's a regression

cc @sonicsonar

**Comment by Rudy2D2** [comment]
I've checked for updates in the last week or so, so it should be up-to-date. It is not an issue with SonarCore installed, only when Calculator is also added in.
