### ISSUE TITLE
[Suggestion] Config option to disable colorful names

### ISSUE THREAD

**Issue by vidaj** [Ellpeck/ActuallyAdditions#591]
Hi

Is it possible to add a config option to disable the colorful rendering of block/item names?

**Comment by Ellpeck** [comment]
Look at your config.

**Comment by Ellpeck** [comment]
Well, or update to 1.11.

**Comment by vidaj** [comment]
Ah, I didn't realize this was added in 1.11. I had looked through the config for 1.10 several times before creating this suggestion ;)

Thanks :)
