### ISSUE TITLE
Worms on Hatchery fertilized dirt

### ISSUE THREAD

**Issue by bubblesayoyo** [Ellpeck/ActuallyAdditions#592]
Doesn't seem to work. Looking back, there was an issue before(for other mods), so this might be on Hatchery's side, but I thought I would put it here for now. 

Your past issue was #338.

**Comment by Ellpeck** [comment]
I don't really want to add a bunch of special cases for the worm, to be honest. It checks if the block instanceof BlockDirt or instanceof BlockFarmland. If that doesn't apply for Hatchery fertilized dirt, then you'll have to use normal farmland. Sorry.
