### ISSUE TITLE
Reduce the number of BioMash recipes

### ISSUE THREAD

**Issue by Samtrion** [Ellpeck/ActuallyAdditions#593]
With a custom derivation from IRecipe it would be possible to reduce the immense number of Bio-Mash recipes to 1. For this, only one Shapeless Recipe variant is required, which accepts List< ItemStack > as an argument and processes it accordingly. Code examples are available in ShapelessOreRecipe.

**Comment by Samtrion** [comment]
In addition, it may be possible to include saplings as an ingredient.

**Comment by Samtrion** [comment]
Is it possible that you can merge this change to 1.10.2 too?

**Comment by Ellpeck** [comment]
Probably not, sorry.
