### ISSUE TITLE
Farmer: Respect right-click to harvest of some crops

### ISSUE THREAD

**Issue by tedsenft** [Ellpeck/ActuallyAdditions#597]
Several mods (*cough* Mystical Agriculture) make their crops keep seeds planted by making it drop stuff on a right click. This saves replanting time and is more efficient. Is there a way to make the farmer respect this?

**Comment by Ellpeck** [comment]
No, and I don't want this to be a feature. Sorry.

**Comment by Eufranio** [comment]
Why not?

**Comment by YasminEndusa** [comment]
Because the way it works currently is the intended behaviour.  
Honestly, does there have to be a specific reason behind this? If yes, it is "because the mod creator wants it that way.".
