### ISSUE TITLE
Direwolf 1.10 Compacted sand Duplication glitch

### ISSUE THREAD

**Issue by healthyhobo123** [Ellpeck/ActuallyAdditions#599]
When i use my Actually addons drill (with all speed upgrades and silk touch upgrade) and break a compacted sand block, it duplicates into a stack of compacted sand (the same block i broke) plus the one i broke (so 64+1) this is a glitch that i hope gets fixed. (compacted sand from extra utils)

**Comment by Ellpeck** [comment]
Can you try to reproduce it with a normal tool with silk touch on it?

**Comment by healthyhobo123** [comment]
Sure i will try

**Comment by healthyhobo123** [comment]
Yes i tested it with both a actually addons and vanilla pickaxe with silk touch, this must just be a extra utils2 glitch

**Comment by bookerthegeek** [comment]
@Ellpeck Here is a breakdown of the bug 
https://github.com/SpongePowered/SpongeForge/issues/1193
