### ISSUE TITLE
[Issue] Plant doesn't trop seeds / [Suggestions] All around Storage Crate

### ISSUE THREAD

**Issue by accessdenied0** [Ellpeck/ActuallyAdditions#6]
Dear @Ellpeck,

I got this issue since 2-3 versions back, I'm not able to get any seeds from plants your mod added... Every-time I try to break a plant my console throws this error: http://puu.sh/itZEx/4ce53f4542.png I don't know exactly if this is your mod's fault and sadly I can't give you any more information but because I got this now since a while, I felt like to report this issue. (edit: This issue seems to be also on agricraft by right clicking, but I can get the seeds back...)

Additionally, I don't know if this is already planed but I would love to see a support for the Dolly from JABBA for the Storage Crate, just my suggestion. Speaking of support... I have Inventory-Tweaks installed and the Buttons this mod added are slightly displaced: http://puu.sh/ivNKZ/fe2bb4871a.png

I'm sorry this is very much for the first time, but I like this mod and it continue its quality.

access_denied

**Comment by Ellpeck** [comment]
Thank you very much for your report.
I will have to look into the seed issue because it doesn't happen on my side (and not on the one of many of my friends), and I tried it with the Infinity Modpack and the Resonant Rise Modpack. What mods and versions are you using? It might be wise to try to update Forge, maybe that would fix the error.

For the chests: Yes, the JABBA Support is actually planned! :)
And the Chest Buttons... yea.. whoops... I always have those buttons hidden on my client.. so derp. Getting fixed soon :)

**Comment by accessdenied0** [comment]
@Ellpeck,

Thank you for your quick response^^

I guess this issue isn't a problem causing from your mod, but it affected yours and agicraft... this is very strange so far, because I disabled all mods which added "right-click"-harvesting...

I got here my mod-list: http://pastebin.com/c0dvfBTq

 maybe you can give me a clue...

access_denied

**Comment by Ellpeck** [comment]
You might just want to try quickly removing AgriCraft and going into a Test World, it might be a bug caused by that. Otherwise, I changed the Plant Harvesting Code up a bit so that it's basically the same as the vanilla one, might work in the next Version again for you then :)

**Comment by accessdenied0** [comment]
Sadly... this didn't solved the problem... >.<

http://puu.sh/ivX8w/2e23a738d6.png

I'm pretty clueless where it could come from... 

thank you anyway for your efforts ^^

access_denied

**Comment by Ellpeck** [comment]
Well, then just wait for the next Update. I hope it'll be fixed there.
Sorry :(

**Comment by accessdenied0** [comment]
@Ellpeck,

I don't know what kind of magic you used, but at least your plants work again and this very well.

Thank you allot,

access_denied
