### ISSUE TITLE
Client crash rendering worm?

### ISSUE THREAD

**Issue by Apocryphai** [Ellpeck/ActuallyAdditions#602]
Hi, I'm running AA r98 on 1.10.2 in a modified AllTheMods pack on a server, and my client crashed earlier on. Now it crashes as soon as I log on every time. The crash log seems to indicate it's having a problem rendering a worm. I have about 16 worms placed down on the ground surrounding crops which are being farmed by an EnderIO Farming Station.

Here's the crash log: https://zerobin.net/?dc5880c3f20480c1#lF+k7JfDS+4AGWzLykeKJASfO36piyIQzh4pOOdrwuI=

Let me know if there's any more information I can provide or if this is caused by something else :) Thanks!

**Comment by Ellpeck** [comment]
There's no stack trace of the crash in that log. It ends before the game even finishes starting up.
But try uninstalling OptiFine and see if it continues happening.

**Comment by Apocryphai** [comment]
That's bizarre, I have no idea why the log got truncated like that! Anyway, you're correct, it's an Optifine error. Disabling Optifine fixes it. Sorry to bother you :)
