### ISSUE TITLE
Ring does not appear to work

### ISSUE THREAD

**Issue by xbony2** [Ellpeck/ActuallyAdditions#603]
![2017-01-28_07 54 00](https://cloud.githubusercontent.com/assets/5623501/22396750/4619a71a-e52f-11e6-9b82-be3f4620549c.png)

Did I mess something up or nah? Version 1.11.2-r99.

**Comment by xbony2** [comment]
Can confirm this is a crossmod issue. Gonna try to figure out what causes it.

**Comment by xbony2** [comment]
It appears to be an issue between Integrated Dynamics and this mod. @rubensworks

**Comment by Ellpeck** [comment]
How? O_o
This is just a custom crafting recipe.

**Comment by xbony2** [comment]
Works without ID, doesn't work with it ¯\_(ツ)_/¯ I tested it with just its dependencies installed- seems to be ID.

**Comment by Ellpeck** [comment]
@rubensworks pls

**Comment by rubensworks** [comment]
Yep, my bad, I hope to fix it soon. CyclopsMC/IntegratedDynamics#121
