### ISSUE TITLE
Liquids doesn't flow the right way when close to an edge

### ISSUE THREAD

**Issue by MisterPeModder44** [Ellpeck/ActuallyAdditions#605]
![2017-01-29_02 59 51](https://cloud.githubusercontent.com/assets/7838479/22401348/ccb8ebe6-e5cf-11e6-95ef-485fd92db6dc.png)

It's hard to see on the image, but the source blocks are not flowing the right way

**Comment by Ellpeck** [comment]
I'm just using the Forge fluids and it's the way they work.
I don't really care about it to be honest, though. Sorry.
