### ISSUE TITLE
Inventory Tweaks cannot sort Storage Crate content.

### ISSUE THREAD

**Issue by Zarepheth** [Ellpeck/ActuallyAdditions#606]
When using Inventory Tweaks along with Actually Additions, the Inventory Sorting/Organizing buttons are displayed next to the storage crate's inventory. However, when I click any of the buttons, a Null Point Exception occurs.

[latest.log.txt](https://github.com/Ellpeck/ActuallyAdditions/files/737350/latest.log.txt)

[Inventory Teaks #431](https://github.com/Inventory-Tweaks/inventory-tweaks/issues/431)

**Comment by Ellpeck** [comment]
This is an InvTweaks bug. I have no control, using the API, how to sort a chest code-wise.
