### ISSUE TITLE
[Suggestion] Crusher support for Modded Ores

### ISSUE THREAD

**Issue by Dragnier** [Ellpeck/ActuallyAdditions#608]
I noticed that the crusher doesn't automatically have support for crushed mod ores. Mods like Forestry don't have a dust/crushed version of the mod ores to even configure as a crusher recipe if that is an option. Perhaps built-in support for the most common modded ores could be added?

Copper, Tin, Lead, Silver, Zinc, Aluminum, and Nickel would probably cover everything in the event that a mod doesn't include it's own dust version.

**Comment by Ellpeck** [comment]
No, I have no interest in implementing this, sorry.

**Comment by Dragnier** [comment]
I was really hoping to use your mod in a slightly modded 1.11.2 vanilla pack, but if I can't use it to crush ores beyond vanilla I'll have to look elsewhere. The other features were just icing. I don't want two mods simply to support the same feature twice in order to keep the extraneous features.

**Comment by YasminEndusa** [comment]
If you don't want to use the mod just because a feature is missing and is not going to be implemented (and honestly, why should it be?), you don't have to use the mod. :)

**Comment by AEnterprise** [comment]
@Dragnier you can always add them in yourself using another mod
