### ISSUE TITLE
Book Formatting Issue

### ISSUE THREAD

**Issue by JaRyCu** [Ellpeck/ActuallyAdditions#612]
![2017-02-01_14 12 40](https://cloud.githubusercontent.com/assets/15949393/22522201/c5d47c76-e888-11e6-853e-8c887603bc2c.png)

On the Item Laser section of the Actually Additions manual, I can only see the first page or two and the last page or two.  Something is majorly messed up with the formatting.  This happens with texture packs and with no texture pack at all, just vanilla images.

I forgot all of the important information:

Modpack: FTB Presents Direwolf20 v1.4.1
AA Version: r98
single player, no server involved

**Comment by Ellpeck** [comment]
This has been fixed already in an unreleased version.
