### ISSUE TITLE
Add break event to blocks that break stuff (in addition to the drop event that there is now)

### ISSUE THREAD

**Issue by Eufranio** [Ellpeck/ActuallyAdditions#614]
When cancelling the Break event of the Vertical Digger (or fake player), it will still generating the item in it's inventory. This is bad because at same time that we are cancelling the event because of griefing pruposes, we're creating a new dupe (since the block won't be harvested, but the player will get the drop).

**Comment by Ellpeck** [comment]
uh, how did I make that happen

**Comment by Ellpeck** [comment]
That doesn't really make any sense according to the code.
Does it actually not break the block when that happens?

**Comment by Eufranio** [comment]
Yes, it doesn't break the block. Gif: https://gyazo.com/9988415df70fb824c541ccb71eb37bed

**Comment by Ellpeck** [comment]
That doesn't make any sense :V 
I guess I gotta look into this some more.

**Comment by Ellpeck** [comment]
How do you cancel the break event in this case? The breaking code is directly tied to the adding to inventory code, so if the area is protected, both should fail.

**Comment by Eufranio** [comment]
[GriefPrevention](https://github.com/MinecraftPortCentral/GriefPrevention) is a Sponge protection plugin that will cancel the break event when it should not happen.

**Comment by Ellpeck** [comment]
The thing I am confused about is that there is no break event occuring. When I implemented the evening calling, I only implemented the HarvestDropsEvent to be called, and that is still being called. When the chance of something dropping that is returned from it is met, then the block will be harvested along with the item being added to the inventory. This couldn't possibly break if GriefPrevention only prevents a BreakEvent.

**Comment by Eufranio** [comment]
@bloodmc @Aaron1011

**Comment by Ellpeck** [comment]
(Note: I realize that there should probably be a BreakEvent occuring here. There just isn't. I'm directly setting the block in the world though, and that should work regardless of protection.)

**Comment by AEnterprise** [comment]
@Ellpeck that would depend on the permissions mod, i know there used to be (not sure if this is still the case) mods that constantly check blocks in the protected area and 'restore' how it should have been in an attempt to 'work arround mods that do not emit the correct events' and then resort to such mesures

not sure if that's the case here, just something i have run accross in the past that could explain this

**Comment by Ellpeck** [comment]
Weird. I guess I'll add the proper break event, that should fix it.
