### ISSUE TITLE
Slice'n'Splice Ender IO with Actually Additions Axes [improvement] [minor]

### ISSUE THREAD

**Issue by kingskybomber14** [Ellpeck/ActuallyAdditions#615]
I'm not sure whether the issue is on your end or on Ender IO's end, but i was unable to put the obsidian axe in the slice'n'splice'

**Comment by Ellpeck** [comment]
I feel like implementing this would be sort of a waste of time. You can just put in an iron axe and it will last basically forever - I've never seen one run out.
Sorry, this doesn't seem that important to me.
