### ISSUE TITLE
endermen Spawner changed with spawner changer refuses to spawn ..

### ISSUE THREAD

**Issue by Rexei** [Ellpeck/ActuallyAdditions#617]
as said in title .. it refuses to spawn after a while.. it just stops 
im using ftb infinity ligth 1.10 
is it something im doing wrong? i tried to kill all mobs in the area. tried with and without ligth

**Comment by Rexei** [comment]
jupp tested in parts not just sawn.. after 3-5 spawns it just stops and i have to move it again

**Comment by Ellpeck** [comment]
Which version are you on?

**Comment by Rexei** [comment]
ActuallyAdditions-1.10.2-r93 says in the mod map :)

**Comment by Ellpeck** [comment]
What type of spawner did you change?

**Comment by Rexei** [comment]
I changed a blaze spawner :)

**Comment by Ellpeck** [comment]
Could you please try to see if this is recreatable in 1.11 also?

**Comment by Rexei** [comment]
that means making a small modpack for 1.11 with some of the same mods? or just actually additons?

**Comment by Ellpeck** [comment]
You should first try with just Actually Additions in 1.10, if you think another mod could be causing it. If it works without any other mods, try finding out which mod causes the issue.

**Comment by Rexei** [comment]
it worked perfectly so far in 1.11 when i tested.. 
i tested it in same modpack on a creative world   and cant seem to recreate it ..
i can say only thing i did with the spawner is move it with cardboard box from mekansim
Maby its just a one time thing?

**Comment by Ellpeck** [comment]
Can you reproduce it on the world that it originally happened in?

**Comment by Rexei** [comment]
i would have to change another spawner  wich tbh takes such a long time to farm.. 
can try with another mob thats needed then comes the question does wither skeletons work with spawning or do i need a skeleton spawner in the nether as normal?

**Comment by Ellpeck** [comment]
Whatever happened to this? 
As I said, please try to see if the issue is recreatable without using the cardboard box and on different spawners. :)

**Comment by Rexei** [comment]
i tried recreating the issue but other than the enderman spawner changed form blaze spawns really slowly it does not stop completly as happend on one server i played on
sorry i tried for a few hours trying to re create it 
any other changed blaze spawner like skeleton works fine
