### ISSUE TITLE
JEI browsing crash

### ISSUE THREAD

**Issue by IlluxiaDragon** [Ellpeck/ActuallyAdditions#618]
So whenever I'm browsing the JEI in game it crashes when I get to actually additions. The problem resolves if I remove actually additions but I love the mod and I was wondering if you knew a fix for it. Here is the crash report that happens when I do that.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 2/4/17 11:30 AM
Description: Rendering screen

java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
	at cofh.api.energy.ItemEnergyContainer.getEnergyStored(ItemEnergyContainer.java:98)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.getDurabilityForDisplay(ItemEnergy.java:99)
	at net.minecraft.client.renderer.RenderItem.func_180453_a(RenderItem.java:420)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderOverlay(GuiIngredientFast.java:205)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderOverlay(GuiIngredientFast.java:195)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:187)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_244_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.api.energy.ItemEnergyContainer.getEnergyStored(ItemEnergyContainer.java:98)
	at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.getDurabilityForDisplay(ItemEnergy.java:99)
	at net.minecraft.client.renderer.RenderItem.func_180453_a(RenderItem.java:420)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderOverlay(GuiIngredientFast.java:205)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderOverlay(GuiIngredientFast.java:195)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:187)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_244_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (433, 11). Absolute: (1298, 732)
	Screen size: Scaled: (456, 256). Absolute: (1366, 768). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Illuxia'/408, l='MpServer', x=161.12, y=64.00, z=248.22]]
	Chunk stats: MultiplayerChunkCache: 420, 420
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (156,64,256), Chunk: (at 12,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1764 game time, 1764 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 128 total; [EntitySheep['Sheep'/256, l='MpServer', x=190.09, y=78.00, z=224.50], EntitySheep['Sheep'/257, l='MpServer', x=191.16, y=79.00, z=224.50], EntityCreeper['Creeper'/258, l='MpServer', x=178.50, y=41.00, z=256.50], EntityWolf['Wolf'/259, l='MpServer', x=185.50, y=71.00, z=301.50], EntityWolf['Wolf'/260, l='MpServer', x=185.50, y=71.00, z=298.50], EntityWolf['Wolf'/261, l='MpServer', x=184.50, y=71.00, z=299.50], EntityWolf['Wolf'/262, l='MpServer', x=186.50, y=71.00, z=300.50], EntitySheep['Sheep'/273, l='MpServer', x=205.45, y=66.00, z=173.50], EntitySheep['Sheep'/274, l='MpServer', x=206.50, y=66.00, z=171.50], EntitySheep['Sheep'/276, l='MpServer', x=206.54, y=66.00, z=173.50], EntitySheep['Sheep'/277, l='MpServer', x=193.64, y=77.00, z=200.31], EntitySheep['Sheep'/278, l='MpServer', x=186.79, y=80.00, z=205.50], EntitySheep['Sheep'/279, l='MpServer', x=200.73, y=76.00, z=195.50], EntityItem['item.tile.doublePlant.paeonia'/280, l='MpServer', x=205.13, y=71.00, z=202.18], EntitySheep['Sheep'/281, l='MpServer', x=203.50, y=76.00, z=236.81], EntitySheep['Sheep'/282, l='MpServer', x=194.44, y=81.00, z=226.18], EntitySheep['Sheep'/283, l='MpServer', x=203.60, y=72.00, z=242.60], EntitySheep['Sheep'/284, l='MpServer', x=206.50, y=71.00, z=243.50], EntityZombie['Zombie'/293, l='MpServer', x=222.35, y=54.00, z=191.35], EntityZombie['Zombie'/294, l='MpServer', x=216.46, y=53.00, z=187.18], EntitySheep['Sheep'/295, l='MpServer', x=212.50, y=70.00, z=190.50], EntitySheep['Sheep'/296, l='MpServer', x=213.50, y=69.00, z=192.50], EntitySheep['Sheep'/297, l='MpServer', x=211.50, y=70.00, z=194.50], EntitySkeleton['Skeleton'/298, l='MpServer', x=222.50, y=10.00, z=215.50], EntitySheep['Sheep'/299, l='MpServer', x=208.51, y=69.00, z=250.27], EntitySheep['Sheep'/300, l='MpServer', x=209.50, y=71.00, z=287.50], EntitySheep['Sheep'/301, l='MpServer', x=209.50, y=72.00, z=284.50], EntitySheep['Sheep'/302, l='MpServer', x=213.50, y=69.00, z=292.26], EntityBat['Bat'/558, l='MpServer', x=138.75, y=19.05, z=312.50], EntitySheep['Sheep'/303, l='MpServer', x=209.50, y=72.00, z=284.50], EntityCow['Cow'/304, l='MpServer', x=210.50, y=71.00, z=280.50], EntityCow['Cow'/305, l='MpServer', x=212.50, y=66.00, z=280.50], EntityCow['Cow'/306, l='MpServer', x=217.20, y=73.00, z=283.50], EntitySheep['Sheep'/307, l='MpServer', x=223.30, y=64.00, z=300.69], EntityCow['Cow'/308, l='MpServer', x=214.55, y=69.00, z=289.87], EntitySheep['Sheep'/309, l='MpServer', x=222.51, y=65.00, z=295.74], EntityCow['Cow'/310, l='MpServer', x=223.55, y=64.00, z=304.47], EntityCow['Cow'/311, l='MpServer', x=222.45, y=64.00, z=305.55], EntityCow['Cow'/312, l='MpServer', x=222.61, y=64.00, z=304.55], EntityZombie['Zombie'/317, l='MpServer', x=225.50, y=47.00, z=175.50], EntityZombie['Zombie'/318, l='MpServer', x=225.50, y=47.00, z=173.50], EntityZombie['Zombie'/319, l='MpServer', x=227.50, y=47.00, z=173.50], EntityZombie['Zombie'/320, l='MpServer', x=218.51, y=53.00, z=172.19], EntityZombie['Zombie'/321, l='MpServer', x=227.50, y=54.00, z=171.50], EntitySheep['Sheep'/322, l='MpServer', x=230.50, y=63.00, z=298.50], EntitySheep['Sheep'/323, l='MpServer', x=227.50, y=64.00, z=300.50], EntityZombie['Zombie'/116, l='MpServer', x=84.50, y=17.00, z=205.50], EntityZombie['Zombie'/117, l='MpServer', x=84.50, y=17.00, z=203.50], EntityZombie['Zombie'/118, l='MpServer', x=85.50, y=17.00, z=204.50], EntityZombie['Zombie'/119, l='MpServer', x=85.50, y=17.00, z=199.50], EntitySheep['Sheep'/120, l='MpServer', x=94.50, y=66.00, z=205.50], EntityBat['Bat'/121, l='MpServer', x=98.86, y=21.97, z=262.24], EntityZombie['Zombie'/122, l='MpServer', x=93.50, y=18.00, z=277.50], EntitySkeleton['Skeleton'/124, l='MpServer', x=93.50, y=18.00, z=324.50], EntitySheep['Sheep'/128, l='MpServer', x=99.52, y=67.00, z=215.28], EntitySheep['Sheep'/129, l='MpServer', x=97.50, y=67.00, z=213.19], EntitySheep['Sheep'/130, l='MpServer', x=111.45, y=64.00, z=248.50], EntityCreeper['Creeper'/131, l='MpServer', x=110.50, y=23.00, z=286.50], EntityCreeper['Creeper'/132, l='MpServer', x=109.50, y=23.00, z=283.50], EntityBat['Bat'/133, l='MpServer', x=105.88, y=18.05, z=322.80], EntitySkeleton['Skeleton'/145, l='MpServer', x=113.50, y=47.00, z=227.50], EntitySquid['Squid'/146, l='MpServer', x=120.84, y=62.51, z=240.88], EntitySheep['Sheep'/147, l='MpServer', x=120.23, y=63.00, z=249.51], EntitySheep['Sheep'/148, l='MpServer', x=112.40, y=64.00, z=248.62], EntitySheep['Sheep'/149, l='MpServer', x=113.38, y=64.00, z=248.02], EntityZombie['Zombie'/150, l='MpServer', x=120.50, y=28.00, z=287.50], EntityZombie['Zombie'/151, l='MpServer', x=123.50, y=29.00, z=289.50], EntityWitch['Witch'/152, l='MpServer', x=126.50, y=22.00, z=315.50], EntityPlayerSP['Illuxia'/408, l='MpServer', x=161.12, y=64.00, z=248.22], EntityCreeper['Creeper'/153, l='MpServer', x=116.49, y=23.00, z=311.34], EntityBat['Bat'/154, l='MpServer', x=111.30, y=20.02, z=311.48], EntityCreeper['Creeper'/171, l='MpServer', x=143.50, y=20.00, z=175.50], EntitySheep['Sheep'/172, l='MpServer', x=141.46, y=73.00, z=177.74], EntitySheep['Sheep'/173, l='MpServer', x=133.51, y=73.00, z=177.73], EntitySheep['Sheep'/174, l='MpServer', x=128.52, y=72.00, z=175.77], EntitySheep['Sheep'/175, l='MpServer', x=133.67, y=72.00, z=179.88], EntitySkeleton['Skeleton'/176, l='MpServer', x=141.50, y=19.00, z=214.50], EntityZombie['Zombie'/177, l='MpServer', x=135.49, y=51.00, z=236.80], EntityItem['item.item.algues'/178, l='MpServer', x=142.88, y=59.00, z=242.41], EntityItem['item.item.algues'/179, l='MpServer', x=138.98, y=57.00, z=243.38], EntitySquid['Squid'/180, l='MpServer', x=140.60, y=62.00, z=249.60], EntityBat['Bat'/181, l='MpServer', x=125.25, y=27.10, z=290.79], EntitySheep['Sheep'/182, l='MpServer', x=143.45, y=67.00, z=297.55], EntityCow['Cow'/183, l='MpServer', x=141.50, y=70.00, z=302.50], EntityCow['Cow'/184, l='MpServer', x=142.50, y=70.00, z=302.50], EntityCow['Cow'/185, l='MpServer', x=143.45, y=65.00, z=295.33], EntitySkeleton['Skeleton'/186, l='MpServer', x=142.28, y=55.00, z=305.52], EntityCow['Cow'/187, l='MpServer', x=143.50, y=71.00, z=306.50], EntityCreeper['Creeper'/197, l='MpServer', x=145.50, y=20.00, z=174.50], EntityPig['Pig'/198, l='MpServer', x=151.50, y=66.00, z=200.75], EntitySheep['Sheep'/199, l='MpServer', x=145.04, y=72.00, z=198.50], EntitySheep['Sheep'/200, l='MpServer', x=145.50, y=71.00, z=196.50], EntitySheep['Sheep'/201, l='MpServer', x=144.50, y=71.00, z=197.50], EntitySheep['Sheep'/202, l='MpServer', x=147.20, y=72.00, z=197.55], EntityPig['Pig'/203, l='MpServer', x=147.50, y=64.00, z=207.50], EntityPig['Pig'/204, l='MpServer', x=145.50, y=66.00, z=209.50], EntityPig['Pig'/205, l='MpServer', x=154.50, y=64.00, z=213.30], EntityZombie['Zombie'/206, l='MpServer', x=151.50, y=22.00, z=234.50], EntityCreeper['Creeper'/207, l='MpServer', x=149.50, y=19.00, z=225.50], EntityCreeper['Creeper'/208, l='MpServer', x=147.50, y=34.00, z=239.50], EntitySkeleton['Skeleton'/209, l='MpServer', x=152.50, y=13.00, z=240.50], EntityCreeper['Creeper'/210, l='MpServer', x=151.50, y=13.00, z=241.50], EntityCreeper['Creeper'/211, l='MpServer', x=147.51, y=16.00, z=246.17], EntitySkeleton['Skeleton'/212, l='MpServer', x=155.50, y=20.00, z=245.50], EntitySheep['Sheep'/213, l='MpServer', x=144.50, y=68.00, z=298.50], EntitySheep['Sheep'/214, l='MpServer', x=147.50, y=66.00, z=297.50], EntitySheep['Sheep'/215, l='MpServer', x=147.50, y=66.00, z=297.50], EntitySkeleton['Skeleton'/216, l='MpServer', x=151.50, y=23.00, z=315.50], EntityBat['Bat'/219, l='MpServer', x=145.39, y=56.10, z=320.83], EntityZombie['Zombie'/232, l='MpServer', x=164.46, y=44.00, z=197.82], EntityBat['Bat'/233, l='MpServer', x=157.18, y=12.12, z=217.51], EntitySquid['Squid'/234, l='MpServer', x=170.10, y=62.41, z=211.29], EntityZombie['Zombie'/235, l='MpServer', x=169.50, y=29.00, z=224.50], EntityZombie['Zombie'/236, l='MpServer', x=178.69, y=30.00, z=223.16], EntityBat['Bat'/237, l='MpServer', x=173.27, y=28.34, z=236.49], EntityWitch['Witch'/238, l='MpServer', x=168.50, y=14.00, z=256.50], EntityBat['Bat'/239, l='MpServer', x=180.59, y=37.00, z=265.50], EntityBat['Bat'/240, l='MpServer', x=170.73, y=38.52, z=268.65], EntitySkeleton['Skeleton'/241, l='MpServer', x=173.50, y=56.00, z=293.50], EntitySheep['Sheep'/247, l='MpServer', x=187.52, y=81.00, z=212.77], EntitySkeleton['Skeleton'/248, l='MpServer', x=179.50, y=45.00, z=210.50], EntitySquid['Squid'/249, l='MpServer', x=177.60, y=61.00, z=217.40], EntitySquid['Squid'/250, l='MpServer', x=175.40, y=59.49, z=218.40], EntitySquid['Squid'/251, l='MpServer', x=175.53, y=59.33, z=220.49], EntitySquid['Squid'/252, l='MpServer', x=179.40, y=60.16, z=223.89], EntitySheep['Sheep'/253, l='MpServer', x=189.50, y=77.00, z=223.50], EntitySheep['Sheep'/254, l='MpServer', x=190.52, y=79.00, z=209.25], EntitySquid['Squid'/255, l='MpServer', x=180.60, y=61.00, z=220.40]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 325110328 bytes (310 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r98} [Actually Additions] (ActuallyAdditions-1.10.2-r98.jar) 
	UCHIJAAAA	aim{1.1.0} [Advanced Inventory Managment] (AdvancedInventoryManagement-1.10.2-1.1.0.jar) 
	UCHIJAAAA	agriculturalexpansion{r-1.2.0} [Agricultural Expansion] (AgriculturalExpansion[1.9.4][1.10.2]-r1.2.2.jar) 
	UCHIJAAAA	animalbikes{1.10.2} [Animal Bikes] (AnimalBikes_1.10.2(19nov16).jar) 
	UCHIJAAAA	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.10.2.jar) 
	UCHIJAAAA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCHIJAAAA	chancecubes{1.10.2-2.3.4.166} [Chance Cubes] (ChanceCubes-1.10.2-2.3.4.166.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.29} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.29.jar) 
	UCHIJAAAA	customstartinggear{1.0.0} [Custom Starting Gear] (CustomStartingGear-1.10.2-1.0.0.5-universal.jar) 
	UCHIJAAAA	D3Core{1.3.0.59} [DÂ³Core] (D3Core-1.9.4-1.3.0.59.jar) 
	UCHIJAAAA	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	UCHIJAAAA	ediblebugs{1.4.6.2099} [Edible Bugs Mod] (ediblebugs-MC1.10.02_EB1.4.6.2099.jar) 
	UCHIJAAAA	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.10-1.10.2.jar) 
	UCHIJAAAA	extraalchemy{0.3.0.4-hotfix-release} [Extra Alchemy] (extraalchemy-0.3.0.4-hotfix-release.jar) 
	UCHIJAAAA	ezstorage{2.2.6} [EZStorage 2] (ezstorage-2.2.6.jar) 
	UCHIJAAAA	samsfooddetails{1.0.1} [Food Details] (FoodDetails-1.10.2-1.0.1.jar) 
	UCHIJAAAA	fe{1.3} [Food Expansion] (FoodExpansion1.3.1-1.10.2.jar) 
	UCHIJAAAA	InventoryPets{1.4.9} [Inventory Pets] (inventorypets-1.10-1.4.9.jar) 
	UCHIJAAAA	JEI{3.14.2.401} [Just Enough Items] (jei_1.10.2-3.14.2.401.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.22} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.22.jar) 
	UCHIJAAAA	JsonLootBags{1.0.0.10} [JsonLootBags] (JsonLootBags-1.9.4-1.0.0.10.jar) 
	UCHIJAAAA	lootbags{2.3.2} [Loot Bags] (LootBags-1.10.2-2.3.2.jar) 
	UCHIJAAAA	LotsOfFood{1.12.0} [Lots of Food] (Lots of Food-1.12.0.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.4.203} [Mantle] (Mantle-1.10.2-1.1.4.jar) 
	UCHIJAAAA	morefood{1.17} [More Foods] (more-foods-1.10.2-2011-1.17.jar) 
	UCHIJAAAA	shear{1.1.2} [More Shearables] (MoreShearables1.2.1-1.10.2.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
	UCHIJAAAA	mc{1.7b} [Primordial Crops] (PrimordialCrops-v1.7b_mc1.9.4.jar) 
	UCHIJAAAA	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCHIJAAAA	reap{1.3.3} [Reap Mod] (ReapMod 1.3.3.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.620} [Reliquary] (Reliquary-1.10.2-1.3.3.620.jar) 
	UCHIJAAAA	shelves{0.1} [Simple Shelves] (SimpleShelves-1.10.2-0.2.jar) 
	UCHIJAAAA	SimpleUpgrades{2.1.7} [SimpleUpgrades] (simpleupgrades-1.10.2-2.1.8-release.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (Waila-Harvestability-Mod-1.10.2.jar) 
	UCHIJAAAA	weaponcaseloot{4.0.1} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 5500'
	D3Core: Debug: false Silliness: true AprilFools: true PastPost:true
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4549, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-5020U CPU @ 2.20GHz

**Comment by canitzp** [comment]
Update your mods, there is a other mod that do bad stuff

**Comment by IlluxiaDragon** [comment]
Please be more specific, that is not helpful. I'm running minecraft 10.2 btw. And again, the only problem is when actually additions is there

**Comment by canitzp** [comment]
One of your mods except from actuallyadditions is outdated. I do not know which one, I maybe can be more specific with the crash report file. (This looks like these are the last lines of the log file, I'm not sure)

**Comment by IlluxiaDragon** [comment]
This is the whole crash report

**Comment by canitzp** [comment]
Normally at the end of a crash report is a list of loaded apis and out of this list I can say you which mod break it, otherwise update every mod

**Comment by Ellpeck** [comment]
Some mod is shipping an outdated version of the RF API. This is not my error.

**Comment by ktole1999** [comment]
@IlluxiaDragon you can try and create this custom pack using curse launcher. save headache of tracking down all the mods.
