### ISSUE TITLE
There seems to be a bug with ender IO capacitors & energy laser relays.

### ISSUE THREAD

**Issue by jazzadellic** [Ellpeck/ActuallyAdditions#619]
I'm playing Direwolf20 modpack for MC 1.10.2, and I just realized I don't have the latest version ;oP, but the pack uses AA 1.10.2. Has this issue been dealt with in the current version? 

The issue is if I have more than one ender IO capacitor bank connected to the same laser relay network, there is a -50 RF per tick drain on every capacitor. This is without any machines running or even **connected** to the network. So if I have 5 ender io capacitors connected to the same laser relay network I'll get a total loss of -250 RF a tick. This is a HUGE waste of energy in early game which is basically where I am at in terms of energy generation. I had a cool build idea which included several EIO capacitors connected to the same network, and the entire build has to be scrapped (after I already wasted several hours on it!), because of this glitch. Note that having only 1 EIO capacitor bank connected to the network results in this problem not showing up at all. At first I thought it might have something to do with the "light energy loss" associated with laser relays but then realized it was specifically only happening with 2 or more EIO capacitors on the network, and is clearly a bug. 

My apologies if this HAS been fixed in the current version, but if it hasn't been addressed specifically, then I would assume this problem still exists.

I'm a little wary of updating AA to the current version as I have screwed up game saves by updating mods before....I usually prefer the modpack author to do the updating so they can make any necessary config changes.

**Comment by Ellpeck** [comment]
Set one capacitor to input only and one to output only. The laser relays will transfer energy back and forth between the capacitors, draining the 5% energy loss they have every time in the process. This is not a bug, just a quirk with how energy transfer works.

**Comment by jazzadellic** [comment]
Ah I see. This does severely limit the ways in which you can use laser relays. A capacitor that has it's output mode turned off is essentially useless then because you can't use it to power anything that needs power...I was trying to make a build which basically had a canola oil processing room as the central power generation area, which then sent all the power (via oil generators) into a laser relay network which was connected to EIO capacitors in several different rooms, and then use the capacitors to distribute the power to all the necessary devices in each room...Which seems like a perfectly good way to utilize the laser relays. But the -250 RF a tick is too much for me at this early stage of the game. Would it be possible for a future version to allow specifically for EIO capacitors to NOT keep sending energy back and forth to each other, and thus simply wasting RF? I understand the idea is the capacitors both pull and send energy, but it seems like the lasers could be "smartly" programmed not to send energy to other capacitors. This would allow for much more flexibility with setting up capacitors (and I imagine other energy storage devices) and laser relays.

**Comment by jazzadellic** [comment]
Well I guess I meant limiting in the sense of how much RF you can afford to lose in this way. Thank you for taking the time, and the quick response! Love the mod btw, just this one thing has confused me a bit. Here is one final idea that just popped in my head. What if the advanced laser relays let you use filters, much like the item laser relays. And these filters you could tell the relay "you are allowed to send energy to this machine, but not this one" etc... I suppose there are other cool things you could do with it like maybe have different colored channels like EIO conduit. It could allow for some more careful management of energy. Anyways, I don't know how logical this would be to have as a feature, just an idea! That could allow someone in the early game to do setups and minimize RF waste. I realize this won't be an issue in later game when you have huge amounts of RF generating, but could be handy in the earlier game ;o)

Again, thanks for the great mod and your time!
