### ISSUE TITLE
Leaf Generator hurts framerate bit too much.

### ISSUE THREAD

**Issue by Kazzamkablam** [Ellpeck/ActuallyAdditions#62]
Hi, I noticed that when I use two Leaf Generators same time it really hurts the frame rate. Would it be possible to have option to disable sound and/or effects it causes for better performance? 

On some other mods i've used that have machines that affect leaves and have option to disable effects/sound, it really improves their performance.

**Comment by Ellpeck** [comment]
Dude, you must have a really bad PC.
When I use multiple ones, performance doesn't change.

**Comment by Ellpeck** [comment]
Closed by https://github.com/Ellpeck/ActuallyAdditions/commit/aa30035cee259afe02040b106490dfacdd633669

**Comment by Kazzamkablam** [comment]
actually very high end PC and if you're within hearing range of them it drops frame rate a lot when it's working
