### ISSUE TITLE
TOP reports AA Crops as their seed versions, instead of plant versions (including the image)

### ISSUE THREAD

**Issue by JaSpr** [Ellpeck/ActuallyAdditions#620]
Running "All The Mods" for 1.10.2.

http://i.imgur.com/lTqEAEb.jpg
http://i.imgur.com/iRV25SG.jpg

Strangely (as the screenshot shows) WAILA gets it right, and WAILA is usually the one that's wrong.

**Comment by JaSpr** [comment]
https://github.com/McJty/TheOneProbe/issues/128

**Comment by Ellpeck** [comment]
This is not a bug, it's intended.

**Comment by Ellpeck** [comment]
TOP displays the Creative Mode picked items of blocks, and for the Wild Plants, this is what gets returned. I personally prefer the wild plants returning the seeds much like things like Wheat plants return the wheat item instead of the actual wheat block.
