### ISSUE TITLE
Canola plant getCrop returns paper cone

### ISSUE THREAD

**Issue by Ricket** [Ellpeck/ActuallyAdditions#623]
See https://github.com/TehNut/HWYLA/issues/49

Actually Additions: ActuallyAdditions-1.10.2-r98

Apparently when HWYLA calls getCrop() on a canola plant, it returns the paper cone item.

**Comment by Ellpeck** [comment]
This isn't my issue. 
All misc items in Actually Additions are the same item, just with different metadatas. The canola item is part of that miscellaneous list, so it's the misc item with a different metadata.
The misc item with metadata 0 just happens to be the paper cone, so it's being displayed that way, I guess.
