### ISSUE TITLE
[1.10.2] Worm Server crash on BOP grass

### ISSUE THREAD

**Issue by DeadSix27** [Ellpeck/ActuallyAdditions#626]
AA version: `ActuallyAdditions-1.10.2-r98.jar`

Not sure what exactly crashes it, but worms on BOP grass seems to be in the trace and it also happened after a I placed the worm..

Stacktrace: https://gist.github.com/DeadSix27/43abfe39d942207e10bbd368d22ceca1

**Comment by Ellpeck** [comment]
Meh.

**Comment by Ellpeck** [comment]
The actual thing that crashes here seems to be `at ruby.bamboo.block.GrowableBase.getGrowRate(GrowableBase.java:104) ~[GrowableBase.class:?]`.
If it turns out that this issue is on my side and I'm just a derp, please reopen this issue.

**Comment by DeadSix27** [comment]
@Ellpeck I checked back on that earlier and I can confirm its caused by the bamboo mod, I just didn't get to close this issue yet,
