### ISSUE TITLE
Biomash Recipe Missing

### ISSUE THREAD

**Issue by IamAlathe** [Ellpeck/ActuallyAdditions#627]
Suddenly, I cannot make biomash for compost.  It's like the recipe doesn't exist.  It's not in the manual, JEI will only send you to the manual if you try to select biomash, trying to make biomash with known recipes will not yield a result.  Reproduced in a clean, new world with only AA.

I didn't mean to eat the biomash recipe, I just got excited. 😆 

And hey, thanks for all your hard work. 😸

**Comment by Ellpeck** [comment]
Read the manual, it tells you how to make it.

**Comment by IamAlathe** [comment]
I know how to make it.  I've been playing with Actually Additions for a long time.  I just looked in the manual, searched "bio" and biomash is not even listed.  Just to test, I loaded a new world, with nothing but AA, went into creative mode, and grabbed a manual.  A search gave me the same result.  Biomash should be listed right there under (or above, I don't remember) Bio Reactor, no?

![screenshot 12](https://cloud.githubusercontent.com/assets/23068703/22856514/12f90304-f050-11e6-97c7-6e1b454e5f92.png)

![screenshot 13](https://cloud.githubusercontent.com/assets/23068703/22856517/181d5d44-f050-11e6-9f74-a5ada1d90a1b.png)

**Comment by IamAlathe** [comment]
I went back into that world, and tried to make biomash, it works with potatoes, but not with (wheat) seeds.  I thought it worked with seeds, because I used to do that to get rid of my excess seeds.  Am I really that confused?  Sorry to be such a pain.

**Comment by Ellpeck** [comment]
Read the changelog, the recipe changed. And yes, it not showing up in the manual is a little bit of a quirk, but just look up the compost page if it doesn't show up in the search results.

**Comment by Ellpeck** [comment]
Also, it DOES show up, looking at the screenshots. It lists the compost page, because that's which category it is explained under. So no quirk, after all.

**Comment by IamAlathe** [comment]
The recipe doesn't show up on the compost page either, I did look there.  I missed the recipe changing, my bad.  Thanks for the explanation. 😄

**Comment by Ellpeck** [comment]
"Bio-Mash is crafted from.." 
Reading is key.

**Comment by IamAlathe** [comment]
Yup, I'm a derp.  I think I need to go away from Minecraft a while and reactivate my brain. 😝
