### ISSUE TITLE
[1.10.2] Item Laser Issue

### ISSUE THREAD

**Issue by JFMillerUSA** [Ellpeck/ActuallyAdditions#628]
Do Item Lasers work with Storage Drawers, I seem to not be able to transfer items between two separate drawer systems. Used Advanced Item Lasers, Item Interface at both ends and nothing.

**Comment by Ellpeck** [comment]
Show me a screenshot of your setup.

**Comment by JFMillerUSA** [comment]
![2017-02-11_14 37 33](https://cloud.githubusercontent.com/assets/9157611/22857731/ee0d140a-f067-11e6-8422-7b8b26a52f4c.png)
![2017-02-11_14 37 58](https://cloud.githubusercontent.com/assets/9157611/22857734/f81d0eb4-f067-11e6-8e41-7a9a09141016.png)
![2017-02-11_14 37 02](https://cloud.githubusercontent.com/assets/9157611/22857737/ff79c224-f067-11e6-8002-73ce44e24ab6.png)
![2017-02-11_14 38 25](https://cloud.githubusercontent.com/assets/9157611/22857739/065769ac-f068-11e6-9f7e-41879df153c4.png)
![2017-02-11_14 38 41](https://cloud.githubusercontent.com/assets/9157611/22857740/0c2f07e0-f068-11e6-9f37-2a44e346e45f.png)
![2017-02-11_14 38 48](https://cloud.githubusercontent.com/assets/9157611/22857742/11ac80b2-f068-11e6-8810-b4ce59c5ec23.png)

**Comment by Ellpeck** [comment]
The inbound config on the laser relay on the drawer is set wrong. "Inbound" means "into this storage device" / "into the system", and the storage drawers are "the system".
