### ISSUE TITLE
Crash when looking at relays with CubeX2's Better Fonts installed.

### ISSUE THREAD

**Issue by OcAMD** [Ellpeck/ActuallyAdditions#629]
This is a copy of the [issue](https://github.com/cubex2/BetterFonts/issues/9) I created on his issue tracker:

I have the same issue in 1.11.2 using TTFR-1.11.2-1.7.2.jar. I am also using forge-1.11.2-13.20.0.2227.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  literalascension (literalascension-1.11.2-1.0.1.0.jar)
  CorePlugin (FluxedRedstone-2.6.0.54.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  BetterFontsCore (TTFR-1.11.2-1.7.2.jar)
  ForgelinPlugin (Forgelin-1.2.0.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.3.34-universal.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 2/11/17 4:31 PM
XRay version: 48
Description: Unexpected error

java.lang.StackOverflowError: Unexpected error
	at cubex2.ttfr.StringCache.cacheString(StringCache.java:741)
	at cubex2.ttfr.StringCache.sizeString(StringCache.java:610)
	at cubex2.ttfr.StringCache.sizeStringToWidth(StringCache.java:664)
	at net.minecraft.client.gui.FontRenderer.func_78259_e(FontRenderer.java)
	at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:935)
	at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:947) 
        This line continues for a really long time!!!!! 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cubex2.ttfr.StringCache.cacheString(StringCache.java:741)
	at cubex2.ttfr.StringCache.sizeString(StringCache.java:610)
	at cubex2.ttfr.StringCache.sizeStringToWidth(StringCache.java:664)
	at net.minecraft.client.gui.FontRenderer.func_78259_e(FontRenderer.java)
	at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:935)
	at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:947)
	Same as before repeats for a long time!
-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['OclockdAMD'/396, l='MpServer', x=372.74, y=63.00, z=510.06]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (208,64,256), Chunk: (at 0,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 280947 game time, 92298 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 91 total; [EntityBat['Bat'/393, l='MpServer', x=416.70, y=42.14, z=458.80], EntityBat['Bat'/394, l='MpServer', x=414.90, y=42.03, z=458.70], EntityZombie['Zombie'/395, l='MpServer', x=402.50, y=64.00, z=454.50], EntityWolf['Wolf'/397, l='MpServer', x=368.73, y=69.00, z=506.45], EntityWolf['Wolf'/398, l='MpServer', x=369.61, y=69.00, z=507.77], EntityBat['Bat'/399, l='MpServer', x=308.32, y=48.10, z=471.45], EntityItem['item.item.arrow'/400, l='MpServer', x=310.49, y=70.00, z=490.12], EntityWolf['Wolf'/401, l='MpServer', x=319.39, y=70.00, z=503.51], EntityCreeper['Creeper'/402, l='MpServer', x=317.50, y=69.00, z=542.50], EntityZombieVillager['Zombie Villager'/531, l='MpServer', x=300.50, y=69.00, z=510.50], EntitySquid['Squid'/403, l='MpServer', x=313.74, y=61.00, z=555.19], EntitySquid['Squid'/404, l='MpServer', x=321.86, y=60.06, z=555.85], EntityChicken['Chicken'/405, l='MpServer', x=304.81, y=68.00, z=574.57], EntityCreeper['Creeper'/279, l='MpServer', x=298.50, y=64.00, z=449.50], EntityWolf['Wolf'/407, l='MpServer', x=328.79, y=65.24, z=467.30], EntityItem['item.item.arrow'/408, l='MpServer', x=329.37, y=64.00, z=469.72], EntityItem['item.item.bone'/409, l='MpServer', x=328.66, y=64.00, z=469.55], EntityCow['Cow'/665, l='MpServer', x=451.43, y=70.00, z=443.74], EntityWolf['Wolf'/410, l='MpServer', x=332.48, y=69.00, z=493.44], EntityWolf['Wolf'/411, l='MpServer', x=331.06, y=69.00, z=500.50], EntityWolf['Wolf'/412, l='MpServer', x=322.40, y=70.00, z=520.10], EntityWolf['Wolf'/413, l='MpServer', x=322.98, y=70.00, z=521.11], EntitySquid['Squid'/414, l='MpServer', x=345.00, y=49.51, z=463.40], EntityWolf['Wolf'/415, l='MpServer', x=346.54, y=69.00, z=486.63], EntityZombie['Zombie'/416, l='MpServer', x=342.18, y=26.00, z=533.32], EntityZombie['Zombie'/417, l='MpServer', x=348.50, y=25.00, z=525.50], EntityWolf['Wolf'/418, l='MpServer', x=340.57, y=69.00, z=512.52], EntityZombie['Zombie'/419, l='MpServer', x=346.50, y=25.00, z=529.50], EntityWolf['Wolf'/420, l='MpServer', x=347.69, y=69.00, z=542.71], EntityChicken['Chicken'/677, l='MpServer', x=298.47, y=68.00, z=577.01], EntityBat['Bat'/421, l='MpServer', x=359.75, y=27.10, z=535.75], EntitySkeleton['Skeleton'/422, l='MpServer', x=358.50, y=26.00, z=530.50], EntityItem['item.item.arrow'/423, l='MpServer', x=354.75, y=69.00, z=552.29], EntityItem['item.item.bone'/424, l='MpServer', x=355.03, y=69.00, z=552.64], EntityWolf['Wolf'/425, l='MpServer', x=375.47, y=64.00, z=471.64], EntityWolf['Wolf'/426, l='MpServer', x=370.46, y=64.00, z=473.73], EntityCreeper['Creeper'/427, l='MpServer', x=380.50, y=21.00, z=524.50], EntityCreeper['Creeper'/428, l='MpServer', x=376.50, y=21.00, z=524.50], EntitySkeleton['Skeleton'/301, l='MpServer', x=311.61, y=62.32, z=439.39], EntitySkeleton['Skeleton'/429, l='MpServer', x=372.50, y=13.00, z=557.50], EntityWolf['Wolf'/302, l='MpServer', x=309.90, y=62.54, z=442.12], EntityZombie['Zombie'/430, l='MpServer', x=371.50, y=13.00, z=558.50], EntitySkeleton['Skeleton'/431, l='MpServer', x=378.50, y=64.00, z=551.50], EntityCreeper['Creeper'/432, l='MpServer', x=374.50, y=64.00, z=554.50], EntitySkeleton['Skeleton'/433, l='MpServer', x=373.14, y=65.00, z=567.50], EntityCreeper['Creeper'/434, l='MpServer', x=393.50, y=65.00, z=467.50], EntityWolf['Wolf'/435, l='MpServer', x=398.49, y=64.00, z=480.54], EntityCreeper['Creeper'/436, l='MpServer', x=385.70, y=43.00, z=522.70], EntitySkeleton['Skeleton'/437, l='MpServer', x=386.50, y=42.00, z=516.30], EntitySkeleton['Skeleton'/438, l='MpServer', x=386.52, y=42.00, z=514.14], EntitySkeleton['Skeleton'/439, l='MpServer', x=385.89, y=42.00, z=516.27], EntityCreeper['Creeper'/440, l='MpServer', x=384.53, y=43.00, z=517.83], EntitySkeleton['Skeleton'/441, l='MpServer', x=387.23, y=44.00, z=521.50], EntitySkeleton['Skeleton'/442, l='MpServer', x=393.50, y=19.00, z=536.50], EntitySkeleton['Skeleton'/443, l='MpServer', x=390.50, y=19.00, z=536.50], EntityWolf['Wolf'/444, l='MpServer', x=396.75, y=63.00, z=542.15], EntityWolf['Wolf'/445, l='MpServer', x=395.53, y=64.00, z=537.41], EntityWolf['Wolf'/446, l='MpServer', x=391.03, y=64.00, z=537.49], EntityWolf['Wolf'/447, l='MpServer', x=397.47, y=64.00, z=540.42], EntityItem['item.item.arrow'/448, l='MpServer', x=387.36, y=66.00, z=534.81], EntityItem['item.item.bone'/449, l='MpServer', x=388.84, y=65.00, z=534.13], EntityItem['item.item.arrow'/450, l='MpServer', x=407.55, y=64.00, z=508.01], EntityItem['item.item.bone'/451, l='MpServer', x=408.53, y=64.00, z=507.56], EntityBat['Bat'/452, l='MpServer', x=405.98, y=25.05, z=524.93], EntityChicken['Chicken'/453, l='MpServer', x=401.50, y=27.00, z=529.50], EntityBat['Bat'/454, l='MpServer', x=422.31, y=33.22, z=451.70], EntityWolf['Wolf'/455, l='MpServer', x=424.08, y=70.00, z=470.30], EntityWolf['Wolf'/456, l='MpServer', x=423.99, y=70.00, z=471.32], EntitySpider['Spider'/584, l='MpServer', x=422.50, y=69.00, z=584.50], EntityWolf['Wolf'/457, l='MpServer', x=428.36, y=70.00, z=466.93], EntityZombie['Zombie'/585, l='MpServer', x=443.64, y=68.00, z=552.09], EntityWolf['Wolf'/458, l='MpServer', x=423.90, y=70.00, z=469.00], EntityWolf['Wolf'/459, l='MpServer', x=420.95, y=67.00, z=462.51], EntityWolf['Wolf'/460, l='MpServer', x=426.70, y=70.00, z=470.00], EntityWolf['Wolf'/461, l='MpServer', x=429.43, y=71.00, z=471.47], EntityWolf['Wolf'/462, l='MpServer', x=433.42, y=68.00, z=462.49], EntityWolf['Wolf'/463, l='MpServer', x=430.50, y=69.00, z=464.70], EntityItem['item.item.arrow'/464, l='MpServer', x=421.13, y=64.00, z=510.61], EntityItem['item.item.bone'/465, l='MpServer', x=421.17, y=64.00, z=510.90], EntityCreeper['Creeper'/466, l='MpServer', x=428.50, y=66.00, z=505.50], EntitySkeleton['Skeleton'/467, l='MpServer', x=426.50, y=65.00, z=534.50], EntityCow['Cow'/468, l='MpServer', x=450.89, y=67.00, z=458.00], EntityCreeper['Creeper'/469, l='MpServer', x=435.20, y=65.00, z=530.53], EntityWolf['Wolf'/726, l='MpServer', x=391.90, y=64.00, z=588.64], EntitySkeleton['Skeleton'/470, l='MpServer', x=441.50, y=32.00, z=565.50], EntitySpider['Spider'/356, l='MpServer', x=360.50, y=63.00, z=440.50], EntityZombie['Zombie'/357, l='MpServer', x=358.50, y=63.00, z=460.50], EntityPlayerSP['OclockdAMD'/396, l='MpServer', x=372.74, y=63.00, z=510.06], EntityZombie['Zombie'/380, l='MpServer', x=387.00, y=64.00, z=446.43], EntityCreeper['Creeper'/381, l='MpServer', x=393.50, y=64.00, z=452.50], EntityZombie['Zombie'/382, l='MpServer', x=387.48, y=64.00, z=449.23]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1413323576 bytes (1347 MB) / 3207856128 bytes (3059 MB) up to 3207856128 bytes (3059 MB)
	LiteLoader Brand: 1.11.2-SNAPSHOT-rAF8F47E-b9-9
	LiteLoader Mods: 4 loaded mod(s)
          - Armors HUD Revived version 1.1.0-beta
          - Pop Enchant Tags Revived version 1.1.1
          - VoxelMap version 1.6.21
          - ChunkBorders version 0.3.3
	LaunchWrapper: 30 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: net.minecraftxray.loader.p
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.reborncore.mixin.transformer.MixinTransformer
          - Transformer: $wrapper.cubex2.ttfr.BFClassTransformer
          - Transformer: $wrapper.brad16840.common.asm.ClassTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: $wrapper.net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
          - Transformer: $wrapper.net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
          - Transformer: $wrapper.shetiphian.core.asm.ClassTransformer
          - Transformer: $wrapper.com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: Minecraft 1.11.2 MCP 9.38 Powered by Forge 13.20.0.2227 Optifine OptiFine_1.11.2_HD_U_B6 60 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2227.jar) 
	UCHIJAAAA	forge{13.20.0.2227} [Minecraft Forge] (forge-1.11.2-13.20.0.2227.jar) 
	UCHIJAAAA	betterfonts{1.7.2} [BetterFonts] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.1.7} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.7.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	actuallyadditions{1.11.2-r100} [Actually Additions] (ActuallyAdditions-1.11.2-r100.jar) 
	UCHIJAAAA	alltheblocks{1.11.2-1.1.0} [All the Blocks] (alltheblocks-1.11.2-1.1.0.jar) 
	UCHIJAAAA	ambientsounds{1.2.0} [AmbientSounds] (AmbientSounds v1.2.2 mc1.11.zip) 
	UCHIJAAAA	jei{4.2.4.229} [Just Enough Items] (jei_1.11.2-4.2.4.229.jar) 
	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	chiselsandbits{13.9} [Chisels & Bits] (chiselsandbits-13.9.jar) 
	UCHIJAAAA	clienttweaks{2.1.2} [Client Tweaks] (ClientTweaks_1.11-2.1.2.jar) 
	UCHIJAAAA	creativeparadise{1.1.0} [Creative Paradise] (creativeparadise-1.1.0.jar) 
	UCHIJAAAA	eleccore{1.6.381} [ElecCore] (ElecCore-1.11-1.6.381.jar) 
	UCHIJAAAA	deepresonance{1.4.5} [DeepResonance] (deepresonance-1.1x-1.4.5.jar) 
	UCHIJAAAA	endercompass{1.2.5.1} [Ender Compass] (EnderCompass-1.11-1.2.5.1.jar) 
	UCHIJAAAA	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.2.jar) 
	UCHIJAAAA	endertanks{1.5.2} [EnderTanks] (endertanks-1.11.0-1.5.2.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.11-5.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.11-5.1.jar) 
	UCHIJAAAA	reborncore{2.13.3.34} [RebornCore] (RebornCore-1.11.2-2.13.3.34-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.3.34} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.3.34-universal.jar) 
	UCHIJAAAA	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.0.54.jar) 
	UCHIJAAAA	limelib{1.4.0} [LimeLib] (limelib-1.11.2-1.4.0.jar) 
	UCHIJAAAA	furnus{1.91} [Furnus] (furnus-1.11.2-1.91.jar) 
	UCHIJAAAA	giacomosfoundry{1.3.10} [Giacomo's Foundry] (GiacomosFoundry-1.11.2-1.3.10.jar) 
	UCHIJAAAA	furniture{1.1.3} [How 'Bout That Furniture] (HowBoutThatFurniture-1.2.1.jar) 
	UCHIJAAAA	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHIJAAAA	justenoughbuttons{1.11.2-1.4.1} [Just Enough Buttons] (justenoughbuttons-1.11.2-1.4.1.jar) 
	UCHIJAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCHIJAAAA	literalascension{1.11.2-1.0.1.0} [Literal Ascension] (literalascension-1.11.2-1.0.1.0.jar) 
	UCHIJAAAA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJAAAA	bonecraft{1.9.4-1.10.2d} [Pam's BoneCraft] (Pam's BoneCraft 1.11a.jar) 
	UCHIJAAAA	harvestcraft{1.11.2b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2b.jar) 
	UCHIJAAAA	rftools{5.83} [RFTools] (rftools-1.1x-5.83.jar) 
	UCHIJAAAA	rftoolsdim{4.54} [RFTools Dimensions] (rftoolsdim-1.1x-4.54.jar) 
	UCHIJAAAA	persistentbits{1.0.6} [Persistent Bits] (PersistentBits-1.11-1.0.6.jar) 
	UCHIJAAAA	pigmanure{1.0} [Pig Manure] (pig-manure-1.0.3-mc1.11.jar) 
	UCHIJAAAA	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	UCHIJAAAA	guilib{1.11 : updated by subaraki} [GUI Library] (PSG Revamper-1.11-1.0.0.0.jar) 
	UCHIJAAAA	paintingselgui{1.11 v1: updated by Subaraki} [PaintingSelectionGui] (PSG Revamper-1.11-1.0.0.0.jar) 
	UCHIJAAAA	redstonefluxarsenal{1.1} [Redstone Flux Arsenal] (RedstoneFluxArsenal-[1.11]-1.1.jar) 
	UCHIJAAAA	ruins{16.4} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHIJAAAA	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCHIJAAAA	simplegrinder{3.060.R1112} [Simple Grinder] (SimpleGrinder-3.060.R1112.jar) 
	UCHIJAAAA	chunkbase_slimemod_ssp{2.1} [Slime Mod (SSP)] (SlimeModSSP-1.11-2.1.jar) 
	UCHIJAAAA	stacksize{1.0} [Stacksize Mod] (stacksize-1.11.2-1.0.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.1.0} [Storage Drawers] (StorageDrawers-1.11.2-4.1.0.jar) 
	UCHIJAAAA	sugiforest{1.3.1} [SugiForest] (SugiForest_1.11-v1.3.1.jar) 
	UCHIJAAAA	timehud{7.1.0} [Time HUD] (TimeHUD-Forge-1.11.2-7.1.0.jar) 
	UCHIJAAAA	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.11-1.1.1a.jar) 
	UCHIJAAAA	chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)] (VillageInfoSSP-1.11-2.1.jar) 
	UCHIJAAAA	villagerinventory{1.0.1} [Villager Inventory Viewer] (VillagerInventory-1.11-1.0.1.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	yalsm{1.0} [Yet Another Leather Smelting Mod] (yalsm-2.1.7-mc1.11.jar) 
	UCHIJAAAA	yeoldetanks{1.9.3} [Ye Olde Tanks] (YeOldeTanks-1.11.2-1.9.3.jar) 
	Loaded coremods (and transformers): 
literalascension (literalascension-1.11.2-1.0.1.0.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
CorePlugin (FluxedRedstone-2.6.0.54.jar)
  
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BetterFontsCore (TTFR-1.11.2-1.7.2.jar)
  cubex2.ttfr.BFClassTransformer
ForgelinPlugin (Forgelin-1.2.0.jar)
  
RebornCoreASM (RebornCore-1.11.2-2.13.3.34-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  brad16840.common.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.81' Renderer: 'GeForce GTX 745/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2227
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 745/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PERSISTENCE.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 368.81
	OpenGlRenderer: GeForce GTX 745/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Ellpeck** [comment]
This doesn't seem related to Actually Additions and the way it works at all.

**Comment by OcAMD** [comment]
This was a courtesy to let you know of a mod conflict. The way it relates has something to do with the way you do your fonts. For example; Better Fonts  makes the fonts look better in Minecraft (including mods) but makes yours look worse. The book that is included with your mod is barely legible with Better Fonts installed and the crash only occurs when you hold the wrench and look directly at the relay. I'm no mod author but maybe you both access the same classes when you render. Try and install Better Fonts and check out how the Minecraft fonts look far better with everything but your book; even if you crash you can simply restart without removing either mod so it isn't world destroying (no need to edit inventory or use MCEdit to remove blocks either). You just need to remove Better Fonts to link relays with the wrench.

**Comment by Ellpeck** [comment]
I scale down the font to make it look good in the book. If you don't want that, you can always change the config option.
Also, as I said, it's very likely that this is a BetterFonts issue as I only call vanilla methods to render this particular information about the Laser Relays.
I am closing this issue for now, however if it actually is an issue on my part, then please reopen it.

**Comment by OcAMD** [comment]
cubex2 just released a fix for this in versions TTFR-1.11.2-1.7.3.jar & TTFR-1.10.2-1.5.3.jar.

"- fixed possible crash (one example was looking at a laser relay from actual additions)"
