### ISSUE TITLE
can't make sticks

### ISSUE THREAD

**Issue by peanutinky** [Ellpeck/ActuallyAdditions#63]
after i make a crusher i can't make sticks anymore. i removed your mod and was able to make sticks again

**Comment by Ellpeck** [comment]
Are you for real?
Someoone told me about this "bug" before, however I and the people I know have never been able to reproduce it.

**Comment by Ellpeck** [comment]
Please submit the full log of the session that this bug occured in.

**Comment by peanutinky** [comment]
i had to logout and log back in and i was able to make sticks again

**Comment by Ellpeck** [comment]
What version are you using?

**Comment by Ellpeck** [comment]
Update your game and try again.
If not fixed, reopen.
