### ISSUE TITLE
Compatibility with The One Probe (tesla/rf display)

### ISSUE THREAD

**Issue by ShaunDreclin** [Ellpeck/ActuallyAdditions#632]
Made an issue over on The One Probe's page for this. https://github.com/McJty/TheOneProbe/issues/134
Not sure which mod needs to make a change to make it work, would be great if you could work with them!

> Minor nitpick but it'd be nice if it showed the blue tesla bar rather than the red RF bar on AA machines when I have it displaying in tesla mode.
>
> Not sure if this is something AA has to do on their end through the API or if its something for here

**Comment by Ellpeck** [comment]
Implementing this doesn't really seem necessary to me, sorry.

**Comment by ShaunDreclin** [comment]
Is there something TOP could read to do it on their side?
