### ISSUE TITLE
[Suggestion] ─ Liquid sorting device ?

### ISSUE THREAD

**Issue by lapin-b** [Ellpeck/ActuallyAdditions#634]
The very basic idea is: you input a liquid and the device sorts it out according to a configuration given by the player. For example, you input some molten gold on one side and you provide `Molten gold goes on the north side` then the inputed liquid (molten gold) goes on the north face.

If you understood nothing... Ask me for a drawing :sweat_smile:

**Comment by Ellpeck** [comment]
What for?

**Comment by Ellpeck** [comment]
I'm not really interested in adding anything like this, sorry.
