### ISSUE TITLE
Various AA TileEntities calling writeToNBT every tick

### ISSUE THREAD

**Issue by bloodmc** [Ellpeck/ActuallyAdditions#635]
DW 20 modpack 1.5.1 beta

ActuallyAdditions-1.10.2-r98

https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/tile/TileEntityHeatCollector.java#L88

HeatCollector's as well as other AA TE's are calling writeToNBT every single tick which is wasting tick time.

Here is the trace
https://gist.githubusercontent.com/bloodmc/6cb0bc0c0eedd42f28958a0d90611f05/raw/4cbb0054174712c4619f4552f55a5044adcb77d9/te_write_trace.txt

Ignore the sponge redirects as we just wrap a few method calls for tracking purposes.

Let me know if you need any other info

**Comment by Ellpeck** [comment]
sendUpdateWithInterval() only sends an update every 10 ticks, and you can change this interval in the config file. I don't see the problem?

**Comment by Ellpeck** [comment]
No one has ever complained about tick time being wasted through syncing machines to the client using the NBT they save, this is pretty much common practise.
Please use a profiler and send me an nps file of the result.

**Comment by bloodmc** [comment]
OK, mind hopping on IRC to discuss? you can find me in #spongedev on esper

Thanks!

**Comment by Ellpeck** [comment]
I don't see why there is a discussion to be held here. An update packet is being sent every 10 ticks in the event that the energy amount inside the machine (or any other thing that has to be updated), changed.
I don't see a problem there.

**Comment by bloodmc** [comment]
Turns out the call per tick was caused by our block snapshot process in order to rollback if needed. Your end is fine, false alarm :)

Thanks!
