### ISSUE TITLE
Missing translations and not translated things

### ISSUE THREAD

**Issue by MisterPeModder44** [Ellpeck/ActuallyAdditions#637]
When I was updating the french language file, I found out that there quite a few things that were not translated properly or missing a translation in the lang files.

#### Not properly translated things:
-Reconstruction master acheivement (achievement.actuallyadditions.getcristalsMilestone)
-Cristal Flux
-Empowered Cristals (blocks and items)
-Crystals and Reconstructors chapter (booklet.actuallyadditions.chapter.crystals.*)
-Solidified Experience (item.actuallyadditions.item_solidified_experience.name)
-Crystal armor and tools (includes AIOTs)
-Crystallised Oil (fluid.actuallyadditions.crystaloil)

#### Missing translation:
-"(Empowerer Recipe)","(Atomic Reconstructor Recipe)",
"(Coffee Maker Recipe)" and (Furnace Recipe)" in the booklet
-"Mod mode" in the advanced item laser relay interface
-"View Online" button
-"_Small_", tooltip of the small storage crate 
-"_Supersolid_", tooltip of the big storage crate 
-"No effect", tooltip of coffee cup
-"Click to search"
-"Blaze Stored", potion rings
-"filled slots", tooltip of sacks
-"Selected block:" tooltip of Handheld filler
-"Auto-Split items off/on" in double crusher and powered furnace

**Comment by Ellpeck** [comment]
"Not translated properly"? All the ones in that list seem fine, you just have a typo in half of them yourself :p

**Comment by MisterPeModder44** [comment]
What I mean by that is they does not get translated when switching languages.
For example, in french language, "Palis Crystal Helmet" is not replaced by "Casque en cristal de palis"

**Comment by Ellpeck** [comment]
That.. doesn't make any sense O_o Are you sure you don't have a typo or have a space on one side of the equals sign?

**Comment by MisterPeModder44** [comment]
Well for the palis crystal Helmet, I wrote this:
item.actuallyadditions.item_helm_cristal_blue.name=Casque en cristal de palis

**Comment by Ellpeck** [comment]
That's really weird, I don't know why it would just happen with those items.

**Comment by MisterPeModder44** [comment]
So... i set the language to german to see if this would happen and I found out that almost no item was translated, only potions rings gets partially translated to german :p

![output_vkt97j](https://cloud.githubusercontent.com/assets/7838479/22892711/d0bd0362-f213-11e6-9fca-05441f9225ab.gif)

**Comment by Ellpeck** [comment]
That's because no one is working on the german translation.

**Comment by MisterPeModder44** [comment]
wait there is a german language file right?

**Comment by Ellpeck** [comment]
Yea.

**Comment by MisterPeModder44** [comment]
So if there is a german translation for the items why it is not working properly?

**Comment by Ellpeck** [comment]
Because not all the items have a german translation, because no one is working on it.

**Comment by MisterPeModder44** [comment]
Yeah but the items shown on the image above do have a german translation


`info.actuallyadditions.booklet.manualName.1=Actually Additions`
`info.actuallyadditions.booklet.manualName.2=Handbuch`

`item.actuallyadditions.itemFoodDoughnut.name=Krapfen`

`item.actuallyadditions.itemDrillUpgradeFortune.name=Bohrerverbesserung: Glück I`

`item.actuallyadditions.itemFoodCheese.name=Käse`

`item.actuallyadditions.goldPaxel.name=Gold-AIEW`

**Comment by Ellpeck** [comment]
These are all the old localizations from pre-1.11..

**Comment by MisterPeModder44** [comment]
Well these localizations are still in the 1.11.2 version of the mod aren't they?

**Comment by Ellpeck** [comment]
no. All items got changed from camelCase to snake_case.

**Comment by MisterPeModder44** [comment]
My bad :D
But the french localizations keys are identical to the english ones, so there is no reason they are not translated properly
