### ISSUE TITLE
Phantom placer not placing wither skulls upwards

### ISSUE THREAD

**Issue by AstroxV** [Ellpeck/ActuallyAdditions#639]
The phantom placer wont allow wither skulls to be placed on top of the block you specify with the phantom connector.
For example a wither spawner you select the blocks on which the skulls should be placed with the phantom connector, and then set the placer to place the blocks upwards. This works fine with the soulsand blocks, but the skulls wont place this way.
To make them work you have to select a block next to the skulls and tell it to place north/south/east/west side of it.

I assume this is because the skulls face the way you place them down manually and the phantom placer tries to rotate them do they face upwards, which they can't.
It doesn't look intended and was a bit of a hassle to figure out why the skulls didn't place. Maybe you can default face them a certain direction and let the place anyway?

**Comment by AEnterprise** [comment]
i made a fully automated wither farm a few days ago using the AA phantom placers, the trick is to first place the soul sand and then the skulls on top (down direction) after a short delay

**Comment by AstroxV** [comment]
I know it is possible, but saying the wither skulls are not placing the way normal blocks work.
Try setting up a phantom placer linked to a block and set the placer in "UP" mode.
When you put a normal block in the placer it works fine, it will place the block on top of the block you linked to. Put wither skulls in there and it will not place the skull at all.

**Comment by Ellpeck** [comment]
There is an open issue for this already. Please check all open issues first.

**Comment by AstroxV** [comment]
I saw the one about the placer and skulls but didn't see it myself as the same issue, my bad.
