### ISSUE TITLE
Tinker's construct "adjacent inventory" access to Item Interface.

### ISSUE THREAD

**Issue by GeekBeam** [Ellpeck/ActuallyAdditions#640]
Tinker's construct crafting table will view Item Interface as an accessible inventory, giving the player a GUI access to the item interface, and ALL the inventory of the connected item sorting system is now available in one GUI, seems like a problem.

using middle click autosorting from the InventorySorter mod results in a MAJOR loss of items (I lost several chests and crates worth of valuables, wrecking a playthrough). I haven't done enough research to tell if this is a unique issue with these three mods in particular.

the most immediately addressable item from this bug is the ability to access the item interface through Tinkers' construct crafting blocks, which gives the GUI that the original block doesn't provide.

applicable mods: Tinkers' Construct, Actually Additions, Inventory Sorter.

**Comment by Ellpeck** [comment]
This has been removed in Tinker's Construct, but I guess that update is not out yet.

**Comment by GeekBeam** [comment]
somebody needs to tell dire to update his pack then, I think.
