### ISSUE TITLE
1.11.2-r101 crashes dedicated Forge 1.11.2 build 2230

### ISSUE THREAD

**Issue by kreezxil** [Ellpeck/ActuallyAdditions#642]
Notes:
     on startup

crash report:
https://gist.github.com/d2bc12bb2c5ab6583066f437a2da7611

fml server latest:
https://gist.github.com/abb36f646264e4e11f809f269405103f

**Comment by Endmateria** [comment]
Same problem, doesn't crash when I revert to version 1.11.2-r100

https://gist.github.com/Endmateria/9dda04c6e4dca0405626edb419ce7c2f#file-crash-2017-02-14_20-26-26-server-txt

**Comment by Ellpeck** [comment]
Yes.
