### ISSUE TITLE
[Suggestion] Ring of Growth on Display Stand

### ISSUE THREAD

**Issue by AceologyGaming** [Ellpeck/ActuallyAdditions#644]
Somewhat self explanatory :3 just uses RF from display stand and grows in AOE as when held by a player.

**Comment by PapiDimmi** [comment]
Don’t see why not.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
