### ISSUE TITLE
Worms don't grow all farm tiles evenly.

### ISSUE THREAD

**Issue by BrickVoid** [Ellpeck/ActuallyAdditions#645]
![2017-02-17_09 13 21](https://cloud.githubusercontent.com/assets/7897425/23045695/7c51c0b6-f4f1-11e6-8487-85ca451e164f.png)

In the attached screenshot, a worm is fertilizing seven tiles of farmland around it, however, it does not appear to be fertilizing the tile in the bottom left corner, all other tiles seem to be fertilized properly.

This flax plant, from Actually Additions itself, seems to get very little additional growth ticks compared to the other six plants the worm is fertilizing.

Is there an issue, within Actually Additions, that causes worms to incorrectly assess the farmland tiles around them for growth ticks?  I don't think this is a vanilla issue, as the worm did actually turn dirt I placed there into farmland, it just won't grow this particular crop placed there.  This hasn't been tested with other crops, just the Actually Additions Flax seeds.

Mod version 1.10.2-r98 .

Cheers ...

BrickVoid

**Comment by Ellpeck** [comment]
The worm fertilizes random farm tiles, so it can happen that for a long time, one crop isn't getting a growth increase at all.
