### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by Puzzledlight** [Ellpeck/ActuallyAdditions#647]
Hey, me again! Got a neat dupe glitch between Actually Additions' Traveler's Sack and Silent's Gems/Gemulation's Shinies Bag. 

When picking up any of Silent's Gems, they appear in both the expected Sack and in the Shinies Bag, allowing for endless gem duping. 

Playing on ATL's Superstitions, Forestry is present, in case that's relevant.

**Comment by Ellpeck** [comment]
Tell the author of Silent's Gems that he has to cancel whatever pickup code he is doing in the EntityItemPickupEvent whenever the event's result has been set to Result.ALLOW.
This is due to the weird way the event works.
