### ISSUE TITLE
Add dusts for Biomes O' Plenty gems/ores

### ISSUE THREAD

**Issue by Endmateria** [Ellpeck/ActuallyAdditions#648]
Would you consider adding dust variants for the gems and ores added by BOP (tin/copper/topaz/emerald/ruby/peridot/topaz/tanzanite/apatite/sapphire)?   The crusher doesn't register them... or at least not the ones I tried so far i.e., tin and copper.  I know that most ore mods usually add their own dust variants, but when I asked the authors of BOP if they would consider it, they replied by saying "this is not a tech mod, get those mod authors to add support for it".  Blah...

**Comment by Ellpeck** [comment]
I don't add dust variants for non-vanilla ores, sorry.
