### ISSUE TITLE
Various Issues, Crashes and item deconstruction

### ISSUE THREAD

**Issue by domretana** [Ellpeck/ActuallyAdditions#649]
So far I've notice that constructing the sickles will cause a random crash.

and when building items like the craft table on a stick, it will auto deconstruct with removing extra material from the craft area or exit the menu.

Please fix (minecraft 1.11.2 forge server)

**Comment by Ellpeck** [comment]
What the heck is a sickle?
Try this without any other mods installed.

**Comment by Ellpeck** [comment]
Closing this because of missing response.
