### ISSUE TITLE
Tile entities are invisible on server but fine in single player. 

### ISSUE THREAD

**Issue by goalie1248** [Ellpeck/ActuallyAdditions#65]
Like the title said, when I place anything down in SP it shows up fine: http://puu.sh/mKjkX/47e4531054.jpg

But on a server they're invisible and unable to be interacted with: https://gfycat.com/BeautifulNaiveBrocketdeer

The behavior is... weird... Sometimes you can place a block on them and it'll show up, others you cannot and it just places the block back in your inventory. I hope the gif does a good job showing it. The turtles are just the way I could harvest the blocks.

Current Version is: 1.8.9-r24 (though it was also happening on r23)
Modlist (if it helps): http://pastebin.com/H6A9T5hJ

**Comment by Ellpeck** [comment]
I've never encountered that :O
Try updating forge to the newest version.

**Comment by goalie1248** [comment]
We're currently on 11.15.0.1715, I'll bug the server owner to update it to the latest.
I went into SP to see if it was caused by two mods conflicting since I didn't think something like this would be a single occurrence, but oddly enough it works just fine there.. 

@Dyonovan I'm tagging you in this to get forge updated :P

**Comment by Ellpeck** [comment]
I think it might be forge, but I don't know for sure.
The version doesn't seem that old, but on the server I play on it all works fine.
Does it fix itself when you restart the game?

**Comment by Ellpeck** [comment]
Closed because of no response.
