### ISSUE TITLE
This comment is a bit of an understatement

### ISSUE THREAD

**Issue by SoniEx2** [Ellpeck/ActuallyAdditions#650]
This comment is a bit of an understatement: https://github.com/Ellpeck/ActuallyAdditions/blob/master/specialPeopleStuff.properties#L15

**Comment by Ellpeck** [comment]
Uh..?

**Comment by SoniEx2** [comment]
srsly u not gonna mention he's ur bf?

**Comment by Ellpeck** [comment]
It's not the reason he gets the floating item. So no.
Also, it's just a comment in a file, how is that even important?

**Comment by SoniEx2** [comment]
Sorry, I'm not good at supporting ppl.

**Comment by xbony2** [comment]
uwat
