### ISSUE TITLE
Add Melon and Pumpkin Behavior to the Farmer

### ISSUE THREAD

**Issue by martindiv** [Ellpeck/ActuallyAdditions#653]
Not sure if this is the intended behavior or not but the farmer doesn't handle melons or pumpkins. If it's intended could you please update the guide to say so?

Thanks.

**Comment by IamAlathe** [comment]
Due to the way the farmer works, breaking the crop then replanting, I never expected it to work with melons and pumpkins, so I never tried.  That would be cool, though. :)

**Comment by Ellpeck** [comment]
Closed by https://github.com/Ellpeck/ActuallyAdditions/commit/0485107c941cd0d4f121c09c04d46c22037d8dcb
