### ISSUE TITLE
Farmer not working with Industrial Hemp

### ISSUE THREAD

**Issue by Novian3002** [Ellpeck/ActuallyAdditions#654]
ATM Expert 1.10.2

Industrial Hemp won't be planted/harvested by the farmer.

Is this a bug or a "feature"?

**Comment by Ellpeck** [comment]
1.10 doesn't add special functionality for special plants, sorry.

**Comment by IamAlathe** [comment]
Playing Sky Factory 3, I noticed this also.  If you're really fussed about it,it might be something to bring up to IE if you haven't already.

**Comment by Ellpeck** [comment]
No, it might not, because the farmer isn't supposed to work with non-standard plants in 1.10.

**Comment by IamAlathe** [comment]
Jeez, you even said that.  I really need to stop trying to help. :p
