### ISSUE TITLE
[Suggestion] Better Tooltip control

### ISSUE THREAD

**Issue by drakray** [Ellpeck/ActuallyAdditions#655]
I think it would be nice to have a better control over what shows when, for exemple, to be able to show oreDict entry at all time, not only with F3+H and all the rest.
Also, having a way to remove the "If you don't want this to appear..." would be nice, once you've seen it once, it become a clutter, more so with all the other info

**Comment by Ellpeck** [comment]
I'm sorry, but no. This information is only supposed to be used for debug purposes and so I don't really think it should be super configurable.

**Comment by drakray** [comment]
Ok, too bad, thanks for the quick answer though :)
