### ISSUE TITLE
Horse armor yields are incorrect

### ISSUE THREAD

**Issue by Zaweri** [Ellpeck/ActuallyAdditions#656]
Original Mojang recipes (which many mods base their horse armor recipes off of) require 6 ingots/gems and 1 wool to make it. Said recipes were introduced in snapshots. AA's crusher gives 8 dust from a piece of crushed horse armor.

**Comment by Ellpeck** [comment]
I don't see how this would make them "incorrect", as the recipe in vanilla was removed before an actual update came out.

**Comment by Zaweri** [comment]
@Ellpeck For example, Base Metals, and most, if not all other mods that add horse armor recipes follow the original Mojang recipe.
