### ISSUE TITLE
Rebalance loot

### ISSUE THREAD

**Issue by Flufferbat** [Ellpeck/ActuallyAdditions#657]
Could you remove just the guide book from the loot table or make it an option in the config? I find it super annoying and don't want to remove all the loot from generating like the config already has, or could you tell me how to remove it myself? thanks

**Comment by Ellpeck** [comment]
I reduced the amount of manuals you get by a significant amount, so there should be barely any spawning. Do you think it's still tooo much?

**Comment by Flufferbat** [comment]
if you have lootbags mod on you constantly get them so yea it is too much plus you dont even need the book most of the time coz of the ? button on most of your objects and you get it on first craft if you have that enabled so yea i think its not really needed at all in the loot table but yea i noticed with lootbags with notenoughwands after i changed the config to not available in chests i still got them in loot bags I know i can just void it with filters but yea it takes up loot spots that may be giving different items instead
