### ISSUE TITLE
AA Crop Seeds don't drop from grass

### ISSUE THREAD

**Issue by codewarrior0** [Ellpeck/ActuallyAdditions#659]
`ActuallyAdditions-1.10.2-r98.jar`

Using three stacks of bonemeal to create grass, I obtained an entire set of HarvestCraft seeds plus a few rare ExtraUtilities seeds, but didn't see a single Rice, Flax or Canola seed. 

FWIW, I couldn't find any calls to `MinecraftForge.addGrassSeed` in your code, either. Are your crops intended to only be found as part of worldgen? This may make them unobtainable on Skyblock packs without some extra tweaking.

**Comment by Ellpeck** [comment]
I know. I never said they would.

**Comment by codewarrior0** [comment]
Got it. AA crops are worldgen-only. This should be documented somewhere.

For any Skyblock pack makers who come across this issue, looking for a way to make them obtainable, here is the MT script to add them to grass drops:

```
vanilla.seeds.addSeed(<actuallyadditions:itemRiceSeed>);
vanilla.seeds.addSeed(<actuallyadditions:itemFlaxSeed>);
vanilla.seeds.addSeed(<actuallyadditions:itemCanolaSeed>);
```
