### ISSUE TITLE
Phantomface doesn't interact with Drawer Controller from Storage Drawers (probably needs support added)

### ISSUE THREAD

**Issue by jlbrewer** [Ellpeck/ActuallyAdditions#661]
Version: 1.10.2-r98 (Sky Factory 3 pack v 1.06)

Setup: (filtered item input from Refined Storage exporter) -> Phantomface -> Drawer Controller -> drawers that match the item filters

Result: no items transfer. If I relink the phantomface to a hopper on top of the drawer controller the items go through (but the hopper becomes a bottleneck).

I say it probably needs support added to work because I remember reading Botania changelogs which noted that Vazkii added support for the drawer controller so it worked with Corporea.

(Belatedly, I realize I could replace the drawer controller with an AA item relay and link the drawers with lasers for the same result but at this point I've already switched the whole thing to RS wireless.)

**Comment by Ellpeck** [comment]
Paging @jaquadro about this.
Phantomfaces just take the capability the thing they are connected to has and pass it on. What would I have to do to make that work?

**Comment by jaquadro** [comment]
I'm not sure why it wouldn't work (I'm also not sure what this block is or is supposed to do).

The controller exposes the IItemHandler capability with the first indexed slot representing a virtual, always-empty slot, and the remaining indexed slots representing drawers from the connected network.  The virtual slot will take items in simulate if it can find a place for them elsewhere.  Adding items to any of the slots may route them to different destinations.  The only way I can imagine running into trouble is if you try to do some type of strict validation after an operation.

**Comment by Ellpeck** [comment]
[This code here](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/tile/TileEntityPhantomface.java#L176-L195) is the capability code for the Phantomface. I don't see why that wouldn't work with drawer controllers.

**Comment by jlbrewer** [comment]
Phantomface in a nutshell for Jaquadro: bind a block to it and items piped into the Phantomface should be inserted into the bound block as if the input was connected directly to that block respecting sides, etc. It can be used for limited-range wireless transport and a solution to having too many cables in a tight space. (The transvector interface from Thaumic Tinkerer in 1.7 is a similar item).

**Comment by jlbrewer** [comment]
@jaquadro Just checking something - the Drawer Controller doesn't care what side things are piped in, right?

**Comment by jaquadro** [comment]
@jlbrewer Did you try attaching the RS exporter to the drawer controller directly?  Since the phantomface appears to be pretty transparent in what it does, it could actually be a problem between RS and SD.

**Comment by jaquadro** [comment]
Yeah, none of the blocks care about side.

**Comment by jlbrewer** [comment]
@jaquadro My current working setup goes RS Wireless Transmitter -> Exporter -> Drawer Controller. I'd seen old mentions of buggy interactions between SD and RS but they didn't appear to apply. (One suggested breaking and replacing the RS controller which I tried with no luck.)

**Comment by Ellpeck** [comment]
I don't see why this would be an Actually Additions issue, to be honest.

**Comment by ktole1999** [comment]
are you using the slave block along with the drawer controller? slave block allows piped input to the controller.

**Comment by jlbrewer** [comment]
No. It's a row of six drawers that feeds an Immersive Engineering
auto-crafting factory. (There are easier ways in Sky Factory to do what I'm
doing but this is cooler.,)

**Comment by Ellpeck** [comment]
Closing this for now as I don't think this is an Actually Additions issue.
