### ISSUE TITLE
[Suggestion] Upgrade System

### ISSUE THREAD

**Issue by SebiKraft** [Ellpeck/ActuallyAdditions#663]
Hi, 

I just thought about the problems you have with your crusher and furnace. May it be the problem that there are faster or  the easier versions in other mods, there is an option to get the player back to your machines. You could simply add an upgrade system.
There are multiple ways to do so, but maybe you should use the crafting system your mod already offers.
Use the machines with the atomic reconstructor and a lens (existing or a new one like an "upgrade lens") to get the first upgrade level, and the empowerer with higher grade ingredients to get to the next level.

And it does not have to end there. You could use it to "enchant" your tools, weapons and armor, you could interact with vanilla armor, tools and weapons. You could empower vanilla seeds and food and so on.

I got many more ideas in head for this, but don't wanna waste your time, if you are interested in hearing more, just tell me.

Greetz 

Sebi

**Comment by PapiDimmi** [comment]
I totally agree. Actually Additions’ furnace and crusher/double crusher are incredibly slow, even though the furnace and double crusher have two slots. Other mods, like Ender IO, IC2, and Thermal Expansion, have upgrade systems, but Actually Additions doesn’t.

I absolutely love this mod, but its crusher and furnace are basically worthless, with the exception of the few times when Actually Additions’ crusher yields more or better items than other mods’ ore processing machines.

A simple tier-driven upgrade system would be very useful. _E.g._, a basic upgrade would be a cheap upgrade that makes the powered furnace, crusher, or double crusher a little bit faster and also slightly increases the RF/CF/t use of the machine. Then there would be tier 2, tier 3, and tier 4 upgrades that increasingly up the speed of a machine, as well as increasing the RF/CF cost.

**Comment by Ravalli03** [comment]
Yes, I agree. I love using your machines but sadly not having an upgrade system sucks. You have everything already to making a tier upgrade system fun to craft. Hope you look into adding this.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
