### ISSUE TITLE
Item interface not detecting inventories through advanced item lasers.

### ISSUE THREAD

**Issue by JustinFlintoff** [Ellpeck/ActuallyAdditions#664]
Hey Ellpeck, to start I want to thank you for making Actually Additions! The mod is truly awesome! I'm currently using version r98 which is part of the DW20 mod pack. I'm trying to get a sorting system set up by using the item interface and Advanced Item Lasers. The item interface is working perfectly with regular item lasers, but I can't get it to work with the advanced ones :/ I have all the settings on the lasers set to default and I've tried using it with and without item filters. Have you updated how they work since DW20 did his mod spotlight? I have them set up pretty much the same as the non advanced lasers but the items wont move from the item interface into the hopper. Any idea what is wrong? Thanks for the time, again, you're the man!

**Comment by Ellpeck** [comment]
Advanced Item Laser Relays are on whitelist mode by default, meaning yours are configured to an empty whitelist, ie nothing is allowed in our out. Change the settings.

**Comment by JustinFlintoff** [comment]
My Laser Relays were on WH green so I changed it to WH red. Items still didn't flow. I took screen shots but Imgur isn't letting me upload so I'll try my best to describe the setup. Item Interface with and Advanced Item Laser Relay on top of it. A hopper is feeding into the side of the Item Interface with a Vanilla minecraft chest on top of it. The Advanced Item Laser Relay on top of the Item Interface is connected to another Advanced Item Laser Relay on top of a Vanilla Minecraft Chest. I tried switching them between whitelist and blacklist but items still wont flow from the hopper into the Item Interface.

**Comment by Ellpeck** [comment]
This sounds like you're feeding the items back into the input chest via the advanced item laser relay on top of it.

**Comment by JustinFlintoff** [comment]
Here is a [screenshot](https://cdn.discordapp.com/attachments/286259507468697600/286259697823121408/2017-02-28_14.13.22.png) of the set up in creative.

**Comment by Ellpeck** [comment]
The advanced laser on the item interface is feeding back into the input chest.

**Comment by JustinFlintoff** [comment]
Oh I think I understand! I need to black list the outbound section on the chest that is by itself because it is sending the items back into the hopper. This makes sense! Thank you very much!

**Comment by canitzp** [comment]
you need a hopper item interface anywhere, that feeds into the relay system
