### ISSUE TITLE
[Feature Request] Agricraft support

### ISSUE THREAD

**Issue by Leonyx1175** [Ellpeck/ActuallyAdditions#665]
Right now, 1.10.2 sorely lacks automation with Agricraft. Agricraft's supposedly still being worked on, but would it be possible to add compatibility to Farmers to allow for a right-click style harvest with Agricraft crops?

**Comment by Ellpeck** [comment]
1.10.2 won't get any new features anymore. Once the mod updates to 1.11, it'll probably get compatibility.
