### ISSUE TITLE
[1.10.2] Crash in PostInit

### ISSUE THREAD

**Issue by XFactHD** [Ellpeck/ActuallyAdditions#671]
Minecraft crashes in PostInit while trying to construct a booklet page.
Crash: http://pastebin.com/BnFf7L15

I took a look at the crashing lines but I have no clue why it would crash right there.
Also, downgrading to r97 didn't fix the crash.

Forge Version: 12.18.3.2239
AA Version: 1.10.2-r98

**Comment by Ellpeck** [comment]
This is a different mod registering an invalid Furnace recipe.
Try removing mods until the issue is gone to find out which mod it is.

**Comment by XFactHD** [comment]
Ok, trying that right now.

**Comment by XFactHD** [comment]
Just saw that it was my own fault as I added an invalid description to ExNihiloAdcensio's OreRegistry... :D
