### ISSUE TITLE
Empowerer not working

### ISSUE THREAD

**Issue by KrazyDee** [Ellpeck/ActuallyAdditions#672]
I am trying to make empowered palis crystal blocks so that i can make greenhouse glass, i was able to make a block one time and now the setup has not worked since. there should be enough power as i have a reactor set up next to it and all the display stands are full of RF. The display stands have 2 blocks of space between them and the empowerer. Am I doing something wrong or is this some sort of bug with the mod? I have included a screen shot of the setup below
![2017-03-08_22 31 55](https://cloud.githubusercontent.com/assets/26291900/23734856/cc68cd84-044f-11e7-8cf9-1c00e5509c06.png)

**Comment by Ellpeck** [comment]
Is that the right color of dye you're using. Can't identify through the resource pack.

**Comment by KrazyDee** [comment]
Oh sorry, using the sphax texture pack.....yes i believe the recipe said it was supposed to be cyan dye

**Comment by Ellpeck** [comment]
Try this in a creative/testing world, and if that also doesn't work, try removing mods until the issue is gone.

**Comment by PapiDimmi** [comment]
The display stands need to be two blocks apart, they all need quite a large amount of RF, and all the items have to be exactly correct. Use JEI or the in-game Actually Additions manual to see the exact recipes. Make sure to double-check the recipe.

**Comment by Meowticia** [comment]
Is that an empowered lapis block thing in the center?   (I forget the name of the AA block for lapis) It's hard to tell but it doesn't look like it.  It  needs to be the empowered version if you're trying to make greenhouse glass.

**Comment by KrazyDee** [comment]
yes it is a palis crystal block, as far as i can tell, everything is set up exactly as it is supposed to be.....i was successful in making an empowered crystal block once, after that it wouldn't work again

**Comment by Ellpeck** [comment]
Could you please just do what I told you to do? There doesn't need to be 20 people joining in on the discussion of an issue.

**Comment by PapiDimmi** [comment]
Do you have enough RF? I don’t know how much it needs, but make sure that you have at least 200k RF in all the display stands. What you should do is test this in a creative world.

I had an equally annoying issue the other day when I was first starting with Actually Additions. I tried to get the empowerer to work for hours, but it never did. I googled, watched tons of YouTube videos again and again, and I even tried in a creative world and gave the machines as much RF as I could possibly give them… and then I realized that I was trying to empowerer an emerald instead of an emeradic crystal.

**Comment by KrazyDee** [comment]
ok so it turns out that there are 2 versions of prismarine shards.....one labelled under vanilla minecraft and one labelled botania....the botania ones don't work.....when it worked the first time they must've been vanilla shards.....figured out that the ones i tried using the second time were botania shards....not sure how that happened, but problem is solved now thanks.

**Comment by Allyraya** [comment]
sorry to comment on a closed issue, but this is the first one I found that talks about a similar problem to mine. Regarding the empowerer setup, for some reason Ender IO conduits will connect to the display stands, but not to the empowerer itself. I have to use an EU2 Energy Node and pipe to connect. Why?

**Comment by Ellpeck** [comment]
Because the empowerer doesn't take energy?
Read the manual.

**Comment by Allyraya** [comment]
Sorry, didn't think of that, I just thought I remembered all parts of the setup needing energy, have a nice night Ellpeck
