### ISSUE TITLE
Switch Phantom Energyface implementation

### ISSUE THREAD

**Issue by SoniEx2** [Ellpeck/ActuallyAdditions#673]
The current Phantom Energyface implementation uses pull API. However, there's a much better implementation described on https://github.com/SleepyTrousers/EnderIO/issues/4085. Its benefits include compatibility with a lot more mods. (Still won't be able to pull power from Immersive Engineering generators, but eh w/e, EnderIO is more important.)

And if you reuse this with standard Phantomfaces, we'll be able to auto-pull through a phantomface!

**Comment by Ellpeck** [comment]
The Phantom Energyface does two things:
1. have the same capability the block it is connected to has, so that it passes on energy values / methods to whatever is interacting with it
2. push energy that it "contains" to all sides.
There is no "pull API".

**Comment by SoniEx2** [comment]
The code is non-functional because I never actually tested it :P

It should work tho, if you just move the tileentity for less than a tick. (Remember to move it back.)

And then we can get support for more mods and more features (like auto-pull for items).

Also, by "pull API" I mean the pull API provided by Forge Energy - the canExtract and extractEnergy stuff.

**Comment by Ellpeck** [comment]
I am not willing to implement this as it seems like a very hacky and unreasonable way to do it.
