### ISSUE TITLE
[1.10.2-r98] Traveler's Sack causes duplication of any items when picking up items with empty hand.

### ISSUE THREAD

**Issue by JaSpr** [Ellpeck/ActuallyAdditions#674]
1) Make sure traveler's sack is set to "Auto-Insert on" [Screenshot](http://i.imgur.com/p7JenfC.png)
2) Throw any stack of items on the ground. [Threw 24 lights on the ground](http://i.imgur.com/kUp0CAy.png)
3) Pick up the stacks with an empty slot selected on the hotbar. [Received 24 lights in inventory, and 24 in sack](http://i.imgur.com/Z69PR0k.png)

We have duplicated this with multiple items from multiple mods, always with the same duplication result. 

AA: 1.10.2-r98
MC: 1.10.2
Forge: 12.18.3.2239
All The Mods (modpack): ATM1 v2.4

**Comment by Ellpeck** [comment]
Find out which mod actually causes this by removing  mods, and then tell the author of the mod that this starts happening with that they need to cancel whatever interaction is happening in the EntityItemPickupEvent if the event's result is already set to ALLOW, so basically doing something like [this](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/items/ItemBag.java#L76-L78).

**Comment by phit** [comment]
It's a SpongeForge issue, I opened a ticket on Sponge's tracker. SpongePowered/SpongeForge#1351

**Comment by JaSpr** [comment]
Thanks @Ellpeck the update to 1.10.2-r105 resolved the issue entirely for us!
