### ISSUE TITLE
[Suggestion] Possibility to add extrautils generators to empowerer

### ISSUE THREAD

**Issue by bontavi** [Ellpeck/ActuallyAdditions#675]
Hello, i wanted to ask if it's possible to make to add generators from extrautils to empowerer for possible craft recipes with empowerer.

**Comment by Ellpeck** [comment]
...what? I don't know what you mean.

**Comment by bontavi** [comment]
I wonder, if empowerer is compatible with nbt tags ?

**Comment by Ellpeck** [comment]
Of course you can't, there's no recipe that involves the culinary generator..?

**Comment by bontavi** [comment]
i have made with mod tweaker recipe. 

mods.actuallyadditions.Empowerer.addRecipe(<extrautils2:machine>.withTag({Type:"extrautils2:generator"}), <extrautils2:machine>.withTag({Type:"extrautils2:generator_culinary"}), <ore:culinary>, <ore:meatball>, <minecraft:dye:15>, <minecraft:redstone>, 24000, 60);

**Comment by Ellpeck** [comment]
The Empowerer doesn't compare NBT Tags. You're not gonna be able to use ExUtil2 machines with them.
