### ISSUE TITLE
actually additions plants generate them in other dimensions

### ISSUE THREAD

**Issue by Hypsellis** [Ellpeck/ActuallyAdditions#676]
I get rice, flax, coffe and canola plants in the Betweelands dimension while they aren't supposed to generate at all in this dimension. You seem to have forgotten to check the dimension for knowing where your structures are supposed to generate them.

**Comment by Ellpeck** [comment]
Add them to the plant dimension blacklist.
I have not forgotten anything, you have just forgotten to check the config.

**Comment by Hypsellis** [comment]
Thanks for the quick answer, and there is no need to be so rude. :)

**Comment by Ellpeck** [comment]
You were the one being rude first, you just edited your comment to remove it ;)

**Comment by Hypsellis** [comment]
Yeah maybe I sounded rude but I didn't want to be. ^^'
