### ISSUE TITLE
Add an option for inverse signal behavior for machines

### ISSUE THREAD

**Issue by AlexiyOrlov** [Ellpeck/ActuallyAdditions#680]
Your machines are on when they don't recieve the redstone signal. I'd like to have a config option for inverse behavior, so they are on when they do recieve a signal. Or you could make this mode be able to switch in-game.

**Comment by Ellpeck** [comment]
No, sorry. I think this is unnecessary as you can just use a Redstone Torch in your circuit to invert your signal.

**Comment by AlexiyOrlov** [comment]
I know about the torch. But this is an easy thing to add. OK, I'll change it myself then.
