### ISSUE TITLE
Bonus Treasure Chests on Air

### ISSUE THREAD

**Issue by kenijey** [Ellpeck/ActuallyAdditions#681]
![2017-03-12_15 40 55](https://cloud.githubusercontent.com/assets/24831406/23831861/167422e0-0732-11e7-800b-7ab57093262d.png)
it is not first time :D i saw this many times
any way to fix this? thanks

**Comment by Ellpeck** [comment]
The tree they're in burns away from the lava. This is not a bug.

**Comment by kenijey** [comment]
what? i mean small storage crate, it's on air. And i saw it alone (no lava) on air again...

**Comment by Ellpeck** [comment]
They can't generate outside of leaves, so the tree must have burned down.
