### ISSUE TITLE
[suggestion] add black quartz recipe to the TE Pulverizer

### ISSUE THREAD

**Issue by mcdodge34** [Ellpeck/ActuallyAdditions#684]
Just a suggestion here, but perhaps Black Quartz Ore should be able to be Pulverized in the Pulverizer from TE, unless its a job for the TE team... Would be nice if we could triple it in the induction smelter with cinnabar like many other ores, you have to put cinnabar and the ore and you triple the output.

**Comment by Ellpeck** [comment]
@KingLemming

**Comment by PapiDimmi** [comment]
It should also be added to Extra Utilities 2, so you can crush black quartz ore with the crusher.

**Comment by KingLemming** [comment]
Absolutely. Can you give me the relevant OreDict names of the items?

**Comment by Ellpeck** [comment]
The ore's name is `oreQuartzBlack`, the dust (if you want to use it, Actually Additions turns one ore into two dust in its Crusher) is `dustQuartzBlack`, and if you want to turn it into the item directly like it works for most other gems, you can use `gemQuartzBlack`.

**Comment by KingLemming** [comment]
Okay so normally does smelting do 1 Ore -> 1 Gem? and presumably crushing 1 Gem -> 1 Dust?

**Comment by Ellpeck** [comment]
in AA, it's:
smelting 1 ore -> 1 gem
crushing 1 ore -> 2 dust
smelting 1 dust -> 1 gem
crushing 1 gem -> 1 dust

**Comment by KingLemming** [comment]
Okay so it's basically an ingot, sure thing.

**Comment by KingLemming** [comment]
Pulverizer already handles this with default logic it turns out, but I'm going to tinker around with it a bit and make sure it's all good. :)
