### ISSUE TITLE
A grammatical error and a typo in the manual

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#685]
There are probably more, but here are the errors that I found whilst reading the manual:

- “There is” should be “there **are**.”
- “Uprgades” should be “upgrades.”

[Screenshot.](http://i.imgur.com/5eqFFY8.png)

**Comment by Ellpeck** [comment]
Can't you say "there is" for plural in colloquial english?
And I consider "Mining Upgrade" a proper name, so I think it should be capitalized.

Please do a pull request fixing this if it's super important to you, this really isn't enough of an issue for me to leave it open, sorry :P

**Comment by PapiDimmi** [comment]
I am not questioning the capitalization. You spelt “Mining Upgrades” as “Mining **Uprgades**.”

**Comment by Ellpeck** [comment]
Huh. Yea, I did. Joke's on me then.
Oh well, there's tons of tiny errors in the manual. It'd be awesome if you could do a pull request for the ones you find <3
