### ISSUE TITLE
The Grass Punch Tango

### ISSUE THREAD

**Issue by ecoay** [Ellpeck/ActuallyAdditions#687]
I have been punching grass and tall glass for quite some time and none of the seeds are appearing. I suppose I will eventually add the seeds to sieve but at current time punching grass is the only method of obtaining.

**Comment by Ellpeck** [comment]
What?
Actually Additions seeds don't drop from tall grass, and they never did and never will.

**Comment by ecoay** [comment]
ahh I was under the assumption they dropped from grass from FTB wiki I see now I was looking at the Canola Seeds from Rotary Craft. I guess I need to add them all to the sieve when sieving dirt.
