### ISSUE TITLE
Smileycloud crash client

### ISSUE THREAD

**Issue by RedAlex** [Ellpeck/ActuallyAdditions#688]
minecraft 1.11.2
1.11.2-forge1.11.2-13.20.0.2252
ActuallyAdditions-1.11.2-r103
Waystones_1.11.2-3.0.12

i have use Waystone mod to teleport me in a "city" with 2 smileycloud are and client crash

Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at de.ellpeck.actuallyadditions.mod.blocks.render.RenderSmileyCloud.func_180535_a(RenderSmileyCloud.java:54)

-- Block Entity Details --
Details:
	Name: actuallyadditions:smileycloud // de.ellpeck.actuallyadditions.mod.tile.TileEntitySmileyCloud
	Block type: ID #267 (tile.actuallyadditions.block_smiley_cloud // de.ellpeck.actuallyadditions.mod.blocks.BlockSmileyCloud)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1336,67,1445), Chunk: (at 8,4,5 in -84,90; contains blocks -1344,0,1440 to -1329,255,1455), Region: (-3,2; contains chunks -96,64 to -65,95, blocks -1536,0,1024 to -1025,255,1535)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:150)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:128)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:703)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1336)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)

**Comment by canitzp** [comment]
Would you please post the complete crash report.

**Comment by RedAlex** [comment]
http://pastebin.com/imri43Q8

**Comment by Ellpeck** [comment]
Please try to reproduce it in a creative world. 
There is a TileEntity in the position of a Smiley Cloud without a block attached to it, which seems like an invalid game state.

**Comment by RedAlex** [comment]
I have try 2 time in creative and 2 time in survival without bug.
And now 1 time in survival after play 15m in another zone of the map
I will teleport me again in my "city" and i have the same bug.

in my city i have the 2 special smily cloud with the 2 special name.

http://pastebin.com/cwzPynTG

**Comment by Ellpeck** [comment]
Try (re-)moving (and replacing) the blocks and see if that will fix the problem.

**Comment by RedAlex** [comment]
After removing the left cloud crash again. I try to remove the right.

**Comment by RedAlex** [comment]
After removing the right special cloud no more crash.
Add normal cloud "without name" no crash
i will retest with a new special named after eat

**Comment by RedAlex** [comment]
I confirm crash again but with this cloud. The normal are ok.

![2017-03-14_12 48 49](https://cloud.githubusercontent.com/assets/855331/23911942/b345d27a-08b4-11e7-9676-15a0effc8b0a.png)

**Comment by Ellpeck** [comment]
Try to reproduce the issue consistently in a creative world. If you can, try removing mods until the issue is (hopefully) fixed. You can do this in batches so that it doesn't take as long.

Also, this isn't a chat room. Please condense all the information you gather into _one_ comment, thanks :)
