### ISSUE TITLE
Recursive Worldgen

### ISSUE THREAD

**Issue by mezz** [Ellpeck/ActuallyAdditions#690]
Hey,

In Forge 1.11.2 - 13.20.0.2258 there is a new detection and log for worldgen features that load new chunks and cause more worldgen.  
This can cause a lot of lag when loading new chunks. [I wrote a post about the issue here.](https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/)

>[Server thread/WARN] [FML/]: Actually Additions loaded a new chunk (-6, 12  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker.

You can debug this by grabbing the latest Forge, creating a new world or flying around, and putting a breakpoint at this log (at the bottom of `Chunk.java`). You should see that one of your worldgen features is loading a new chunk and causing more worldgen.

**Comment by Barteks2x** [comment]
Apparently my fix for it was still slightly wrong. And there was much easier way to do it.

**Comment by Ellpeck** [comment]
It's fixed.

**Comment by Barteks2x** [comment]
I'm almost sure that lush caves don't generate 100% correctly now. Unless there is some magic besides what I see in this commit.

**Comment by Ellpeck** [comment]
As I already said, the issue is solved and lush caves are fixed.
