### ISSUE TITLE
[Suggestion] Light source so those Lush Caves make sense.

### ISSUE THREAD

**Issue by Zarepheth** [Ellpeck/ActuallyAdditions#692]
I just find it odd to stumble into a Lush cave while spelunking; there are plenty of trees, grass, and flowers - but somehow they perform photo synthesis with no sunlight - or any other light.

So my suggestion is that the Lush Caves generate with a glow-stone stalactite hanging from the ceiling - or perhaps some other type of light source. Not only would this provide a reason why the plants can grow, but would bring welcome relief from the underground darkness.

**Comment by Ellpeck** [comment]
They do in 1.11.

**Comment by Zarepheth** [comment]
They do?
I've seen crystals in those caves, but they don't seem to change the lighting...

MC 1.11.2
Forge 2259
ActuallyAdditions r106
Optifine 1.11.2_HD_U_B7

**Comment by Ellpeck** [comment]
They do, lighting updates in Minecraft are just stupid and unreliable.

**Comment by Zarepheth** [comment]
So light emitting blocks and items rarely work as the developer intends?

**Comment by Zarepheth** [comment]
Of course, Optifine seems to make my iron tools into light sources that interfere with normal vision - so maybe I need to adjust Optifine's settings (or find a replacement for it).
