### ISSUE TITLE
[Suggestion]  Configure farmer for different sizes

### ISSUE THREAD

**Issue by Cntrldfusion** [Ellpeck/ActuallyAdditions#694]
Right now the farmer does a 9x9 area which is nice but not really helpful if you want to do multiple kinds of crops with one farm.  I was thinking it would be nice if the Farmer could have adjustable sizes from 3x3, 5x5, 7x7, 9x9, etc, or have an Advanced Farmer that acts like the old MFR Planter/Harvester combo or the EnderIO farm station.

**Comment by Ellpeck** [comment]
No, sorry.
