### ISSUE TITLE
How To Dismantle A Machine?

### ISSUE THREAD

**Issue by kenijey** [Ellpeck/ActuallyAdditions#695]
I need to change the place of my crusher, what should i do? thanks

**Comment by Ellpeck** [comment]
Mine it..?

**Comment by kenijey** [comment]
then why i'm getting this message "The block shattered as you tried to break it. Maybe it wasn't sturdy enough to be broken?" and how can i dismantle that machine

**Comment by kenijey** [comment]
and i searched it on internet and i found [this](http://ftb.gamepedia.com/Engineer%27s_House_(Actually_Additions)) but i made my crusher and all other machines MYSELF i am not trying to break any machine in engineer's house. i just placed a crusher in my own house and i just wanted to change it's place, there is no wrench so i tried breaking it, but it said the block shattered bla bla...

**Comment by Ellpeck** [comment]
Take a video of the issue.

**Comment by kenijey** [comment]
dunno but i can't reproduce it anymore........ really annoying

**Comment by kenijey** [comment]
ah whatever, i will open new issue when i reproduce it again. thanks.
