### ISSUE TITLE
You can’t unlock achievements by using the crafting table on a stick

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#697]
You don’t get achievements for crafting furnaces, pickaxes, hoes, _etc._ when you use a crafting table on a stick.

**Comment by Ellpeck** [comment]
Are you shift clicking? You can't get achievements in general when you shift-click out of *any* crafting window in 1.10/1.11.

**Comment by PapiDimmi** [comment]
I just tested this in a test world, and I got achievements from using the crafting table on a stick. I don’t know why I didn’t in my survival world.

Anyway, you _can_ get achievements by shift-clicking items; I just tested.
