### ISSUE TITLE
[Suggestion] Phantom Dropper

### ISSUE THREAD

**Issue by feldim2425** [Ellpeck/ActuallyAdditions#699]
A block that is just spawns an Item at a remote location as long as the location is not obstructed.
Maybe the Phantom Dropper should also require a very small amout of RF for that.

**Comment by PapiDimmi** [comment]
Sounds like something that’d fit in Actually Additions.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
