### ISSUE TITLE
[Suggestion] Phantom inventory

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [Ellpeck/ActuallyAdditions#7]
Can you add a phantomface inventory that acts Just Like regular phantomfaces except that they Can be bound to a player, so you Can remote access that player's inventory, to pipe in items or RF to remotely charge RF powered armors, mayb even across dimensions (config option) And with configurable range (or infinite, config option)

**Comment by Ellpeck** [comment]
Sounds cool. Will add to the list! Thanks :D
