### ISSUE TITLE
[Suggestion] Adding a config for whether to generate crystals or not

### ISSUE THREAD

**Issue by starg09** [Ellpeck/ActuallyAdditions#700]
Forgot to request this a few days ago, and now I'm actually ok with having them on our pack (thought they'd be way more common than they are). However, I still think it'd be a good idea to offer the choice of turning these off, in the event that someone is not a fan of them :smile:

**Comment by PapiDimmi** [comment]
What do you mean by “generate crystals”? What crystals are you talking about?

**Comment by starg09** [comment]
Oh, yeah my bad. Meant the clusters that appear on caves!

They seem to be more common on lush caves, you break them and get shards of
the mods gems.

**Comment by starg09** [comment]
Actually interested in keeping them now, but felt like something certain
people might appreciate a toggle for :)
