### ISSUE TITLE
Interaction with Greenhouse glass and Vein Mining

### ISSUE THREAD

**Issue by Hondor64** [Ellpeck/ActuallyAdditions#706]
Hey I discovered a weird interaction with Greenhouse glass, glass cutter and vein miner.
 This may be multiplayer only have not tested in single/creative.

If you place 2 greenhouse glass blocks and then vein mine one. you will get 2 back in your inventory but one will remain in the world. 

If you then destroy the one in the world you get nothing back.
But using this method (and patience) you could place as many as you want in the world and never need to make more than 2 greenhouse glass.

Was able to have my friend in the game repeat the interaction. I watched him place two, vein mine one, and then be able to place 2 again.

**Comment by Ellpeck** [comment]
Please report this to the author of the vein mining mod in question.

**Comment by Hondor64** [comment]
Sorry, new to modded minecraft and reporting things. I was playing Skyfactory 3. not sure what vein mining addon it is...

**Comment by Ellpeck** [comment]
Please find out and report it there, too :) 
It should be somewhere in the mod list that you can find in your main menu.

**Comment by Hondor64** [comment]
done.
thanks for your patience. Just trying to help (love the mod btw)

**Comment by Ellpeck** [comment]
Please keep me updated on this issue!

**Comment by Hondor64** [comment]
I posted in OreExcavation but have not heard anything from him on the matter.

**Comment by PapiDimmi** [comment]
”Love the mod btw.” Not even a “thanks.” Shameful.
