### ISSUE TITLE
Lamps - Manual correction

### ISSUE THREAD

**Issue by Forcy24** [Ellpeck/ActuallyAdditions#708]
Hello,
I found a small mistake in the manual: 
Under the chapter "Lamps" it says:

"When right-clicking them with an empty hand, they will turn on and off."

But you need to shift-right-click with an empty hand.

I know it's a small thing but it may be confusing ^^

**Comment by PapiDimmi** [comment]
[I created a pull request.](https://github.com/Ellpeck/ActuallyAdditions/pull/711)
