### ISSUE TITLE
Random Things - fertilized dirt blocks

### ISSUE THREAD

**Issue by Endmateria** [Ellpeck/ActuallyAdditions#709]
Hey Ellpeck, would it be possible to make your auto farming machines in AA compatible with the fertilized dirt blocks from the Random Things mod, or is this an issue that can be addressed on his end?

**Comment by garantiertnicht** [comment]
Which version are you using?

**Comment by Endmateria** [comment]
Nevermind, my mistake.  I didn't realize that I had to till the fertilized dirt.... now they're working.
