### ISSUE TITLE
Intermittent crash on startup due to block breaker?

### ISSUE THREAD

**Issue by cha0s** [Ellpeck/ActuallyAdditions#710]
## Short description:

Ever since updating to Direwolf 1.10.2 1.8.1 I have been getting an intermitten crash on starting the server which is pointing to the block breaker. I'm not sure which block breaker on the server is causing it if there is a specific one. This is an issue that has only cropped up since updating and is getting to be where the server almost reliably crashes the first time trying to come up, but luckily a subsequent restart has worked so far every time. I haven't had to spin it up more than twice.

## Possible hint:

I have a block breaker in my base which is constantly breaking obsidian formed from lava/water. Most of the time the breaker is idle, as the output is fed into a storage drawer without a void upgrade. So eventually the drawer fills and the breaker backs up with a full inventory and stops. **Is it possible this has something to do with trying to do a break right away when the inventory is already full**? Just a thought, might be totally wrong.

## Crash report:

https://gist.github.com/cha0s/294c421a4606fc42b3e1165ad8dadb28

As I said, I'm running dw20 1.10.2 v1.8.1. The corresponding Actually Additions jar is **ActuallyAdditions-1.10.2-r105.jar**

## etc.

This was also reported here: https://www.reddit.com/r/FeedTheBeastCrashes/comments/60774i/dw20_110_v180_actually_additions_block_breaker_in/ by someone else but you probably didn't see it over there.

**Comment by cha0s** [comment]
btw, after perusing that crash log I can see that it does actually list the coordinates of the block, and it is the block breaker in my base causing it. So... I think I'll break that for now ;)

**Comment by canitzp** [comment]
This crash happens at the breaker, but ithappens through a error on the ftb util side. They have a NPE when the breaker breaks something, but I also can see that is has todo with a player logging in at the same time. It also should reported atthe FTBUtil or however the ftb mod id called issue tracker

**Comment by Ellpeck** [comment]
This seems like an issue with FTB Utilities.
Please report to them.

**Comment by LatvianModder** [comment]
Temp fix is to clear your MOTD from FTBU
