### ISSUE TITLE
Refined Storage Integration [Seguestion]

### ISSUE THREAD

**Issue by darkshadow543** [Ellpeck/ActuallyAdditions#712]
I decided I did not want to rip up my Actually additions storage system and just placed an external storage bus onto the item interface. I could put items in, but not out.  Is there a something that already does this or maybe you could add it.

**Comment by Ellpeck** [comment]
You should be able to go both ways if you set up all your Item Interfaces correctly with an External Storage. This is all the interaction that I'm willing to do, sorry.

**Comment by Ellpeck** [comment]
If pulling doesn't work, it's probably because you need to configure all your whitelisted Item Laser Relays to be an empty blacklist in output mode :)

**Comment by darkshadow543** [comment]
My Bad

**Comment by darkshadow543** [comment]
Forgot to set the lasers to empty black lists when I set it up.

**Comment by darkshadow543** [comment]
![2017-03-26_13 44 43](https://cloud.githubusercontent.com/assets/14943673/24335569/dcd969f6-124d-11e7-85b0-ce956d10c358.png)
Though check out this industrial farm I made using pretty much your mod.

**Comment by Ellpeck** [comment]
nice! :D
