### ISSUE TITLE
The crafting table on a stick item does not stack

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#713]

**Comment by Ellpeck** [comment]
I know.

**Comment by PapiDimmi** [comment]
y tho? Regular crafting tables stack.

**Comment by bookerthegeek** [comment]
Not a regular crafting table?

**Comment by PapiDimmi** [comment]
So? It works identically to crafting table, except that you don’t have to place it down. Wouldn’t it make sense that it stacks, just like a regular crafting table?

**Comment by Ellpeck** [comment]
No, because tools don't stack, and I consider it to be a tool.
