### ISSUE TITLE
Mod interation issue (Mystical agriculture)

### ISSUE THREAD

**Issue by darkshadow543** [Ellpeck/ActuallyAdditions#717]
I attempted to use Mystical Agriculture with the farmers, and they did not recognize the seeds as plantables

**Comment by Ellpeck** [comment]
Is this 1.11?
If so, I'll add compatibility. If not, then I won't be able to, sorry.

**Comment by darkshadow543** [comment]
Sorry, my bad, put in the wrong seeds.  Go ahead and close this.
