### ISSUE TITLE
AA Manual Textures messed up

### ISSUE THREAD

**Issue by horrid1999** [Ellpeck/ActuallyAdditions#720]
I was reading through the manual, and the book was showing the missing textures image for pages 3-8 of the Laser Relay Item Storage section. No other parts of the book that I have seen appear to be messed up, but I have not checked the whole thing. I am playing the FTB Beyond pack with nothing extra installed or settings changed.

![2017-03-29_10 52 19](https://cloud.githubusercontent.com/assets/26773536/24466681/f7b982c4-146e-11e7-931e-0b80b859378a.png)
![2017-03-29_10 52 24](https://cloud.githubusercontent.com/assets/26773536/24466693/fca060fa-146e-11e7-8e67-794bd2b28aab.png)
![2017-03-29_10 52 26](https://cloud.githubusercontent.com/assets/26773536/24466697/ff73a2ce-146e-11e7-832a-fcc1c3b25ef4.png)

**Comment by Ellpeck** [comment]
Update your mod.
