### ISSUE TITLE
A config option to completely disable the ability to eat canola seeds

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#722]
I don’t get why you can eat canola _seeds_ in the first place. Who eats _seeds_?

Anyway, it’s really annoying, because I sometimes accidentally eat it and get sick from the long nausea effect.

**Comment by Ellpeck** [comment]
That's the joke behind it. No config option.

**Comment by PapiDimmi** [comment]
Well, it ain’t funny.

**Comment by Ellpeck** [comment]
I think it's funny, and so I'm going to keep it in.
That's the main reason people do things for their hobbies: Because they like them ;)

**Comment by PapiDimmi** [comment]
Well, this “funny” effect makes me sick. I don’t see how a config option to disable it for the people who don’t want this feature makes it any less funny for you.

**Comment by Ellpeck** [comment]
I don't care how sick it makes you. I make the decisions around here, and if you have a problem with that, then stop using the mod.
