### ISSUE TITLE
OreDictionary issues (Rice/Coffee)

### ISSUE THREAD

**Issue by Serifina** [Ellpeck/ActuallyAdditions#724]
Currently, although Coffee and Rice are ore dictionaried, Pam's versions (with the same OreDict) don't work for some things. Specifically, the Rice->Paper recipe doesn't work, nor do any of the AA coffee recipes, including using the coffee maker.

**Comment by Ellpeck** [comment]
I don't really think Pam's version should work for these kinds of recipes, sorry.
