### ISSUE TITLE
[Suggustion] Prevent Generation of monster_egg in Quantum Quarry DIM

### ISSUE THREAD

**Issue by Cryoplex** [Ellpeck/ActuallyAdditions#726]
I've noticed that minecraft:monster_egg has a tendency to generate in the Quantum Quarry dimension. Upon visiting the world, I was greeted with tens of thousands of silverfish. For some god awful reason, they are naturally occurring in vanilla generation of Extreme Hills biomes. I purpose we remove the generation of them all together in the Quantum Quarry dimension, and replace them with generic stone.

**Comment by Ellpeck** [comment]
Neither the Quantum Quarry, nor monster eggs are from Actually Additions.
