### ISSUE TITLE
Crashing Server with Minecolonies Permission interacting with "Actually additions

### ISSUE THREAD

**Issue by djpanda** [Ellpeck/ActuallyAdditions#729]
### Minecolonies version

minecolonies-universal-1.11-0.6.3282.jar

### ActuallyAdditions version

ActuallyAdditions-1.11.2-r106.jar

### Expected behavior

- no problems with other mods 

### Actual behaviour

- there seems to be problems fakeplayerevents and permissions from minecolonies
### Steps to reproduce the problem

1. build a minecolonie 
2. place a longrangebraker from actually additions at the protected area and let him do his work

Log attached ->  https://pastebin.com/DgEFkL7j
Issue posting @Minecolonies GIT -> https://github.com/Minecolonies/minecolonies/issues/753

**Comment by Ellpeck** [comment]
This is an issue with MineColonies trying to send a chat message to a Fake Player which crashes since 1.11, annoyingly.

**Comment by djpanda** [comment]
Do you think it would work as a workaround till the next version from minecolonies released to add the name of the fakeplayer to the townhall ? Whats the name of the fakeplayer ?

**Comment by Ellpeck** [comment]
I use the Minecraft fake player whose name is `[Minecraft]` and whose UUID is `41C82C87-7AfB-4024-BA57-13D2C99CAE77`

**Comment by djpanda** [comment]
thx will check that

**Comment by djpanda** [comment]
https://github.com/Minecolonies/minecolonies/issues/753#issuecomment-292717183
