### ISSUE TITLE
Tiny Torch render/hidden problem

### ISSUE THREAD

**Issue by benten2000** [Ellpeck/ActuallyAdditions#730]
When you have 9 tiny torches in you inventory it is fine but once you go to 10 and above it looks like the item is invisible maybe due to the font text of double digits obscuring the model.
![2017-04-03_12 12 00](https://cloud.githubusercontent.com/assets/2871768/24606983/a87d7b28-1867-11e7-8546-92b8cdbe6911.png)

**Comment by Ellpeck** [comment]
Yea, I know. I think it's sort of funny though, same with when you hold the item in your hand. It looks like it's invisible.
Sorry, but I think this makes the Tiny Torch seem even tinier and so I think it fits :P
