### ISSUE TITLE
[Suggestion] Upgrades

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#731]
* A speed upgrade for the powered furnace, canola press, item repairer, crusher, double crusher, energizer, enervator, _etc._
* An efficiency upgrade for the oil generator and canola press.
* A range upgrade for the automatic feeder, leaf-eating generator, and ranged collector.

Actually Addition’s machines—mainly the powered furnace, crusher, double crusher, and energizer—cannot compete with those of other mods’, as most mods’ machines are much quicker and/or have upgrades.

I think that upgrades for these machines would be very useful in this mod.

**Comment by Ellpeck** [comment]
There's already a suggestion open like htis.
