### ISSUE TITLE
Balance storage crates

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#732]
Storage crates are overpowered. They allow for huge inventories in one single block for just some wood and coal for the latter tiers. The entire Iron Chests mod is pretty much redundant with Actually Additions’ storage crates.

I think that the recipes should be changed.

**Comment by Ellpeck** [comment]
Nope.

**Comment by PapiDimmi** [comment]
So you don’t care about balance at all?

**Comment by Ellpeck** [comment]
I do, just not about your personal opinion of what balance is.
You can always disable their recipe if you don't like them.

**Comment by PapiDimmi** [comment]
Balance is not being able to create single blocks that are equivalent to six double chests with just some wood and coal. The first tier _only_ requires wood, and it’s just as big as a double chest, if not bigger.

**Comment by Ellpeck** [comment]
I don't know how much I'll have to tell you this until you understand: If I disagree about an opinion you have about Actually Additions, then you will just have to accept that.
This is my hobby, you don't pay me money for it, so you don't have the right to make any decisions. I do.
And if I say no, then that means no.
