### ISSUE TITLE
[Suggestion] Small to large storage crate upgrade

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#733]

**Comment by Ellpeck** [comment]
Hm.
I don't think that makes a lot of sense, because you can just upgrade the small one to a large one in two steps easily.

**Comment by PapiDimmi** [comment]
@Ellpeck If you upgrade a small storage crate by replacing the block, you just need a large storage crate, but by upgrading it with the upgrade items, you need a medium storage crate _and_ a large storage crate, which means that if you do it this way, you have to craft two medium storage crates, which means eight void crystal blocks, rather than four.

**Comment by Ellpeck** [comment]
That's the penalty for being too lazy to replace the block.

**Comment by PapiDimmi** [comment]
Well, I had to upgrade a crate that was full of items. The items can’t fit in my inventory, so it’d be quite the hassle to upgrade it that way.

Besides, I don’t see why upgrading it with items costs more resources than replacing the block. That’s just really inconvenient.

**Comment by Ellpeck** [comment]
No means no. Just accept that.

**Comment by PapiDimmi** [comment]
k
