### ISSUE TITLE
The energizer and batteries cannot charge items from Ender IO

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#734]
RF-using items from [Ender IO](https://minecraft.curseforge.com/projects/ender-io), such as the staff of travelling, cannot be charged using the energizer or batteries from Actually Additions.

I’m not sure if this is an Actually Additions bug or an Ender IO bug.

**Actually Additions version**: r105 (latest for 1.10.2)
**Ender IO version**: 3.1.156 (latest for 1.10.2)
**Forge version:** 12.18-3-2254 (latest for 1.10.2)

(I also posted this on Ender IO’s GitHub page: SleepyTrousers/EnderIO/issues/4130)

**Comment by Ellpeck** [comment]
Neither.
Even though EnderIO pretends to support RF on its items, it doesn't. Just use a Capacitor Bank.

**Comment by PapiDimmi** [comment]
@Ellpeck Can you elaborate? What do you mean by “[Ender IO] pretends to support RF on its items”? The staff of travelling, along with the other RF-using items from Ender IO, _do_ use RF, so what makes them incompatible with Actually Additions?

**Comment by Ellpeck** [comment]
The tooltip says "X RF", but in reality, they don't extend IEnergyContainerItem from the RF API, making them incompatible with RF.

**Comment by PapiDimmi** [comment]
Oh, I see. So it _is_ an issue on Ender IO’s part. I don’t see why @SleepyTrousers didn’t do that.

**Comment by VT-14** [comment]
For future reference, Ender IO Items accept either Forge Energy or Tesla.  Installing the Tesla API fixes this.

**Comment by PapiDimmi** [comment]
Does that mean that installing Tesla allows me to charge Ender IO items using AA’s energizer?

**Comment by VT-14** [comment]
Yes.

**Comment by PapiDimmi** [comment]
OK; thanks.
