### ISSUE TITLE
Bowl of Water—unbalanced?

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#735]
The bowl of water is a water bucket that just requires some wood, rather than iron, which makes vanilla buckets useless, unless you’re going to use them for liquids other than water.

I expected it to break after placing the water, but it didn’t. Isn’t it a bit unbalanced?

**Comment by garantiertnicht** [comment]
They can't be used in crafting recepies, and yeah, you need other liquids too

**Comment by PapiDimmi** [comment]
You’re right, but still… I think that they should break after each use. With just one wood block, you get four bowls and _still_ have one plank block left over.

**Comment by Ellpeck** [comment]
This isn't a valid issue.
