### ISSUE TITLE
Drills not mining obsidian.

### ISSUE THREAD

**Issue by 343N** [Ellpeck/ActuallyAdditions#736]
Seems like it'd make sense for the Drill to mine obsidian sicne it requires empowered diamonds to craft, but it can't mine it.

This a design choice or a simple oversight? Can't find anything saying that it specifically can't mine obsidian anywhere.

Thanks.

**Comment by Ellpeck** [comment]
I can't reproduce this issue. It's always been able to mine it.
Did you change the config option of its mining level, or does some mod modify Obsidian?

**Comment by 343N** [comment]
Ah, turns out it's a server specific issue. Works fine in singleplayer, no issues. Can't verify on the server end since I'm not the owner but I'll presume it's a server issue not a mod issue.
