### ISSUE TITLE
The bowl of water cannot put water into a smeltery drain from Tinkers’ Construct

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#737]
**Minecraft version**: 1.10.2
**Actually Additions version**: r105 (latest for 1.10.2)
**Tinkers’ Construct version**: 2.6.3 (latest for 1.10.2)
**Forge version**: 12.18.3.2254 (latest for 1.10.2)

**Comment by garantiertnicht** [comment]
Which ActAdd, TCon and Forge version? Do other bucket-like-items from other mods work?

**Comment by PapiDimmi** [comment]
I have added the versions to the main post.

I haven’t tried with other bucket-like items.

**Comment by YasminEndusa** [comment]
The tanks from mekanism work when used in bucket mode. This is just from memory though, so it might have changed. If needed, i can have a look in a test instance later?

**Comment by Ellpeck** [comment]
I know, it's only supposed to be used for transporting water around in the world.
