### ISSUE TITLE
Bowls of water don’t work well with one’s left hand

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#738]
When holding a bowl and a block in your left hand, using the bowl on water places the block, as well as picking up the water in the bowl.

**Comment by Ellpeck** [comment]
This isn't really all that easy to fix by the way that Minecraft handles placement and item usage.
It'd be a big hastle and not really worth it, in my opinion.

**Comment by PapiDimmi** [comment]
This bug makes it infuriating to pick up water with something, like a torch, in your left hand, so I’d say that it’s worth fixing—at least prioritizing over other, less important bugs.

Anyway, most items from other mods don’t place the block in one’s left hand after right-clicking with the item. There’s a similar—or perhaps identical—bug in the [Ender Storage](Chicken-Bones/EnderStorage) mod that makes you place blocks in your left hand when using the ender backpack, but this doesn’t happen with items from other mods, so it must be a bug in the mod, not in vanilla Minecraft, and I would _assume_ that it’s not that difficult to fix, considering that this behaviour is present in very few mods.
