### ISSUE TITLE
The snowflake pendant from Botania turns oil, crystallized oil, and empowered oil to ice

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#739]
The snowflake pendant is supposed to turn water into ice, but it also turns all types of oil from Actually Additions to ice, which disrupts my automatic canola oil system.

I also posted this on Botania’s GitHub page: Vazkii/Botania/issues/2236

**Comment by Ellpeck** [comment]
Can't really fix this as it's a vanilla issue, sorry.

**Comment by DaedalusGame** [comment]
Make your own material for fluid blocks. Frost Walker only applies to blocks with Material.Water.
