### ISSUE TITLE
Bowl of water incompatible with Refined Storage’s fluid grid

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#740]
I can’t put water from the bowl of water into the fluid grid from Refined Storage.

**Comment by YasminEndusa** [comment]
May i quote Ellpeck from that other issue about the water bowl not being compatible with another mod?  
> I know, it's only supposed to be used for transporting water around in the world.

**Comment by PapiDimmi** [comment]
So… it’s intended? _It’s not a bug; it’s a feature!_

Well, I think that you should be able to put water into your RS system. You’re still just transporting water.

**Comment by Ellpeck** [comment]
I know, it's only supposed to be used for transporting water around *in the world*.

**Comment by PapiDimmi** [comment]
All right, then. This should be written in the Actually Additions manual.

**Comment by Ellpeck** [comment]
No. Not everything should be written in the Actually Additions manual. Just accept that it's a thing, please.

**Comment by PapiDimmi** [comment]
I have accepted it. It would be a lot clearer if information like this were written in the manual.

Something like “The bowl of water can only be used to transport water in the world” in the manual would suffice. I don’t know why you disagree, though; I think it’s useful information.

**Comment by Ellpeck** [comment]
Just stop arguing. No means no, and it also means that you should shut up.
