### ISSUE TITLE
[Suggestion] Option to completely remove items disabled in config

### ISSUE THREAD

**Issue by Lgk2** [Ellpeck/ActuallyAdditions#741]
Could you add an option to completely remove items/blocks/machines that are disabled in config. Currently they still show up in JEI but without recipes. Someone who develops a modpack will probably have to use item hiding mode to hide the disabled items so that the irrelevant items don't show up when people search for stuff.

**Comment by Ellpeck** [comment]
That's almost entirely impossible.
Just hide them from JEI.
