### ISSUE TITLE
[Request] Liquiface Tinkers smeltery controler

### ISSUE THREAD

**Issue by ml0130** [Ellpeck/ActuallyAdditions#743]
Would is be possible to get the Liquiface to be able to pull liquid ore out of a Tinkers smeltery controller? 

![untitled 1](https://cloud.githubusercontent.com/assets/27445711/25049108/eb497e62-20f4-11e7-87eb-487fde93d2ae.png)
![untitled](https://cloud.githubusercontent.com/assets/27445711/25049109/eb4e8556-20f4-11e7-8fc5-14f90a978282.png)

**Comment by Ellpeck** [comment]
You don't pull liquids out of a Smeltery Controller, you always use a Smeltery Drain.
