### ISSUE TITLE
Actually Additions coffee not working with Spice of Life

### ISSUE THREAD

**Issue by Redlotus99** [Ellpeck/ActuallyAdditions#744]
Actually Additions does not work with Spice of Life rules and diminishing returns. After speaking with the dev of Spice of Life this can v fixed by looking here. https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore

**Comment by Redlotus99** [comment]
Guess it would help mentioning I'm using the 1.10.2 version.

**Comment by Utildayael** [comment]
R105 specifically

**Comment by Utildayael** [comment]
Oddly I think all other AA food follows Spice of Life fine. The coffee is odd. As you drink it you can see the nutrition % go down but the actual food value never changes.

**Comment by Ellpeck** [comment]
I do everything the way it is listed on that page.
What exactly is the problem with this?

**Comment by Redlotus99** [comment]
I will do a bit more testing and verify this works as it should once more.

**Comment by Redlotus99** [comment]
Seems like this works fine to me.
