### ISSUE TITLE
Chisel marble and limestone clusers generate them in undergardens

### ISSUE THREAD

**Issue by Hypsellis** [Ellpeck/ActuallyAdditions#745]
The marble and limestone cluster from Chisel float in the void of undergardens and cut often the trees.

**Comment by Ellpeck** [comment]
Forwarding this to @Drullkus because I have no idea why it happens :^)

**Comment by Drullkus** [comment]
@tterrag1098

**Comment by tterrag1098** [comment]
Chisel worldgen only replaces stone. So you must be generating afterwards...

**Comment by Hypsellis** [comment]
The same happens with basalt from Quark.

**Comment by Ellpeck** [comment]
@tterrag1098 as I said to Drullkus, I replace all blocks that have a harvestability of greater than 0, I don't make any restrictions on it having to be stone or anything like that. So this makes no sense to me.

**Comment by Ellpeck** [comment]
For reference, [this](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/gen/WorldGenLushCaves.java#L200) is the code I'm using.
