### ISSUE TITLE
Diamatine Armor Toughness?

### ISSUE THREAD

**Issue by Endmateria** [Ellpeck/ActuallyAdditions#746]
Are you planning on adding armor toughness to the Diamatine and/or Emeradic armor sets?  I'm not gonna do the math, but it seems like a full set of diamatine armor is about the same as regular diamond armor i.e., 4 more defense points, but at the expense of 8 armor toughness.  

"Damage formula is now damage = damage * ( 1 - max( defensePoints / 5, defensePoints - damage / ( 2 + toughness / 4 ) ) / 25 ), i.e. increased toughness means less armor defense point reduction from strong attacks.
Diamond armor has toughness 2, all other armor has toughness 0. A full set of diamond armor, therefore gives a toughness attribute of 8." -Minecraft wiki

**Comment by Ellpeck** [comment]
Not really interested in the toughness system, sorry.

**Comment by Endmateria** [comment]
Oh come on, just fix it... I'll buy you some girl scout cookies and a pirate hat! haha  Nah, it's fine I guess.  Probably won't use those armors as a result, but whatever.  Your mod.
