### ISSUE TITLE
Automatic Precision Dropper duplicates redstone with Flux Networks installed

### ISSUE THREAD

**Issue by VampireValik** [Ellpeck/ActuallyAdditions#747]
- Minecraft: 1.11.2
- Forge: 13.20.0.2284 (and 13.20.0.2282)
- Actually Additions: ActuallyAdditions-1.11.2-r106.jar
- Flux Networks: FluxNetworks-1.11.2-2.0.0.jar, SonarCore-1.11.2-4.0.0.jar (dependency)

With Flux Networks installed, placing either redstone dust or a redstone block in the Automatic Precision Dropper causes it to emit an infinite amount. Reproducing is simple and can be done in Creative or Survival. Place an automatic dropper, put a single redstone dust or block into the dropper, reap the benefits of infinitely duplicated redstone. Even though the dropper is emitting the dust/block it's not removed from its internal inventory causing it to emit again and again.

I narrowed this down to being some sort of interaction between Flux Networks and Actually Additions and have tested with just those two mods enabled. I know that Flux Networks modifies redstone so it can be tossed into a fire to create flux for use in Flux Networks crafting recipes. I suspect that is the cause of this bug but I'm not sure which mod is responsible for the problem so I'm reporting here first.

**Comment by Ellpeck** [comment]
Hey @SonarSonic, do you know what this is about? O_o

**Comment by SonarSonic** [comment]
@Ellpeck Yeah I've been meaning to fix this. the problem is my end. Basically at the moment I cancel the drop event and replace the entity with one which can withstand fire. I just haven't got around to rewriting it

**Comment by Lost-Ninja** [comment]
Just discovered this with diamonds? Is this the same issue?
