### ISSUE TITLE
Positive Feedback Loop Between AA Batteries and NeoTech RF Batteries.

### ISSUE THREAD

**Issue by Pinaz9** [Ellpeck/ActuallyAdditions#749]
If you have a NeoTech RF battery and an activated single/double/triple/quadruple/quintuple battery, and there's power in either of them, they will establish a positive feedback loop that will drain the NeoTech battery and charge the AA battery to capacity, along with any other items in your inventory that can accept power.

**Comment by Ellpeck** [comment]
"positive feedback loop" = you have more power in the end than what you started with?

**Comment by Pinaz9** [comment]
Exactly.

**Comment by Ellpeck** [comment]
I'm presuming the NeoTech battery can also charge other RF holding items?
Please try if this happens with only two NeoTech batteries or with only two Actually Additions batteries.

**Comment by Pinaz9** [comment]
Just checked, NeoTech batteries don't seem to charge each other. They do, however, charge other RF-enabled devices anywhere in your inventory, assuming they're compatible (i.e., not EnderIO.)

**Comment by Ellpeck** [comment]
Please ask the NeoTech dev about this. Actually Additions batteries don't create a loop when charging each other, so I suspect that this is an issue with NeoTech's battery implementation.

**Comment by Pinaz9** [comment]
Couldn't you just blacklist the NeoTech batteries altogether? Just out of curiosity. ALso, I forgot to say, I installed TESLA to make AA batteries compatible with EIO items. So, that might have a bearing on the current situation.

**Comment by Ellpeck** [comment]
No, I can't just blacklist them because that would be ignoring and not fixing the issue. I'd rather not do that.

**Comment by Pinaz9** [comment]
That's a fair point. I'm reporting it now.
