### ISSUE TITLE
MC crashes during LAN games when Crusher or Furnace is being used

### ISSUE THREAD

**Issue by LocoMinerDad** [Ellpeck/ActuallyAdditions#75]
Hello, I am playing MC 1.8.9 everything works fine when I play solo but when I start a Lan game and try to use a crusher or a double furnace. the game crashes. If I dont use these the game is stable. I am not sure where the crash logs are.

**Comment by canitzp** [comment]
You can find the Crash Reports at you Minecraft Instance Folder at crash-reports (Win+r -> %appdata% -> .minecraft -> crash-reports , if you are using the normal Minecraft Launcher an Windows)

**Comment by canitzp** [comment]
The new Forge-Version 11.15.1.1757 has fixed the crash: [Changelog](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.8.9-11.15.1.1758/forge-1.8.9-11.15.1.1758-changelog.txt)
