### ISSUE TITLE
Add support for Crafting tweaks for the Portable Crafting table

### ISSUE THREAD

**Issue by th4umiel** [Ellpeck/ActuallyAdditions#753]
As the title says :)

**Comment by Ellpeck** [comment]
This is already a thing

**Comment by th4umiel** [comment]
Mmm are you sure? I don't see the classic 3 buttons of Crafting Tweaks when using the portable crafting table. Btw I'm using r105 on 1.10.2, so the latest version.

**Comment by Ellpeck** [comment]
It's only on 1.11. 1.10 does not get content updates anymore.

**Comment by th4umiel** [comment]
Oh, my bad. Thanks for the attention though :)
