### ISSUE TITLE
Manual still states Phantom Liquiface needs redstone signal to output fluids

### ISSUE THREAD

**Issue by TomyLobo** [Ellpeck/ActuallyAdditions#754]
<sub>Original title: Phantom Liquiface always outputs liquids to adjacent containers/conduits, regardless of redstone signal</sub>

This is my test setup:
![test setup](http://img.ctrlv.in/img/17/05/03/5909abc506f46.png)

* No hidden components anywhere
* The Phantom Liquiface is connected to the drum on the left
* The drum on the right was initially empty
* The Ender Fluid Conduit is at default settings (in/out, but deactivated)

Alternative test setup (thanks, Phily)
![alternative test setup](https://puu.sh/vE7AA/3d95a83097.jpg)
* No hidden components anywhere
* The Phantom Liquiface is connected to the drum on the left
* The drums on the right and in front were initially empty
* The Ender Fluid Conduit is at default settings (in/out, but deactivated)

In all cases, the initially empty drums get filled with lava, even though they shouldn't

I used:
* AA 1.10.2-r105
* Forge 12.18.3.2254
* EU2 1.3.3

**Comment by Ellpeck** [comment]
Yea, that's just old information in the manual. Whoops.

**Comment by TomyLobo** [comment]
Hmm, I'd suggest changing the behaviour instead of the manual.
It's useful as document, especially in conjunction with liquid-related blocks that can themselves push/pull, like conduits.
