### ISSUE TITLE
Phantom Block Breaker/Placer show misleading distance information

### ISSUE THREAD

**Issue by TomyLobo** [Ellpeck/ActuallyAdditions#755]
My test setup:
![test setup](http://img.ctrlv.in/img/17/05/03/5909faf2a8cb6.png)

* No hidden components anywhere
* The Phantom Breaker is connected to the stone block on the left

As you can see, the overlay shows that the stone block is "3 Blocks away", which would be within the range of 3 of an unboosted Phantom Breaker.
However, it also shows an unspecific message that can mean that the target is too far away, but doesn't have to.

Solution:
I think it the value displayed should be rounded up, not down.

**Comment by Ellpeck** [comment]
I don't really think this is an issue. In this case, the block calculation distance includes the block itself, meaning the connected block is three away, including the block itself. 
I admit this isn't the regular fashion, but I also wouldn't say this is an actual issue, sorry.

**Comment by TomyLobo** [comment]
````
<TomyLobo> i could make a PR :)
<Ellpeck> nah
<Ellpeck> its fine
<TomyLobo> i already cloned it and set up my IDE :)
<Ellpeck> oh
<Ellpeck> then do it
````

Done :)
