### ISSUE TITLE
[Bug] Medium storage crate sorting issue

### ISSUE THREAD

**Issue by ibedek** [Ellpeck/ActuallyAdditions#758]
Not sure if crossmod or not.

I'm playing FTB Beyond 1.5.3 on server (default config), MC 1.10.2.

Steps to reproduce:
1. Create small storage crate, fill it up
2. Apply small to medium crate upgrade, fill up first "page"
3. Start filling second page
4. take some items (stacks) from first page
5. try to sort it with middle mouse button (MouseTweaks mod)
-> error in chat, and sorting doesn't work (will upload screenshot of error if needed)

Expected behavior: to pull items from second page into free slots on first one and sort items

**Comment by Ellpeck** [comment]
This is an InvTweaks bug. Last time I asked the dev, they responded something along the lines of "This is broken, I might fix it some time".

**Comment by ibedek** [comment]
Created issue over there, hopefully "some time" will arrive sooner :D
