### ISSUE TITLE
Make Phantomfaces give out Comparator signal

### ISSUE THREAD

**Issue by Knito58** [Ellpeck/ActuallyAdditions#759]
Possibly not a bug! Just a scream for help.

I wanted to make an xp shower and it should look pretty. The dispenser is set flat in the ceiling, surrounded by glowstone. A lever should start shooting the bottles of enchanting. Due to being surrounded by glowstones, there is no place for a comparator and of course no room for the firing circuit.

Yay we have phantomfaces! 
I thought this should be perfectly possible.

The phantomface says:

> Range: 16
> The connected Block is Dispenser at -68, 84,
> -122 that is 9 Blocks away.
> 
> The connection is fine and working.
> 

Shift - TOP on the phantomface told me, that there were 64 bottles of enchanting inside.

Happily I connected a comparator to the PF. Bof. In short: I was not happy anymore. The comparator stuck dark. Neh.

Just to be sure theres nuts I attached a button to the PF and pressed it. This was my initial thought: Setting up a firing mechanism which is set off of the real dispenser. Pressing the PF's button did not fire a bottle off of the connected dispenser. Pressing and pressing and pressing and pressing did not do anything either.  :)

This is my first approach to using PFs and there might be some misunderstanding on my side.
Either I can do this or I am forced to put the dispencer noobishly one block higher (ugly!).

HELP!

MC 1.11.2
Forge 13.20.0.2294
AA 1.11.2-r107
Game version: SMP
![phantomface-issue](https://cloud.githubusercontent.com/assets/2604989/25740511/2351dd02-3187-11e7-89ff-65097de1539f.jpg)

**Comment by Ellpeck** [comment]
Huh.

**Comment by Ellpeck** [comment]
Normal Phantomfaces only deal with items, that's why the button doesn't work, by the way.

**Comment by Knito58** [comment]
Ok thank you. I read the manual and it states: 

"..., a Phontomface simulates the inventory it is connected to, meaning...."

I wasn't aware that it was meant that way and really felt save about "comparating" and "firing with redstone". 

If you have to make something new, then maybe the Players should craft a Redstone PF Interface and add it to the normal PF to make an inherited RI-PF block. This would not break too much with already existing PFs in all that games where it is used.
