### ISSUE TITLE
ender io + AA

### ISSUE THREAD

**Issue by macqo004** [Ellpeck/ActuallyAdditions#763]
![2017-05-09 15_32_34-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/4783435/25853380/e0458efc-34cc-11e7-8588-3716c7ce2650.jpg)
I dont know if it was supposed to be as is but me conduits wont connect to phantom face even if it has valid output (connectable block)
I know that 1.7.10 is not supported anymore probably but still....
(as not native en speaker Im sorry for any misunderstandings in my message)

**Comment by Ellpeck** [comment]
Phantomfaces only handle items, not AE networks.
