### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kenijey** [Ellpeck/ActuallyAdditions#767]
i just tried to create a new world...hope crash report is enough, and be fixed
[crash-2017-05-14_20.53.15-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/999606/crash-2017-05-14_20.53.15-server.txt)
but it didn't happen again, ( i think so (can't say it won't happen) ).

**Comment by Ellpeck** [comment]
Does it happen every time? Because this has never happened before, and it doesn't make any sense either :^)

**Comment by kenijey** [comment]
no it doesn't. i will repoen this issue if it happens again..
