### ISSUE TITLE
Fluid Laser Relay crash with IC2

### ISSUE THREAD

**Issue by Chryseus** [Ellpeck/ActuallyAdditions#768]
So I had an issue with the fluid laser relays causing a crash when used with IC2, I suspect it's caused by AA since there isn't any problem when using other mods like xnet.
Minecraft 1.11.2
Forge 13.20.0.2292

[crash.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1001434/crash.txt)

**Comment by Ellpeck** [comment]
This is a report of the server stalling. The trace at the top has nothing to do with the actual cause of the crash, but it was just the thing that happened to be executed at the time the server crashed due to taking too long to tick.

**Comment by Chryseus** [comment]
The stalling is caused by AA though ? it stopped the instant I removed all the fluid relays.

**Comment by Ellpeck** [comment]
That doesn't really make much sense.
What's your setup?

**Comment by Chryseus** [comment]
I had a bunch of laser fluid relays feeding water to some IC2 ore washing machines and a canning machine along with biomass to a bunch of fermenters, it worked fine at first but then started crashing whenever the chunk was loaded, I removed them with worldedit and it stopped, I've not had any problem since switching to using xnet, might have something to do with the different fluids being used in the same network but I'm not sure how AA deals with that.
If you want any more info I'm happy to provide.

**Comment by Ellpeck** [comment]
I'd like a screenshot of a recreation of the original setup if that's possible without crashing.

**Comment by Chryseus** [comment]
This is what the original setup looked like:
![mc](https://cloud.githubusercontent.com/assets/3189691/26072049/19fb8a6e-39a2-11e7-9ef6-cfbe56c808a0.jpg)

**Comment by Ellpeck** [comment]
Could you try the same setup, but with the lasers configured to input only and output only, and just having different networks, and seeing if that causes crashes too?

**Comment by Chryseus** [comment]
I've been unable to replicate the crash, there have been a lot of other problems with the server so it may just be a coincidence, I'll report back if I can get it to happen again.

**Comment by Ellpeck** [comment]
Okay. Closing for now.
