### ISSUE TITLE
AIOTs have too high mining Level

### ISSUE THREAD

**Issue by 456Xander** [Ellpeck/ActuallyAdditions#77]
Any AIOT can mine Blocks with any mining Level, if this mod isn't from Vanilla. For Example, you can mine Shiny Ore from Thermal Foundation with a wood or stone AIOT, but you can't mine Diamond ore, which has the same Mining Level as Shiny. When I tried mining Shiny with a stone pickaxe then, it didn't work, so it's a bug with AIOTs.

**Comment by canitzp** [comment]
Which MC Version you are  playing on

**Comment by 456Xander** [comment]
1.7.10

**Comment by canitzp** [comment]
Actually Additions doesn't support 1.7.10 anymore.
