### ISSUE TITLE
rice seed pops up of a tilted dirt?

### ISSUE THREAD

**Issue by Jiraiyah** [Ellpeck/ActuallyAdditions#770]
Hi
I'm using 1.10.2-r105
I encountered an interesting issue, I have a 11*11 farm in the middle of ocean right on water level, the land is always tilted and wet but when i plant a rice seed, sometimes one or two of the seeds beside it pops out also, every now and then a random seed pops out of land.
not sure where to look for any sort of log file or what but it looks like when the seed is going to tick for growth, sometimes it fails and the plant won't go forward and for some reason it thinks that the plant is being broken or something like that so it drops the seed !!!

**Comment by Jiraiyah** [comment]
Ummm is there a need for a light level for being able to plant seeds? because when i lit up the area better, the seeds are not popping up anymore !

**Comment by canitzp** [comment]
Every plant that you can put on tiled dirt needs a certain amount of light
