### ISSUE TITLE
Infinite Energy Bug (Mod Compatibility)

### ISSUE THREAD

**Issue by kenijey** [Ellpeck/ActuallyAdditions#771]
on minecraft 1.11.2, forge 2298. RebornCore 2.14.2.94, TechReborn 2.2.1.142, Actually Additions r107.
this happens:(solar panel is full but mfsu is filling)
![bug](https://cloud.githubusercontent.com/assets/24831406/26191623/459b093a-3bb7-11e7-8e93-9b7ef4c6eea9.gif)
https://github.com/TechReborn/TechReborn/issues/1083

**Comment by canitzp** [comment]
This is very likely a problem with TechReborn, since the lasers only transfer the power and if they work fine with other machines they could't be the problem

**Comment by kenijey** [comment]
hey ah, i don't know how did i do  it but i tried it in vanilla, TR + RC + AA, and laser relay doesn't work.  so this gif happens only in my modpack i think. dunno what causes that infinity problem. but if you make a clean install with TR + RC + AA, laser relay won't connect the energy from solar panel to MFSU.

**Comment by Ellpeck** [comment]
I have no idea what this is about, so I'm going to wait on what @modmuss50 says.

**Comment by modmuss50** [comment]
I bet it's a TR issue, especially if it's fine with other mods. There is an issue open on our tracker about so I can look into it. If it turns out to be your issue I will get back to you. This can be closed.
