### ISSUE TITLE
Request: Ender Lily and Red Orchid Farmer Support

### ISSUE THREAD

**Issue by Darkosto** [Ellpeck/ActuallyAdditions#772]
Hello Good Sir!

I would very, very much appreciate if you would consider adding compatibility  for Extra Utils 2 Red Orchid and Ender Lily seeds. I know you're a very busy individual, and what would absolutely make my entire year... scratch that... my entire Minecraft career is if you could please consider this. I will send curse points, pictures, coffee? Pink Post-it notes, or anything else you could think of that would inspire you to put those magic fingers to work onto your beautiful keyboard and make this happen. Don't think of it like you're doing me a favor, think of it as doing the entire minecraft modded community a favor. One that we will all be in your debt for. I know this may sound rude, but trust me, it is not. I love you very much and thank you for taking the time to check this out.

MC: 1.11.2
AA: r107
Forge: 2299

Oh! One more thing: I will record myself dancing to Michael Jackson's "Beat it" if you figure why the RFTools dimension thingy isn't charging correctly. Thanks!

Sincerely and always yours,
Dankosto

**Comment by Ellpeck** [comment]
ok

**Comment by Darkosto** [comment]
kthx

**Comment by HILeotomasMC** [comment]
I agree. This is really needed. Without it, the mod is completely UNUSABLE!!!!!!
Plz fix your mod so we can use it.


![darkoHeart](https://static-cdn.jtvnw.net/emoticons/v1/122195/2.0.png)

**Comment by Mattabase** [comment]
Dear, Glorious Sir!


We are forever in your debt Ellpeck.

I agree with everything @Darkosto Said hands down, you have done a great service for not just the Minecraft modding community but the entire World.

Warm Regards, and With Great Appreciation
TheMattaBase

**Comment by h1nk** [comment]
Referencing what @Shadows-of-Fire mentioned in #1009
> XU2 is not supported. I will not special case its nonsense. That's already done for the farmer, and only still exists because it was written before I got here and I have not removed it.

If XU is not going to be supported can the pages saying it's supported please be removed from the mod book?

![image](https://user-images.githubusercontent.com/12993584/35850789-fa734eec-0af3-11e8-8c39-cd3d231d667d.png)
Extremely misleading and frustrating to find out it doesn't work and isn't supported and has no intent 
 to be supported whatsoever yet it's cited as a working example.

**Comment by Shadows-of-Fire** [comment]
That part does work, or at least it works from aa's end.

**Comment by h1nk** [comment]
So a standalone Farmer block in 1.12 should be able to gather XU Ender Lilies?
