### ISSUE TITLE
Work out why RFTools Dimensions things don't charge in the Energizer

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#774]
> I will record myself dancing to Michael Jackson's "Beat it" if you figure why the RFTools dimension thingy isn't charging correctly. Thanks!

Quote from @Darkosto from #772

**Comment by Ellpeck** [comment]
Quote from @feldim245: The Item still uses the "IEnergyContainerItem" from the RF API and doesn't have Capabiilities. Bug on the RFTools side

Go dance, @Darkosto!

**Comment by Ellpeck** [comment]
Oh also, forwarding this to @McJty cause it's a bug with RFTools dimensions.

**Comment by McJty** [comment]
That's not a bug. The RFTools Dimension realized tab is not an item that supports power. It can *only* be charged in a dimension builder. In nothing else. The item itself does not contain energy. The dimension does and that can only be charged with a dimension builder

**Comment by McJty** [comment]
Sorry, wrong item it seems

**Comment by feldim2425** [comment]
Yup. I also thought he means the Dimension Tab but I think he meant the Phased Field Generator
