### ISSUE TITLE
Request: Wood Farmer

### ISSUE THREAD

**Issue by tia79** [Ellpeck/ActuallyAdditions#776]
Theres a miner but no wood farmer in actually additions. I wish for one :)

**Comment by Ellpeck** [comment]
Nope, sorry :(

**Comment by tia79** [comment]
Thats it? No comment beyond nope?

**Comment by Ellpeck** [comment]
I think wood farms that you don't have to build manually (ie using the long range breaker) make the game boring because you can just make a simple wood farm and power fueled generators with that, which makes all other ways of power gen completely pointless.

**Comment by tia79** [comment]
In 1.11.2 No trees grows when there is buildt something beside it. I tried with the piston and autobreaker but i have not have any luck with that. However its fine you think that. but i feel the same about the miner. But its a choice you take to use it. so at least let people have a choice to use a wood farmer if they so wish even tho you wont personally.

**Comment by Ellpeck** [comment]
If I say no, that means I won't implement it. I'm sorry.
