### ISSUE TITLE
Spawner Changer not working on Villagers

### ISSUE THREAD

**Issue by Vyraal1** [Ellpeck/ActuallyAdditions#777]
Playing on All the Mods 2 modpack (on the official server) for 1.11 with Actually Additions r107 .

Spawner Changer wouldn't work on villagers, and funny enough it would work on Iron Golems. I don't think the server admins altered the configs at all on the server, so it just might be it was accidentally blacklisting villagers, and not golems.

**Comment by Ellpeck** [comment]
It does work on villagers, you just have to do the same trick as when using a nametag: Stand in a nether portal so that the villager's GUI doesn't open.
