### ISSUE TITLE
[Minor Suggestion] Crafting Table On A Stick + Crafting Tweaks

### ISSUE THREAD

**Issue by thegreatersea** [Ellpeck/ActuallyAdditions#778]
I'm unsure as to which mod would have to fix this, so I'm adding this to both repositories. Would it be at all possible to make the crafting table on a stick compatible with Crafting Tweaks, so that the rebalance/rotate/remove buttons are available? Or would this need to be done on Crafting Tweaks' end?

**Comment by JuliusFreudenberger** [comment]
This was already discussed in #753
