### ISSUE TITLE
Game Crash with auto breaker

### ISSUE THREAD

**Issue by BrewAndCode** [Ellpeck/ActuallyAdditions#779]
AA ver 1.10.2-r105
Forge ver: 12.18.3.2297

I can regularly repeat this;  Place an auto breaker down then a birch plank in front of it.  Insta-crash and can no longer load that world

Crash reports enclosed.
[crash-2017-05-22_11.42.33-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1019435/crash-2017-05-22_11.42.33-server.txt)
[crash-2017-05-22_11.53.52-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1019436/crash-2017-05-22_11.53.52-server.txt)

**Comment by Ellpeck** [comment]
Whatever `com.cjm721.overloaded.common.item.functional.ItemMultiTool` is is causing the crash, not Actually Additions.

**Comment by BrewAndCode** [comment]
Crap; I didn't even see that; was looking at the bottom of the stack not the top.  Sorry will look into it further.
