### ISSUE TITLE
Inv Tweaks support for CrafterOnAStick

### ISSUE THREAD

**Issue by tahg** [Ellpeck/ActuallyAdditions#782]
Title basically says it all.  Right now you can't use Inventory Tweaks shift-click functionality with the crafter.

**Comment by tahg** [comment]
I had totally forgotten about this, but alas the fix doesn't fix the problem. It *does*, as the javadoc implies, add Inventory Tweaks menu button to the GUI, but does not allow sorting or quick movement to the crafting grid.

**Comment by Ellpeck** [comment]
I don't really care about InvTweaks compatibility to tbe honest, and I thought this would fix it, but if it doesn't, then I have no clue and honestly not really any interest in finding out how it actually is fixed.
