### ISSUE TITLE
Can you add the Embers mod ore to work in the crusher?

### ISSUE THREAD

**Issue by Luckyday84** [Ellpeck/ActuallyAdditions#783]
Im playing a mod pack with just Actually Addition and Embers and cant use the Actually Addition crusher with Embers ore.

But I guess this could be also an issues with Embers ores not being in the ore dictionary?

Im using Minecraft 1.11.2 with latest version of both mods and latest forge.

Thanks

**Comment by Ellpeck** [comment]
Which Embers ore..?

**Comment by Luckyday84** [comment]
Its all of them. Copper, Tin, Silver ,Nickel, Aluminum and Lead ores
Here's also a screen shot of the crushers GUI.
![2017-05-25_07 48 05](https://cloud.githubusercontent.com/assets/16806699/26449185/d5ea7f2c-411e-11e7-9f87-330a90c4da19.png)

**Comment by Ellpeck** [comment]
The crusher automatically adds recipes for entries in the OreDictionary with ore[something] to be crushed into 2x dust[something], if the ore isn't in the OreDictionary, or the dust isn't present, this won't work. It's not an issue on my side.
