### ISSUE TITLE
TileEntityLaserRelayEnergy#transferEnergyToReceiverInNeed - Performance

### ISSUE THREAD

**Issue by Sir-Will** [Ellpeck/ActuallyAdditions#784]
hey,
can the performance of this method be improved?

![](http://i.imgur.com/JlWJHsK.jpg)

**Comment by Ellpeck** [comment]
What's your setup? The usage shouldn't be this high.

**Comment by Sir-Will** [comment]
It's on a server with 20+ players so I can't check for an setup.

**Comment by Ellpeck** [comment]
Then it's hard for me to just increase the performance of the method.
It's as well performing as I could make it at the time, and I doubt I can change anything about that without actually seeing what the problem looks like in-game. 
Please try finding out the place that this high usage is originating from.

**Comment by Sir-Will** [comment]
Performance is better now but it is still overall bad:
![](https://i.imgur.com/zYTexra.jpg)
