### ISSUE TITLE
Feature Request: Not Sneaking With Bowl of Water Spills

### ISSUE THREAD

**Issue by Darkosto** [Ellpeck/ActuallyAdditions#785]
Ellpeck the Mighty,

Hey there! I had a pretty cool idea that I think you would absolutely love!!1!!one! 

Picture this: you're in a world. It's early game, and you can't make buckets. I open my JEI up and all I see are Actually Additions water bowls. I think to myself! "SELF! LETS GO GET SOME WATER!". I quickly run to the river with my trusty vanilla bowl! I scoop up 1 helping of water and turn around back towards my base. I'm so excited because now! I have water and I can start my wheat farm. BUT! Little did darkosto know, the water spills out. "WHAT!" I exclaimed! That's not right! I didn't right click. I grab another bowl, it spills again. I look at chat, and all I see are FailFish's. Turns out, I didn't carefully sneak the bowl back to my base and the water fell out. 

^^ This could be your experience if you so graciously use your magic coding fingers and make it so! I would forever be in your debt, again. Just imagining all of the wonderful and epic times that could be had. 

MC: 1.11.2
AA: Whatever the latest version is
Forge: 2304

I love you,
Darkosto

**Comment by Ellpeck** [comment]
u got it, bro

**Comment by OhCreative** [comment]
I rate 10/10 Plz Implement Immediately. I WANT THIS EXPERIENCE!

**Comment by Akiishii** [comment]
Lets do this! Hypuuuuu

**Comment by Knito58** [comment]
I want this, too! Great idea. Should change my name to "RestartFromScratch". I use the bowls alot in early games. This would balance the bowls greatly. Master Ellpeck: PLEASE!
