### ISSUE TITLE
ESD (Enhanced Soupe Diner) wants to fill all slots

### ISSUE THREAD

**Issue by Knito58** [Ellpeck/ActuallyAdditions#786]
Versions:
MC 1.11.2, Forge 13.20.0.2294, AA 1.11.2-r108

I have set up an AIM Inventory Relay and put it into hotbar mode. I want torches to be filled into the last slot of the hotbar. If I put a normal hopper under the torches chest then all of the slots of my hotbar get spammed with torches. Yay we have ESDs (Extremely Stinking Diaper) where we can tell which slots to fill. When putting the ESD (Ernie Says: "Duh!?") under the torch-chest it doesn't do anything because both input and output are disabled. As soon as "inbound" is set to "up" the torches appear in the preview box. As soon as "outbound" is set to "north" it pre-sets the slot numbers to 0 and 9 and begins to spam torches into my hotbar. Well, I only want the ESD (Entertaining Slot Dialer) to put torches into the last slot and I change the 0 Zero to become an 8 Eight. The ESD (Elvis Still Dead) becomes miffed and stops working. Other numbers have the same issue: All or nothing! 
Maybe there is some misunderstanding upon the behaviour of the slot counting on my side.
Need help!

**Comment by Ellpeck** [comment]
Can't reproduce with this setup.

[!](https://puu.sh/w31sf/8ea197363b.jpg)
[!](https://puu.sh/w31rY/0f8cc092b4.jpg)
[!](https://puu.sh/w31sp/abfc43e633.jpg)

**Comment by Knito58** [comment]
Your setup is great for this. Now try to tell the ESD to only fill the last slot of the northern chest. I copied your setup and changed the numbers for "North" to 26 (start) and 27 (end+1) for a vanilla chest. It does not fill a single thing into the target chest, when the numbers do not start from zero. 25 and 27 do not work either. There's a "last slot problem".

**Comment by Ellpeck** [comment]
Huh, yea.

**Comment by Knito58** [comment]
Sorry.
