### ISSUE TITLE
[1.10.2] Rendering screen crash opening a crate

### ISSUE THREAD

**Issue by Eufranio** [Ellpeck/ActuallyAdditions#787]
Every time I try to open my crate the game crashes. I can easily fix it by breaking the crate and placing again, but after a few minutes it will crash again after opening. This specific crate **DOES NOT** have any modded item other than actually additions ones (that's my ActAdd crate).

Let me know if you need any other info. Crash-report: https://hastebin.com/uxutuyolom
Running:

    ActuallyAdditions-1.10.2-r105
    Minecraft 1.10.2
    Forge 12.18.3.2281

**Comment by Ellpeck** [comment]
Does this happen with any other crates, or only one specific one that you keep breaking and picking up again?
Also, does this keep happening if you remove all the other mods that you have installed?

**Comment by Eufranio** [comment]
Only the one I keep breaking, and it happens if I remove all mods (happened like 6 times in the same map, on singleplayer, while I was testing). I believe it happens when I break the crate and try to open it at the same time...

**Comment by Ellpeck** [comment]
If it only happens with that exact crate, then please press F3+H to turn on advanced info, make sure you have the advanced AA info turned on in its config, and then press shift and control together on the crate in question while it is in your inventory and take a screenshot.

**Comment by canitzp** [comment]
Can you post the crash report if no other mod also not optifine is installed? For me it seems like a forge bug, but such a bug should be noticed by the forge team earlier

**Comment by Eufranio** [comment]
Without OptiFine it worked (the crashing crate), so I updated my OptiFine version and it is now working, no crashes. Still want the debug info?

**Comment by canitzp** [comment]
No, if removing optifine fixed it we don't need further logs.
