### ISSUE TITLE
Custom Item Handler is inefficient

### ISSUE THREAD

**Issue by tahg** [Ellpeck/ActuallyAdditions#788]
TileEntityInventoryBase creates a ItemStackHandlerCustom which has a poor implementation of canInsert.  The method defers to the machine's isItemValidForSlot, which can potentially be an expensive check.  It should first do some simple checks stack compatibility and size.

**Comment by Ellpeck** [comment]
ur a poor implementation

**Comment by tahg** [comment]
That must be why I never get anything done.
