### ISSUE TITLE
Fluid Collector Improvement (TL:DR bolded for convenience)

### ISSUE THREAD

**Issue by greenking13** [Ellpeck/ActuallyAdditions#789]
Hello Ellpeck,

I've been using your mod for quite some time now, and decided recently to try and automate your oil generators with empowered canola oil. I'm using a nifty compact setup in which I have two ExU2 scanners detecting the block they are pointing to, and when they "see" the correct block, they output a signal to your Precision droppers to drop their respective seeds. The first scanner scans for basic oil, and the corresponding dropper drops the crystalized canola seed. The second scanner scans for crystalized oil, and the corresponding dropper drops the empowered canola seed. Then I have a fluid collector pick up the liquid it can "see" and it gets moved around to the proper spot, to be used for power generation. An issue I am running into is that the collector will occasionally run out of empowered liquid, and will either pick up regular oil or crystalized oil. **TL:DR** I was wondering if it would be possible to be able to filter the fluid collector in some method, such that it could have a whitelist of acceptable fluids.

Thank you,
Greenking13

**Comment by Ellpeck** [comment]
No. Just use a clock if you don't have the ExU scanner available.

**Comment by greenking13** [comment]
It's all well and fine, I just figured I would ask since it sounded like a good idea. I'm still trying to figure out how I would go about using a third scanner since I am using all 6 sides of my designated liquid block. 2 for scanners, 2 for precision droppers, 1 for fluid collector, and 1 for fluid placer. Maybe what I could do is see about forcing the collector to always retain a bucket of empowered canola oil...

Have a good day,
Greenking13

**Comment by Ellpeck** [comment]
If you need an easy setup, I made one on my Youtube channel that uses only Actually Additions and Vanilla Redstone, and is completely over- and underflow proof, both for the oil and the seeds.
https://youtu.be/E3krUdD8o6g
