### ISSUE TITLE
[1.10.2, FTB Beyond Modpack] Ranged collector dupe bug

### ISSUE THREAD

**Issue by XxZajoZzO** [Ellpeck/ActuallyAdditions#790]
If you drop an item near the ranged collector and try to pick it up both you and collector will pick it up, duplicating the item. Also works with stacks of items.
ActuallyAdditions-1.10.2-r105
https://www.youtube.com/watch?v=vh-hKgoR6es

**Comment by Ellpeck** [comment]
nice

**Comment by Ellpeck** [comment]
Please try without any other mods installed and see if the same thing happens. If not, please try finding out which mod causes it to happen.

**Comment by XxZajoZzO** [comment]
NEI Magnet mode causes that. I forgot I had it enabled.
Nut sure if this is a bug now because magnet mode is considered cheating (I guess)

**Comment by Ellpeck** [comment]
Regardless, it's not a bug with the Ranged Collector.
