### ISSUE TITLE
No JEI handler for Composting

### ISSUE THREAD

**Issue by jaredlll08** [Ellpeck/ActuallyAdditions#791]
Dear Lord Ellpeck, of House penguin. Rightful heir to the Milkshake Throne, King of the Seven Kingdoms of Germany, the Rhoynar, and the First Men. Mother of penguins, the modder of the great frozen plains, the unbroken and breaker of mods,

As it stands, The composter lacks a JEI handler, so I come to you, Lord Ellpeck, of House penguin. Rightful heir to the Milkshake Throne, King of the Seven Kingdoms of Germany, the Rhoynar, and the First Men. Mother of penguins, the modder of the great frozen plains, the unbroken and breaker of mods, as a simple peasant, with nothing to his name, asking for you, Lord Ellpeck, of House penguin. Rightful heir to the Milkshake Throne, King of the Seven Kingdoms of Germany, the Rhoynar, and the First Men. Mother of penguins, the modder of the great frozen plains, the unbroken and breaker of mods, to add a JEI handler for the composter, I know I am not asking for something easy, and I know that blood and tears will be involved fulfilling this request, but I urge you, Lord Ellpeck, of House penguin. Rightful heir to the Milkshake Throne, King of the Seven Kingdoms of Germany, the Rhoynar, and the First Men. Mother of penguins, the modder of the great frozen plains, the unbroken and breaker of mods, to bear through it, for the good of your kingdom, for the good of all, to fulfill my request and add a JEI handler for The composter.

With regards,
Jared
~A humble peasant

**Comment by Guard13007** [comment]
Translation: Please add a JEI handler for the composter.
