### ISSUE TITLE
[Suggestion] Seed Slot in Farmer

### ISSUE THREAD

**Issue by 016Nojr** [Ellpeck/ActuallyAdditions#792]
I am using the Farmer to farm different seeds, (Rice, Ender-Lily's and Inferium Essence) and I am suggesting a feature to make the farmer only have one stack if a single item in the 6 seed slots to avoid a certain seed filling all 6 slots, in my case it would be Rice.

**Comment by Ellpeck** [comment]
No, the farmer isn't supposed to be used with multiple plants at once.
