### ISSUE TITLE
[Suggestion] Empowered TNT

### ISSUE THREAD

**Issue by Dolinmyster** [Ellpeck/ActuallyAdditions#793]
Was thinking it would be really cool to have some sort of empowered TNT for bigger booms. You could use the Atomic Reconstructor for the first tier, but you have to use the Lens of Detonation to change it the first time. Then maybe using that same TNT in the empowerer setup to make a bigger boom as well.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
