### ISSUE TITLE
No Rice Dough Recipe?

### ISSUE THREAD

**Issue by EZKatnipz** [Ellpeck/ActuallyAdditions#795]
There isn't a recipe to make rice dough. lol
In the book where I think it is supposed to show it, it says null with an empty crafting grid. Right next to the rice dough to rice bread entry.

Version:  ActuallyAdditions-1.10.2-r105

**Comment by Ellpeck** [comment]
Then it's probably disabled in the config in the modpack you're playing.

**Comment by EZKatnipz** [comment]
Man, i even looked through that. Thanks. Love the mod, the drill is probably my favorite part.
