### ISSUE TITLE
BC Compat

### ISSUE THREAD

**Issue by tahg** [Ellpeck/ActuallyAdditions#796]
BC's energy module is named "buildcraftenergy" as of April a year ago.  Seems like they overhauled mod ids to be lowercase and not have |'s

**Comment by AEnterprise** [comment]
so someone just pointed me to this and the id change isn't the only energy change by far: Buildcraft is now using MJ again. MJ is quite different from RF in that it is not realy ment to be stored in blocks or batteries

Buildcraft is also still in early alpha and we are not quite sure ouselfs what final compat with RF will or should look like

**Comment by Ellpeck** [comment]
This isn't about RF.

**Comment by AEnterprise** [comment]
no but i'm just pointing out the difference of MJ with RF (and derived energy systems) what it used in the prev version.

The point i'm trying to make is that it is a seperate type of energy (with an api that's still in alpha like the rest of the mod) that is not ment to be stored in batteries that AA adds (or other energy storing blocks, machine buffers are fine: some storage is needed so engines can kick in). With MJ you are suposed to expand your energy production for all your energy needs, not just make a few that cover the basics and then a huge buffer to provide energy on peak power usage

**Comment by Ellpeck** [comment]
And I never said it was supposed to be stored in batteries from AA, and it's not the point of this issue. The point is that in the @Mod annotation of Actually Additions, the modid of BuildCraft is an outdated one.

I honestly don't care about MJ or RF or whatever :>

**Comment by AEnterprise** [comment]
ah alright, sorry to have barged in here then. The guy who linked me this issue claimed we should allow conversion with other energy types because major mods like AA where going to do it anyways, my apologies for not getting better informed in advance
