### ISSUE TITLE
Missing Features 1.10.2-r105

### ISSUE THREAD

**Issue by Finalruner** [Ellpeck/ActuallyAdditions#800]
The farmers arent compatible with your newer compatibility additions in for the 1.11 updates. Upgrade plox! I need my melons!

**Comment by Ellpeck** [comment]
No, it's called "downgrade". Updating is the thing you are supposed to be doing ;)

**Comment by Finalruner** [comment]
Most mod packs are still on 1.10.2

**Comment by Ellpeck** [comment]
I don't care.
