### ISSUE TITLE
Worms! - FPS Drops

### ISSUE THREAD

**Issue by saibotk** [Ellpeck/ActuallyAdditions#804]
Hey Ellpeck,
first, thank you for your awesome mod,

But when using your Item/Energy/Fluid Laser Relays, I noticed huge FPS drops, when looking towards them. 
Maybe it is just because the 1.10.2 version is not on the same update as 1.11, but I would really enjoy at least a config option, as a temporary solution, to disable or decrease the particles / lasers.
I really want to keep using your laser system in my base.

Thank you.
----

Danke nochmal ;)

**Comment by Ellpeck** [comment]
Particles?

**Comment by Ellpeck** [comment]
I am going to blame @elucent and @feldim2425, they were the only ones that worked on the renderer :V

**Comment by saibotk** [comment]
@Particles: i was just thinking of a simpler level instead of lasers, particles. just to see that lasers are connected, but i just meant lasers for now, sorry. 
What about the possibility to show the Lasers only when i hold the wrench? 
Could save me a ton of FPS

**Comment by Ellpeck** [comment]
No, I don't want that to be a feature, especially with the hiding upgrades.
I'd rather the FPS issues were just fixed.

**Comment by saibotk** [comment]
Oh i did not know about these 👍 i guess this will help me for now. Thanks.

**Comment by saibotk** [comment]
But @Ellpeck sry for spamming, but could you explain where to find them? 
They seem to not be implemented yet?/anymore? in the 1.10.2-r105

**Comment by Ellpeck** [comment]
They're not in 1.10, and, before you ask, no, they won't be.
Don't use an outdated version of Minecraft if you want them :P

**Comment by saibotk** [comment]
Outdated but still more mods available, and therefore more fun, for now.
But i respect your decision to not update the "old" version.

Thank you for your fast response.

**Comment by saibotk** [comment]
EDIT: Sorry just figgured out, it was the worms causing many and many chunkupdates. 
Note to myself: Never use worms on a big automatic farm.

**Comment by Ellpeck** [comment]
Yea, not really anything I can do about that. You should still keep water around your worms.
