### ISSUE TITLE
[1.11.2] Lens of disenchanting not working

### ISSUE THREAD

**Issue by 016Nojr** [Ellpeck/ActuallyAdditions#806]
When I try to move "Smite 4" from a book with "Smite 4" and Looting "2" to an unenchanted book it does nothing when I activate it. The enchanted book and the normal book has 1 block between them and the laser with a piece of chiseled stone behind (The laser does not go through it). The Reconstructor is full of CF (300.000 CF).

Mod Versions
AA: 1.11.2-r108
Forge: 13.20.0.2298

**Comment by Ellpeck** [comment]
As stated in the manual, the things you want to enchant/disenchant need to be in the same blockspace. Also, you can't disenchant books.

**Comment by 016Nojr** [comment]
Ah, I thought I could because the manual just says that it can move a single enchantment from an "Enchanted Item"
