### ISSUE TITLE
[1.10.2 - r105] Crash on entering Abyssal portal

### ISSUE THREAD

**Issue by VallenFrostweaver** [Ellpeck/ActuallyAdditions#807]
Spawned in dark bricks and wither dust, used them to make the portal in a snowy biome in the Craft of the Titans modpack and upon entering the portal, crashed and can't recover.  See pastebin below for crash report. If you believe it's another mod please let me know and I will report there.

https://pastebin.com/Np44MBS8

NOTE: Originally reported this at Ad-Inferos github here but was directed to this mod for further action:
https://github.com/superdextor/Ad-Inferos-Mod/issues/1

**Comment by Ellpeck** [comment]
Is this using Sponge?

**Comment by VallenFrostweaver** [comment]
No. Forge.
