### ISSUE TITLE
Notifies "New version" for 1.8.9 in 1.7.10

### ISSUE THREAD

**Issue by Tomson124** [Ellpeck/ActuallyAdditions#81]
The mod always notifies me in the chat that there is a new version available but I have the newest one for 1.7.10. It always tells me to install the ones for 1.8.9.

**Comment by canitzp** [comment]
There is a config option to disable the Update Checker.

**Comment by Ellpeck** [comment]
There is also a config option to have version-specific update checking when you want to only be notified for 1.7 versions.
Which there are no more to be released.
