### ISSUE TITLE
[1.12] Server crash on first run

### ISSUE THREAD

**Issue by Seth0067** [Ellpeck/ActuallyAdditions#811]
[crash report] (https://pastebin.com/3eXZgNur)

There are a bunch of mods throwing this error - maybe its a known forgebeta thing, but thought i would send it over.  

thanks for being on 1.12 so early (hey, it works in single player)

**Comment by Ellpeck** [comment]
"Hey, let's just change the entire registry system to something new! It'll be fun!~"
Forge really likes to be a dick sometimes.

**Comment by Zarepheth** [comment]
I'm encountering the same problem, but since @Seth0067 has already reported it to you, no need for me to create a new issue. Now to report the issue to the other mods' authors...

**Comment by Ellpeck** [comment]
**I'm locking this issue as I am aware that all users of the mod will get it if they update Forge to the newest version.
Forge changed the entirety of the registry system in its latest update, and I am not willing to update Actually Additions to this system before it is stable enough not to have to be adapted to again.**
