### ISSUE TITLE
Rename AA fluids to avoid mods clashing

### ISSUE THREAD

**Issue by Silvrus** [Ellpeck/ActuallyAdditions#813]
Forge 13.20.0.2315
AA 1.11.2-r110
BuildCraft 7.99.4

Actually Additions appears to be overriding the oil registry entries. Pumps don't recognize BC oil geysers, and bucketing the oil from the geyser gives AA oil instead of normal BC crude oil. I suspect it might be doing the same for Immersive Petroleum's oil, but have not been able to test yet. Disabling AA returns BC oil functionality.

**Comment by Ellpeck** [comment]
This shouldn't be a bug and everything should still work the way it normally does with every other oil.
What's the problem here?

**Comment by Silvrus** [comment]
The problem is that pumps don't recognize it as a valid fluid and won't pump the oil geysers. I tried Buildcraft and Immersive Engineering's pumps.

**Comment by Ellpeck** [comment]
Which oil do the geysers use?
Pinging @AlexIIL as I have no idea why this would be happening.
Even if AA oil were to override BuildCraft oil by having the same name (probably "oil"), it should still not cause any trouble with pumps and the like.

**Comment by Silvrus** [comment]
![2017-06-25_08 27 02](https://user-images.githubusercontent.com/8472891/27517367-249a0cae-5980-11e7-8104-2cd848d5d4ad.png)

This is the crude oil geyser that Buildcraft adds. You pump the crude oil, then refine it into fuel.

**Comment by AlexIIL** [comment]
Does AA add any blocks for oil? BC might not be handling fluids correctly...

**Comment by Silvrus** [comment]
AA adds canola oil you refine from canola plants.

**Comment by Ellpeck** [comment]
Actually Additions adds an oil block that is bound to the oil fluid. What I do for Actually Additions is I register the oil fluid regardless of there already being one, but then I use the fluid that is actually registered as the main fluid in the registry.
You can see this done [here](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/fluids/InitFluids.java#L46-L52).
This is how Thermal Foundation and most other mods I looked at did it at least in 1.7 and 1.10, but this might bot be the right way to do it anymore.

**Comment by AlexIIL** [comment]
I have no idea 2what the right way of doing it is either, sorry.

**Comment by Ellpeck** [comment]
What does the pump check for when trying to pump fluids?

**Comment by AlexIIL** [comment]
FluidUtil.getFluidHandler -- forge class + methods

**Comment by AlexIIL** [comment]
Although we might not be registering it correctly...

**Comment by Ushupiuck** [comment]
Galacticraft oil is also affected...

**Comment by KingLemming** [comment]
I had a feeling this was happening. This is specifically why I called my fluid crude_oil. ;)

I'd maybe recommend changing the names of AA's oils. Potentially:

canola_oil
refined_canola_oil
crystal_canola_oil
empowered_canola oil

and that'll solve all the issues outright, except mods adding compatibility will have to update their references. (I'm doing it, and wouldn't mind though.)

**Comment by AlexIIL** [comment]
The whole point of fluids sharing names is to allow different mods to allow the same fluid, but from different mods to work as if they were the same though? Changing the names of fluids to be different won't solve that...

**Comment by Ellpeck** [comment]
It solves this issue though, so it's what I'm going with.

**Comment by Ellpeck** [comment]
Apparently this is all @AEnterprise's fault, so I'm not renaming the oils after all. It's just more convenient to keep it the way it is.
