### ISSUE TITLE
Coffee Maker not working?

### ISSUE THREAD

**Issue by Liliturra** [Ellpeck/ActuallyAdditions#815]
Using FTB Beyond 1.8.1 running Minecraft 1.10.2.  Made coffee maker, it's full of beans, water and power.  Put coffee cups in correct slot.  I've put all sorts of different combos of items in the right hand slots though and when I click OK nothing happens.  I get the "you pressed a button" clicking noise and then nothing.  I've tried multiple combos of gold carrots, sugar, magma creams and milk and even when I just put one of any one thing in, it doesn't do anything.  Please help, this is driving me crazy.

**Comment by Ellpeck** [comment]
Reconnect and try again, also show me your setup and the GUI.

**Comment by Liliturra** [comment]
Ack, sorry I didn't get back quickly, life got crazy.  I still have no idea why but when I went to try it the next day, it worked fine and has continued to work since.  No clue why it didn't work at first or why it then worked later.  Thank you for responding though.
