### ISSUE TITLE
Lamps don't turn on with right click

### ISSUE THREAD

**Issue by tofof** [Ellpeck/ActuallyAdditions#816]
Documentation says lamps turn on from right clicking with an empty hand.
Reality is that you shift+rightclick with an empty hand.

Please align the two.

**Comment by Shadows-of-Fire** [comment]
This issue is either very old or invalid 
![image](https://user-images.githubusercontent.com/3682588/27976174-5aa69a1c-6333-11e7-8b60-f8f5c2c21c50.png)
Unless it specifies to not shift-right-click somewhere else

**Comment by tofof** [comment]
Appears in 1.10.2-r105

**Comment by Shadows-of-Fire** [comment]
So, `very old`
