### ISSUE TITLE
Lamps won't turn on when clicking with a item in offhand

### ISSUE THREAD

**Issue by Eufranio** [Ellpeck/ActuallyAdditions#819]
I think it would be nice to turn the lamps on when we have a item in offhand, but the main hand empty (as it should be).

**Comment by canitzp** [comment]
I wonder why this is closed. I use the latest version 1.12.2-r124 and this bug does still appear.

**Comment by Shadows-of-Fire** [comment]
Removing the sneak criteria from toggling lamps due to forge changes.
