### ISSUE TITLE
Crash in 1.12 with your mod

### ISSUE THREAD

**Issue by Migmag789** [Ellpeck/ActuallyAdditions#822]
Actually Additions crashed :/
[crash-2017-06-29_12.08.12-client.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1111619/crash-2017-06-29_12.08.12-client.txt)

**Comment by Ellpeck** [comment]
It doesn't look like this issue is caused by Actually Additions.
Paging @TehNut though.

**Comment by Migmag789** [comment]
New crash, after deleting many mods listed on "errored" : 
https://pastebin.com/ke2bK0Jv

**Comment by Ellpeck** [comment]
Yea there we go, now it's a duplicate of #820 which is a duplicate of #811.
Nice.

**Comment by TehNut** [comment]
Yeah that first one has already been reported to me, I just haven't gotten a chance to fix it.
