### ISSUE TITLE
[Suggestion] [1.10/1.10+] Add new tool and upgrade module. 

### ISSUE THREAD

**Issue by CrossVas** [Ellpeck/ActuallyAdditions#824]
Hey!
What you think about a saw, similar to IC2 Saw, but powered by RF-energy? 
By default saw can be used like a sword. I think it will be great to add some upgrade module (like upgrade for Drill):
     - **_Axe Upgrade Module_** (give ability to break wooden items/blocks)
     - **_Shears Upgrade Module_** (can take some wool from sheep, leaves from tree & grass)
     - Efficiency Upgrade, etc. 

Another one suggested thing is **_TorchPlace Upgrade Module_** for Drill (that place torch when right-click with drill on the block). 
What's the difference of  **_Placer Upgrade Module_** and **_TorchPlace Upgrade Module_**?
 - **_Placer Upgrade Module_** can place block (and torch as well) only from player's Hotbar.
 - **_TorchPlace Upgrade Module_** can place torch from player's inventory (any slots)
 
Why add **_TorchPlace Upgrade Module_** when we have Player Left Hand?
Because when we hold Torch in Left Hand and do right-click on block, some mechanics from other mods  works incorrectly or don't work at all (ex. **_ProjectRed' gate_** or **_SuperCircuitMaker_**)

Thanks!

P.S. I know all of this content we can get with IC2, but i love all RF-based mods.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
