### ISSUE TITLE
using latest forge doesnt work (14.21.1.2387)

### ISSUE THREAD

**Issue by nmwael** [Ellpeck/ActuallyAdditions#827]
It crashes onload:
[crash-2017-06-30_17.50.29-client.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1116386/crash-2017-06-30_17.50.29-client.txt)

added complete crash, instead of the stack trace.

**Comment by canitzp** [comment]
Please post the complete crash report, instead of the end of the log file

**Comment by Morphyloon** [comment]
I'm also seeing the same error in Forge versions *.2380 through *.2387

Currently testing with *.2387 in the latest report below

[fml-client-latest.log.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1116775/fml-client-latest.log.txt)

**Comment by Ellpeck** [comment]
Remove OptiFine and try again.

**Comment by Morphyloon** [comment]
Optifine was the culprit. Alas, version *.C3 also results in the same error halfway through the mod loading process.

On a side note, Just Enough Buttons also crashes but right after everything has loaded.

**Comment by nmwael** [comment]
I can confirm actually additions works on clean 1.12 with latest forge.. Thanks for help:)
