### ISSUE TITLE
1.10.2-r105: At server startup, Actually Additions causes server to run at < 0.5 TPS

### ISSUE THREAD

**Issue by JaSpr** [Ellpeck/ActuallyAdditions#830]
We're running All the Mods 1 v3.00b.  Whenever the server restarts (every few hours) Actually Additions attempts to do something with all of the registered dimensions.  Since ATM includes Advanced Rocketry, this ends up being a lot of dimensions.  For a period of about 2 minutes, nothing can be done on the server, and all users who are connected get timed out.

```
[21:49:40] [Server thread/TRACE] [ArsMagica2/]: Saving all cached power data for DIM 1055 to disk
[21:49:40] [Server thread/INFO] [Actually Additions/]: Unloading WorldData for world 1055!
[21:49:40] [Server thread/ERROR] [Actually Additions/]: Tried to save WorldData for 1055 without any data handler being present!?
[21:49:40] [Server thread/INFO] [Sponge/]: Unloading world [advRocketry/DIM1055] (DIM1055)
```

**Comment by Ellpeck** [comment]
The log message you are sending definitely does not cause any lag. Because there isn't even a data handler present, the method that is called in that place does absolutely nothing. It just checks "Do I have data? Oh, no I don't. Okay."
Remove Actually Additions and see if the issue persists.

**Comment by JaSpr** [comment]
Actually, yeah, I don't believe AA is *causing* it, but AA is involved in the logging.  It's an production ATm server, so I can't just remove one of the mods without interfering with the players.

**Comment by Ellpeck** [comment]
If you also don't believe it's causing it, then I'm closing this issue for now. Just reopen it when you notice that it's in fact AA's fault.
