### ISSUE TITLE
1.12 Water bowls spilling from player inventory while walking

### ISSUE THREAD

**Issue by DingoX3** [Ellpeck/ActuallyAdditions#831]
I noticed you had a commit 16 days ago for not spilling while standing but it looks like its doing while the player is walking now.

gify video: http://imgur.com/25rDlXE

mc: 1.12
AA: 1.12-r113
modpack: All The Mods 3
forge: 2387

**Comment by YasminEndusa** [comment]
This is wanted. As you can see in #785 you have to sneak, or else the bowl will spill.

**Comment by DingoX3** [comment]
Thank you. Did not even see that :)
