### ISSUE TITLE
[1.11.2] Item description bug

### ISSUE THREAD

**Issue by Endmateria** [Ellpeck/ActuallyAdditions#834]
Hey Ellpeck, I'm just gonna forward this issue to you... https://github.com/Vazkii/Quark/issues/417 I originally noticed the problem when installing your mod alongside Quark, but apparently any mod that adds content to the tooltip render box will most likely cause the same overlapping effect.  https://ibb.co/inUvVk  I noticed it in 1.11.2, but it probably affects all versions of your mod.

**Comment by Ellpeck** [comment]
I don't add any content to the tooltip render in that image though?

**Comment by Ellpeck** [comment]
This seems like a non-Actually Additions bug, because as @Vazkii explained, `The issue is the mod that calls the tooltip render, not the mod that provides the contents`, which Actually Additions doesn't do.

**Comment by Endmateria** [comment]
I don't know, I'm no expert on this stuff, just forwarding the info.  It happens when only AA and Quark are installed (any versions)... and apparently nobody wants to claim responsibility for it hahaha.

**Comment by Ellpeck** [comment]
JEI is the mod that displays the blue name of the mod at the bottom of the tooltip, so it's probably JEI.

**Comment by Endmateria** [comment]
Yeah, I guess I never thought of that obvious possibility...  I'll send this issue their way.  Thanks.
