### ISSUE TITLE
Vertical Digger doesn't post HarvestDropsEvent

### ISSUE THREAD

**Issue by DemoXinMC** [Ellpeck/ActuallyAdditions#84]
This is problematic for mods that alter drops.

Additionally, it's probably prudent that the drops be checked for CONTAINING "ore" rather than requiring the block itself STARTING WITH "ore" as this likely will also cause problems with mods such as DenseOres

**Comment by trentv4** [comment]
We had a bug report related to this over at Glenn's Gases, I believe. [The Jira entry is here.](https://bitbucket.org/jamieswhiteshirt/glenns-gases/issues/37/no-gas-created-when-breaking-coal-with)

**Comment by Ellpeck** [comment]
The bug you mentioned is about the Drill, not the Vertical Digger. That, however, posts the mentioned event by default.

**Comment by trentv4** [comment]
Might be an old version or bug, then. I'll test it later.

**Comment by Ellpeck** [comment]
Closed by https://github.com/Ellpeck/ActuallyAdditions/commit/a8365724f85dff338baa8119db61f99aff3509b5
