### ISSUE TITLE
[1.10.2-r105]Fluid Laser Relay wont extract from Tinkers Tank

### ISSUE THREAD

**Issue by kingchills** [Ellpeck/ActuallyAdditions#846]
Versions: 
- Forge: 12.18.3.2316 (Minecraft 1.10.2)
- Actually Additions: 1.10.2-r105
- Tinkers Construct: 1.10.2-2.6.5

Description of Problem: I was looking to do some bulk storage of the different stages of oil, and I thought a Tinker's tank would be a great, easily expandable storage solution.  I am using Fluid Laser Relays to extract from the Canola Press, and insert into a tank, but I cannot get the Fluid Laser Relays to extract from the tank into the fermenter for the next stage.  Using a compass I have toggled the modes to make it as one way as possible to not confuse the situation, I have also tried leaving everything on default 'both ways'.  My original attempt was in the Age of Engineering Modpack, and I tested again in a world only utilizing Tinkers Construct, Actually Additions, and NEI.  Am I doing something wrong or is this not working the way it should?

Steps to Reproduce:

1. Create one complete tinkers tank, with a controller and a drain.
2. Set up a Fermenter.
3. Add a relay to the tank drain, and one on the fermenter.
4. Add some Canola oil to the tinkers tank.
5. Connect the laser from canola oil tank, to the fermenter.
6. Observe no canola oil is entering the fermenter.
7. Using a compass adjust the relay on the tank to extract from adjacent blocks, and adjust the relay on the fermenter to insert to adjacent blocks.
8. Observe no canola oil is entering the fermenter.

**Comment by kingchills** [comment]
Does that mean there's a fix incoming, or that this wasn't actually a bug, and I'm doing something wrong?

**Comment by Shadows-of-Fire** [comment]
It means reproduce it on 1.12, and I'll look at it later.  I'm not working on 1.10

**Comment by kingchills** [comment]
Fair enough, thanks!
