### ISSUE TITLE
[1.8.9] Repairer does not work with Tinkers' Construct

### ISSUE THREAD

**Issue by F4ndroid** [Ellpeck/ActuallyAdditions#85]
Works otherwise but will not repair TiCon tools.

**Comment by Ellpeck** [comment]
TiCon tools work differently.
But repairing them like this doesn't make a whole lot of sense anyways because you can just add moss or a battery. So it's fine.

**Comment by F4ndroid** [comment]
Not in TiCon 2. Only way to get repair is to use wood. It's more of a quality of life thing to have this feature.

**Comment by Ellpeck** [comment]
Oh, well. Then never mind.
