### ISSUE TITLE
[Request] Allow crates use the Quark sort, export, import features.

### ISSUE THREAD

**Issue by winsrp** [Ellpeck/ActuallyAdditions#858]
well, quark mod has this great feature to import export or sort items, really handy, but your crates don't support that so I never use them, but they do have a ton of space so it would be great to have this features to sort import and extract on your crates too!!

thanks for giving us a great mod!!

**Comment by Shadows-of-Fire** [comment]
I literally cannot get this to work

**Comment by Shadows-of-Fire** [comment]
Quark doesnt work with IItemHandler and IInventory is stupid so this can't happen rip

**Comment by WenXin20** [comment]
Is this something that can now be added, or is it still incompatible?
