### ISSUE TITLE
ActuallyAdditions causes mangled TC5 graphics in FTB Unstable

### ISSUE THREAD

**Issue by charlesbevans** [Ellpeck/ActuallyAdditions#86]
I added ActuallyAdditions 1.8.9-r26 to FTB Unstable 3.0.42 (for MC 1.8.9) and most of Thaumcraft 5's item graphics became squares of randomly colored static, as if the system had used the wrong bit of data for the graphics.

**Comment by Ellpeck** [comment]
Please describe it more specifically.
Did you use JEI? What things were mangled when looking at what? Did you have anything else around from any mod that rendered in any specific way?

**Comment by charlesbevans** [comment]
I'm using the JEI that comes in the pack (2.28.7.174). I'm putting in a shot of JEI and of the view of the Thaumcraft research table. Everything looked normal prior to adding AA, and has remained like this after multiple restarts (SSP world, no separate server).
The only graphical problems I found were in Thaumcraft, except for one of the two Thaumic Infusion items.
![2016-04-25_08 09 43](https://cloud.githubusercontent.com/assets/15851438/14788714/11843e76-0abe-11e6-8ea6-6c4d7a80a420.png)
![2016-04-25_08 11 59](https://cloud.githubusercontent.com/assets/15851438/14788716/1621dca4-0abe-11e6-97ac-085a9ad88e69.png)

**Comment by charlesbevans** [comment]
I've discovered that Quantum Flux has the same effect. I've notified Azanor and joekaiser in the hopes this can be more easily resolved.

**Comment by Ellpeck** [comment]
Did you get any new information on this?

**Comment by charlesbevans** [comment]
Azanor said it was a mod pack issue and closed it. I tried a custom pack with just TC5 and a couple of others and didn't have the same problem. joekaiser gave me some good information though. F3+s reloads the texture pack, which fixes the graphic until the game is reloaded.
