### ISSUE TITLE
Farmer suggestion: Plant back what was harvested and seed slot lookup in 2nd place

### ISSUE THREAD

**Issue by Knito58** [Ellpeck/ActuallyAdditions#860]
In 1.12-r116 Shadow made the farmer replant the crop instantly. Now that is a super move in my eyes as it speeds up farming remarkably. And one more:

Now the farm could be a true multi-crop-farm which respects what was planted by simply taking the seed (or crop) from the harvested plant when replanting instead of checking the internal seed slots. Only if the harvested crop doesn't throw a seed then it should look for seeds in the internal slots.

This would allow to have all the vanilla plants in one field. Atm the farmer tends to plant what is in the first slot and so cleans out the field to be a monoculture finally.

I read the comments and Ellpeck doesn't like this idea, because the farmer is thought to be a one-crop-farmer. But it really can do more. It doesn't crash or anything when plants are mixed. I always have one of the coal-fields with one row of soulsand and netherwart. There the farmer cannot clean the mixture and it works just fine. Would be great if I could make a field with flax, rice, potatoes, wheat, beetroot and carrots. Also the mixture of melons and pumkins in one field already worked just fine in older versions.

I hope you'll do this. From my view there's not missing very much...

Greetings, Konitor

**Comment by Ellpeck** [comment]
The farmer isn't supposed to work with multiple crops at once.

**Comment by Knito58** [comment]
Short cut.
