### ISSUE TITLE
Extract seed not used on the Farmer

### ISSUE THREAD

**Issue by BenjaminCo** [Ellpeck/ActuallyAdditions#863]
I encoutered a little problem on my full automated empowered oil maker.
The fact that i can't get the cannola seeds not used out of my farmer.
It would be great to add a button on GUI of the farmer to put the seeds not used on the output slots.

Technically after a full check of the field to see if there is no empty blocks where to plant then transfer seed on the input slots to output slots.

**Comment by leasoncre** [comment]
I'm having an issue similar to this as well, 
I'm farming Mystical Agriculture, Actually Additions and VanillaMC crops. (with multiple fields, 6 crop types per field)
++I LIKE that the Mystical Agriculture stuff i put in worked as intended. (I put 13 of a different seed in each of the 6 slots, and it planted all of them (with a few empty tiles, w/e), But it looks like MA doesn't produce random seeds, so the planter isn't getting any new seeds to plant)
--I DON'T like that if i set the farmer with 13 seeds/crops in 6 slots, as soon as new seeds enter the farmer it REPLACES any crop already planted in the field.
>>I think and/or expected it to be smarter and only plant NEW/Empty tiles with new seeds, and _not simply replace the entire field_ with w/e seed is in the first slot. (Similar to how EnderIO's farmer works, though EnderIO isn't available in 1.12.2 yet :/ )

[[AllTheMods3,MC1.12.2,Forge-14.23.0.2517,Singleplayer]]
Love the mod!

**Comment by Quarris** [comment]
As Ellpeck said in other posts, "The farmer isn't supposed to work with multiple crops at once." which is what I believe the issue would be. Also this mod isn't developed anymore, it is only being maintained and I believe will only have bug fixes.

**Comment by Shadows-of-Fire** [comment]
The farmer doesnt track what is planted where.  It just plants.  This discussion should not be continued on this issue, as it is not relevant to it.
