### ISSUE TITLE
Farmer destroys sugar cane

### ISSUE THREAD

**Issue by Knito58** [Ellpeck/ActuallyAdditions#866]
MC 1.12
Forge 14.21.1.2420
AA 1.12-r116
Mode SSP

I've already done some sugar cane farms in previous versions and they were all fine. Now this one never delivered any sugar cane to the target chest although I saw it harvesting. I first blamed xnet for this and to verify it I deleted the xnet connector which left the farmer with full energy - enough for the test. 

The farmer destroys a sugar cane which is grown into the second stage. But it is not delivered to any side of its inventories. It is just gone. The inventory of the farmer staying empty.

![Farmer inventory stays empty](https://www.dropbox.com/s/9k3uj4zvqswimgq/2017-07-26_184558.jpg?dl=1)

**Comment by xenxero1** [comment]
Why was this closed?

**Comment by JonathanxD** [comment]
Because was fixed in d5902dee86e65de2fab8d99c10af5d6d1fe72903

**Comment by Knito58** [comment]
AA 1.12-r.117

Yay! Works again!
Thank you.
