### ISSUE TITLE
Coffee Machine Eats Buckets of Milk

### ISSUE THREAD

**Issue by EarthwormO** [Ellpeck/ActuallyAdditions#869]
1.10.2, but cannot see anywhere it was fixed in newer version.

Brew coffee with config, 2 sugar, Bucket of Milk to get Speed 1 for longer duration, and the coffee machine eats the bucket itself and doesn't return it.  Tried many configurations, all buckets of milk disappear after Coffee brewed, should get empty bucket back.  Tried using Can's of milk from Forestry and IC2 Universal Fluid Cells, to see if cheaper containers would work, but the Coffee Machine does not recognize these.  Need to get Bucket back, or be able to use cheaper Milk container for coffee machine to be worth it.

**Comment by Shadows-of-Fire** [comment]
Cannot reproduce (1.12)
