### ISSUE TITLE
1.9-Client crash when filling vanilla bucket

### ISSUE THREAD

**Issue by RealGrep** [Ellpeck/ActuallyAdditions#87]
Unable to fill a bucket with water (sort of puts a crimp on things). Try and fill the bucket from a water source, and get this on the client side:

java.lang.NullPointerException: Unexpected error
	at de.ellpeck.actuallyadditions.mod.event.BucketFillEvent.fillBucket(BucketFillEvent.java:33)

Log from the point of the problem: http://pastebin.com/mBfy4WQ5

This is with ActuallyAdditions-1.9-r27.jar and forge version 1867.

Thanks! P.S. Love the mod.

**Comment by Ellpeck** [comment]
Closed by https://github.com/Ellpeck/ActuallyAdditions/commit/e267d0110d53aa538b1012bb2ddd1cf7aec24429

**Comment by RealGrep** [comment]
Thank you very much for that quick response. :)
