### ISSUE TITLE
Engineer House 1.12

### ISSUE THREAD

**Issue by Larky2k** [Ellpeck/ActuallyAdditions#870]
Testing out a 1.12 pack on a server and everyone testing came to the conclusion that the spawn rate of the Engineer house is to high for what you get in it. 
Would there be any chance down the line to add another Variable into the spawning that allows you change the weight of the spawn so instead of it being 1/1 so if you want change it to 1/12 so it only spawns in 1 in every 12 villages. 

Regards Larky2k

**Comment by Ellpeck** [comment]
I don't understand why people think this. You can't take the stuff in the house with you, so you have to base in there. It's a good compromise and a great way to make people actually make use of villages instead of just raiding and then ignoring them.

**Comment by Larky2k** [comment]
Oh ok we didn't realise if you tried breaking it broke. just tested it out. we only thought this as we where flying around exploring to see what the spawn rate was. We thought you could raid loads of villages get to endgame quickly.
