### ISSUE TITLE
[Suggestion] Config options to COMPLETELY disable tools / weapons individually

### ISSUE THREAD

**Issue by oitsjustjose** [Ellpeck/ActuallyAdditions#872]
Just something a lot of Ellpeck's friends have talked with me about, and we all agree that we'd love ways to get rid of the bloat of extra armor and tools added by AA. It's a great mod, but we don't install it for _that_ in particular..

**Comment by Ellpeck** [comment]
Blaaaaaaaaaaaaaaaaargh.png

**Comment by nmarshall23** [comment]
I have a question would you accept a pull request with this feature?

**Comment by Shadows-of-Fire** [comment]
why would i accept a pr of an implemented feature

**Comment by nmarshall23** [comment]
Oh, sorry about that, I didn't see the config option.
