### ISSUE TITLE
[Suggestion] Baubles compatibility

### ISSUE THREAD

**Issue by oitsjustjose** [Ellpeck/ActuallyAdditions#873]
Me again. Told you I'd spam the GitHub with requests!

This is it for today. Basically, I'd love to see [this](https://github.com/Jacky1356400/ActuallyBaubles) be part of native AA. I think it should be, to be honest, and the Baubles API isn't too terribly difficult to interface with. I hate having so many "mod that makes another mod bearable" mods in a pack, it just adds more headache overall (referring to Angel Rings to Baubles, Actually Baubles, etc).

Alright. /spam

**Comment by Shadows-of-Fire** [comment]
@Jacky1356400 I might be making your mod obsolete :p

**Comment by Jacky1356400** [comment]
What? After I've spent 3 days on a new mod and becomes completely useless afterwards?

**Comment by Shadows-of-Fire** [comment]
I said might. I don't *have* to, but I'm being asked to

**Comment by Jacky1356400** [comment]
I mean, it's really up to Ellpeck since it's his mod. But if this actually becomes a thing, would also means I've wasted my time for nothing.

**Comment by oitsjustjose** [comment]
Unless you made a PR with all your excellent hard work added, and perhaps became a contributor to the project? Again, not my mod either, but just my two cents.

**Comment by bogger33** [comment]
think of it as having triggered a change for the better

or something

**Comment by bogger33** [comment]
@ellpeck just out of curiosity, why don't you like baubles?

**Comment by p455w0rd** [comment]
I've talked with Shadows about this...seeing that this issue is still open makes me question his character...

**Comment by Ellpeck** [comment]
Okay how about this:
Overruled.
No Baubles.
