### ISSUE TITLE
Redstone Flux and Crystal Flux might have compatibility issues on Forge server.

### ISSUE THREAD

**Issue by zzApotheosis** [Ellpeck/ActuallyAdditions#876]
# Information
Java Version 8 Update 141 (build 1.8.0_141-b15)
Minecraft 1.12
MCP 9.40
Forge 14.21.1.2443 (Client and Server)
OptiFine_1.12_HD_U_C5_pre
RedstoneFlux-1.12-2.0.1.2-universal

# Problem
It seems as though standard Redstone Flux (RF) generating machines like dynamos do not play nice with Crystal Flux (CF) consuming machines from Actually Additions. However, this problem only happens on a Forge server, as it works fine on single player.

Here's a 5 minute video demonstration of the problem: https://drive.google.com/open?id=0B_wljXPJi507N3dlTVkxMW5LdVk

**Comment by Shadows-of-Fire** [comment]
Invalid. That dynamo is literally not on.  It will not transmit when not on, regardless of side.  Also, for the record, CF == FE,  its just renamed.

**Comment by zzApotheosis** [comment]
I'm fairly certain the problem persists. https://drive.google.com/open?id=0B_wljXPJi507XzBaY3dTd3N0ZFk
