### ISSUE TITLE
Registry Block: Found a missing id from the world actuallyadditions:block_oil

### ISSUE THREAD

**Issue by Cyancraft** [Ellpeck/ActuallyAdditions#877]
Title, basically. It's preventing people from logging into a server with this mod on it.

The above error message comes up right after preparing level 'world' and before applying holder lookups

**Comment by canitzp** [comment]
If a registry entry is missing, no matter which reason, then at world load it should show a message no matter if client or server with two buttons for client or a command to type into the console for server
