### ISSUE TITLE
Nethercoal from BetterWithMods is being made from grinding coal ore or coal block with AA Crusher

### ISSUE THREAD

**Issue by ToadStar** [Ellpeck/ActuallyAdditions#878]
See title, happens in the latest version of BWM (Version 2.0.2 for 1.12) and AA (Version r117, also for 1.12), using the Crusher from AA causes the coal ore block to produce 3 nethercoal ore and crushing a normal coal block from minecraft causes the crusher to output 9 nethercoal instead of 9 normal coal, probably an oredict issue.

**Comment by primetoxinz** [comment]
This is due to checking the last item in the oredictionary rather than the first.
