### ISSUE TITLE
[Suggestion] Comparator support for the Atomic Reconstructor

### ISSUE THREAD

**Issue by KaseiFR** [Ellpeck/ActuallyAdditions#881]
Hi,

Could you allow comparators to read the energy stored in an Atomic Reconstructor? It would slightly ease its automation, to throttle it if it doesn't have enough power. As a workaround, I had to put a dedicated IE capacitor next to it and use it to get an energy reading.

Thanks.

Actually Additions 1.10.2-r105

**Comment by KaseiFR** [comment]
Does the `getEnergy()` method use a different scaling? Because I may be wrong but the reconstructor has a 300kRF buffer, not 20000.
Also, [IE](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityCapacitorLV.java#L53) seems to use a way to update comparators without block updates (or maybe a block update behind the curtain, but only on comparator changes).

**Comment by Shadows-of-Fire** [comment]
getEnergy() / 20000 results in output lv 15 at max capacity, and I'll go look at that world method
