### ISSUE TITLE
storage crate dupe bug when use with refined storage buses

### ISSUE THREAD

**Issue by CatAndHorse** [Ellpeck/ActuallyAdditions#883]
https://github.com/raoulvdberge/refinedstorage/issues/1407#issuecomment-321193102

this happens with storage crate from AA too.

aa ver 1.12 r117
rs ver 1.12 1.5.13

**Comment by Shadows-of-Fire** [comment]
I cannot find evidence this is on AA's end whatsoever through various tests. As such, I am declaring this a RS issue.
