### ISSUE TITLE
The Jam Zombie

### ISSUE THREAD

**Issue by AugiteSoul** [Ellpeck/ActuallyAdditions#884]
Texture is glitchy.
![2017-08-09_14 20 14](https://user-images.githubusercontent.com/16467639/29179923-550641ce-7df6-11e7-9775-b84a9fbd09ba.png)

**Comment by Shadows-of-Fire** [comment]
https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/resources/assets/actuallyadditions/textures/entity/villager/jam_villager_zombie.png
(Texture file, for reference, if anyone who knows how to art cares)

**Comment by Shadows-of-Fire** [comment]
@InsomniaKitten do stuff pls thx

**Comment by thiakil** [comment]
![jam_villager_zombie](https://user-images.githubusercontent.com/1788847/29596378-6ff543c4-87ef-11e7-9574-0630070920a5.png)

How bout da'? Literally just added the missing bit from the vanilla zombie villager
