### ISSUE TITLE
[1.12] Worlds never finish loading

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Ellpeck/ActuallyAdditions#887]
everytime i try to make a new world it stops at
`
Actually Additions | main | info | Unloaded WorldData!
`

it never goes beyond this, so i had to uninstall AA, and reinstall it after creating the world

**Comment by Shadows-of-Fire** [comment]
So you can actually be useful and provide me a `fml-client-latest.log` but either way this isn't AA's fault so rip this issue

**Comment by ProxyPlayerHD** [comment]
the log ends there, there is nothing more that could be useful... and what causes it then? it only mentions AA

**Comment by Shadows-of-Fire** [comment]
Whatever it is, its not AA.  It can't be reproduced with just AA.

**Comment by ProxyPlayerHD** [comment]
i cannot reproduce it either, this is VERY strange.

imma get back to it if it ever reappears
