### ISSUE TITLE
[1.12] Idea - Option to allow Rings to use RF

### ISSUE THREAD

**Issue by llloyd4** [Ellpeck/ActuallyAdditions#888]
To be frank, I've not used the rings in 1.12, just 1.10.2, I see in the tool tip it needs blazes (says 0/100 Blaze), and I don't see an option in the settings to return it to 1.10.2 RF usage instead. So, perhaps, please?, an option so we can choose weather or not to use Blaze or RF for the rings?

**Comment by Shadows-of-Fire** [comment]
yeah but rf is lame

**Comment by llloyd4** [comment]
Ok, what about, oh, coal coke? It's slow to produce so there is a finite limit to it. Actually, thinking on it, I don't have any on hand, it's been all going into steel production. O.o
