### ISSUE TITLE
[1.10.2] Server crash while generating RFtools Dimension at de.ellpeck.actuallyadditions.mod.tile.TileEntityBase.<init>(TileEntityBase.java:48)

### ISSUE THREAD

**Issue by JonoColwell** [Ellpeck/ActuallyAdditions#889]
Attempted to generate RFTools Dimension, had done this successfully not five minutes before. Got a massive crash report which basically claims it''s something to do with actually additions.

https://pastebin.com/fjdJMrVi

**Comment by Shadows-of-Fire** [comment]
This is technically due to how vanilla handles redstone... and it does it badly.
This issue will be random and there's not a whole lot to be done about it
