### ISSUE TITLE
[Suggestion] Simple machine to plant trees

### ISSUE THREAD

**Issue by winsrp** [Ellpeck/ActuallyAdditions#893]
As simple as it says, put a tree planter block, put some tree saplings in it, and it places saplings in a 5x5 around it, put some phantom range upgrades, go to 7x7, 9x9 and 11x11, no need to break the trees. It could even be an upgrade for the item placer, which already plants saplings but only one space in front which makes very hard to use for this, specially with other mods that require 2x2 arranges for bigger trees..

To make it even easier, it could be like farmer, where it has an area in front of it, predefined no upgrades needed, an it checks one tile at a time, but instead of tilting land, and placing and gathering crops, it just places a sapling if there is a free space.

This would make a huge addition to this mod. If you want to make it super super useful make it chop the tree but to be honest there are other machines that could that from other mods, or even your own mod, like the ranged breaker.

Thanks for such a great mod.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
