### ISSUE TITLE
[1.12] Possible AA Crash?

### ISSUE THREAD

**Issue by MokahTGS** [Ellpeck/ActuallyAdditions#894]
Got a weird crash with AA named in the log, but I'm not sure what caused it.

https://pastebin.com/xyH9qMVD

**Comment by Shadows-of-Fire** [comment]
This issue belongs to the ConnectedTexturesMod (I think).
The only reason AA is in the stacktrace is because you have an AA gui open

**Comment by Shadows-of-Fire** [comment]
It was also fixed about right now so don't bother reporting to to them
