### ISSUE TITLE
advanced item laser relay filter blacklist is not working with oredic

### ISSUE THREAD

**Issue by killmetohell** [Ellpeck/ActuallyAdditions#895]
I'm playing on mc 1.10.2 using r105 for actuallyadditions and i'm playing on modpack sky factory 3.
I don't know if you fix this bug for later version or could be my game but when using blacklist for oredictionary it doesn't seem to work i don't if is applies to whitelist but thought should let you know about this bug and do you know why is this happening.
![2017-08-16_19 03 59](https://user-images.githubusercontent.com/11909414/29392987-201f58c8-82b6-11e7-8881-40c9e264a462.png)
![2017-08-16_19 04 07](https://user-images.githubusercontent.com/11909414/29392988-202fd446-82b6-11e7-824f-59096657dae6.png)

hope these help a bit

**Comment by Shadows-of-Fire** [comment]
will check if issue persists on 1.12

**Comment by Shadows-of-Fire** [comment]
Cannot reproduce

**Comment by killmetohell** [comment]
oh well i did a little testing with diffrent  item transfer system that can use oredic and it didn't work i guess some reason its modpack or ore dict didn't like what mystical agri did with it oredics
