### ISSUE TITLE
broke atomic reconstructor ghost lazer still goes off

### ISSUE THREAD

**Issue by codydbgt** [Ellpeck/ActuallyAdditions#899]
![2017-08-17_22 59 10](https://user-images.githubusercontent.com/1176479/29442597-9c324c78-83a0-11e7-8058-b2aebe58ba3f.png)

i had a mekanism cable hooked to it so i don't know if that matters

using latest forge for 1.11 and latest version for the mod for 1.11

we try to test it on some block and it works but when dropped redstone it fixed it self

**Comment by Shadows-of-Fire** [comment]
1.11 is not supported

**Comment by codydbgt** [comment]
do u plan on updating this mod in the future? to 1.13 +

**Comment by canitzp** [comment]
I reopened it cause he said that it happens in 1.12 too. Hace fun shadow

**Comment by Shadows-of-Fire** [comment]
Cannot reproduce at all.
