### ISSUE TITLE
"Ring of Growth"-Bug [GER]

### ISSUE THREAD

**Issue by MineLoad** [Ellpeck/ActuallyAdditions#9]
Fehler-Bericht vom 12.08.2015
Als ich Minecraft mit dem Mod "Actually Additions" benutzte, wollte ich die neuen Ringe von dessen Mod testen. Somit pflanzte ich ein paar Seeds - diese wuchsen auch durch den "Ring of Growth" schneller. Als ich allerdings einen Sapling gepflanzt hab', bekam er anscheinend keine Wirkung ab - er wuchs nicht schneller. Da ich dieses Geschehen komisch fand, hab' ich "Ellpeck" auf Twitter angeschrieben - kurz darauf hab' ich Minecraft neugestartet. Als ich die Welt erneut betrat, und als ich den Ring wieder in der Hand hatte, funktionierte es wieder - die Saplings wuchsen durch den "Ring of Growth" wieder schneller, und die Seeds wuchsen immer noch schneller als die "normale Minecraft-Geschwindigkeit".
Ich hoff', dass das alle nötigen Informationen waren
~MineLoad

**Comment by Ellpeck** [comment]
Couldn't reproduce. Tested several times. Just bad luck, I hope.
