### ISSUE TITLE
[suggestion] Peanuts, AKA growable gunpowder

### ISSUE THREAD

**Issue by Umber0010** [Ellpeck/ActuallyAdditions#900]
Why no, that title wasn't clickbait

My suggestion is a new utility crop to join the ranks of rice and canola

Peanuts would have 3 main uses, First they can be eaten like the old natura berries, not a lot of hunger points gained but are consumed really fast. second, they can be put into a crusher to make peanut butter which can also be eaten or spread on toast. but the REAL fun comes in with use number 3. blasting (pun not intended) the peanuts with an atomic reconstructer to convert them into a blob of Nitroglycerin. no, really, you can literally turn peanuts into high-power explosives with the right procedures.
http://www.wisegeek.com/what-unusual-product-can-be-made-with-peanut-oil.htm
but anyways, Nitroglycerin would simply be our-dictionaried with gunpowder. because for some reason gunpowder is quite hard to automate, at least In my experience.

but if you wanted to go a step further, you could add empowered Nitroglycerin, which could be used to make powerful explosives such as nukes, only without the nuclear materials. or you could add bananas and make those the nuclear materials. probably not but it would be funny.

**Comment by xenxero1** [comment]
Definitely seems right in line with the mod, I don't see why not. Other than the effort of actually adding all of this in.

**Comment by Shadows-of-Fire** [comment]
Okay but like... things need textures, i'm not even close to an artist

**Comment by xenxero1** [comment]
Since _Elucent is taking a hiatus from the modding community, I hear the artists in his embers+ discord channel have had some extra time. Maybe bring it up to them?

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
