### ISSUE TITLE
Add Embers Quartz Ore to the mining lens

### ISSUE THREAD

**Issue by KaseiFR** [Ellpeck/ActuallyAdditions#901]
Hi,

I suggest to add Embers Quartz Ore to the loot table of mining lens.  

While I'm at it, I find the Black Quartz drop rate a little too high, because you need very few of it, and a way to blacklist (for players, not from the config) some mods from the loot table would be nice: the more modded ores (like gems from BOP), the rarer vanilla (like redstone) ores get. If you're interested I can open new issues :)

Thanks

**Comment by Shadows-of-Fire** [comment]
Quartz ore and Embers quartz use the same tag (`oreQuartz`) and the lens works by oredict, so this cannot be done without adding nether quartz to the normal roll table, which would be stupid.
