### ISSUE TITLE
The crusher is literally on fire pls fix it self thx

### ISSUE THREAD

**Issue by kwpugh** [Ellpeck/ActuallyAdditions#904]
Forge: 2459
Mod: ActuallyAdditions-1.12-r118.jar

Crash report: https://gist.github.com/kwpugh/5290f28df4046a3837313c8c4a09bb66

**Comment by Shadows-of-Fire** [comment]
I'm gonna just leave this here; this jar fixes said crash https://cdn.discordapp.com/attachments/330437210900004874/349706592259670016/ActuallyAdditions-1.12-r118-1.jar

**Comment by Nargath** [comment]
Just on that new jar

It looks like it breaks a significant amount of dust-related functionality.
I now can't grind anything apart from Coal, Iron and Gold into dusts.
Won't even accept Black Quartz.

I have both Mekanism and Thermal Expansion, so they both offer dusts of all the common ores (copper, tin, etc), and I've confirmed that those ores are all oredicted by looking at the various metal gears and ensuring all mods ores are usable.

**Comment by Shadows-of-Fire** [comment]
*ugh*

**Comment by Shadows-of-Fire** [comment]
https://www.dropbox.com/s/eek1kbw4btf72z5/ActuallyAdditions-1.12-r118-2.jar?dl=1
Well, try that one, that should have fixed all the things that are on fire and r119 should be soon
