### ISSUE TITLE
[Suggestion] Add an anti-magnet block

### ISSUE THREAD

**Issue by ShaunDreclin** [Ellpeck/ActuallyAdditions#905]
Would be great if there was a block we could place that would disable the magnet ring near it, maybe with a changeable radius of effect. For things like applied energistics crystal growing, and other mods that use item entities in-world for crafting

**Comment by xenxero1** [comment]
It should probably hit all mod's magnet rings too... if possible.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
