### ISSUE TITLE
Milk effects don't work with coffee

### ISSUE THREAD

**Issue by 23Link89** [Ellpeck/ActuallyAdditions#909]
So for the past while I've been having this problem where I'll brew a cup of coffee with 4 sugar and 1 milk but, instead of a Speed 3, 1:30 duration cup of coffee I get Speed 4 0:30 duration coffee, even though it consumes the milk. Oddly enough it worked the first time but gave me a Speed 3, 2:30 duration coffee. Which isn't a visual or name glitch, upon drinking it you get Speed 3 for 2:30. In the manual, it says milk should only add 1:00 instead of 2:00. Same thing happened the first time I made a Regen 2, Speed 3 (3 Ghast tears and 4 sugar) cup of coffee with milk. Am I going insane or is this working as intended?

Actually Additions: 1.10.2-R105
Forge: 12.18.3.2316

**Comment by Shadows-of-Fire** [comment]
1.10.2 is not supported
