### ISSUE TITLE
Neotech batteries and AA batteries result in infinite power

### ISSUE THREAD

**Issue by austinkam1** [Ellpeck/ActuallyAdditions#913]
With an elite neotech battery and quintuple battery from AA, the elite battery drains out to 0 RF and the AA battery remains the same amount of RF.

Video of this in action: [https://www.youtube.com/watch?v=aVMyOao5BTI](url)

I don't know if this is important or not but this was on Minecraft version 1.10.2 on the Age Of Engineering modpack.

Actually Additions 1.10.2-r105 and Forge 12.18.3.2422

**Comment by Shadows-of-Fire** [comment]
1.10.2 is not maintained, nor do i even believe that issue could be on our side.
