### ISSUE TITLE
Any item dupe with applied Llamagistics

### ISSUE THREAD

**Issue by Sonic2423** [Ellpeck/ActuallyAdditions#915]
Put a storage bus with higher priority than everything else on a crate and set to desired block. Now get an export bus with 4 acceleration cards and export the desired item to the same crate. now place a stack of the desired item in the crate and a single one next to it. now the crate fills up with the item.

video:
https://youtu.be/5prAYjeh7_w

running:
ActuallyAdditions-1.12.1-r119.jar
applied-llamagistics-1.12-rv5-beta-7.jar
forge 1.12.1-14.22.0.2467

Works in singleplayer and multiplayer. only works with storage crates. normal chests and strongboxes from TE arent affected. this is why i guess its on AAs side.

originally found on my server with forge 2444, AA-r119 and applied-llamagistics-1.12-rv5-beta-7 with various other mods.

**Comment by Shadows-of-Fire** [comment]
There was a similar issue with RFTools.  This is not on our end.

**Comment by Sonic2423** [comment]
ok. thanks for fast response. i will open an issue on applied llamagistics then.

**Comment by Shadows-of-Fire** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/1407#issuecomment-321193102
That's the issue in question that was resolved on RS's end, if it helps.

**Comment by thiakil** [comment]
@Shadows-of-Fire (see [this comment](https://github.com/raoulvdberge/refinedstorage/issues/1407#issuecomment-321338091) for reference) while the Javadoc doesn't specify one way or another, the wrapper implementations in Forge *do always* return a copy, especially when simulating. 

So, essentially neither assumption is invalid. Though it seems naive to return whatever is there without copying in a simulation.
