### ISSUE TITLE
1.12.1 java.lang.IllegalArgumentException with 1st world gen

### ISSUE THREAD

**Issue by Seth0067** [Ellpeck/ActuallyAdditions#916]
[pasted crash report](https://pastebin.com/hnFer25r)

Hey... any idea what might be going on here?

Also using Lost Cities by McJty, which plays a large part in world gen.

**Comment by Shadows-of-Fire** [comment]
Huh.  Neat.  This might actually be a forge issue, either that or it's Lost Cities' issue.
This crash would also appear say if you used bonemeal on grass in that biome that you're in.
@McJty can you call `Biome#addDefaultFlowers` on your biome?  Theres no way for me to check if that list is empty and when it's empty BlockGrass#grow throws this IllegalArgumentException.
Really, forge should be checking this, as this goes right through a forge method.

**Comment by Shadows-of-Fire** [comment]
I'm gonna go see about a forge pr on this one.

**Comment by Seth0067** [comment]
Thanks, Shad.
