### ISSUE TITLE
handheld filler holding right-click slows the player

### ISSUE THREAD

**Issue by rahangar** [Ellpeck/ActuallyAdditions#918]
To use the handheld filler, one must hold right-click while traveling to the second corner.   The act of holding right-click, however, slows the user.   

This doesn't happen with other mods (example tape measure in chisels&bits) where a similar mechanic is used.

So I'm wondering if ActAdd is intentionally slowing the user for balance purposes or something?  If so, the slowness seems so extreme that it makes the tool useless in cases where the player has to travel between the first corner and the second corner.  In those cases, it is much faster to place blocks manually or with a builder's wand.  

Is the slowness intentional?  Anything I can do to get around this?

**Comment by YasminEndusa** [comment]
#533 indicates this is intentional.  
Personally, i use flight when working with the handheld filler. Still get slowed down but it's not as bad.

**Comment by rahangar** [comment]
I'm already using flight.  I tried both jetpack and going into creative mode for creative flight.   Same result.  For my purposes, this makes the handheld filler unusable.  :-(

Thanks for the reply.
