### ISSUE TITLE
1.12 crash when generating world

### ISSUE THREAD

**Issue by falizure** [Ellpeck/ActuallyAdditions#919]
When attempting to put together a 1.12 pack today i received a really interesting crash when it first generated the world, while i was able to load in the 2nd time i still figured it was worth reporting as it seamed to be relating to a common item.

[crash-2017-09-13_10.47.05-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1300089/crash-2017-09-13_10.47.05-server.txt)

i am using actually additions: 1.12.1-r119
minecraft 1.12.1
forge 14.22.1.2479

**Comment by Shadows-of-Fire** [comment]
Yeah... so this is the same crash that has been going around for a while that makes no sense and is technically impossible... I suppose I'll just ignore it being null and see what catches on fire from there.
