### ISSUE TITLE
[Minecraft 1.12.1] Very abuseable Duplication Glitch

### ISSUE THREAD

**Issue by andr9528** [Ellpeck/ActuallyAdditions#920]
Having a almost full (one slot remaining) medium storage crate, i were noticing things began stacking above 64, item that exist in one slot and when more are put in to fil the last slot, is also added to the existing ones in the crate while also filling up the remaining open slot.

I noticed this while pulling out a lot of pulverized ores from them, through my applied Llamagistics system, i should also have gotten around 54 pulverized iridium, but ended up with 423 pulverized iridium. i'm unsure if the crate was full while pulling those out, so it might not even be completely related to them being full, but something funky is happening with insertion and extraction of them.
While pulling out the pulverized dusts other were continually duplicating, so where i should have gotten a half small crate i got over a hole small crate of pulverized dust.

![2017-09-15_15 57 27](https://user-images.githubusercontent.com/21788044/30486635-6ec5c1a0-9a31-11e7-8f76-96ca6f9fef69.png)

Notice the Cinnabar.

![2017-09-15_16 23 20](https://user-images.githubusercontent.com/21788044/30486948-3aee0abc-9a32-11e7-9959-bc87f5aae93a.png)

This next one is just from me taking out and putting back in the cinnabar (after a couple of tries, as it didn't do it immediately)

![2017-09-15_16 25 04](https://user-images.githubusercontent.com/21788044/30487062-974e3cf0-9a32-11e7-90e7-f3a05d235812.png)

I'm unsure if this only is a problem with the medium one or if all 3 has the issues, but it is a big one, that needs to be fixed rather quickly, hope this helps.

**Comment by Shadows-of-Fire** [comment]
It's some issue with priority and the crates, but its not on our end.

**Comment by andr9528** [comment]
they have priority 0, with nothing from the AE pulling it out automaticly

**Comment by thiakil** [comment]
https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/util/ItemStackHandlerCustom.java#L107

You return your internal copy of the `ItemStack` when it's a simulation. Check against the Forge implementations that copy it before returning.
