### ISSUE TITLE
[Visual Bug, Mod Interaction] Energy Bar freaks out if the Empowerer uses more RF than the Internal Buffer of the Stands can hold

### ISSUE THREAD

**Issue by MainFreak** [Ellpeck/ActuallyAdditions#923]
I am currently working on a modpack and found this while testing things with CraftTweaker. I made a recipe that uses about 625000 RF per tick. During the crafting the Stands look normally but when the crafting is done their buffer gets extremely overfilled. I know this is probably because the Empowerer is not intended to be used this way, but I would really appreciate it if that could be fixed. Note: Breaking/Replacing it "fixes" it as well
![2017-09-18_22 03 28](https://user-images.githubusercontent.com/20734190/30562455-c455930e-9cbe-11e7-87a1-2c48a4575d0f.png)

**Comment by Shadows-of-Fire** [comment]
This is like trying to overflow a chest and complaining its overflowing.

**Comment by MainFreak** [comment]
I was just asking you if it would be possible to add a way to stop it forcefully from overflowing... I was not trying to complain and I apologize if that's how it looked like.
