### ISSUE TITLE
[Suggestion] Farmer replanting in place with same crop that it harvested from that spot

### ISSUE THREAD

**Issue by togreglove** [Ellpeck/ActuallyAdditions#924]
I noticed the improvement of the farmer so that it replants the most recently harvested spot instead of skipping ahead and planting in the next available spot and I approve.

My suggestion is that you attempt to replant the seed that just dropped from harvesting that slot first instead of taking the first available from all seeds.  I find that if I have more wheat than carrots in my field, then my field eventually fills up with wheat, and carrots never get replanted. If you replanted the same seed you just broke, each spot would retain the crop that was originally planted there and we could manage a multi-crop farm much easier.

Thank you for your time.

Greg Love - Jhereg

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
