### ISSUE TITLE
Small coal not usable in furnace

### ISSUE THREAD

**Issue by Shadow952** [Ellpeck/ActuallyAdditions#927]
os windows 7, minecraft 1.12.2, small coal can't be placed in the furnace.

**Comment by Shadow952** [comment]
Also running Brad16840's backpacks, and BetterFps_1.12-1.4.6 as well as ActuallyAdditioons-1.12.1-r120

**Comment by Shadow952** [comment]
Just to verify that it was not a conflict with one of the other mods, I started a new world with just the Accually Additions on, same results.  I can make tiny coal and tiny torches, but can't use the tiny coal in a furnace.  Have not tried to use tiny coal in a coal generator yet.

**Comment by Shadows-of-Fire** [comment]
![image](https://user-images.githubusercontent.com/3682588/30770599-d9a09a1e-a002-11e7-8ec2-366a59eb211e.png)

Cannot reproduce
