### ISSUE TITLE
[1.10.1] Leadstone Fluxducts don't connect to Oil Generators

### ISSUE THREAD

**Issue by llloyd4** [Ellpeck/ActuallyAdditions#930]
Right, so, I tried putting a leadstone fluxduct (from Thermal Dynamics) onto an oil generator and it doesn't connect, tried all 6 sides to boot, and nada. This is AA 1.10.2-r105 and is, according to the file list, the latest version.

**Comment by Shadows-of-Fire** [comment]
MC 1.10 is not supported
