### ISSUE TITLE
ESD weirdness with mekanism

### ISSUE THREAD

**Issue by jamzam90** [Ellpeck/ActuallyAdditions#931]
The esd doesnt appear to see the slots of mekanism machines

**Comment by Shadows-of-Fire** [comment]
Did you have a security manager active?

**Comment by jamzam90** [comment]
no i did not

**Comment by Shadows-of-Fire** [comment]
So looking back at this, the ESD checks all sides of the machine for caps and handles accordingly.  Unless mek is doing something weirdly, it should work fine, but I can't see an issue on our end.
