### ISSUE TITLE
[Suggestion] Configurable RF Capacity and Charge Rate on Drills

### ISSUE THREAD

**Issue by Boolyman** [Ellpeck/ActuallyAdditions#935]
Hello, I would love to use your mod in my upcoming pack, but would really appreciate your consideration of adding a config option.  Due to the difficulty and progression of my pack, I would really like to make your mining drills hold a bit more RF, but not be rechargeable.  Is there any way that you can add the option for the RF Capacity and Charge Rate to be adjusted in the config files?  This will increase the flexibility of your Drills in a variety of ways in my pack, and others.  Thanks for your consideration.

**Comment by Quarris** [comment]
#926 Yeah I'd recommend closing this now. It's been disapproved before
