### ISSUE TITLE
Source code not working for custom villager trade tables

### ISSUE THREAD

**Issue by mahilo3550** [Ellpeck/ActuallyAdditions#936]
Seems to be the only mod whose ids/code for its items/blocks cannot simply be copied as viewed after hitting F3+H in game and pasted into a JSON file for custom villager trades. For example: the in-game id shown for the Angel Block from Extra Utilities 2 is "extrautils2:angelblock", which can successfully be copied and implemented into a custom villager trade or command, yet the same in-game id shown for this mod's Canola Press ("actuallyadditions:block_canola_press" does not work when applied in the same fashion. Any reason why the ids don't work?

**Comment by Shadows-of-Fire** [comment]
This has nothing to do with AA, which means it is user error.
