### ISSUE TITLE
Blocks/Items with id: "item_misc"/"block_misc" error

### ISSUE THREAD

**Issue by mahilo3550** [Ellpeck/ActuallyAdditions#938]
The above mentioned blocks and items ids (including all metadata) cannot be copied and entered into a trading/loot table as is. All other items/blocks with their own specific id ("block_xp_solidified") work.

**Comment by Shadows-of-Fire** [comment]
Wat.  This isn't even valid.  They are just normal items.

**Comment by mahilo3550** [comment]
No I mean, when you input any of the blocks/items with a "misc" in their id into a custom villager trade, it doesn't work.... for example the full code would be something like this: "{action:"add", CareerLevel:1,buy:{id:"minecraft:cobblestone",Count:1},sell{id:"actuallyadditions:item_misc",Count:64,Damage:0}}. But it doesn't work. This does though:
			{action:"add", CareerLevel:1,
				buy:{id:"minecraft:cobblestone",Count:1},
				sell:{id:"actuallyadditions:item_solidified_experience",Count:64}},
