### ISSUE TITLE
possible bug or misunderstanding with auto-placers/breakers

### ISSUE THREAD

**Issue by iamblackornot** [Ellpeck/ActuallyAdditions#939]
auto-placers and auto-breakers dont' work on a server with an age of engineering modpack. placer doesn't place a block (but corresponding sound of block placing still happens).

when i run a singleplayer world within the same modpack, everything works fine. the only difference is that server has a hardcore configs setup. i've checked actually additions config and found options for enabling/disabling recipe. nothing more that can disable functions placer/breaker. since i can craft them on the server it leaves only two version: 
- there are some other options in configs that disable functions of placers/breakers 
- some unknown bug

**Comment by Shadows-of-Fire** [comment]
Versions below 1.12 are not supported.
