### ISSUE TITLE
great mod! one small (but very annoying bug) found

### ISSUE THREAD

**Issue by cocopuffs99** [Ellpeck/ActuallyAdditions#940]
Using small storage crate, the GUI does not fit with the crate- so whenever you click the sort 'z' icon, it sorts the crate but closing the inventory then drops the item that was near the 'z' icon on the ground.  If not careful can lose items this way, also if careful, need to pick up the item and re insert it again, making using the crates a hassle (although they are great otherwise).  

This doesnt happen with normal chests, just a GUI issue, tried using larger or smaller GUI in normal MC options, doesnt fix it, the proportions stay the same and the items always drop out of the crate onto the floor when using the crate-

**Comment by Ellpeck** [comment]
Just use middle mouse click to sort instead. This isn't really something that can be fixed on Actually Additions' side.

**Comment by cocopuffs99** [comment]
Ahh got it.  Makes sense.  K! Thanks for the tip!! ☺️
