### ISSUE TITLE
Coffee troubles (and possible bug with invisibility coffee?)

### ISSUE THREAD

**Issue by macks2008** [Ellpeck/ActuallyAdditions#941]
to best explain my issue, I think I should use illustration/demonstration. It's much quicker than trying to describe what the hell is going on here. So without further ado...

I started with this (note that 4 fermented spider eyes are in the recipe):
![2017-10-10_23 26 50](https://user-images.githubusercontent.com/7110033/31421137-b58f376a-ae13-11e7-9ef6-9eefcaa0d4a5.png)
I got this (note the lack of effects and that only 2 spider eyes were used.):
![2017-10-10_23 28 02](https://user-images.githubusercontent.com/7110033/31421151-c21de7ec-ae13-11e7-898c-0b2fae3229d2.png)

is this a bug or undocumented "feature"? Either way, it's pretty lousy. I really wanted 18 minutes of invisibility (6 x3) to go with my 15 minutes of fame 😛

**Comment by macks2008** [comment]
also I realize the issue could be as simple as "you're not supposed to put so much milk after one effect", but  without proper documentation, this limitation is obscurely arbitrary, or, to put it differently, "it is because it is but you don't know it is"

**Comment by Shadows-of-Fire** [comment]
@Ellpeck idk how this is supposed to work, so uh, gib insight

**Comment by Ellpeck** [comment]
You need to stagger the milk. The maximum effect of spider eyes is two, so two of the eyes are consumed, and then the three milk cancel it out again.
You can make this work by putting two eyes, a milk, then another eye, then another milk, and so on.
