### ISSUE TITLE
Empowerer not working Age of Engineering

### ISSUE THREAD

**Issue by KaylaSlays** [Ellpeck/ActuallyAdditions#943]
HI

I have an empowerer, 4 stands, 2 blocks apart, fully powered. Have checked the recipes to make sure I have the correct items (all vanilla minecraft items or actually additions in Age of Engineering). Once I place the item on the empowerer, it blinks a couple of times, no effects (they are turned on) and the empowering never happens.  Taken it apart, and rebuilt it elsewhere, same thing.  Have built working empowerer in other mod-packs.

Thanks!
![screenshot 2017-10-11 15 10 03](https://user-images.githubusercontent.com/15056782/31461333-36c1b186-ae97-11e7-9648-2454d95d98f0.png)

**Comment by Shadows-of-Fire** [comment]
User Error

**Comment by tterrag1098** [comment]
Try the actual recipe: ![](https://i.imgur.com/fuYGZB4.png)

**Comment by KaylaSlays** [comment]
DOH, thanks
