### ISSUE TITLE
Does AA Have Crafttweaker Support?

### ISSUE THREAD

**Issue by Somedudesbutonlyone** [Ellpeck/ActuallyAdditions#944]
I'm Using Crafttweaker2 4.0.8 an d Modtweaker 4.0.3 and Actually Additions release 121. I've been making a modpack using craftweaker and actuallyadditons and decided to search up crafttweaker packs and look at their code to find ID names. so I imported <actuallyadditions:blockMisc:9> and <actuallyadditions:blockCoalGenerator>, and it didn't work. I've been having the same problems with IC2 Machine Casing, (Before I found out about the OreDict Entry. Help!

**Comment by Quarris** [comment]
Crafttweaker Supporting mods is on their sides. If you want to learn more go to this site http://crafttweaker.readthedocs.io/en/latest/#

**Comment by Shadows-of-Fire** [comment]
Registry names are all lowercase as of 1.12, so follow suit in your scripts.  The names of blocks/items can be accessed by pushing `f3+h` ingame, and they will be shown as a tooltip.  But this has nothing to do with aa.
