### ISSUE TITLE
Crash with block breakers.

### ISSUE THREAD

**Issue by ICiscoStu** [Ellpeck/ActuallyAdditions#945]
complete crash using the auto-breaker on ATM3

to reproduce: 

place wood, 
place breaker next to it,
set to pulse,
put a timer next to the breaker
wait for timer tick

current error:
-don't copypaste crash reports-
-snipped

any tips on how to solve ?

**Comment by ICiscoStu** [comment]
Gist Provided
https://gist.github.com/ICiscoStu/cabea8d9b0d9c9e62b09879aaa0f4ac3

**Comment by Shadows-of-Fire** [comment]
Outdated version of AA.  Was fixed in r121.
