### ISSUE TITLE
Traveler's Sack & TiC Smeltery Dupe v. 1.10.2-r105 

### ISSUE THREAD

**Issue by Tipsied** [Ellpeck/ActuallyAdditions#946]
**Forge Version:** 12.18.3.2422
**ActuallyAdditions Version:** 1.10.2-r105
**Multiplayer or Singleplayer:** Both
**Affected Features:** unlimited ores 
**Description:** You can duplicate ores using the Traveler's Sack and Tinker's Construct Smeltery. Per past dupe threads ([here](https://github.com/Ellpeck/ActuallyAdditions/issues/674) and [here](https://github.com/SpongePowered/SpongeForge/issues/1351)), duping with the Traveler's Sack was fixed in version 1.10.2-r105, however, it still works on FTB Beyond. So this may be another dupe. Ores can be duplicated by having at least 2 ores in the Traveler's Sack first slot and shift+right clicking the controller of the smeltery. It will take 1 ore from the first slot of the Traveler's Sack and fill the entire smeltery (of any size) with it.    

Items required to replicate:
- Smeltery set up
- x1 Traveler's Sack
- At least 2 ores of any kind (Iron was used for this testing)

Steps to replicate:
1) Put at least 2 ores in the first slot of the Traveler's Sack as seen [here](https://gyazo.com/da77f9afb415d297db9dab5603024253).
2) Shift+Right click on the smeltery controller as seen [here](https://gyazo.com/cb4d2b2b6b32602a0192f9f21aa3ced9) (GIF)

**Comment by Ellpeck** [comment]
1.10.2 is not supported.
