### ISSUE TITLE
[1.12.2] Vertical digger derps up metadata

### ISSUE THREAD

**Issue by Bodidl** [Ellpeck/ActuallyAdditions#947]
When mining IC2 ores (ic2:resource:1, ic2:resource:2, and so on) it gives back IC2 basalt (ic2:resource:0). This also apply to other ores that has same registry name but different metadata.

minecraft: 1.12.2
forge: x.2512
AA: 1.12.1 -r121
+a heap of mods...

**Comment by Shadows-of-Fire** [comment]
So, this is likely due to IC2 overriding the deprecated `getDrops` method.  It will need to be reported to them.  I will not support the old method.
