### ISSUE TITLE
1.12.2 - CraftTweaker support - error in syntax

### ISSUE THREAD

**Issue by tjsd** [Ellpeck/ActuallyAdditions#948]
Hello!
I am removing some stuff from the Crusher and I noticed you seem to have it mixed. You have to remove the output and not the input. It also has trouble accepting ore dictionary. I cant use dustGold I have to specify the version of the dust it makes.

This will successfully remove gold ore from being processed in the crusher
`mods.actuallyadditions.Crusher.removeRecipe(<immersiveengineering:metal:19>);`

But the logic way is to remove the input stack like this:
`mods.actuallyadditions.Crusher.removeRecipe(<ore:oreGold>);`

This has changed in later versions it seems in 1.11.2 it was they "normal" way 
ref: http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Actually_Additions_Support_1.11.2

Not sure if I need to post it here or in CraftTweaker github.

Mods used:
ActuallyAdditions-1.12.1-r121
CraftTweaker2-1.12-4.0.8
modtweaker-4.0.3

**Comment by Quarris** [comment]
Thats probably CraftTweaker issue. Also use the updated Documentation here http://crafttweaker.readthedocs.io/en/latest/#

**Comment by tjsd** [comment]
AA is not listed under latest, but you can still use it to modify recipes, remove and add custom. So only documentation is the previous article. Again not sure who should take care of that. @Quarris

**Comment by Ellpeck** [comment]
This is CraftTweaker.
AA adds no functionality for this itself whatsoever.
