### ISSUE TITLE
Drill augment Not working.

### ISSUE THREAD

**Issue by Jblade123** [Ellpeck/ActuallyAdditions#950]
None of the Drill Augments work, exepct the silk touch one. I am playing FTB Beyond 1.10.2

Gif From Gyazo: https://gyazo.com/3c0f08370eff89c785b8d54b1260e007

**Comment by Quarris** [comment]
Cant have fortune and silktouch at the same time

**Comment by Jblade123** [comment]
if you look at the gif silk touch and fortune arent in at the same time

**Comment by Jblade123** [comment]
And that doesnt explain why the drill mining augment 2 and speed augment dont work

**Comment by Shadows-of-Fire** [comment]
It's because you are using the augments improperly.  Read the book.  This is not a bug.

**Comment by Jblade123** [comment]
I am infact just an idiot haha thank you very much.
