### ISSUE TITLE
[1.12.1-r121] Premature worm death

### ISSUE THREAD

**Issue by xenoflot** [Ellpeck/ActuallyAdditions#958]
Hi,

Running AllTheMods3 ver 4.4. 

I'm finding that worms are expiring before expected.  The pack sets the worm timer to 864000 which should be 10 RL days however they're expiring sooner than that. I couldn't put a specific time on it, but I noticed yesterday some time that my worms were gone, so I replaced them, and I've noticed just now that they're gone again.

Cheers!

Forge 14.23.0.2517

**Comment by Quarris** [comment]
Im pretty sure (but not 100%) that the numbers is the amount of ticks, not the amount seconds. 20 ticks in a seconds meaning it should 12 hours.

**Comment by canitzp** [comment]
Quarris is right. These are ticks not seconds.
864000/20/60/60 = 12h

**Comment by xenoflot** [comment]
Got it, thanks.
