### ISSUE TITLE
[1.12.2] Villagers will harvest vanilla crops in villages but not replant

### ISSUE THREAD

**Issue by SnowShock35** [Ellpeck/ActuallyAdditions#959]
#### Issue Specification

- Minecraft 1.12.2
- Minecraft Forge 14.23.0.2537
- Actually Additions r124

#### Issue Description

Villagers that have a profession from Actually Addition will harvest vanilla crops (as they should) however, do not replant vanilla crops which leads to them ultimately all being gone over a period of time or leaving items on the ground when they're full on seeds/carrots/potatoes/wheat.

**Comment by Shadows-of-Fire** [comment]
Well.  Thats a weird issue.  I'll look into it soon

**Comment by temp1011** [comment]
Can confirm this in r130

**Comment by temp1011** [comment]
Ah. Unfortunately villager crop harvesting AI seems to be hardcoded for vanilla crops. So this would need Forge to do something. I'll probably open a PR for this.
