### ISSUE TITLE
[1.9] Tools do not correctly render in 3rd person

### ISSUE THREAD

**Issue by sblectric** [Ellpeck/ActuallyAdditions#96]
Using version 1.9-r33, tools render as simple items instead of as they should.

Example, with Emerald Sword: http://i.imgur.com/W1ZlsAf.png
With vanilla golden sword (correct): http://i.imgur.com/sUZeZVS.png

You can fix this by having the tool model JSONs extend item/handheld instead of item/generated.

**Comment by Ellpeck** [comment]
God darn it.
I knew this bug.
I was just too lazy to fix it, and I hoped no one would notice >_>
