### ISSUE TITLE
[1.12.2][r124] - Book Crash

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [Ellpeck/ActuallyAdditions#960]
What Happened:
Using Jei to see the book for a recipe and this happened

Expected:
Show me recipe like normal

how to reproduce:
install mods i have on this pack, check recipes for infusing the lapis block(blue block that comes from lapis)

Versions:
forge: 14.23.0.2528
ActuallyAdditions: r124
JEI: 4.8.0.114

Crash:
https://pastebin.com/qZrknzex

**Comment by Shadows-of-Fire** [comment]
So, some mod you have in that pack is making the mc player `Minecraft.getMinecraft().player` null, which doesn't make any sense, but I can't reproduce it with just AA.

**Comment by EPIICTHUNDERCAT** [comment]
"this isnt my issue so i wont fix it" youre starting to sound like someone lol anyways thanks! luckily this isnt a recurring issue

**Comment by Shadows-of-Fire** [comment]
The player can't be null at runtime.  If some mod is making it so, they need to learn how to not set everything on fire.
