### ISSUE TITLE
2 little ideas

### ISSUE THREAD

**Issue by Greg9711** [Ellpeck/ActuallyAdditions#961]
1.
It would be nice if there would be a compressed generator (for coal and oil) that just produces 8x the power with 8x the fuel consumption. This would be the most usefull lategame so the recipe could be 8 generators around 1 empowered crystal of the high tier crystals (diamond or emerald) or a empowered block of one of the others.

2.
A block that can disable the magnet in the inventory when walked over it, either 2 blocks where 1 enables and the other disables the magnet or 1 that toggles it.

Those where just some ideas i had in mind for some time, let me know what you think.

**Comment by Shadows-of-Fire** [comment]
`Actually Additions is not taking suggestions at this time`

**Comment by Greg9711** [comment]
Alright
