### ISSUE TITLE
New config option: crusher output multiplier

### ISSUE THREAD

**Issue by SethWilliamson** [Ellpeck/ActuallyAdditions#962]
```
# Number of grit per ore in the crusher. Valid values: 1.0 through 64.0 [Default: 2.0].
oreToGritRatio: 2.0
```

Like in Tinkers' Construct, add a config option for the crusher output. This would make life so much easier on mod pack developers and players. Personally I want to push ore doubling later in the pack. Others might want to nuts with 10.0 or something. (Hey, it's their sandbox, right heh?)

**Comment by Shadows-of-Fire** [comment]
`neh`
