### ISSUE TITLE
Memory leak!

### ISSUE THREAD

**Issue by handi7a** [Ellpeck/ActuallyAdditions#964]
I'am facing a memory leak with this mod, when I using Shock Breaker block for my farm all over it to make it creeper resistant, its great but I dont know why when I AFK around the farm, my memory would rise to 100% then crash.... I try afk at other place(far from the farm) my memory its not rising and normal
pls fix this, this is an awesome mod... thx before..

**Comment by ron-popov** [comment]
Can you please also specify Minecraft version and game log.

**Comment by Shadows-of-Fire** [comment]
There is no evidence to put this on AA.
