### ISSUE TITLE
[suggestion] Sawmill block

### ISSUE THREAD

**Issue by beckyh2112** [Ellpeck/ActuallyAdditions#967]
It would be nice to have some way to get more planks out of logs. When I'm doing a big wood build before I've gotten an automated tree-farm going, it gets tiresome to have to constantly go plant, cut down, and process trees to make sure I have all the resources I need.

Thermal Expansion is about the only mod I know of that does something like this, but I thought it might suit Actually Additions as well.

**Comment by canitzp** [comment]
I really like the idea of such a block and it would fit perfectly into Actually Additions
