### ISSUE TITLE
Issue with knife crafting

### ISSUE THREAD

**Issue by AF-Bunny** [Ellpeck/ActuallyAdditions#968]
While playing Modern Skyblock 2 I attempted to make noodles to make spaghetti. I was able to make 1 noodle and now all that comes up is bio mash. Making a new knife I was able to make 1 noodle again and now all that knife will make is bio mash. Iron is a hard to make item in this mod pack in the early stages, constantly making new knives wouldn't be helpful for 1 food item.

**Comment by Quarris** [comment]
That sound very much like a pack issue. Make sure to report it to the pack maker first. I would assume the metadata for the knife is not considered in the crafting recipe but I may be wrong.

**Comment by Shadows-of-Fire** [comment]
So yeah, this is an issue.  It might be related to the forge bug where recipes involving damage were broken, but I thought that was fixed.

**Comment by Shadows-of-Fire** [comment]
Yeah, this was fixed by forge.  There was also another recent fix for an issue with the dough recipe.
