### ISSUE TITLE
Vertical digger won't work with claimed chunks

### ISSUE THREAD

**Issue by madcad** [Ellpeck/ActuallyAdditions#969]
I've playing this mod in the direwolf20 for Minecraft 1.12 mod pack. Currently I can see when I have a claimed chunk (via the FTB libs) the vertical digger doesn't mine anything.

**Comment by Shadows-of-Fire** [comment]
![](https://cdn.discordapp.com/attachments/254799354248822785/383765558740385794/i685cimgpsh_orig.png)

**Comment by InsomniaKitten** [comment]
https://github.com/LatvianModder/FTBUtilities/issues
