### ISSUE TITLE
Strange Inventory Issue

### ISSUE THREAD

**Issue by TigersFangs** [Ellpeck/ActuallyAdditions#97]
Was using the Quick/Smart Deposit inventory features from Quark when I ran into this error.

http://pastebin.com/Ln80Bvjs

It only seems to happen when I am in range of any Actually Additions blocks, regardless of if they have an inventory or not.

**Comment by Ellpeck** [comment]
You'd do me a huge favor if you compiled the mod from github and then checked with Quark again.
However, if you don't know how to or don't want to, just wait until the next update is released :)

**Comment by Ellpeck** [comment]
There.
Now this should be proper.

**Comment by TigersFangs** [comment]
Awesome!  I would certainly not mind checking it for you, but I have no idea how to compile it from GitHub.
