### ISSUE TITLE
[Suggestion] Better Anvils

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Ellpeck/ActuallyAdditions#971]
Vanilla anvil sucks, when you play a hard game, have 10000000000 enchants available, and can only have like 2-3 depending on cost, on your stuff.

This mod needs 2 sorts of anvils: An anvil with upped level limit made out of mid-game ingredients, and an anvil with "removed" (not sure how the mechanics work) level limit made out of empowered ingredients.

**Comment by Quarris** [comment]
I very much doubt this one is going to get implemented into this mod. Idea seems... okay I guess but still. Im not the mod developer though.
