### ISSUE TITLE
Dropper not updating blocks beside it

### ISSUE THREAD

**Issue by Rabinol** [Ellpeck/ActuallyAdditions#972]
I was trying to make an automated canola oil processing plant to improve power production, and was using AA's precision dropper to drop the canola seeds. However, I hooked up a comparator next to it to detect when I ran out of seeds. Unfortunately, the comparator doesn't detect when the dropper is out of items. I had to use a Redstone clock to update the comparator. This is all in the Direwolf20 pack by the way.

**Comment by Quarris** [comment]
Can you send a Screenshot of the setup with the clock?

**Comment by Rabinol** [comment]
![javaw_2017-11-26_13-17-24](https://user-images.githubusercontent.com/25218647/33242149-055405b8-d2af-11e7-871d-8c664faf8441.png)

**Comment by Quarris** [comment]
https://gyazo.com/c92e1a47ab750dbf50fc7c5a9184f59d Well I did this as a test and it works fine. I'm not sure what the issue is, can you send me a picture a little further out so I can more accurately replicate the design?

**Comment by Rabinol** [comment]
Oh, I know what Im doing wrong here... What the comparator doesnt detect is when you manually take the items out... which I guess doesnt really bother me in this case. Anyways, not sure if thats supposed to happen. Thanks Quarris
