### ISSUE TITLE
Bowl of Water automatically placing source block

### ISSUE THREAD

**Issue by Y0ungSandwich** [Ellpeck/ActuallyAdditions#973]
ActuallyAdditions-1.12.2-r124
forge-1.12.2-14.23.1.2554-universal
The Bowl of Water will set a source block if within range of a solid block even when not in your hand(s)

**Comment by Shadows-of-Fire** [comment]
learn2sneak

**Comment by Y0ungSandwich** [comment]
What a ridiculous mechanic XD
