### ISSUE TITLE
[Feature] Abilities to Blacklist items from entering Sacks

### ISSUE THREAD

**Issue by JoeSGT** [Ellpeck/ActuallyAdditions#974]
can this feature be on 1.12.2
basically what the title said Abilities to Blacklist items from entering any sacks either traveler sack or void sacks
an configuration option to disallow items in sacks the reason for this is to prevent players from putting certain items that can cause you to crash example issue having over sized packet when you tried to put ME cells in them because it's having an HUGE NBT thing causing playerdata or the server to crash cause that error
i feel this is the best way to prevent it because it might be more item's beside just Applied Energistics ME cells that can cause issues and another thing config or just prevent Sack in Sack
this way it can improve the way not to get corrupted

thanks

**Comment by canitzp** [comment]
Does to big stack nbttags cause crashes? Then this would be an important feature

**Comment by YasminEndusa** [comment]
Yes, too much NBT data can cause crashes. The have been more then enough instances where player .dat files needed to be deleted because the player had a big ME drive (filled) in their inventory when they logged off and after that were unable to log in again for example.

**Comment by JoeSGT** [comment]
what @YasminEndusa  said this is why i want this feature so i can disallow player from doing that
because it's a pain for the players having to lose those items in there ME Drives
