### ISSUE TITLE
coffee machine crashing server?

### ISSUE THREAD

**Issue by Sulpicena** [Ellpeck/ActuallyAdditions#978]
hi! I'm running a forge 1.12.2.14.23.1.2556 server, with actually additions ver 1.12.2-r124 (the very latest atm). In order to add new mods I had to prune world maintaining only our base as before. Issue is created when I pruned my world, for next to our home a village with a coffee machine is created, and server crashes right after startup ever since.
The error shown in console is this one:
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, east, south, west, down, up]} as it does not exist in BlockStateContainer{block=actuallyadditions:block_coffee_machine, properties=[facing]}
as if coffee machine is not loaded properly. I already tried watching inside the config files to see if I was able to remove that item (and verify if this is in fact the issue) But I could not find the option. 
I can attach the latest crash report, if it can be of any help. World seed is: -921141197320197506
[crash-2017-12-01_23.22.24-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1523135/crash-2017-12-01_23.22.24-server.txt)

Thanks in advance!

**Comment by canitzp** [comment]
I understand why you're thinking that this is cause by actually additions, but it isn't. Some lines below we can see that a forestry machine tries to update and causes this error. The coffe machine is only the victim. Maybe you can try to post this issue there too, but it's more likely that the world is corrupted. Does this happen on complete new created worlds too?

**Comment by Sulpicena** [comment]
in fact it doesn't, i even tried saving this world and using it in singleplayer, and no problems at all, i mean, no lag or crashes! I updated recently forestry, do you suggest I try and restore the older version which had no bugs as I can recall? Thanks again ;D

**Comment by canitzp** [comment]
You can try to do it. You also can try to remive the coffee machine with world edit or so. But it isn't an actadd issue and I close this. If I'm wrong than feel free to reopen it
