### ISSUE TITLE
Phantom Redstoneface not working

### ISSUE THREAD

**Issue by Fey142** [Ellpeck/ActuallyAdditions#979]
They are not working no matter what I do (see image).
![ff6haddzrwwo38vu7h19rg](https://user-images.githubusercontent.com/16908410/33518498-2c9e826a-d796-11e7-85d7-accdc786a112.jpeg)

Latest version DW20 pack 1.12.2, AA-r124

**Comment by Shadows-of-Fire** [comment]
Weird.  I had someone tell me yesterday it was working after they thought it wasn't.

**Comment by Fey142** [comment]
Tried every possible scenario but it's not coming through the linked block :/

**Comment by Fey142** [comment]
Lever on the block, linking adjacent blocks, etc. Nothing.

**Comment by Shadows-of-Fire** [comment]
Okay so uh, it works, it just is intended to work backwards.  The phantomface watches the linked block and copies the signal of that block, you cannot transmit from the phantomface to the other block.

**Comment by Shadows-of-Fire** [comment]
![](https://i.imgur.com/kub2MjK.png)
like that

**Comment by Fey142** [comment]
Ohhhh thanks! my bad
