### ISSUE TITLE
[Suggestion] Ability to in some way combine a battery with an atomic reconstructor to expand the available energy buffer.

### ISSUE THREAD

**Issue by ManMan36** [Ellpeck/ActuallyAdditions#981]

**Comment by Shadows-of-Fire** [comment]
Not so sure I want to implement this one.  That is, unless there is a need for it within AA.  I'm not a whole fan of the bigger numbers competition that is rampant throughout other mods.

**Comment by canitzp** [comment]
It would be to hard to implement, but then why only the atomic reconstructer? I really don't want to rewrite a lot of machine code for this and the reconstructors buffer is more than enough. You can put a batterybox on top of it for more energy

**Comment by Ellpeck** [comment]
I don't like this idea, I'm sorry.
