### ISSUE TITLE
Sound deafens when using 5x5 drill augment.

### ISSUE THREAD

**Issue by JadeDrgn** [Ellpeck/ActuallyAdditions#982]
Noticed this happening when I had a video playing in the background and everytime I broke blocks the sound of the video lowered. This happens to all sound, including the ingame sound but it's harder to notice.

Using 1.12.2 r124

Also, I have "Allow applications to take exclusive control of this device" in my speaker properties off.

**Comment by canitzp** [comment]
Wtf. I never heared of this thing. Can you try other speaker or headphones? Maybe it is a power limitation of your speaker

**Comment by Shadows-of-Fire** [comment]
No, its a limitation of Minecraft.  Playing that many break sounds causes everything to sound quieter when doing it.  Nothing AA can do about it, sadly.
