### ISSUE TITLE
Precision dropper + pressure plate

### ISSUE THREAD

**Issue by karolans** [Ellpeck/ActuallyAdditions#984]
Hi, we had some major tps issues on our server caused by my Canola setup. Specifically the simple part of dropping seeds from precision dropper (deactivation mode) on a pressure plate underneath. Instead of stopping the dropper kept going until there were 1000s of seeds sitting on the plate, crashing everyone near the chunk. Picture says it all.
Weirdly enough this works perfectly when I am near, seemed to happen overnight without me even being online.  We use FTBlib for loading chunks, however I didn't even have any loaded. Could this be some weird issue where the dropper is loaded but not the plate, therefore not receiving redstone signal? Is that possible? *Confused*
Any tips for other reliable and safe ways to use the dropper?

Thanks!
![2017-12-02_20 23 49](https://user-images.githubusercontent.com/23509525/33674075-d3f0fc12-daae-11e7-996f-366834aabb3e.png)

**Comment by Shadows-of-Fire** [comment]
That would be on FTBU's end, and there's nothing I can do about it.

**Comment by ktole1999** [comment]
was this tested in a claimed or non ftbu claimed chunk?
