### ISSUE TITLE
Useless Enchated Book

### ISSUE THREAD

**Issue by MarikCZ** [Ellpeck/ActuallyAdditions#985]
It not so uncommon to got from enchant table book with more than one enchant. Unfortunately, in 90% time the enchants are not compatible and book is useless. Can you make option, that when i have book with 3 enchants, i drop it with 2 other classic books in front of atomic reconstructor, it will split the book to 3 other with only 1 enchant?

**Comment by Shadows-of-Fire** [comment]
I actually like this idea.  Nor will it be hard to implement.

**Comment by Shadows-of-Fire** [comment]
https://streamable.com/btsr2 wew it works

**Comment by MarikCZ** [comment]
Big thanks, und thums up!
