### ISSUE TITLE
[BuildTool]

### ISSUE THREAD

**Issue by Sanduhr32** [Ellpeck/ActuallyAdditions#987]
Well i started writing mods too and had some issues with registering items and thier textures so i looked up for good examples and found this mod.
Well I noticed Mincraft modding is a lot of ugly static and complex method stack.
At building Gradle told me that it cant find / cant resolve the jei dependency but it gets a version somehow.

**Comment by Shadows-of-Fire** [comment]
This has nothing to do with AA

**Comment by Sanduhr32** [comment]
Well isnt the BuildScript a part of AA?

**Comment by canitzp** [comment]
But it isn't an error. The build.gradle file is fine and works like intended. There are plenty if tutorials outside. The best ones are McJtys and Shadowfacts.
