### ISSUE TITLE
[1.12.2] Random crash

### ISSUE THREAD

**Issue by elijahlorden** [Ellpeck/ActuallyAdditions#989]
This crash just started happening for no apparent reason, and is now preventing the server from running.

[crash-2017-12-25_19.42.27-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/1586292/crash-2017-12-25_19.42.27-server.txt)

**Comment by Shadows-of-Fire** [comment]
Enable remove erroring tile entities in forge.cfg.  Your world is corrupted and somehow you have a grinder tile entity where there is no grinder block.
