### ISSUE TITLE
Lamps not working in Aroma mining world

### ISSUE THREAD

**Issue by FK187** [Ellpeck/ActuallyAdditions#990]
Lamps and lamp controllers are not working in the mining world of the Direwolf20 1.12.2 1.4.0 version.
![2017-12-29_02 43 52](https://user-images.githubusercontent.com/34934428/34432109-20902010-ec3a-11e7-9ec4-aa130a2a02a3.png)

**Comment by Quarris** [comment]
https://gyazo.com/c444f85ebc012262d33dadbcca509be7
Im not sure what your problem is, it's working fine on the same version of DW20 pack.
Are you sure that the orientation of the lamp controller is correct?

**Comment by Shadows-of-Fire** [comment]
Lamps aren't dim sensitive and they work just fine, so you're doin somethin wrong.
