### ISSUE TITLE
Atomic reconstructor and enchanted books MC 1.12.2

### ISSUE THREAD

**Issue by MasterSloth1** [Ellpeck/ActuallyAdditions#994]
So when a enchanted book (with 2 enchants) is thrown down in front of a atomic re-constructor the enchanted book gets destroyed.

ActuallyAdditions = 1.12.2-r126.jar
forge = 14.23.1.2575

**Comment by Shadows-of-Fire** [comment]
I can't reproduce this issue with AA, so this is probably a mod interaction.

**Comment by MarikCZ** [comment]
It works properly for me. Sometimes after reconstruction items get stucked in wall or floor or teleported behind the wall. This is caused by insufficient space around reconstructor. (Same thing with obstructed bed) So I recommend you make sure, that books get destroyed.

**Comment by Shadows-of-Fire** [comment]
Yeah I don't really believe this is an actual issue.

**Comment by MasterSloth1** [comment]
... Download skyblock adventures mod pack from twitch launcher and ull see

**Comment by fepoe** [comment]
can confirm the bugg is happening to me with the mech & tech modpack in atlauncher
