### ISSUE TITLE
Fuel Has No Burn Time

### ISSUE THREAD

**Issue by BryanBoru** [Ellpeck/ActuallyAdditions#995]
from MultiMC Log:

>  [main/ERROR] [jei]: Fuel has no burn time (0): 1xitem.actuallyadditions.item_dust@6 actuallyadditions:item_dust

running 1.12.2-r126

**Comment by canitzp** [comment]
Does this only happens with this one item or with some more?

**Comment by BryanBoru** [comment]
This wasn't an issue, per se. As I had not tested or even 'try' to burn dust as fuel in my sessions., however I saw this in my log and figured I would share for you.
Dust was the only AA item listed in this error list (two others were unrelated mods).

**Comment by Shadows-of-Fire** [comment]
@mezz What exactly causes this error line?

**Comment by BryanBoru** [comment]
Launching the game in MultiMC, was just sitting in the log. Wasn't a crash or even an issue for me.

**Comment by mezz** [comment]
This logs when `TileEntityFurnace.isItemFuel` returns true, but the item has 0 burn time.

**Comment by Shadows-of-Fire** [comment]
That case seems impossible to even happen... simply because isItemFuel is just `getItemBurnTime(stack) > 0;`, which if the burn time was 0, could never be true.
