### ISSUE TITLE
Drill doesn't trigger some forge events

### ISSUE THREAD

**Issue by roboderpy** [Ellpeck/ActuallyAdditions#996]
E.g. breaking a block will not trigger related events (or drill triggers them partially).

Drill usage doesn't gets tracked by Statistics Screen
Drill can not be used with VeinMiner

**Comment by Shadows-of-Fire** [comment]
What events specifically are you asking be fired?

**Comment by roboderpy** [comment]
Idk but you should test drill with VeinMiner https://github.com/portablejim/VeinMiner

Minecraft statistics use same event as VeinMiner.

**Comment by roboderpy** [comment]
https://i.dbot.serealia.ca/2018/01/4a985e685d_%25pn_-2018-01-05_10-12-14.webm

**Comment by YasminEndusa** [comment]
I've seen this happening before with my own code. Weirdly enough, ForgeHooks.onBlockBreakEvent (which is used by AA) does not trigger the BlockEvent.BreakEvent, though it should, because internally it actually does call the BlockEvent.BreakEvent.

**Comment by roboderpy** [comment]
any updates?

**Comment by roboderpy** [comment]
nope, still not fixed

**Comment by Shadows-of-Fire** [comment]
Well unless you can tell me exactly which events you want fired, its staying as is.

**Comment by roboderpy** [comment]
Idk what events exactly are, but drills are still not tracked by statistics (when Tinker's tools does) and im still unable to use Drills with VeinMiner (im able to use VeinMiner with Tinker's tools too)

**Comment by Ellpeck** [comment]
If you want the Drill to work with VeinMiner, then report an issue on their repository. This isn't the right place for it.
Also, as for the statistics: It's probably something obscurely hidden in the vanilla code, @Shadows-of-Fire. You're probably gonna have to backtrack from the statistics menu to see which call exactly causes the statistics to be updated. I honestly doubt it's as simple as just firing an event for stuff like that.
