### ISSUE TITLE
Mod Interaction w/ MeeCreeps Causing Duplication of Blocks

### ISSUE THREAD

**Issue by SnowShock35** [Ellpeck/ActuallyAdditions#998]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2583
- Actually Additions 1.12.2-r126
- Other Mods:
  - McJtyLib 2.6.2
  - MeeCreeps 1.1.0  

#### Issue Description

When told to flatten an area (Not tried with other commands.) MeeCreeps will destroy actually additions blocks however somehow two of them will be dropped. Giving you an easy way to duplicate items.

I have speculation that this is related to `getDrops()` but that's just speculation.

#### Issue Media

https://imgur.com/rZPbuHu

**Comment by canitzp** [comment]
Is it the same with every block or just a few?

**Comment by SnowShock35** [comment]
@canitzp Replied in Mcjty/MeeCreeps#30

**Comment by SnowShock35** [comment]
Thank you
